### ISSUE TITLE
The transfer command doesn't understand special chars

### ISSUE THREAD

**Issue by seb128** [canonical/multipass#1840] opened 2020-11-17 11:08 UTC
Using 1.5.0 (2857) on Ubuntu 20.10

$ multipass launch focal -n lts
Launched: lts    
$ echo "txt" > bug
$ multipass transfer bug lts:~/
transfer failed: [sftp push] open failed: 'SFTP server: Failure'

But also

$ multipass exec lts -- ls /home/ubuntu/example
one  dir  example
$ multipass transfer lts:/home/ubuntu/example/* .
transfer failed: [sftp pull] open failed: 'SFTP server: No such file'
$ multipass transfer lts:/home/ubuntu/example/one .
-> works

it makes it a bit less obvious to use the transfer command

**Comment by luis4a0** [comment] 2020-11-17 15:13
Hi @seb128,

Thanks for reporting! This seems to be caused by not escaping some characters, as in https://github.com/canonical/multipass/issues/1495. We'll work soon on this and keep you posted.

**Comment by luis4a0** [comment] 2020-11-17 15:19
Duplicate of #1495, closing by now.

**Closed by luis4a0** 2020-11-17 15:19 UTC
Labels: duplicate
