### ISSUE TITLE
[win]multipass just no any response in my cmd or powershell

### ISSUE THREAD

**Issue by baozidai** [canonical/multipass#1403] opened 2020-03-04 04:18 UTC
```
PS C:\Users\包子戴> multipass set local.driver=virtualbox
PS C:\Users\包子戴> multipass version
PS C:\Users\包子戴> multipass launch --name ubuntu-lts
PS C:\Users\包子戴> multipass launch --name ubuntu-lts
PS C:\Users\包子戴> ^C
PS C:\Users\包子戴>
```

It just totally nothing, by the way my user folder is Non_ASCII named. The device is win10 Pro with virtualBox installed while I don't use HyperV.

**Comment by Saviq** [comment] 2020-03-09 10:15
Hi @baozidai this looks like #1314 - we'll fix this in our next release. In the mean time the workaround is to use a second user with ASCII username.

**Comment by Saviq** [comment] 2020-03-09 10:16
Duplicate of #1314

**Closed by Saviq** 2020-03-09 10:16 UTC
