### ISSUE TITLE
idle Multipass memleak ?

### ISSUE THREAD

**Issue by cryptosven76** [canonical/multipass#3454] opened 2024-04-01 07:20 UTC
**Describe the bug**
Describe what your problem is.
i noticed that since earlier this year multipassd consumes GB's of memory over time even its not used at all

**To Reproduce**
How, and what happened?
1. simply start multipass when your OS reboots 

**Expected behavior**
What did you expect to happen?
Not growing in consumption if not used. 

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS:  macOS 14.4.1
 -  ~ % multipass version
multipass   1.13.1+mac
multipassd  1.13.1+mac

multipass info --all
Warning: the `--all` flag for the `info` command is deprecated. Please use `info` with no positional arguments for the same effect.
Name:           rex101
State:          Stopped
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f885a8e8f62a (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

- `multipass get local.driver`
 multipass get local.driver
qemu

**Additional context**
[multipassd.log](https://github.com/canonical/multipass/files/14820717/multipassd.log)

**Comment by cryptosven76** [comment] 2024-04-01 07:21
PID    COMMAND          %CPU TIME     #TH    #WQ  #PORT MEM    PURG  CMPRS  PGRP  PPID  STATE    BOOSTS            %CPU_ME  %CPU_OTHRS UID  FAULTS    COW     MSGSENT    MSGRECV    SYSBSD     SYSMACH    CSW         PAGEINS IDLEW     POWE INSTRS    CYCLES    JETP USER               #MRE RPRV VPRV VSIZ KPRV KSHR
789    multipassd       0.4  27:31.49 22     1    81    24G+   0B    23G    789   1     sleeping *0[1]             0.00000  0.00000    0    3328701+  253     5156       1787       19511677+  60661      4758750+    795     21577     0.4  7419645   5633897   40   root               N/A  N/A  N/A  N/A  N/A  N/A

**Comment by cryptosven76** [comment] 2024-04-01 07:22
you can see it consumed 24G at this time, since the boot of this OS i never started any VM, its in idle state for a week. i see the same behavior on 2 completely independent systems

**Comment by ricab** [comment] 2024-04-02 15:31
Hi @cryptosven76,

Thank you for reporting, it looks like we have a memory leak.

**Comment by ricab** [comment] 2024-04-02 15:39
@cryptosven76, for the time being, you can try to restart the daemon from time to time. Something like this should do, when your instances are stopped:

```
sudo launchctl kickstart /Library/LaunchDaemons/com.canonical.multipassd.plist
```

**Comment by ricab** [comment] 2024-04-02 20:16
As a data point, this does not appear to manifest in a snap over a period of ~2h.

**Comment by cryptosven76** [comment] 2024-04-06 22:44
i restarted it yesterday and today i have again 3 GB without using it at all. 
i wonder if this gets triggered by suspend or sleeps states as the growth seems to be much larger on my macbook than on my mac pro workstation.

**Comment by ricab** [comment] 2024-04-08 11:13
Hi @cryptosven76, how are you measuring memory? If you are referring to Virtual Memory, it is normal for `multipassd` to use 3GB right after being launched. But that is very different from actual RAM being used. Virtual Memory includes a lot of stuff that is not actually loaded, like all the libraries, many of which will be shared by other processes.

I also see `multipassd` using 3GB of Virtual Memory right after being launched, but the actual Resident Set Size (memory in RAM) is 88MB, and some of that is shared. For comparison, I see a browser with a dozen tabs using 21GB of Virtual Memory, with RSS being 600 MB. 

Of course, if the 3GB you see are RSS, that is a problem, especially if you observe it growing over time.

How many VMs do you have when you see this? Do you usually have them running?

**Comment by kacperk** [comment] 2024-05-03 08:02
I have similar issue on Mac. It can grow to sizes that it kills OS (> 24GB) and it happens when there is no VMs running.

**Comment by ricab** [comment] 2024-05-03 11:21
Hi @kacperk, sorry you are experiencing this. A few questions to help us understand the issue to better reproduce/debug:

- How long had your `multipassd` been running? 
- Had you been suspending/resuming often? 
- Do you observe it growing after closing and opening the laptop lid? 
- Do you see it growing at a steady rate? 
- Do you see it changing over a period of a few hours?
- And how/where are you measuring the memory size?

**Comment by kacperk** [comment] 2024-05-06 08:13
Observation from today:
1. From Friday morning (around 72h)
2. Around 10-20 times + whatever macOS decide to wake up when connencted on charger
3. Don't know
4. Don't know
5. I'll look for it during the day
6. Whatever ActivityMonitor shows

**Comment by kacperk** [comment] 2024-05-06 09:31
Screen recording - https://letsbuild.d.pr/i/ueIpt0/2VUO5IPqzF This time machine wasn't suspended, no VMs running - just idle.

**Comment by ricab** [comment] 2024-05-07 11:49
Great, thank you @kacperk. That should give us enough to track it down.

**Comment by sharder996** [comment] 2024-08-21 07:15
I have been daily driving Multipass on my Macbook for the past 6 months now and have never noticed any behavior indicative of a memory leak. However, I tried reproducing with the steps described above (focusing on suspending machines and/or host machine) and the daemon process never went higher than around 50MB. Using `leaks` to analyze the daemon, I found some small signs of memory leakage, but orders of magnitude lower than what OP reported (somewhere on the order of bytes or kilobytes over days).

Looking at the supplied log from original post, it seems suspicious that the multipass daemon is spamming the manifest retrieval every 15 seconds. I tried replicating this by executing `while true; do multipass find --force-update > /dev/null 2>&1; done` which caused the memory usage to double (according to `htop`, but not according to Activity Monitor), but was still nowhere near the scale reported by OP.

If memory serves me correctly, I think there was a bit of fine tuning that done to `multipass find` and asynchronous manifest retrieval which made it into `1.14` so I'd be curious to know if this is still an ongoing issue.

For context, I'm using a M2 Macbook on version 14.6.1

**Comment by ricab** [comment] 2024-08-21 10:13
@cryptosven76, @kacperk, do you still experience this with the latest release (1.14)?

**Comment by cryptosven76** [comment] 2024-09-05 15:39
i haven't experienced this since the upgrade , but i only updated beginning of this week

**Comment by kacperk** [comment] 2024-09-19 08:34
@ricab After update to 1.14 it works fine - no memory leak.

**Comment by ricab** [comment] 2024-09-19 09:44
Good to know, thanks. Closing then.

**Closed by ricab** 2024-09-19 09:44 UTC
