### ISSUE TITLE
MULTIPASS INTANCE BUG

### ISSUE THREAD

**Issue by arsh-kamal** [canonical/multipass#3712] opened 2024-10-02 23:24 UTC
**Describe the bug**
Describe what your problem is.
I am experiencing issues with Multipass on macOS. The virtual machine instances are either stuck in the "Unknown" state or fail to start, remaining in the "Stopped" state. Despite trying multiple troubleshooting steps (restarting instances, switching drivers, reinstalling Multipass, and checking logs), the issue persists.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

Ran the command to launch a new instance:
bash

multipass launch -c 1 -m 512M -d 5G --name test-vm
The instance either remains in the "Unknown" or "Stopped" state, and logs show it's stuck at "Waiting for SSH to be up."

**Expected behavior**
What did you expect to happen?
I expected the virtual machine to start successfully and be able to access the shell via multipass shell <instance-name>.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
[2024-10-02T15:50:23.387] [info] [test-vm] process started
[2024-10-02T15:50:23.388] [debug] [test-vm] Waiting for SSH to be up
[2024-10-02T15:50:23.414] [debug] [test-vm] QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 2, "major": 8}, "package": ""}, "capabilities": ["oob"]}
[2024-10-02T15:50:23.434] [debug] [test-vm] QMP: {"return": {}}
[2024-10-02T15:50:33.649] [debug] [test-vm] QMP: {"timestamp": {"seconds": 1727909433, "microseconds": 649322}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]/virtio-backend"}}
[2024-10-02T15:51:26.821] [debug] [test-vm] QMP: {"timestamp": {"seconds": 1727909486, "microseconds": 821158}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

**Additional info**
 - OS: macOS 15.0 (24A335)
- `multipass version`multipass   1.14.0+mac
multipassd  1.14.0+mac
- `multipass info`
- Name:           calm-imp
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           dev01
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           spotless-fish
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           test-vm
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
Dell@ucsc-guest-169-233-117-175 ~ % 

- `multipass get local.driver`
qemu
**Additional context**
I have tried the following troubleshooting steps:

Restarting the instances (multipass stop <instance> and multipass start <instance>).
Switching drivers between qemu and hyperkit.
Reinstalling Multipass and its dependencies.
Checking network connectivity and firewall settings.
Running Multipass in Safe Mode.

**Comment by georgeliao** [comment] 2024-10-03 08:44
Hi @arsh-kamal 
Sorry that you have encountered this. It smells like the known [issue](https://github.com/canonical/multipass/issues/3661) on macos sqenoia, can you try the [test package](https://github.com/canonical/multipass/issues/3661#issuecomment-2363403467) and see whether that solves the problem?

**Comment by arsh-kamal** [comment] 2024-10-03 22:44
Hi 
It didnt solve the problem still timed out

**Comment by georgeliao** [comment] 2024-10-04 08:50
@arsh-kamal 
Ok, then that is more complicated. Can you share the log on the new test package run? What exact commands did you try? Did you try to launch a new instance or just try to start an existing instance?

**Comment by arsh-kamal** [comment] 2024-10-04 15:04
Ohh its finally worked with the package thankyou for your help

**Comment by georgeliao** [comment] 2024-10-04 16:18
@arsh-kamal 
Glad it worked. Can you share more details what did not work, what worked and what did you do right to get it work?

**Comment by arsh-kamal** [comment] 2024-10-04 16:27
So basically apple mac could not verify multipass 1.15.0 dev that it is free of malware or not so it wss giving me error message so i went to settings in settings i went to privacy and security and scroll down and there was a option to allow this version to setup i click that and its finally worked.

**Comment by ricab** [comment] 2024-10-04 16:44
Good to know, thanks @arsh-kamal.

**Comment by ricab** [comment] 2024-10-04 16:44
Duplicate of #3661

**Closed by ricab** 2024-10-04 16:44 UTC
Labels: needs triage
