### ISSUE TITLE
VM state  is Unknown after issuing systemctl start reboot.target

### ISSUE THREAD

**Issue by nhasian** [canonical/multipass#2035] opened 2021-04-02 17:26 UTC
**Describe the bug**
Within the VM the command "systemctl start reboot.target" was issued to restart the VM. Unable to start the VM again and it is in an Unknown state.

**To Reproduce**
How, and what happened?
1. multipass shell test-server
2. sudo systemctl start reboot.target
3. multipass list

**Expected behavior**
I expected the virtual machine to restart and then I could continue working on it. However I am no long able to start or access the virtual machine.

**Logs**
Apr 02 10:23:42 MES-LIT042 multipassd[11696]: process program 'qemu-system-x86_64'
Apr 02 10:23:42 MES-LIT042 multipassd[11696]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/test-server/ubuntu-20.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:30:d5:7d, -netdev, tap,id=hostnet0,ifname=tap-79d728f10a0,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/test-server/cloud-init-config.iso, -loadvm, suspend, -machine, pc-i440fx-bionic'
Apr 02 10:23:42 MES-LIT042 multipassd[11696]: Resuming from a suspended state
Apr 02 10:23:42 MES-LIT042 multipassd[11883]: Applying AppArmor policy: multipass.test-server.qemu-system-x86_64
Apr 02 10:23:42 MES-LIT042 multipassd[11696]: [11883] started: qemu-system-x86_64 --enable-kvm -device virtio-scsi-pci,id=scsi0 -drive file=/var/snap/multipass/common/data/multipassd/vault/instances/test-server/ubuntu-20.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:30:d5:7d -netdev tap,id=hostnet0,ifname=tap-79d728f10a0,script=no,downscript=no -qmp stdio -cpu host -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/snap/multipass/common/data/multipassd/vault/instances/test-server/cloud-init-config.iso -loadvm suspend -machine pc-i440fx-bionic
Apr 02 10:23:42 MES-LIT042 multipassd[11696]: process started
Apr 02 10:23:42 MES-LIT042 multipassd[11696]: Trying SSH on 10.237.101.94:22
Apr 02 10:23:42 MES-LIT042 multipassd[11696]: QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 11, "major": 2}, "package": "(Debian 1:2.11+dfsg-1ubuntu7.36)"}, "capabilities": []}}
Apr 02 10:23:43 MES-LIT042 multipassd[11696]: qemu-system-x86_64: warning: TSC frequency mismatch between VM (2807983 kHz) and host (2807984 kHz), and TSC scaling unavailable
Apr 02 10:23:43 MES-LIT042 multipassd[11696]: 
Apr 02 10:23:43 MES-LIT042 multipassd[11696]: QMP: {"return": {}}

**Additional info**
 - OS: Ubuntu 20.10
- `multipass version 1.6.2
- `multipass info --all`

Name:           test-server
State:          Unknown
IPv4:           --
Release:        --
Image hash:     da9122a1174f (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

**Additional context**
It appears that the VM was stuck in a suspended state. The issue was resolved with:
sudo killall -9 qemu-system-x86_64   
sudo qemu-img snapshot -d suspend ./var/snap/multipass/common/data/multipassd/vault/instances/test-server/ubuntu-20.04-server-cloudimg-amd64.img

Then I was able to start the VM and log back into it. Thanks to @townsend2010

**Comment by Saviq** [comment] 2021-04-06 13:41
Hi @nhasian,

Upon `sudo systemctl start reboot.target`, you just terminate all services (including `sshd`), but don't _actually_ restart the machine. `sudo systemctl reboot` should do better, or simply `sudo reboot`.

That said, a `multipass stop/restart` should allow to deal with that, by forcefully shutting the instance down.

There's #1909 to deal with that.

**Comment by Saviq** [comment] 2021-04-06 13:41
Duplicate of #1909

**Closed by Saviq** 2021-04-06 13:41 UTC
Labels: bug
