### ISSUE TITLE
sshfs_server using 100% CPU and not responding to SIG_TERM

### ISSUE THREAD

**Issue by pkolaczk** [canonical/multipass#2286] opened 2021-10-16 07:14 UTC
**Describe the bug**
After a fresh upgrade to Ubuntu 21.10 I noticed sshfs_server using 100% CPU all the time. It is already there after logging in.
I couldn't terminate it normally, I had to use SIG_KILL.

**To Reproduce**
Just upgraded from 21.04 to 21.10.

**Expected behavior**
Please don't fry my CPU. 

**Logs**
```
paź 16 08:47:59 p5520 multipassd[2243]: [3716] started: /snap/multipass/5317/bin/sshfs_server 10.186.197.2 22 ubuntu /home/pkolaczk/Projekty/fclones /root/project 1001:0, 1001:0, 3
paź 16 08:47:59 p5520 multipassd[2243]: QMP: {"return": ""}
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:174 make_sftp_server(source = /home/pkolaczk/Projekty/fclones, target = /root/project, …):
paź 16 08:47:59 p5520 sshfs_server[3716]: Executing 'snap run multipass-sshfs.env'
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 1, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 256
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 256
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 256
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 256
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 56
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: Executing 'sudo env LD_LIBRARY_PATH=/snap/multipass-sshfs/145/lib /snap/multipass-sshfs/145/bin/sshfs -V'
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 1, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 88
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: Executing 'sudo /bin/bash -c 'P="/root/project"; while [ ! -d "$P/" ]; do P="${P%/*}"; done; echo $P/''
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 1, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 15
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: Executing 'id -u'
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 1, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 5
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:183 make_sftp_server(): `id -u` = 2002
paź 16 08:47:59 p5520 sshfs_server[3716]: Executing 'id -g'
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 1, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1):
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 5
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
paź 16 08:47:59 p5520 sshfs_server[3716]: /build/multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:188 make_sftp_server(): `id -g` = 2002
paź 16 08:47:59 p5520 sshfs_server[3716]: Executing 'sudo env LD_LIBRARY_PATH=/snap/multipass-sshfs/145/lib /snap/multipass-sshfs/145/bin/sshfs -o slave -o transform_symlinks -o allow_other -o Compression=no -o dc>
paź 16 08:47:59 p5520 sshfs_server[3716]: handle_stat: cannot stat  '/home/pkolaczk/Projekty/fclones': no such file
paź 16 08:52:21 p5520 multipassd[2243]: QMP: {"timestamp": {"seconds": 1634367141, "microseconds": 951156}, "event": "RTC_CHANGE", "data": {"offset": -34955}}
paź 16 09:03:31 p5520 multipassd[2243]: QMP: {"timestamp": {"seconds": 1634367811, "microseconds": 506218}, "event": "RTC_CHANGE", "data": {"offset": 1}}
paź 16 09:07:36 p5520 multipassd[2243]: [10942] started: qemu-system-x86_64 --version
```

**Additional info**
ubuntu 21.10
multipass  1.7.1
multipassd 1.7.1

**Comment by jedahan** [comment] 2021-11-16 15:41
See #1677

**Comment by Saviq** [comment] 2021-11-16 15:52
Indeed. Thanks @jedahan!

**Comment by Saviq** [comment] 2021-11-16 15:52
Duplicate of #1677

**Closed by Saviq** 2021-11-16 15:52 UTC
Labels: bug
