### ISSUE TITLE
multipass start takes several minutes and then the instance is changed to state unknown

### ISSUE THREAD

**Issue by Relento** [canonical/multipass#2479] opened 2022-03-12 07:27 UTC
**Describe the bug**
When I try to start the created instance (named `foo`) by `multipass start foo`, it will take more than 10 minutes to complete, showing:
```
start failed: The following errors occurred:
foo: timed out waiting for response
```
and the state of the instance will then change to "unknown". I can normally use the instance (which uses Ubuntu 20.04 image) the first time I created it. The issue started after a reboot.

**Logs**
```
[2022-03-11T23:17:45.804] [debug] [qemu-system-aarch64] [1972] started: qemu-system-aarch64 -machine virt,highmem=off -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.VErveM
[2022-03-11T23:17:45.864] [info] [foo] process state changed to Starting
[2022-03-11T23:17:45.866] [info] [foo] process state changed to Running
[2022-03-11T23:17:45.866] [debug] [qemu-system-aarch64] [1973] started: qemu-system-aarch64 -machine virt,highmem=off -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72 -cpu cortex-a72 -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/foo/ubuntu-20.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 3885M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/foo/cloud-init-config.iso
[2022-03-11T23:17:45.866] [info] [foo] process started
[2022-03-11T23:17:45.867] [debug] [foo] Waiting for SSH to be up
[2022-03-11T23:17:45.909] [warning] [foo] qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: Started vmnet interface with configuration:
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: MTU:              1500
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: Max packet size:  1514
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: MAC:              d2:8c:d5:34:d6:91
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: DHCP IPv4 start:  192.168.64.1
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: DHCP IPv4 end:    192.168.64.254
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: IPv4 subnet mask: 255.255.255.0
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:86:9f:72: info: UUID:             727A783D-78BB-4315-A9CC-C36C02AC3DF9

[2022-03-11T23:17:45.909] [warning] [qemu-system-aarch64]
[2022-03-11T23:17:45.909] [debug] [foo] QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 1, "major": 6}, "package": ""}, "capabilities": ["oob"]}}
```

**Additional info**
 - OS: macOS 12.2.1 (M1 Arch)
- `multipass version` multipass   1.8.1+mac
- `multipass info --all`

```
Name:           foo
State:          Unknown
IPv4:           --
Release:        --
Image hash:     e905900cd0a0 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

**Comment by Saviq** [comment] 2022-03-15 15:29
Duplicate of #2387

**Closed by Saviq** 2022-03-15 15:29 UTC
Labels: bug
