### ISSUE TITLE
port forwarding 

### ISSUE THREAD

**Issue by HenryJi529** [canonical/multipass#1998] opened 2021-03-08 18:06 UTC
**What are you trying to do?**
I hope that port-forwarding will be more convenient.
**What's your proposed solution?**
for example:
```bash
$ multipass port-forwarding 1087 grand-setter:1087
```

**Additional context**
This feature will help rookies like me a lot, thx~

**Comment by Saviq** [comment] 2021-03-08 18:53
Hi @HenryJi529, this would be #309, I'll mark this as a duplicate.

In the mean time, you can [use `--network`](https://multipass.run/docs/additional-networks) to expose the instance on your network.

**Comment by Saviq** [comment] 2021-03-08 18:53
Duplicate of #309

**Closed by Saviq** 2021-03-08 18:54 UTC
Labels: enhancement
