### ISSUE TITLE
Consider making the location for Multipass files configurable on Linux (do not risk exhausting space on root partition!)

### ISSUE THREAD

**Issue by callegar** [canonical/multipass#1274] opened 2019-12-30 18:11 UTC
Currently, on Linux, multipass images go in `/var/snap/multipass/` (at least as long as multipass is installed as a snap).  This is probably a less than ideal location.  For instance, many systems have their root on smallish SSDs to make them faster and `\var` as a subdir of root.  In this case filling up the disk with multipass becomes way to easy, and may bring severe consequences (e.g., breaking system updates or making the system configuration inconsistent because a part of a system setup change cannot make it to the root disk).

As an example, trying to build complex snap packages with snapcraft (which uses multipass) can easily lead to many tens of GB of disk being taken.

For maximum safety, it would be ideal to set up ad hoc spaces for virtual machines to make sure that virtual machine creation cannot end up with filling root. Indeed, this would be automatically guaranteed by placing `\var` on its own partition, but this is not how most system get setup as of today. While the appearance of `multipass` and `snapcraft` may now make one reconsider the advantage of  placing `\var` in its own partition, changing that for systems that had already been setup is not easy.

Setting up multipass to store its images in other places would thus be ideal. However, without a configuration option it is not easy to do so. Trying to move away `\var\snap\multipass` and use a symlink to make it still appear in `\var\snap` does not work. Apparently, the only thing that works is a bind mount of some dedicated space to `\var\snap\multipass`.

Please, let `multipass` have a configuration file (e.g., in `\etc\multipass.conf`) and let it contain an entry for the location of the images.

**Comment by Saviq** [comment] 2020-01-10 07:03
Duplicate of #1215

**Closed by Saviq** 2020-01-10 07:03 UTC

**Comment by Saviq** [comment] 2020-10-08 08:16
Hi @callegar, I've described a workaround in https://github.com/canonical/multipass/issues/1215#issuecomment-705408845.
