### ISSUE TITLE
mutipass needs to support windows server 2016 and 2019

### ISSUE THREAD

**Issue by kundeng** [canonical/multipass#1500] opened 2020-04-21 00:29 UTC
**What are you trying to do?**
A description of what you want to happen.
It installs but errors out when run on the server edition, complaining about hyper-v not enabled. 
In fact, hyper-v is enabled and has other VMS running. 

**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.
I think it has something to do with API compatibility. 

**Additional context**

**Comment by Saviq** [comment] 2020-04-21 06:09
Duplicate of #1323

**Closed by Saviq** 2020-04-21 06:09 UTC

**Comment by arielcattaneo** [comment] 2021-05-31 01:19
Idem +1
