### ISSUE TITLE
multipass needs to support custom switch instead of default switch in hyper-V

### ISSUE THREAD

**Issue by kundeng** [canonical/multipass#1501] opened 2020-04-21 03:25 UTC
A caution for anybody who wants to use hyper-v and k3s.  

Hyper-V default switch doesn't give out persistent static IP.  It changes upon reboot.  For example, You will have an issue if you want to set-up say a k3s cluster,  worker node will lose connections to the master node. 

I guess this can be a feature request rather than a bug??

**Comment by Saviq** [comment] 2020-04-21 06:17
Hi @kundeng we are planning (#118) to add support for bridged networking soon, at which point you'll be able to use those IPs, or set static ones (#567).

**Comment by Saviq** [comment] 2020-04-21 06:17
Duplicate of #567

**Closed by Saviq** 2020-04-21 06:17 UTC

**Comment by Saviq** [comment] 2020-04-21 07:40
@kundeng there's one thing you could do - rather than use IPs, could you make the cluster using `<instance>.mshome.net` hostnames? Those should always point to the right IP.
