### ISSUE TITLE
not enough disk space VM too small

### ISSUE THREAD

**Issue by alexladerman** [canonical/multipass#1387] opened 2020-02-25 14:33 UTC
I just spent hours installing all the prerequisites for an application onto a new VM only to find at the last step there is not enough disk space to copy some 15 GB of files that the application needs. 

Is there any way of increasing the disk allocation for an existing container? or perhaps launch a new container with --disk but based on the image of earlier one?

**Comment by Saviq** [comment] 2020-02-26 08:47
Hi @alexladerman see #62, growing the filesystem is not a trivial task, as the underlying block device needs to be resized, then the partitions inside, and then the filesystem itself. There's a non-negligible chance of things going wrong, so we're generally recommending a new VM with a generous `--disk`.

That said, if you want to dive into it, `qemu-img` can help you try and achieve what you need. You didn't say what your platform is - on Linux, all the data is stored in `/var/snap/multipass/common`, on macOS, in `/var/root/Library/Application\ Support/multipassd` and on Windows, in `C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd`.

I'm going to close this as a duplicate of #62.

**Comment by Saviq** [comment] 2020-02-26 08:47
Duplicate of #62

**Closed by Saviq** 2020-02-26 08:47 UTC
