### ISSUE TITLE
Possibility to run a command for all VMs

### ISSUE THREAD

**Issue by Daitan9** [canonical/multipass#2546] opened 2022-05-02 20:23 UTC
Hello, just installed Multipass and works like a charm, tho I noticed a lacking parameter for the exec command : 

-- > A feature to allow this type of command  $ : multipass exec --all touch test.txt 

Because as of now we're limited to choose by name our VMs and if you got many, it can be quite long.

Hope it will be added without too much difficulties ! (I'm not a professional developper, I can't really know)

**Comment by Saviq** [comment] 2022-05-03 05:34
It's more likely we'd use wildcards for this instead.

**Comment by Saviq** [comment] 2022-05-03 05:34
Duplicate of #2404

**Closed by Saviq** 2022-05-03 05:34 UTC
Labels: enhancement
