### ISSUE TITLE
Launching RISC-V daily build fails

### ISSUE THREAD

**Issue by xypron** [canonical/multipass#2472] opened 2022-03-04 10:31 UTC
**Describe the bug**
Launching a RISC-V VM fails.

**To Reproduce**
How, and what happened?
On an  x86_64 Ubuntu Jammy run:
```
$ multipass launch -n riscv-jammy http://cdimage.ubuntu.com/ubuntu-server/daily-preinstalled/current/jammy-preinstalled-server-riscv64+unmatched.img.xz
launch failed: The following errors occurred:                                   
riscv-jammy: timed out waiting for response
```
**Expected behavior**
multiplass uses qemu-system-riscv64 to lauch the image as described in https://wiki.ubuntu.com/RISC-V.

**Logs**
see above

**Additional info**

```
 $ uname -a
Linux LT2ubnt 5.15.0-18-generic #18-Ubuntu SMP Fri Jan 21 14:57:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ multipass --version
multipass   1.8.0
multipassd  1.8.0
```

```
$ multipass info --all                                           
Name:           riscv-jammy
State:          Unknown
IPv4:           --
Release:        --
Image hash:     c987ca916bed
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

**Additional context**
n/a

**Comment by Saviq** [comment] 2022-03-04 10:32
Duplicate of #886

**Closed by Saviq** 2022-03-04 10:32 UTC
Labels: bug
