### ISSUE TITLE
Update GUI icon color as monochrome.

### ISSUE THREAD

**Issue by lukeholder** [canonical/multipass#1542] opened 2020-05-17 13:23 UTC
**What are you trying to do?**
Have the application feel native to the platform. (Windows and Mac)

The GUI menubar icon currently looks like this:
![image](https://user-images.githubusercontent.com/133571/82147908-97044a80-9883-11ea-859a-b22290c839d2.png)

**What's your proposed solution?**
Replace the icon with a monochrome version, or give the GUI app a preference to set the icon to monochrome.

**Comment by Saviq** [comment] 2020-05-18 09:52
Duplicate of #1240

**Closed by Saviq** 2020-05-18 09:52 UTC
Labels: enhancement
