### ISSUE TITLE
[OSX] Use default terminal app

### ISSUE THREAD

**Issue by avetisk** [canonical/multipass#1347] opened 2020-02-10 16:13 UTC
Currently, the "Open Shell" command opens with `Terminal.app` which may not be the default terminal app as defined globally on one's system, would be much better if it would use the default app (e.g iTerm2, etc.).

https://github.com/canonical/multipass/blob/03e6588aef6c608d0309f0373671b4e73cc85376/src/platform/client/client_platform_linux.cpp#L25-L29

**Comment by Saviq** [comment] 2020-02-10 17:29
Hi @avetisk, we're tracking this in #1273.

**Comment by Saviq** [comment] 2020-02-10 17:29
Duplicate of #1273

**Closed by Saviq** 2020-02-10 17:29 UTC
