### ISSUE TITLE
info command does not display CPUs 

### ISSUE THREAD

**Issue by anthonydillon** [canonical/multipass#1855] opened 2020-11-25 11:45 UTC
**Describe the bug**
If I would like to see how many CPUs an instance is allocated I can't find that information in the `info` command

**To Reproduce**
How, and what happened?
1. Run `multipass info m1 -v` and see:
```
Name:           m1
State:          Stopped
IPv4:           --
Release:        --
Image hash:     151e5e797dc0 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
```

**Expected behavior**
I would expect to see the CPUs allocation and if set to the default. Display the default value.

**Comment by townsend2010** [comment] 2022-04-25 13:43
Duplicate of #1804

**Closed by townsend2010** 2022-04-25 13:43 UTC
