### ISSUE TITLE
Multipass changes mount permissions to uid:1000 gid:1000

### ISSUE THREAD

**Issue by nadav-lavy-exa** [canonical/multipass#1651] opened 2020-07-20 15:03 UTC
**Describe the bug**
When a multipass instance runs with a mount, and data is written to that mount - at some point the permissions of that mounted dir. change its permissions to uid:1000 gid:1000.

**To Reproduce**
How, and what happened?
1. `multipass launch --name ubuntu-lts --mem 5G --cpus 4 --disk 20G`
2. `multipass mount /path/to/data/directory ubuntu-lts:/data`
3. run k8s -> kafka (https://github.com/bitnami/bitnami-docker-kafka) inside ubuntu-lts; mounted `/data` folder is kafka's data folder
4. write data to kafka. at some point (after ~5sec.) after data was successfully written & read from /data folder - kafka errors; fails to read (!) and write to the data folder

**Expected behavior**
would not fail to read & write to the mounted folder

**Logs**
attached logs
[multipassd.log](https://github.com/canonical/multipass/files/4948452/multipassd.log)
[ubuntu-lts-hyperkit.log](https://github.com/canonical/multipass/files/4948453/ubuntu-lts-hyperkit.log)

also - kafka log with the error:
[kafkalogs.log](https://github.com/canonical/multipass/files/4948472/kafkalogs.log)

**Additional info**
 - OS: macOS 10.15
- multipass version: multipass  1.3.0+mac
- `multipass info --all`:
» multipass info --all

Name:           ubuntu-lts-dbg
State:          Stopped
IPv4:           --
Release:        --
Image hash:     d6d0a7f24c68 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /Users/me/dev/k8s => /cc-descriptors
                    UID map: 501:default
                    GID map: 20:default
                /Users/me/dev/k8s-dbg            => /data
                    UID map: 501:default
                    GID map: 20:default

**Additional context**
issue occurred on two different mac machines; one of which w/o FUSE/Tuxera etc.
issue did not occur on plain Ubuntu 18.04 w/o multipass

**Comment by ricab** [comment] 2020-07-20 17:30
Thank you @nadav-lavy-exa. To confirm, the directory that gets the ownership changed is _outside_ the VM, correct?

I looked at your logs but I couldn't see anything special at the time those kafka errors happen (14:54 today). This will need some more digging and new attempts to reproduce.

Note: this got branched from a very similar case in #1346, but this time it doesn't happen to the auto-mount in primary.

**Comment by nadav-lavy-exa** [comment] 2020-07-21 06:28
@ricab correct. when the directory is not mounted outside the issue does not occur.

**Comment by ricab** [comment] 2020-07-21 09:15
> @ricab correct. when the directory is not mounted outside the issue does not occur.

Right, but I mean: the ownership changes on the outside directory, not the *reflection* that the VM sees. Can you confirm? 

Just so that we get an exact picture of the problem. Thank you.

**Comment by nadav-lavy-exa** [comment] 2020-07-21 09:27
@ricab it changes on the internal representation. from outside of multipass the permission stayed the same.
from within the VM it sees it with the new permissions.

**Comment by ricab** [comment] 2020-07-21 10:25
Ahh, I see, then this is quite a different issue. You're not by any chance hitting space limits, either inside or outside the VM, are you @nadav-lavy-exa ?

SSHFS is crashing on multiple occasions for some reason:

```
[2020-06-30T12:11:18.182] [debug] [/Library/Application Support/com.canonical.multipass/bin/sshfs_server] [2020-06-30T12:11:18.027] [error] [sftp server] sshfs in the instance appears to have exited unexpectedly.  Trying to recover.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: unable to create a channel for remote process: 'findmnt --source :/Users/nadavlavy/dev/repos/skyformation/compose/k8s  -o TARGET -n', the SSH session is not connected

[2020-06-30T12:11:18.182] [debug] [ubuntu-lts] Trying SSH on 192.168.64.23:22
[2020-06-30T12:11:18.182] [error] [sshfs-mounts] There was an error with sshfs_server for instance "ubuntu-lts" with path '/Users/nadavlavy/dev/repos/skyformation/compose/k8s': Crashed - program: /Library/Application Support/com.canonical.multipass/bin/sshfs_server; error: Process crashed
[2020-06-30T12:11:18.182] [warning] [sshfs-mounts] Mount '/Users/nadavlavy/dev/repos/skyformation/compose/k8s' in instance "ubuntu-lts" has stopped unexpectedly: program: /Library/Application Support/com.canonical.multipass/bin/sshfs_server; error: Process crashed
[2020-06-30T12:11:18.182] [debug] [/Library/Application Support/com.canonical.multipass/bin/sshfs_server] [2020-06-30T12:11:18.025] [error] [sftp server] sshfs in the instance appears to have exited unexpectedly.  Trying to recover.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: unable to create a channel for remote process: 'findmnt --source :/Users/nadavlavy/dev/deployments/k8s  -o TARGET -n', the SSH session is not connected

[2020-06-30T12:11:18.182] [error] [sshfs-mounts] There was an error with sshfs_server for instance "ubuntu-lts" with path '/data': Crashed - program: /Library/Application Support/com.canonical.multipass/bin/sshfs_server; error: Process crashed
[2020-06-30T12:11:18.182] [warning] [sshfs-mounts] Mount '/data' in instance "ubuntu-lts" has stopped unexpectedly: program: /Library/Application Support/com.canonical.multipass/bin/sshfs_server; error: Process crashed
```

Although not when the kafka errors happen, but those could be a red herring...

**Comment by nadav-lavy-exa** [comment] 2020-07-21 10:52
@ricab no space issues.

**Comment by ricab** [comment] 2020-07-24 16:00
@nadav-lavy-exa I circled back to have a second look at this and I am afraid it stopped making sense to me. 

What do you mean by "changes mount permissions to uid:1000 gid:1000"? The issue you originally commented on reported ownership being changed *on the host*, but it is supposed to be 1000 inside the instance.

So, that wouldn't cause read/write problems and I don't see anything happening in multipass justifying the errors in that kafka log. What makes you think multipass is causing it?

**Comment by Saviq** [comment] 2020-09-04 05:42
I believe #1718 explains this issue, so I'll duplicate it to that.

**Comment by Saviq** [comment] 2020-09-04 05:42
Duplicate of #1718

**Closed by Saviq** 2020-09-04 05:42 UTC
Labels: question
