### ISSUE TITLE
launch failed: The check_kvm_support script failed to start. 

### ISSUE THREAD

**Issue by CaptainLoop** [canonical/multipass#2360] opened 2021-11-30 18:59 UTC
Sorry I'm asking this here, but here: https://discourse.ubuntu.com/c/multipass/21 I can't find any "ask a question" button. I searching the site for 30 min, and I don't know how to ask a questin. (I have an account, and verify)

I have an error: launch failed: The check_kvm_support script failed to start.  Ubunut 20.04  virtual machine on hyper-v.  (freshly installed)

Multipass not wokring on hyper-v ubunut? I have WSL, and multipass woking on WSL. 

How can I use multipass on hyper-v virtual machine.

**Comment by Saviq** [comment] 2021-11-30 19:14
@CaptainLoop why do you want to run Multipass inside a Hyper-V VM? Just run the native Windows version instead?

https://multipass.run/

You'd have to enable nesting in Hyper-V otherwise, but that has performance impact and is been generally unnecessary.

The error message should say that virtualization is disabled, that got fixed in #2336.

**Comment by Saviq** [comment] 2021-11-30 19:14
Duplicate of #2336

**Closed** 2021-11-30 19:14 UTC
Labels: duplicate
