### ISSUE TITLE
multipass VM unable to access the internet if host machine connected to an openVPN connection

### ISSUE THREAD

**Issue by RichardoC** [canonical/multipass#2276] opened 2021-10-07 11:56 UTC
**Describe the bug**
multipass VM unable to access the internet if host machine connected to an openVPN connection. 
It's unclear whether this is an issue with Ubuntu's multipass networking, or something similar to https://github.com/sshuttle/sshuttle/issues/188#issuecomment-345207791

Tried asking this [here](https://askubuntu.com/questions/1367915) but didn't have much luck.

**To Reproduce**
Connect to a VPN on the host macOS machine (I'm using openVPN Connect)
Try to access the internet from a multipass VM
Fail.

While disconnected from VPN on the macOS host, cka is the name of the VM

**Expected behavior**
What did you expect to happen?

multipass VM connects to the internet over the hosts VPN connection.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

[cka-hyperkit.log](https://github.com/canonical/multipass/files/7302957/cka-hyperkit.log)
[multipassd.log](https://github.com/canonical/multipass/files/7302958/multipassd.log)
[primary-hyperkit.log](https://github.com/canonical/multipass/files/7302959/primary-hyperkit.log)

**Additional info**
```
$ multipass exec cka -- ping 1.1.1.1 -c 5
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=52 time=19.5 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=52 time=19.9 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=52 time=18.6 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=52 time=19.4 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=52 time=24.9 ms

--- 1.1.1.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 18.617/20.449/24.851/2.237 ms
While connected to the VPN

$ multipass exec cka -- ping 1.1.1.1 -c 5
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=52 time=19.5 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=52 time=19.9 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=52 time=18.6 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=52 time=19.4 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=52 time=24.9 ms

--- 1.1.1.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 18.617/20.449/24.851/2.237 ms
rtweed-tm01046-mbp:~ rtweed$ multipass exec cka -- ping 1.1.1.1 -c 5
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.

--- 1.1.1.1 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4535ms
System

macOS 11.6 x86

$ multipass --version
multipass  1.7.2+mac
multipassd 1.7.2+mac

$ multipass info cka
Name:           cka
State:          Running
IPv4:           192.168.64.2
                172.17.0.1
Release:        Ubuntu 20.04.3 LTS
Image hash:     99e25e6e344e (Ubuntu 20.04 LTS)
Load:           0.27 0.20 0.12
Disk usage:     2.2G out of 4.7G
Memory usage:   189.9M out of 981.3M
Mounts:         --
VPN client in use

$ /Applications/OpenVPN\ Connect.app/Contents/MacOS/OpenVPN\ Connect --version
{
  "build-number": "4000",
  "version": "3.3.1"
}
ifconfig output post connection to the VPN

$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
    options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
    inet 127.0.0.1 netmask 0xff000000
    inet6 ::1 prefixlen 128
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
    nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether ac:de:48:00:11:22
    inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x4
    nd6 options=201<PERFORMNUD,DAD>
    media: autoselect (100baseTX <full-duplex>)
    status: active
ap1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    options=400<CHANNEL_IO>
    ether a6:83:e7:9c:41:b2
    nd6 options=201<PERFORMNUD,DAD>
    media: autoselect
    status: inactive
en0: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=400<CHANNEL_IO>
    ether a4:83:e7:9c:41:b2
    inet6 fe80::1cfc:ae09:ce99:480f%en0 prefixlen 64 secured scopeid 0x6
    inet 10.102.190.54 netmask 0xffff8000 broadcast 10.102.255.255
    nd6 options=201<PERFORMNUD,DAD>
    media: autoselect
    status: active
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=400<CHANNEL_IO>
    ether a2:03:73:db:f3:e8
    inet6 fe80::a003:73ff:fedb:f3e8%awdl0 prefixlen 64 scopeid 0x7
    nd6 options=201<PERFORMNUD,DAD>
```

**Additional context**

**Comment by Saviq** [comment] 2021-10-07 12:01
Hi @RichardoC, thanks for a detailed report!

You need to configure your VPN in a way to allow traffic from Multipass instances. We can't be messing with your firewall / VPN settings and there's just too many solutions out there to even document.

For OpenVPN people [have reported](https://github.com/canonical/multipass/issues/495#issuecomment-448461250) this to work:

> Not sure if this is a workaround or solution, but I was able to make this work by nat-ing the multipass bridge with my vpn interface. I added `nat on utun1 from bridge100:network to any -> (utun1)` to file `/etc/pf.conf`. Then I reloaded the file: `$ sudo pfctl -f /etc/pf.conf`.

**Comment by Saviq** [comment] 2021-10-07 12:01
Duplicate of #1121

**Closed by Saviq** 2021-10-07 12:01 UTC
