### ISSUE TITLE
Allow users to specify cloud-init network-config for VMs

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#1034] opened 2019-09-09 21:07 UTC
In addition to user data, cloud-init can process network metadata from data sources that specifies how networking in the launched instance should be configured. It would be great if multipass exposed this to users, so that they can more easily experiment with, and use for real cases, cloud-init's network configuration functionality.

**Comment by Saviq** [comment] 2019-09-10 08:24
Hi @OddBloke IIUC could you describe in more detail how would this work in your mind? Other than allowing configuration of more than one network interface, what else would you see a first-class citizen in Multipass?

Note we're planning to add bridged networking (#118), but we do rely on network connectivity with the instance for most of Multipass functionality (`shell`, `mount`, `exec`, `transfer` etc.), so if your network config in user-data breaks that, you're kinda on your own…

**Comment by OddBloke** [comment] 2019-09-10 12:09
> Hi @OddBloke IIUC could you describe in more detail how would this work in your mind? Other than allowing configuration of more than one network interface, what else would you see a first-class citizen in Multipass?

So, I'd simply like to be able to do something like:

```shell
cat << EOF > network.yaml
version: 2
...
EOF

multipass launch xenial --network-config network.yaml
```

and have that passed into cloud-init as network metadata. This is similar to `lxc launch -c user.network-config="$(cat network.yaml)" ...`.

> Note we're planning to add bridged networking (#118)

This is something of an aside, but I wouldn't expect this to require any different network configuration than the fallback "DHCP on first interface" inside the guest. Am I mistaken? If not, then I think this is orthogonal to the issue at hand.

> but we do rely on network connectivity with the instance for most of Multipass functionality (shell, mount, exec, transfer etc.), so if your network config in user-data breaks that, you're kinda on your own…

Yeah, this is a danger, for sure. Obviously you _could_ break things with user-data today (e.g. `#cloud-config\nruncmd: rm -rf /`), but I agree that it's less likely than with network configuration. I think it would be fine if this configuration option weren't immediately obvious to users, because I don't think _most_ people will want it, and then people who are using it will have opted into the pain.

**Comment by Saviq** [comment] 2019-09-10 13:39
@OddBloke we'd probably also need `--network-interfaces`? Otherwise you'd only be able to configure the one that we give you "by default"?

It's not really orthogonal to bridged networking, as each hypervisor handles networking differently, you'd need to be able to decide which NICs get connected how. We have to design the whole feature together, IMO.

**Comment by OddBloke** [comment] 2019-09-10 13:53
> we'd probably also need at least --network-interfaces <count>? Otherwise you'd only be able to configure the one that we give you by default?

I certainly wouldn't object to being able to add more network interfaces, that would be a great feature that I would definitely use, but I do think that's orthogonal to this ask. You can happily configure a bunch of internal-to-the-VM networking using only the one external interface that multipass currently gives you.

> It's not really orthogonal to bridged networking, as each hypervisor handles networking differently

No matter the hypervisor, I would expect a bridged interface to still present to userspace as one NIC that should be DHCP'd on, which is exactly the same in-instance behaviour as non-bridged networking today.

> you'd need to be able to decide which NICs get connected how

It's not clear to me that bridging implies more than one NIC, so perhaps you're using "bridged networking" as a stand-in for more general networking features?

> We have to design the whole feature together, IMO.

I agree that any complex networking configuration _in multipass_ would require substantial, thoughtful design. But this request is only intended to ask for a way to specify network-config text that will be presented directly to cloud-init, so I've updated the title a little to reflect that.

This would not (and should not) give us first-class multipass networking support.

**Comment by Saviq** [comment] 2019-09-10 14:00
ACK!

**Comment by Saviq** [comment] 2019-09-18 12:59
@OddBloke would solving #1040 help you with this?

**Comment by OddBloke** [comment] 2019-09-18 13:01
Depending on the interface decided on for that feature, it certainly could!

**Comment by Saviq** [comment] 2019-09-18 13:17
@OddBloke I think it would simply be a `multipass launch --cloud-init-tree <folder>` that you could populate.

**Comment by OddBloke** [comment] 2019-09-18 13:29
And that would be exactly the contents of the ISO that gets mounted?

**Comment by Saviq** [comment] 2019-09-18 14:53
@OddBloke yeah, ± `{vendor,user}-data`, will have to decide on precedence.

**Comment by OddBloke** [comment] 2019-09-18 15:20
Yeah, then that does sound like it would probably do the trick!

**Comment by Saviq** [comment] 2019-09-18 15:28
I'll mark it as:

Duplicate of #1040

**Closed** 2019-09-18 15:28 UTC
Labels: help wanted, good first issue
