### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by jslawler** [canonical/multipass#1691] opened 2020-08-15 01:08 UTC
**Describe the bug**
Installer fails to install product.

**To Reproduce**
How, and what happened?
1. Double-click installer
2. Proceed through default installation instructions
3. Installer fails at install stage

**Expected behavior**
Product installs

**Logs**
[Install.log](https://github.com/canonical/multipass/files/5077965/Install.log)

**Additional info**
 - OS: macOS 11.0 Beta (20A5343j)
- `multipass version` 1.4.0

**Comment by puccaso** [comment] 2020-08-15 15:44
ditto

**Comment by Saviq** [comment] 2020-08-20 09:20
Duplicate of #1664

I'll collect all the macOS 11 issues under this one: #1664

**Comment by Saviq** [comment] 2020-08-20 09:21
Duplicate of #1664

**Closed by Saviq** 2020-08-20 09:20 UTC
Labels: bug
