### ISSUE TITLE
Wrong version being set when building from master

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#713] opened 2019-04-04 13:48 UTC
After the release/0.6 branch was merged, the version is now being set to `v0.6.0-37-ge59f178` and not with the `v0.7.0-dev` tag.  This is because `git describe` uses the first tag is finds, in which case is `v0.6.0` now.

We'll instead need to come up with some way to find the newest **versioned** tag and then add the number of commits and the git hash to that.  I don't think `git describe` can do that.

**Comment by ricab** [comment] 2019-04-04 14:42
I had a look and I believe there are actually two problems here:

1. non-annotated tags not being considered (or, alternatively, tag 0.7.0-dev not annotated)
2. both parents of merge commits are being considered

So `git describe --tags --first-parent` seems to give what we want.

**Comment by ricab** [comment] 2019-04-04 14:45
Of course the command above only works if we always follow the same pattern: tagging the dev commit directly in master, but having the release commit tagged in a separate branch and merged into master.

**Comment by Saviq** [comment] 2019-04-09 09:42
Yeah I was thinking we might fall into this, and that `--first-parent` would be the solution. It might not work as intended on the `full` branch though.

**Comment by Saviq** [comment] 2019-04-09 09:48
I'll have a play with this, but it seems that we can use `--exact` to get the release version, and if that's not found, use `--match *-rc --match *-dev` to handle those cases. That should work across the board.

**Closed** 2019-04-10 11:42 UTC
