### ISSUE TITLE
It  is taking (too much time) time to get IP assigned, as a result, timeout happens while starting multipass

### ISSUE THREAD

**Issue by RamuRChenchaiah** [canonical/multipass#1374] opened 2020-02-20 13:01 UTC
Details:

Sequence:
- multipass installed successfully,
- configured successfully
- while starting, the below failure happened

We get : 
```
id_rsa_microcloud & id_rsa_microcloud.pub keys generated successfully
config/microcloud-cloud-init.yaml Generated for microcloud
launch failed: The following errors occurred:
microcloud: timed out waiting for response
```

Would you please help ?

**Comment by rajasoun** [comment] 2020-02-20 14:11
I am having the same issue - its on windows laptop

**Comment by townsend2010** [comment] 2020-02-26 16:30
Hi @RamuRChenchaiah,

I'm not sure where the
```
id_rsa_microcloud & id_rsa_microcloud.pub keys generated successfully
config/microcloud-cloud-init.yaml Generated for microcloud
```
lines come from and it's not clear what your cloud-init config looks like.  I know it's arbitrary and we have a bug to fix it, but the timeout to establish an ssh connection is 2 minutes.  It seems like your generated cloud-init either does some long running operations before ssh is enabled or it has an error which can also cause this issue.

**Comment by kush-daga** [comment] 2020-03-29 16:13
I'm having the  same issue with windows 10
![image](https://user-images.githubusercontent.com/40840079/77854173-41f27380-7206-11ea-8b23-b22578216726.png)

**Comment by Saviq** [comment] 2020-03-29 17:45
Hi @kush-daga that "N/A" value suggests you're using VirtualBox? The default networking support in VirtualBox does not allow for "real" IP addresses - so it doesn't make sense to show it here. You should still be able to `multipass shell on-rattler`, though.

Can you please file [a separate issue here](https://github.com/canonical/multipass/issues/new?template=bug_report.md&labels=bug) for the timeout issue?

**Comment by Saviq** [comment] 2020-03-29 17:45
I'm going to close this for now as we've not received a reply from @RamuRChenchaiah.

**Closed by Saviq** 2020-03-29 17:45 UTC
Labels: question

**Comment by kush-daga** [comment] 2020-03-29 18:45
I guess this was the timeout issue thread? And alright I'll do it that way, yes I agree that it was a virtual box issue, but is there anyway then to connect via ssh to my enviroment?

**Comment by Saviq** [comment] 2020-03-30 08:21
Hi @kush-daga not with the VirtualBox driver, since the network it creates by default is confined to the virtual machine - the outside world does not "see" it at all. See [VBox's documentation on the matter](https://www.virtualbox.org/manual/ch06.html).

We'll be working on adding support for bridged networking (#118), which will make it possible for the instances to appear on your physical network.

And I asked you to file a separate issue so that we can track it separately - there's no reason (at the moment) to think it's the same problem. You providing us with more data (logs, for example) would help tracking it down.

**Comment by kush-daga** [comment] 2020-03-31 08:56
@Saviq surprisingly, the error is not happening now, dont know what fixed it. If I am able to reproduce it ill put up an issue

**Comment by kush-daga** [comment] 2020-03-31 09:03
I created an issue #1455 @Saviq

**Comment by RamuRChenchaiah** [comment] 2020-04-20 05:52
Thank you, All.
Below tries helped us:
- Using a different network (home/office/mobile)
- Removing virtual box from our local setup.
