### ISSUE TITLE
Export a Multipass-VM to a .QCOW2 file

### ISSUE THREAD

**Issue by jrmejiaa** [canonical/multipass#1364] opened 2020-02-15 19:56 UTC
I was working with `Multipass` to create a VM machine of Ubuntu Bionic. I have made a lot of changes to the initial installation (one includes kernel changes) and that's why I would like to export in a QCOW2 image, because I need to recreate this environment in the Google Cloud Platform. From this [question](https://askubuntu.com/questions/1180895/import-export-vms-from-multipass) with a similar topic, @townsend2010 said that there were not a easy way to do it, but maybe there is a "hard" way to do it? Thanks

PS: Sorry if I copy the question here, but I haven't received a response in askubuntu

**Comment by Saviq** [comment] 2020-02-17 08:33
Hi @jrmejiaa, it somewhat depends on your host, but on Linux and macOS the image _is_ a QCOW2 one, sitting under `/var/snap/multipass/` and `/var/root/Library/Application Support/com.canonical.multipass/` (uncompressed), respectively. On Windows it's a VHDX image that you'd have to convert back to QCOW2.

But more importantly, it's not trivial (or clear) what exactly you'd need to do to make it generic again, so that it boots in the cloud.

[Packer](http://packer.io/) is a tool designed to do just that - rebuild an image into a clean one, making any changes to it necessary along the way. I've [explored how Multipass images can be prepared](https://discourse.ubuntu.com/t/building-multipass-images-with-packer/12361) using Packer, which could be a good starting point.

Things to consider:
- authorized SSH keys
- MAC addresses
- cloud-init state

Let us know how it goes!

**Comment by Saviq** [comment] 2020-02-17 08:34
I'm going to close this in favour of the more generic #208, though.

**Comment by Saviq** [comment] 2020-02-17 08:34
Duplicate of #208.

**Closed by Saviq** 2020-02-17 08:34 UTC

**Comment by Saviq** [comment] 2020-02-19 17:20
Also related: #1271.
