### ISSUE TITLE
Multipass Launch failed: timed out waiting for response

### ISSUE THREAD

**Issue by Luckisagu** [canonical/multipass#3718] opened 2024-10-05 11:21 UTC
**Describe the bug**
Every time I try to launch an instance in multipass, its state is unknown and I cannot start it.
When it try to launch it, it gives me the message:
"launch failed: The following errors occurred:
primary: timed out waiting for response"

**To Reproduce**
How, and what happened?
1. type "multipass launch -n primary" on the terminal or launching an instance in the app's GUI

**Expected behavior**
I expected the program to launch a virtual machine and a usable ubuntu shell

**Logs**

[2024-10-05T18:05:19.211] [debug] [blueprint provider] Loading "anbox-cloud-appliance" v1
[2024-10-05T18:05:19.212] [debug] [blueprint provider] Loading "charm-dev" v1
[2024-10-05T18:05:19.213] [debug] [blueprint provider] Loading "docker" v1
[2024-10-05T18:05:19.214] [debug] [blueprint provider] Loading "jellyfin" v1
[2024-10-05T18:05:19.214] [debug] [blueprint provider] Loading "minikube" v1
[2024-10-05T18:05:19.215] [debug] [blueprint provider] Loading "ros-noetic" v1
[2024-10-05T18:05:19.215] [debug] [blueprint provider] Loading "ros2-humble" v1
[2024-10-05T18:05:19.222] [debug] [qemu-system-aarch64] [13177] started: qemu-system-aarch64 --version
[2024-10-05T18:05:19.246] [debug] [qemu-img] [13178] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/noble-20240911/ubuntu-24.04-server-cloudimg-arm64.img
[2024-10-05T18:05:19.262] [debug] [qemu-img] [13179] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-24.04-server-cloudimg-arm64.img 5368709120
[2024-10-05T18:05:19.271] [debug] [qemu-img] [13180] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-24.04-server-cloudimg-arm64.img
[2024-10-05T18:05:19.277] [debug] [qemu-img] [13181] started: qemu-img amend -o compat=1.1 /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-24.04-server-cloudimg-arm64.img
[2024-10-05T18:05:19.282] [debug] [primary] process working dir ''
[2024-10-05T18:05:19.282] [info] [primary] process program 'qemu-system-aarch64'
[2024-10-05T18:05:19.282] [info] [primary] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:ac:02:42, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-24.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/cloud-init-config.iso'
[2024-10-05T18:05:19.284] [debug] [qemu-system-aarch64] [13182] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.ONwZPi
[2024-10-05T18:05:19.312] [info] [primary] process state changed to Starting
[2024-10-05T18:05:19.314] [info] [primary] process state changed to Running
[2024-10-05T18:05:19.314] [debug] [qemu-system-aarch64] [13183] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:ac:02:42 -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-24.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/cloud-init-config.iso
[2024-10-05T18:05:19.314] [info] [primary] process started
[2024-10-05T18:05:19.314] [debug] [primary] Waiting for SSH to be up
[2024-10-05T18:05:19.456] [debug] [primary] QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 2, "major": 8}, "package": ""}, "capabilities": ["oob"]}}

[2024-10-05T18:05:19.481] [debug] [primary] QMP: {"return": {}}

[2024-10-05T18:05:29.577] [debug] [primary] QMP: {"timestamp": {"seconds": 1728126329, "microseconds": 577645}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]/virtio-backend"}}

[2024-10-05T18:06:23.884] [debug] [primary] QMP: {"timestamp": {"seconds": 1728126383, "microseconds": 884381}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

[2024-10-05T18:10:59.057] [debug] [async task] fetch manifest periodically
[2024-10-05T18:10:59.067] [info] [VMImageHost] Did not find any supported products in "appliance"

**Additional info**
 - OS: MacOS 15.0.1
- `multipass version`
multipass   1.14.0+mac
multipassd  1.14.0+mac
- `multipass info`
Name:           primary
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
- `multipass get local.driver`
qemu

**Additional context**
I tried to reinstall MacOS and cleaned the disk but It still does not work.

**Comment by georgeliao** [comment] 2024-10-07 07:27
@LwkPhoenix 
It looks like it is the renowned macos sequoia [issue](https://github.com/canonical/multipass/issues/3661) we had. Can you try the [test package](https://github.com/canonical/multipass/issues/3661#issuecomment-2363403467) and let us know if it fixes that?

**Comment by sharder996** [comment] 2024-10-07 18:08
Duplicate of #3661

**Closed by sharder996** 2024-10-07 18:08 UTC
Labels: needs triage
