### ISSUE TITLE
timed out error at M3Max MacBook Pro

### ISSUE THREAD

**Issue by meishaoqing** [canonical/multipass#3309] opened 2023-11-19 12:35 UTC
I Can't start or launch a VM. My PC is MacBook Pro, the processor is M3 Max, and the system is macOS Sonoma 14.1.1.

The error is: 
start failed: The following errors occurred:
ubuntu128g16g: timed out waiting for response

When I get this error, the 'qemu-system-aarch64' process takes up **100%** of the CPU resources.

**To Reproduce**
How, and what happened?
1. `multipass launch -c 8 -m 16g -d 128g -n ubuntu128g16g`
OR 
1. `multipass start ubuntu128g16g`

**Logs**
[2023-11-19T20:28:22.801] [debug] [qemu-system-aarch64] [40911] started: qemu-system-aarch64 --version
[2023-11-19T20:28:26.688] [debug] [qemu-img] [40912] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/jammy-20231026/ubuntu-22.04-server-cloudimg-arm64.img
[2023-11-19T20:28:27.020] [debug] [qemu-img] [40913] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu128g16g/ubuntu-22.04-server-cloudimg-arm64.img 137438953472
[2023-11-19T20:28:27.040] [debug] [qemu-img] [40914] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu128g16g/ubuntu-22.04-server-cloudimg-arm64.img
[2023-11-19T20:28:27.048] [debug] [ubuntu128g16g] process working dir ''
[2023-11-19T20:28:27.048] [info] [ubuntu128g16g] process program 'qemu-system-aarch64'
[2023-11-19T20:28:27.048] [info] [ubuntu128g16g] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:eb:19:fd, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu128g16g/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 8, -m, 16384M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu128g16g/cloud-init-config.iso'
[2023-11-19T20:28:27.051] [debug] [qemu-system-aarch64] [40915] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.zPYnVE
[2023-11-19T20:28:27.089] [info] [ubuntu128g16g] process state changed to Starting
[2023-11-19T20:28:27.091] [info] [ubuntu128g16g] process state changed to Running
[2023-11-19T20:28:27.091] [debug] [qemu-system-aarch64] [40916] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:eb:19:fd -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu128g16g/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 8 -m 16384M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu128g16g/cloud-init-config.iso
[2023-11-19T20:28:27.091] [info] [ubuntu128g16g] process started
[2023-11-19T20:28:27.091] [debug] [ubuntu128g16g] Waiting for SSH to be up
[2023-11-19T20:28:27.367] [debug] [ubuntu128g16g] QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 0, "major": 8}, "package": ""}, "capabilities": ["oob"]}}

[2023-11-19T20:28:27.415] [debug] [ubuntu128g16g] QMP: {"return": {}}

**Additional info**
- OS: macOS 14.1.1
- `multipass version`: 1.12.2+mac
- `multipass info --all`:
Name:           ubuntu128g16g
State:          Unknown
IPv4:           --
Release:        --
Image hash:     eafa7742ce5f (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
- `multipass get local.driver`:  qemu

**Comment by meishaoqing** [comment] 2023-11-19 12:37
It seems that the qemu-system-aarch64 process is stuck in an infinite loop.

**Comment by luis4a0** [comment] 2023-11-20 12:25
Hi @meishaoqing, thanks for reporting. Are you using a firewall or VPN software on your Mac? Thanks!

**Comment by meishaoqing** [comment] 2023-11-20 12:44
> Hi @meishaoqing, thanks for reporting. Are you using a firewall or VPN software on your Mac? Thanks!

Hi Luis, thanks for your reply. @luis4a0 

![img_v2_4f81f7bc-c1a4-48db-9dca-b47d29291a2l](https://github.com/canonical/multipass/assets/4637443/a6352f87-7dd6-41a7-a7d9-c72f5467dcfd)
I have disabled the firewall, and no VPN software is running. It still didn't work properly and I had to force stop the qemu-system-aarch64 process.

**Comment by luis4a0** [comment] 2023-11-20 13:36
Thanks for confirming @meishaoqing. We are unfortunately having some issues with the M3 processor, we are investigating them.

**Comment by townsend2010** [comment] 2023-11-21 16:55
This is a duplicate of #3308.

**Comment by townsend2010** [comment] 2023-11-21 16:55
Duplicate of #3308.

**Closed by townsend2010** 2023-11-21 16:55 UTC
