### ISSUE TITLE
 Caught an unhandled exception: failed to open file 'C:/Users/xxx/AppData/Roaming/multipass/client-certificate/multipass_cert_key.pem': No such file or directory(2)

### ISSUE THREAD

**Issue by Tumb1eweed** [canonical/multipass#2381] opened 2021-12-25 16:02 UTC
My platform is Windows, and I download and install Multipass, put "Multipass shell" and I got this:
      Caught an unhandled exception: failed to open file 'C:/Users/xxx/AppData/Roaming/multipass/client-certificate/multipass_cert_key.pem': No such file or directory(2)
I find something like this in another path: 
      C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\certificates 
      in this directory there are two files : localhost.pem and localhost_key.pem, is that what Multipass neeed ? Should I set environmental variables to make Multipass accessing these files ?

**Comment by Saviq** [comment] 2022-01-04 16:46
Duplicate of #1314

**Closed by Saviq** 2022-01-04 16:46 UTC
Labels: bug
