### ISSUE TITLE
macOS 11.1 multipass.gui crashes

### ISSUE THREAD

**Issue by richmisat** [canonical/multipass#1896] opened 2020-12-20 03:21 UTC
Removed and reinstalled _multipass  1.5.0+mac_ , but crash persists.  Gui and tray icon never appear.

Normal operations using multipass commands in terminal seem ok.

[multipass.gui_2020-12-19-190202_rm15.crash.zip](https://github.com/canonical/multipass/files/5720446/multipass.gui_2020-12-19-190202_rm15.crash.zip)

Excerpted from attached...
> Process:               multipass.gui [34224]
> Path:                  /Applications/Multipass.app/Contents/MacOS/Multipass
> Identifier:            ???
> Version:               0
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           multipass.gui [34224]
> User ID:               502
> 
> Date/Time:             2020-12-19 19:01:56.744 -0800
> OS Version:            macOS 11.1
> [multipass.gui_2020-12-19-190202_rm15.crash.zip](https://github.com/canonical/multipass/files/5720441/multipass.gui_2020-12-19-190202_rm15.crash.zip)
> 
>  (20C69)
> Report Version:        12
> Bridge OS Version:     3.0 (14Y908)
> Anonymous UUID:        36E0C220-74D1-46CA-4BB7-AE1D1D47F894
> 
> 
> Time Awake Since Boot: 24000 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> dyld2 mode
> abort() called
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libsystem_kernel.dylib        	0x00007fff202ec462 __pthread_kill + 10
> 1   libsystem_pthread.dylib       	0x00007fff2031a610 pthread_kill + 263
> 2   libsystem_c.dylib             	0x00007fff2026d720 abort + 120
> 3   QtCore                        	0x000000011179f259 0x111787000 + 98905
> 4   QtCore                        	0x00000001117a09a4 QMessageLogger::fatal(char const*, ...) const + 202
> 5   QtGui                         	0x0000000111254579 QGuiApplicationPrivate::createPlatformIntegration() + 7321
> 6   QtGui                         	0x000000011125459b QGuiApplicationPrivate::createEventDispatcher() + 27
> 7   QtCore                        	0x000000011196ff1f QCoreApplicationPrivate::init() + 1567
> 8   QtGui                         	0x000000011124f7b9 QGuiApplicationPrivate::init() + 57
> 9   QtWidgets                     	0x00000001107a99aa QApplicationPrivate::init() + 26
> 10                                	0x000000010f3eae8b (anonymous namespace)::main_impl(int, char**) + 75
> 11                                	0x000000010f3eab7f int multipass::top_catch_all<int (*)(int, char**), int&, char**&>(multipass::logging::CString, int (*)(int, char**), int&, char**&) + 95
> 12                                	0x000000010f3eab14 main + 68
> 13  libdyld.dylib                 	0x00007fff20335621 start + 1
> 
>

**Comment by Saviq** [comment] 2020-12-20 12:14
Hi @richmisat, from all that info it sounds like #1248 maybe?

Can you provide the output from running `/Library/Application\ Support/com.canonical.multipass/bin/multipass.gui.app/Contents/MacOS/multipass.gui` directly?

**Comment by richmisat** [comment] 2020-12-22 17:38
Thanks @Saviq . Just read through #1248. The common factor is APFS case sensitive file system.  I'll check to see if adding the symlink to QT solves the issue for me too.

**Comment by Saviq** [comment] 2020-12-23 07:21
Duplicate of #1248

**Closed by Saviq** 2020-12-23 07:21 UTC
Labels: question
