### ISSUE TITLE
MultiPass services and VirtualBox cannot run simultaneously 

### ISSUE THREAD

**Issue by banderlog** [canonical/multipass#1386] opened 2020-02-25 12:14 UTC
Currently it is impossible to use VirtualBox and MultiPass at the same time because VirtualBox machines will fail to start while multipass services are running, due to competition over resources (presumably).

Crash log for VBox machine with multipass services running: <https://gist.github.com/banderlog/1a100d29343fc2483f0caeb56a64ab97>

I've searched for multipass services:

```
user$ systemctl list-units | grep multi
snap-multipass-1597.mount                                                                 loaded active mounted   Mount unit for multipass, revision 1597
snap.multipass.multipassd.service                                                         loaded active running   Service for snap application multipass.multipassd
```

And stopped them:

```
systemctl stop snap.multipass.multipassd.service
systemctl stop snap-multipass-1597.mount
```

VBox machine log after stopping multipass services: <https://gist.github.com/banderlog/798dceaf7bb59dfefffb97bd72ce363d>

VirtualBox 6.1, installed from official repo
multipass Rev 1597,  installed via `snap`
Ubuntu 18.04 LTS

**Comment by townsend2010** [comment] 2020-02-26 15:43
Yes, this is a duplicate of #1289.  If `qemu` is running, then VirtualBox cannot run and vice versa.  This is not an issue in Multipass, but is just a problem in general.  The solution would be for Multipass to use VirtualBox as a backend as that bug is requesting.

**Closed by townsend2010** 2020-02-26 15:43 UTC
