### ISSUE TITLE
macOS Big Sur 11.2.2 fail to launch multipass 1.6.2+mac

### ISSUE THREAD

**Issue by sudo8com** [canonical/multipass#2060] opened 2021-04-16 16:20 UTC
**Describe the bug**
Describe what your problem is.
Unable to start Ubuntu new macOS Big Sur 11.2.2
**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

==> multipassd.log <==
[2021-04-17T00:15:35.990] [debug] [primary] process working dir ''
[2021-04-17T00:15:35.990] [info] [primary] process program '/Library/Application Support/com.canonical.multipass/bin/hyperkit'
[2021-04-17T00:15:35.990] [info] [primary] process arguments '-c, 1, -m, 1024M, -u, -A, -H, -U, 386bba5a-5dc4-3ac2-95c9-cf0b9a29b352, -s, 0:0,hostbridge, -s, 2:0,virtio-net, -s, 5,virtio-rnd, -s, 31,lpc, -l, com1,autopty=/var/root/Library/Application Support/multipassd/vault/instances/primary/pty,log=/Library/Logs/Multipass/primary-hyperkit.log, -s, 1:0,virtio-blk,file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false, -s, 1:1,ahci-cd,/var/root/Library/Application Support/multipassd/vault/instances/primary/cloud-init-config.iso, -f, kexec,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/vda1 rw panic=1 no_timer_check'
[2021-04-17T00:15:35.990] [info] [primary] process state changed to Starting
[2021-04-17T00:15:36.015] [info] [primary] process state changed to Running
[2021-04-17T00:15:36.147] [error] [primary] Using fd 5 for I/O notifications
[2021-04-17T00:15:36.147] [error] [primary] hv_vm_create unknown error -85377023
[2021-04-17T00:15:36.147] [error] [primary] process error occurred Crashed
[2021-04-17T00:15:36.147] [info] [primary] process state changed to NotRunning
[2021-04-17T00:15:36.147] [info] [primary] process finished with exit code 6

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

==> multipassd.log <==
[2021-04-17T00:15:35.990] [debug] [primary] process working dir ''
[2021-04-17T00:15:35.990] [info] [primary] process program '/Library/Application Support/com.canonical.multipass/bin/hyperkit'
[2021-04-17T00:15:35.990] [info] [primary] process arguments '-c, 1, -m, 1024M, -u, -A, -H, -U, 386bba5a-5dc4-3ac2-95c9-cf0b9a29b352, -s, 0:0,hostbridge, -s, 2:0,virtio-net, -s, 5,virtio-rnd, -s, 31,lpc, -l, com1,autopty=/var/root/Library/Application Support/multipassd/vault/instances/primary/pty,log=/Library/Logs/Multipass/primary-hyperkit.log, -s, 1:0,virtio-blk,file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false, -s, 1:1,ahci-cd,/var/root/Library/Application Support/multipassd/vault/instances/primary/cloud-init-config.iso, -f, kexec,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-20.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/vda1 rw panic=1 no_timer_check'
[2021-04-17T00:15:35.990] [info] [primary] process state changed to Starting
[2021-04-17T00:15:36.015] [info] [primary] process state changed to Running
[2021-04-17T00:15:36.147] [error] [primary] Using fd 5 for I/O notifications
[2021-04-17T00:15:36.147] [error] [primary] hv_vm_create unknown error -85377023
[2021-04-17T00:15:36.147] [error] [primary] process error occurred Crashed
[2021-04-17T00:15:36.147] [info] [primary] process state changed to NotRunning
[2021-04-17T00:15:36.147] [info] [primary] process finished with exit code 6

**Additional info**
 - OS: [e.g. macOS 10.15] macOS Big Sur 11.2.2
- `multipass version` 
multipass  1.6.2+mac
multipassd 1.6.2+mac

- `multipass info --all`
Name:           primary
State:          Starting
IPv4:           --
Release:        --
Image hash:     38b82727bfc1 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
**Additional context**
Fresh installation can't start vm

**Comment by Saviq** [comment] 2021-04-16 16:24
@sudo8com this seems to be the problem: `hv_vm_create unknown error -85377023`… any chance you're running Apple M1? If so, you'll need to wait for #1857.

If not, can you share what hardware you're running?

**Comment by sudo8com** [comment] 2021-04-16 16:28
Thanks :)

**Comment by Saviq** [comment] 2021-04-16 16:39
Duplicate of #1857

**Closed by Saviq** 2021-04-16 16:39 UTC
Labels: question
