### ISSUE TITLE
Disable HyperV dynamic memory

### ISSUE THREAD

**Issue by tomaswarynyca** [canonical/multipass#2192] opened 2021-08-06 00:53 UTC
When creating a new machine the memory is allocated correctly, but it allows having dynamic memory
Which should not be the case. A machine with 2GB ends up consuming 3.5GB.
Can you remove the dynamic memory option?

**Comment by Saviq** [comment] 2021-08-06 06:52
Duplicate of #604

**Closed by Saviq** 2021-08-06 06:52 UTC
Labels: enhancement
