### ISSUE TITLE
The shell scripts on mounted folders doesn't run ''

### ISSUE THREAD

**Issue by amit17051980** [canonical/multipass#1628] opened 2020-07-01 15:13 UTC
Hi,

It is not possible to chmod 775 on mounted shell scripts.
I was using one automation script to execute this way where media is the mounted folder.

```
# Mount the current directory on to created VM
multipass exec -v dctm-16-4 -- mkdir -p /home/ubuntu/media
multipass mount . dctm-16-4:/home/ubuntu/media

# Install Process Engine
multipass exec -v dctm-16-4 -- bash -c ~/media/DCTM-xCP-16.4.0/SetupPE.sh
```

> _**ERROR**_ : bash: /home/ubuntu/media/DCTM-xCP-16.4.0/SetupPI.sh: No such file or directory

**Thanks
Amit Gupta**

**Comment by Saviq** [comment] 2020-07-01 15:36
Hi @amit17051980 what's your host? Is it Windows? If so, that's because Windows does not have an _executable_ bit that we can translate to Linux.

```bash
multipass exec -v dctm-16-4 -- bash -c ~/media/DCTM-xCP-16.4.0/SetupPE.sh
```

You don't want the "-c" there, just have `bash` interpret the file.

**Comment by amit17051980** [comment] 2020-07-01 15:40
Yes, I am running Windows on Mac BootCamp.
This is due to a product requirement. :(

**Comment by Saviq** [comment] 2020-07-01 16:00
Duplicate of #1252

**Closed by Saviq** 2020-07-01 16:00 UTC
Labels: question
