### ISSUE TITLE
Inexplicably unable to connect to the internet

### ISSUE THREAD

**Issue by 2014qirong** [canonical/multipass#2845] opened 2022-12-02 10:34 UTC
unless reboot the mac

**Comment by 2014qirong** [comment] 2022-12-02 10:36
version multipass   1.10.1+mac and Ubuntu 22.04 LTS

**Comment by luis4a0** [comment] 2022-12-02 13:19
Hi @2014qirong, thanks for reporting. You are probably hitting the macOS firewall issue. I closing this as duplicate of https://github.com/canonical/multipass/issues/2387 but don't hesitate in reopening if you determine it's not a firewall issue.

**Closed by luis4a0** 2022-12-02 13:19 UTC
Labels: duplicate
