### ISSUE TITLE
Can't resume a halted new image launch with qemu driver on OSX 11.6

### ISSUE THREAD

**Issue by gbrindisi** [canonical/multipass#2335] opened 2021-11-11 08:30 UTC
**Describe the bug**
Hello :wave:

On OSX 11.6 (not M1) I've switched from hyperkit to qemu as the driver.
Then I tried to launch the new default image but I halted the download (sigint), since then I cannot `launch` successfully again.

**To Reproduce**
How, and what happened?
```
❯ multipass stop --all

~ took 3s
❯ sudo multipass set local.driver=qemu

~

❯ multipass launch impish
One quick question before we launch … Would you like to help
the Multipass developers, by sending anonymous usage data?
This includes your operating system, which images you use,
the number of instances, their properties and how long you use them.
We’d also like to measure Multipass’s speed.

Send usage data (yes/no/Later)? Later
Retrieving image: 1%^C

❯ multipass launch impish
launch failed: Operation canceled

~
❯ multipass launch impish
launch failed: Operation canceled
```

**Expected behavior**
I would expect to be able to successfully resume/retry the download and launch the image

**Logs**
In `multipassd.log` I have these entries, one for every time I try `launch` again:
```
[2021-11-09T18:18:02.455] [debug] [qemu-system-x86_64] [66998] started: qemu-system-x86_64 --version
[2021-11-09T18:18:02.482] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Application Support/multipassd/qemu/multipassd-vm-instances.json"): device not open
[2021-11-09T18:18:44.934] [debug] [qemu-system-x86_64] [67372] started: qemu-system-x86_64 --version
[2021-11-09T18:18:44.955] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Application Support/multipassd/qemu/multipassd-vm-instances.json"): device not open
[2021-11-09T18:18:46.613] [debug] [qemu-system-x86_64] [67424] started: qemu-system-x86_64 --version
[2021-11-09T18:18:46.631] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Application Support/multipassd/qemu/multipassd-vm-instances.json"): device not open
[2021-11-09T18:19:08.963] [debug] [qemu-system-x86_64] [67483] started: qemu-system-x86_64 --version
[2021-11-09T18:19:08.981] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Application Support/multipassd/qemu/multipassd-vm-instances.json"): device not open
[2021-11-09T18:19:23.062] [debug] [qemu-system-x86_64] [68040] started: qemu-system-x86_64 --version
[2021-11-09T18:19:23.090] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Application Support/multipassd/qemu/multipassd-vm-instances.json"): device not open
```

**Additional info**
 - OS: macOS 10.16

```
❯ multipass version
multipass   1.8.0+mac
multipassd  1.8.0+mac

~
❯ multipass info --all


~
```

**Additional context**
It looks like by halting I did not let multipass create the necessary `qemu/` directory to store the instances data:
```
❯ sudo tree "/var/root/Library/Application Support/multipassd"
/var/root/Library/Application\ Support/multipassd
├── certificates
│   ├── localhost.pem
│   └── localhost_key.pem
├── multipass-unique-id
├── multipassd-send-metrics.yaml
├── multipassd-vm-instances.json
├── registered-certs
├── saved_metrics.json
├── ssh-keys
│   └── id_rsa
└── vault
    ├── instances
    │   ├── pious-flycatcher
    │   │   ├── cloud-init-config.iso
    │   │   ├── pty
    │   │   ├── ubuntu-21.10-server-cloudimg-amd64-initrd-generic
    │   │   ├── ubuntu-21.10-server-cloudimg-amd64-vmlinuz-generic
    │   │   └── ubuntu-21.10-server-cloudimg-amd64.img
    │   └── touted-polliwog
    │       ├── cloud-init-config.iso
    │       ├── pty
    │       ├── ubuntu-21.10-server-cloudimg-amd64-initrd-generic
    │       ├── ubuntu-21.10-server-cloudimg-amd64-vmlinuz-generic
    │       └── ubuntu-21.10-server-cloudimg-amd64.img
    └── multipassd-instance-image-records.json

7 directories, 18 files
```

**Comment by gbrindisi** [comment] 2021-11-11 08:53
I suppose this is related: https://github.com/canonical/multipass/issues/2288

**Comment by Saviq** [comment] 2021-11-15 12:54
Duplicate of #2288

**Closed by Saviq** 2021-11-15 12:54 UTC
Labels: bug
