### ISSUE TITLE
Apparmor log messages in journalctl

### ISSUE THREAD

**Issue by tasdomas** [canonical/multipass#1939] opened 2021-01-25 21:07 UTC
**Describe the bug**
Running `journalctl -f` shows a lot of log entries like this:
```
Jan 25 22:57:28 g multipassd[2159]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:117 read_stream(type = 0, timeout = -1):
Jan 25 22:57:28 g multipassd[2159]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:135 read_stream(): num_bytes = 50
Jan 25 22:57:28 g audit[2159]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipassd" name="/etc/ssh/ssh_config" pid=2159 comm="multipassd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan 25 22:57:28 g multipassd[2159]: /root/parts/multipass/src/src/ssh/ssh_process.cpp:135 read_stream(): num_bytes = 0
Jan 25 22:57:28 g kernel: audit: type=1400 audit(1611608248.367:1647): apparmor="DENIED" operation="open" profile="snap.multipass.multipassd" name="/etc/ssh/ssh_config" pid=2159 comm="multipassd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jan 25 22:57:28 g multipassd[2159]: Executing ip -brief -family inet address show scope global.
```
I only observe this if there is at least one running multipass vm.

**To Reproduce**
1. Run a multipass vm.

**Additional info**
 - OS: ubuntu 20.04
- `multipass version`
```
multipass  1.6.0-rc.267+g8595c334
multipassd 1.6.0-rc.267+g8595c334
```
- `multipass info --all`
```
Name:           lp
State:          Stopped
IPv4:           --
Release:        --
Image hash:     3a5f89659c7a (Ubuntu 16.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /home/d/envs/livepatch/livepatch-server => /src/lp
                    UID map: 1000:default
                    GID map: 1000:default

Name:           lp-mojo
State:          Stopped
IPv4:           --
Release:        --
Image hash:     e65e1c605ce4 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           lpc
State:          Stopped
IPv4:           --
Release:        --
Image hash:     645479821de3 (Ubuntu 16.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           lpmojo
State:          Stopped
IPv4:           --
Release:        --
Image hash:     fe3030939822 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           snapcraft-canonical-livepatch-server-admin
State:          Stopped
IPv4:           --
Release:        --
Image hash:     782eaa4ed910 (Ubuntu Snapcraft builder for Core 16)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /home/d/envs/livepatch/livepatch-server/newpatch => /root/project
                    UID map: 1000:0
                    GID map: 1000:0
```

**Additional context**

**Comment by Saviq** [comment] 2021-01-26 11:45
Hi @tasdomas, these are benign and an effect of Multipass being confined as a snap. Is there a problem you're seeing, or are you simply not enjoying the log messages?

I'll mark this as duplicate, as we have an issue for this already.

**Comment by Saviq** [comment] 2021-01-26 11:45
Duplicate of #1939

**Closed by Saviq** 2021-01-26 11:45 UTC
