### ISSUE TITLE
first server replied: Forbidden and now kinetic-server-cloudimg-amd64-disk.img - server replied: Not Found 

### ISSUE THREAD

**Issue by giacosa-franco** [canonical/multipass#2587] opened 2022-05-24 11:31 UTC
**Describe the bug**
Multipass fails for different reasons after the latest updates

**To Reproduce**
How, and what happened?
1. Building core20 image
2. Multipass fails when trying to download image information

**Expected behavior**
What did you expect to happen?
Either for multipass not to fail or to find the image that it needs, it's also not clear to me why building a core20 image its fetching something else

**Logs**
With version 1.9.0 (this happened yesterday)
Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/daily/jammy/current/jammy-server-cloudimg-amd64-disk.img': Error transferring https://cloud-images.ubuntu.com/buildd/daily/jammy/current/jammy-server-cloudimg-amd64-disk.img - server replied: Forbidden

With version 1.9.1 (freshly installed)
2022-05-24T13:22:32+02:00 multipassd[868968]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img: Error transferring https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img - server replied: Not Found
2022-05-24T13:22:32+02:00 multipassd[868968]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img': Error transferring https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img - server replied: Not Found
2022-05-24T13:22:33+02:00 multipassd[868968]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket
2022-05-24T13:22:33+02:00 multipassd[868968]: QIODevice::write (QFile, "/var/snap/multipass/common/cache/multipassd/vault/multipassd-image-records.json"): device not open
2022-05-24T13:22:33+02:00 multipassd[868968]: Starting Multipass 1.9.1
2022-05-24T13:22:33+02:00 multipassd[868968]: Daemon arguments: /snap/multipass/7106/bin/multipassd --verbosity debug --logger platform
2022-05-24T13:22:47+02:00 multipassd[868968]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img: Error transferring https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img - server replied: Not Found
2022-05-24T13:22:47+02:00 multipassd[868968]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img': Error transferring https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img - server replied: Not Found
2022-05-24T13:24:09+02:00 multipassd[868968]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img: Error transferring https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img - server replied: Not Found
2022-05-24T13:24:09+02:00 multipassd[868968]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img': Error transferring https://cloud-images.ubuntu.com/buildd/daily/kinetic/current/kinetic-server-cloudimg-amd64-disk.img - server replied: Not Found

**Additional info**
This was also reported https://bugs.launchpad.net/snapcraft/+bug/1975468 and in my team everybody is experiencing the same issue.

**Comment by townsend2010** [comment] 2022-05-24 12:36
Hi @franco-semioticlabs!

Thanks for the bug report.  The name of an image artifact was changed without our knowledge and broke this.  We have #2585 up which should fix this.  If you are interested in trying it out, you can do:
`$ snap refresh multipass --channel edge/pr2585`

Sorry for your troubles!

**Comment by franco-semioticlabs** [comment] 2022-05-24 12:53
Hi @townsend2010 thanks for your reply.

I'm trying to build `core20` why is that it doesn't just download https://cloud-images.ubuntu.com/buildd/releases/focal/release/focal-server-cloudimg-amd64-disk.img which seems to be available?

**Comment by townsend2010** [comment] 2022-05-24 12:59
Hi @franco-semioticlabs,

Right, so we have to handle these special images differently than the regular cloud images and this exposed another bug in Multipass where we don't handle these error conditions correctly.  There is a protocol used for the other cloud images called `simplestreams` and we will hopefully be moving to that once the support on the image server is in place.  That will essentially fix the bug here as well since that accounts automatically for artifact changes, etc. without breaking other images.

**Closed** 2022-05-24 16:57 UTC

**Comment by rlewkowicz** [comment] 2022-05-31 17:49
@townsend2010 There's still no 1.9.2 for for brew. I'm not throwing stones, but this is becoming increasingly difficult to use. Lots of esoteric issues and regressions from release to release. 

It would almost be fair to advertise this as beta software imo. I put disclaimers on my projects and I wish more did the same. There's just a ton of rough edges with this

**Comment by townsend2010** [comment] 2022-06-06 18:31
@rlewkowicz,

We originally targeted 1.9.2 for Linux *only* thinking that only Linux was affected by this issue.  We were wrong and are now working on 1.9.2 for both macOS and Windows.  We simply made a mistake :slightly_frowning_face: 

Regarding things becoming increasingly difficult to use, severe issues, etc., you've reported one issue that needs fixing but is not critical IMO.  Are all the problems you are seeing already have issues associated with them?  Otherwise, please report *any* issues you encounter.  We are a small team, but they are not ignored.  We simply have to prioritize things.

Thanks!
