### ISSUE TITLE
Different ip addresses for different instances

### ISSUE THREAD

**Issue by K-Hoffmann** [canonical/multipass#1412] opened 2020-03-07 18:19 UTC
Windows Edition Windows 10 Pro
Version 1809
Build 17763.1039

multipass  1.1.0+win
multipassd 1.1.0+win

The instances created by `multipass launch` always get the IP address 10.0.2.15. Is it possible to configure the instances with different ip addresses so that they can communicate with each other, e.g. vm1 10.0.2.15, vm2 10.0.2.16 and vm2 10.0.2.17?

**Comment by Saviq** [comment] 2020-03-09 10:03
Hi @K-Hoffmann, it looks like you're using the VirtualBox backend? That one only supports the "host" mode of networking, meaning the IPs the instances are getting are not reachable from the outside.

At the moment, you'd need to use the Hyper-V backend to have real IPs available.

Please reopen if you're in fact using that.

**Comment by Saviq** [comment] 2020-03-09 10:04
Duplicate of #1262

**Closed by Saviq** 2020-03-09 10:04 UTC
