### ISSUE TITLE
Enable emulation of different architectures for instances

### ISSUE THREAD

**Issue by ZelnickB** [canonical/multipass#2996] opened 2023-03-29 01:20 UTC
**What are you trying to do?**
Create a Multipass instance with an architecture other than that of the host. For example, I'd like to be able to run an (emulated) amd64 Multipass instance on my arm64 device.

**What's your proposed solution?**
As far as I understand, Multipass already uses QEMU, so the simplest solution would probably be to expose QEMU's emulation functionality to the user. Perhaps this could be accomplished with an option added to the `multipass launch` command. For example:
```console
$ multipass launch --architecture amd64 --memory 8G kinetic
```

**Additional context**
This is somewhat related to #2995, but it is not specific to MacOS.

**Comment by luis4a0** [comment] 2023-03-29 11:50
Hi @ZelnickB, this was already reported in #886. We plan to implement it but don't know when.

**Comment by townsend2010** [comment] 2023-11-03 14:35
Duplicate of #886

**Closed by townsend2010** 2023-11-03 14:35 UTC
