### ISSUE TITLE
Lost all multipass instances after update to Win 11 Pro

### ISSUE THREAD

**Issue by tanthdyn** [canonical/multipass#2455] opened 2022-02-23 09:16 UTC
Hi,

After an Win 11 Pro update yesterday (22/Feb) I discovered that no instances are listed anymore.

**Logs**
[Multipass log events.zip](https://github.com/canonical/multipass/files/8123071/Multipass.log.events.zip)

**Additional info**
 - OS: Windows 11 Prod
-  multipass version
multipass   1.8.0+win
multipassd  1.8.0+win
- `multipass info --all`
EMPTY result

** Extra ***
![image](https://user-images.githubusercontent.com/64088554/155290361-26d05409-f195-434a-b4df-5b0473358db6.png)

![image](https://user-images.githubusercontent.com/64088554/155290237-2d67ca79-0a2a-4fd4-b63a-bb9ba28598ba.png)

Thanks for your help.
Tony

**Comment by tanthdyn** [comment] 2022-02-23 09:20
I had a look in the hyper V manager where I saw my instances.
Upon starting the one I used last I got an error.

![image](https://user-images.githubusercontent.com/64088554/155290988-52109e4e-02bb-4b94-8a7d-1a2d4d985775.png)

**Comment by Saviq** [comment] 2022-02-23 09:34
Hi @tanthdyn, sorry about that, you fell victim of #1119 - do you still have your `C:\Windows.old` folder? If so, please see this comment for help:

https://github.com/canonical/multipass/issues/1119#issuecomment-803675750

We'll work on putting our data in a better location ASAP.

**Comment by Saviq** [comment] 2022-02-23 09:34
Duplicate of #1119

**Closed by Saviq** 2022-02-23 09:34 UTC
Labels: bug

**Comment by tanthdyn** [comment] 2022-02-23 10:19
I followed the procedure mentioned on the duplicate issue entry but now my multipass service doesn't start anymore.
![image](https://user-images.githubusercontent.com/64088554/155299855-c1dbb274-7b75-4441-a622-ed8aed70bd37.png)

I rebooted my laptop and restarted the multipass service again > no resolution
I reinstalled the 1.8.0 version > no resolution

Attached : windows application log filtered for multipass events. Restarts from approx 11am CET.
[Multipass log events.zip](https://github.com/canonical/multipass/files/8123467/Multipass.log.events.zip)

**Comment by Saviq** [comment] 2022-02-23 10:56
@tanthdyn unfortunately there's nothing informative there :/

There's mention of wrong permissions when the folder gets moved around, tried fixing those?

You could try launching the service with an extra `--verbosity trace`, that could maybe have a bit more clue. If not, you could also run it from the command line through `PsExec.exe -s multipassd.exe --logger stderr --verbosity trace`. PsExec comes from PsTools.

**Comment by tanthdyn** [comment] 2022-02-23 18:54
I started the service (multipassd using a different port and from a PS admin terminal) and was able to launch a new instance. But I do not see my old instances anymore.

PS C:\Users\tony.anthonis> multipass launch
Launched: credited-flamingo
PS C:\Users\tony.anthonis> multipass list
Name                    State             IPv4             Image
credited-flamingo       Running           172.20.232.90    Ubuntu 20.04 LTS


```
PS C:\WINDOWS\system32>  multipassd.exe -V debug --logger stderr --address localhost:5001
[2022-02-23T12:00:30.944] [debug] [update] Latest Multipass release available is version 1.8.0
[2022-02-23T12:00:31.888] [info] [rpc] gRPC listening on localhost:5001, SSL:on
[2022-02-23T12:00:31.896] [warning] [Qt] QIODevice::write (QFile, "C:\Users\tony.anthonis\AppData\Local\multipassd\cache\vault\multipassd-image-records.json"): device not open
[2022-02-23T12:00:31.896] [info] [daemon] Daemon arguments: C:\Program Files\Multipass\bin\multipassd.exe -V debug --logger stderr --address localhost:5001
[2022-02-23T12:01:53.473] [warning] [process] Process is already in Job, spawned processes will not be cleaned up
[2022-02-23T12:01:53.477] [debug] [powershell.exe] [5184] started: powershell.exe -NoProfile -NoExit -Command -
[2022-02-23T12:01:53.477] [debug] [Hyper-V Health Check] [5184] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty CurrentMajorVersionNumber'
[2022-02-23T12:01:54.165] [debug] [Hyper-V Health Check] [5184] Cmdlet exit status is 'true'
[2022-02-23T12:01:54.165] [debug] [Hyper-V Health Check] [5184] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty ReleaseId'
[2022-02-23T12:01:54.196] [debug] [Hyper-V Health Check] [5184] Cmdlet exit status is 'true'
[2022-02-23T12:01:54.196] [debug] [Hyper-V Health Check] [5184] Cmdlet: 'Get-CimInstance Win32_ComputerSystem | Select-Object -ExpandProperty HypervisorPresent'
```

**Comment by Saviq** [comment] 2022-02-24 08:15
@tanthdyn you need to run it through `PsExec.exe -s` to get in the right environment. Also `Stop-Service Multipass` prior.

**Comment by tanthdyn** [comment] 2022-02-24 11:00
Multipass was not running.
```
PS C:\LABO ENVIRONMENT\PsTools> .\PsExec.exe -s 'C:\Program Files\Multipass\bin\multipassd.exe' --logger stderr --verbosity trace

PsExec v2.34 - Execute processes remotely
Copyright (C) 2001-2021 Mark Russinovich
Sysinternals - www.sysinternals.com


[2022-02-24T11:58:01.745] [trace] [url downloader] Found https://cloud-images.ubuntu.com/releases/streams/v1/index.json in cache: false
[2022-02-24T11:58:01.831] [trace] [url downloader] Found https://multipass.run/static/latest-release.json in cache: false
[2022-02-24T11:58:01.833] [debug] [update] Latest Multipass release available is version 1.8.0
[2022-02-24T11:58:02.536] [trace] [url downloader] Found https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json in cache: false
[2022-02-24T11:58:02.655] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/appliances/streams/v1/index.json in cache: true
[2022-02-24T11:58:02.661] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/appliances/streams/v1/com.ubuntu.appliances:released:download.json in cache: true
[2022-02-24T11:58:02.672] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/SHA256SUMS in cache: true
[2022-02-24T11:58:03.127] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/18/stable/current/SHA256SUMS in cache: true
[2022-02-24T11:58:03.377] [trace] [url downloader] Found https://cloud-images.ubuntu.com/buildd/releases/bionic/release/SHA256SUMS in cache: true
[2022-02-24T11:58:03.661] [trace] [url downloader] Found https://cloud-images.ubuntu.com/buildd/releases/focal/release/SHA256SUMS in cache: true
[2022-02-24T11:58:03.934] [trace] [url downloader] Found https://cloud-images.ubuntu.com/minimal/releases/xenial/release/SHA256SUMS in cache: true
[2022-02-24T11:58:03.935] [trace] [url downloader] Found https://codeload.github.com/canonical/multipass-workflows/zip/refs/heads/main in cache: true
E0224 11:58:03.964000000 10100 ssl_transport_security.cc:808] Invalid private key.
E0224 11:58:03.964000000 10100 ssl_security_connector.cc:263] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0224 11:58:03.964000000 10100 server_secure_chttp2.cc:125] {"created":"@1645700283.964000000","description":"Unable to create secure server with credentials of type Ssl","file":"D:\a\multipass-private\multipass-private\3rd-party\grpc\src\core\ext\transport\chttp2\server\secure\server_secure_chttp2.cc","file_line":108}
error: Failed to start multipass gRPC service at localhost:50051.
C:\Program Files\Multipass\bin\multipassd.exe exited on TAG009443333998 with error code 1.
```

**Comment by tanthdyn** [comment] 2022-02-24 11:16
```
PS C:\LABO ENVIRONMENT\PsTools> netstat -a -b -n -o | Select-String 50051
PS C:\LABO ENVIRONMENT\PsTools>
```

**Comment by Saviq** [comment] 2022-02-24 13:13
@tanthdyn glad I could help! No, there's no default password. You could interrupt the boot process in Hyper-V (frantically tap Tab and Shift right after starting it ;)), though, and set the password through there.
