### ISSUE TITLE
Multipass stopped working after upgrading to MacOS 12.2

### ISSUE THREAD

**Issue by jakule** [canonical/multipass#2416] opened 2022-01-28 18:09 UTC
**Describe the bug**
I updated my MacOS today to 12.2, then multipass stopped working.

**To Reproduce**
How, and what happened?

Looks like multipass is not able to start a VM (commands exits with timeout). Here is an example from `launch`.
```
multipass launch -vvvv -c 6 -m 6G  -d 100G -n ubuntu3
[2022-01-28T12:54:23.911] [debug] [qemu-system-aarch64] [1526] started: qemu-system-aarch64 --version
[2022-01-28T12:54:23.932] [debug] [qemu-img] [1527] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/focal-20220118/ubuntu-20.04-server-cloudimg-arm64.img
[2022-01-28T12:54:23.948] [debug] [qemu-img] [1528] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img 107374182400
[2022-01-28T12:54:23.958] [debug] [qemu-img] [1529] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img
[2022-01-28T12:54:23.964] [debug] [ubuntu3] process working dir ''
[2022-01-28T12:54:23.964] [info] [ubuntu3] process program 'qemu-system-aarch64'
[2022-01-28T12:54:23.964] [info] [ubuntu3] process arguments '-machine, virt,highmem=off, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -nic, vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1, -cpu, cortex-a72, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 6, -m, 6144M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/cloud-init-config.iso'
[2022-01-28T12:54:23.967] [debug] [qemu-system-aarch64] [1530] started: qemu-system-aarch64 -machine virt,highmem=off -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.doyULV
[2022-01-28T12:54:24.008] [info] [ubuntu3] process state changed to Starting
[2022-01-28T12:54:24.010] [info] [ubuntu3] process state changed to Running
[2022-01-28T12:54:24.010] [debug] [qemu-system-aarch64] [1531] started: qemu-system-aarch64 -machine virt,highmem=off -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1 -cpu cortex-a72 -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 6 -m 6144M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/cloud-init-config.iso
[2022-01-28T12:54:24.010] [info] [ubuntu3] process started
launch failed: The following errors occurred:
ubuntu3: timed out waiting for response
```

**Expected behavior**
What did you expect to happen?

I'd expect `multipass` to create a new VM. Instead multipass hangs ends with timeout.

**Logs**
```
[2022-01-28T12:54:23.911] [debug] [qemu-system-aarch64] [1526] started: qemu-system-aarch64 --version
[2022-01-28T12:54:23.932] [debug] [qemu-img] [1527] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/focal-20220118/ubuntu-20.04-server-cloudimg-arm64.img
[2022-01-28T12:54:23.948] [debug] [qemu-img] [1528] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img 107374182400
[2022-01-28T12:54:23.958] [debug] [qemu-img] [1529] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img
[2022-01-28T12:54:23.964] [debug] [ubuntu3] process working dir ''
[2022-01-28T12:54:23.964] [info] [ubuntu3] process program 'qemu-system-aarch64'
[2022-01-28T12:54:23.964] [info] [ubuntu3] process arguments '-machine, virt,highmem=off, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -nic, vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1, -cpu, cortex-a72, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 6, -m, 6144M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/cloud-init-config.iso'
[2022-01-28T12:54:23.967] [debug] [qemu-system-aarch64] [1530] started: qemu-system-aarch64 -machine virt,highmem=off -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.doyULV
[2022-01-28T12:54:24.008] [info] [ubuntu3] process state changed to Starting
[2022-01-28T12:54:24.010] [info] [ubuntu3] process state changed to Running
[2022-01-28T12:54:24.010] [debug] [qemu-system-aarch64] [1531] started: qemu-system-aarch64 -machine virt,highmem=off -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1 -cpu cortex-a72 -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/ubuntu-20.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 6 -m 6144M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/ubuntu3/cloud-init-config.iso
[2022-01-28T12:54:24.010] [info] [ubuntu3] process started
[2022-01-28T12:54:24.010] [debug] [ubuntu3] Waiting for SSH to be up
[2022-01-28T12:54:24.116] [warning] [ubuntu3] qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: Started vmnet interface with configuration:
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: MTU:              1500
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: Max packet size:  1514
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: MAC:              22:4f:00:46:99:ca
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: DHCP IPv4 start:  192.168.64.1
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: DHCP IPv4 end:    192.168.64.254
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: IPv4 subnet mask: 255.255.255.0
qemu-system-aarch64: -nic vmnet-macos,mode=shared,model=virtio-net-pci,mac=52:54:00:fd:89:c1: info: UUID:             0214963A-F4B1-447A-BB69-A74A9DF96F9C

[2022-01-28T12:54:24.116] [warning] [qemu-system-aarch64]
[2022-01-28T12:54:24.116] [debug] [ubuntu3] QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 1, "major": 6}, "package": ""}, "capabilities": ["oob"]}}

[2022-01-28T12:54:24.141] [debug] [ubuntu3] QMP: {"return": {}}

[2022-01-28T12:54:37.857] [debug] [ubuntu3] QMP: {"timestamp": {"seconds": 1643392477, "microseconds": 857700}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[11]/virtio-backend"}}
```

**Additional info**
 - OS: macOS 12.2 M1 Pro
- `multipass version`
```
multipass   1.8.1+mac
multipassd  1.8.1+mac
```

**Comment by Saviq** [comment] 2022-01-28 19:16
Hi @jakule, this would be the unfortunate #2265, I'll add some debugging steps there.

**Comment by Saviq** [comment] 2022-01-28 19:16
Duplicate of #2265

**Closed by Saviq** 2022-01-28 19:16 UTC
Labels: bug
