### ISSUE TITLE
launch failed: The bridging feature is not implemented on this backend on Apple M1 device

### ISSUE THREAD

**Issue by satanch** [canonical/multipass#2506] opened 2022-03-31 23:08 UTC
**Description**
When I'm trying to bridge network I'm getting this message:

```
launch failed: The bridging feature is not implemented on this backend.   
```

**To Reproduce**
```sh
multipass launch --network en0 --network name=bridge0,mode=manual
```

**Additional info**
```
multipass   1.8.1+mac
multipassd  1.8.1+mac
```

**Comment by satanch** [comment] 2022-03-31 23:12
`multipass networks` is also reporting:
```
networks failed: The networks feature is not implemented on this backend.
```

**Comment by gamelife1314** [comment] 2022-04-01 02:14
https://github.com/canonical/multipass/issues/2364

**Comment by Saviq** [comment] 2022-04-01 05:36
Duplicate of #2364

**Closed by Saviq** 2022-04-01 05:36 UTC
Labels: bug
