### ISSUE TITLE
VM instances do not remember mount points

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/multipass#2986] opened 2023-03-22 14:24 UTC
**Describe the bug**

VMs do not remember mount points after `stop`

**To Reproduce**
How, and what happened?
1. I launch a VM using one of these [cloud-init scripts](https://github.com/Abuelodelanada/charm-dev-utils/tree/main/cloud-init):
    ```shell
    $ multipass launch --cloud-init charm-dev-juju-2.9.yaml \
    --timeout 1200 \
    --name charm-dev-juju-29 \
    --memory 4G \
    --cpus 3 \
    --disk 30G \
    --mount /home/jose/trabajos/canonical/repos:/home/ubuntu/repos
    ```
2. After launch is ready I verify that the mount point is used:
    ```shell
    $ multipass info charm-dev-juju-29
    Name:           charm-dev-juju-29
    State:          Running
    IPv4:           192.168.122.10
                    10.231.145.1
                    10.1.82.192
    Release:        Ubuntu 22.04.2 LTS
    Image hash:     345fbbb6ec82 (Ubuntu 22.04 LTS)
    CPU(s):         3
    Load:           0.44 0.99 0.89
    Disk usage:     8.4GiB out of 28.9GiB
    Memory usage:   1.4GiB out of 3.8GiB
    Mounts:         /home/jose/trabajos/canonical/repos => /home/ubuntu/repos
                        UID map: 1000:default
                        GID map: 1000:default
    ```
3. Stop the VM: `$ multipass stop charm-dev-juju-29`
4. Check that mount point is still defined:
    ```
    $ multipass info charm-dev-juju-29
    Name:           charm-dev-juju-29
    State:          Stopped
    IPv4:           --
    Release:        --
    Image hash:     345fbbb6ec82 (Ubuntu 22.04 LTS)
    CPU(s):         --
    Load:           --
    Disk usage:     --
    Memory usage:   --
    Mounts:         /home/jose/trabajos/canonical/repos => /home/ubuntu/repos
                        UID map: 1000:default
                        GID map: 1000:default
    ```
5. Start the VM again: `$ multipass shell charm-dev-juju-29`
6. After the start process is completed, verify that the mount point dissapeared:
    ```shell
    $ multipass info charm-dev-juju-29
    Name:           charm-dev-juju-29
    State:          Running
    IPv4:           192.168.122.10
    Release:        Ubuntu 22.04.2 LTS
    Image hash:     345fbbb6ec82 (Ubuntu 22.04 LTS)
    CPU(s):         3
    Load:           1.62 0.36 0.12
    Disk usage:     8.3GiB out of 28.9GiB
    Memory usage:   219.7MiB out of 3.8GiB
    Mounts:         --
    ```

**Expected behavior**
What did you expect to happen?

I expect that VM remember the mount points

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

Logs: [multipass_22-3-2023.log](https://github.com/canonical/multipass/files/11040960/multipass_22-3-2023.log)

**Additional info**
 - OS: Ubuntu 22.10
- ```shell
   $ multipass version
   multipass   1.11.0
   multipassd  1.11.0
   ```
- ```shell
   $ multipass info charm-dev-juju-29
   Name:           charm-dev-juju-29
   State:          Running
   IPv4:           192.168.122.10
                   10.231.145.1
                   10.1.82.192
   Release:        Ubuntu 22.04.2 LTS
   Image hash:     345fbbb6ec82 (Ubuntu 22.04 LTS)
   CPU(s):         3
   Load:           1.04 0.77 0.52
   Disk usage:     8.6GiB out of 28.9GiB
   Memory usage:   1.4GiB out of 3.8GiB
   Mounts:         --
   ```
- ```shell
   $ multipass get local.driver
   libvirt
  ```

**Additional context**
Add any other context about the problem here.

**Comment by sed-i** [comment] 2023-03-22 15:36
I too encounter this frequently.

**Comment by townsend2010** [comment] 2023-03-22 18:05
Hi @Abuelodelanada!

Thanks for entering this report! Looking through the log you provided, this is occurring during instance start where there is a race between `multipassd` querying `snapd` inside the instance to determine if `multipass-sshfs` is installed and `snapd` actually being ready.  We'll work on a fix for this.

**Comment by townsend2010** [comment] 2023-04-03 17:36
Hey @Abuelodelanada and @sed-i!

I'm unable to reproduce this myself, so I would appreciate it if you could try out a test package and see if it fixes this for you.

`$ snap refresh multipass --channel edge/pr3009`

Thanks!

**Closed** 2023-04-03 23:27 UTC

**Comment by soredake** [comment] 2023-04-12 08:31
I've installed [1.12.0 RC](https://github.com/canonical/multipass/releases/tag/v1.12.0-rc) but unfortunately mount are still not working after first start.

**Comment by townsend2010** [comment] 2023-04-12 11:38
Hi @soredake!

Could you please provide [logs](https://multipass.run/docs/accessing-logs) so I can see if the same issue is occurring or something else?

**Comment by soredake** [comment] 2023-04-12 11:45
@townsend2010 https://github.com/canonical/multipass/issues/3033

**Comment by townsend2010** [comment] 2023-04-12 12:00
Hi @soredake!

Thanks for the pointer to your log.  A quick look through the log shows that the underlying issue you see is not the same as what was the underlying issue in this bug, although the symptoms are the same.  We'll follow up in the other bug you reported and leave this one closed.

**Comment by sed-i** [comment] 2023-09-19 00:36
I am still having this issue with
```
multipass   1.12.2
multipassd  1.12.2
```
[mp.log](https://github.com/canonical/multipass/files/12654425/mp.log)

**Comment by townsend2010** [comment] 2023-09-19 17:57
Hey @sed-i!

Your issue, although the same symptoms, is from a different issue.  I created a new issue at #3232 and we can resume the conversation there.
