### ISSUE TITLE
VM date/time outdated after daemon resumed

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#982] opened 2019-08-19 11:06 UTC
If I leave a vm in running state and quit the daemon, it gets suspended. When launching the daemon again, after a while, the vm is resumed, but with the time out of sync:

```console
ubuntu@in-nighthawk:~$ date
Tue Aug 13 11:25:06 WEST 2019
ubuntu@in-nighthawk:~$ timedatectl
               Local time: Tue 2019-08-13 11:24:57 WEST
           Universal time: Tue 2019-08-13 10:24:57 UTC
                 RTC time: Mon 2019-08-19 10:47:28
                Time zone: Europe/Lisbon (WEST, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

I am not sure whether this happens with any suspending vm, but I would guess so. 

This has perverse effects, such as:

```console
$ multipass mount ~/tmp/ in-nighthawk:/home/ubuntu/tmp
mount failed: Error enabling mount support in 'in-nighthawk'
```

Because, from the daemon's log:

```
[2019-08-19T11:41:16.952] [warning] [daemon] Failed to install 'sshfs', error message: '
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Release file for http://security.ubuntu.com/ubuntu/dists/disco-security/InRelease is not valid yet (invalid for another 5d 21h 19min 52s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/disco-updates/InRelease is not valid yet (invalid for another 5d 21h 20min 4s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/disco-backports/InRelease is not valid yet (invalid for another 5d 21h 20min 27s). Updates for this repository will not be applied.'
```

Doing `sudo systemctl restart systemd-timesyncd.service` gets the clock back in sync. Perhaps we should do that when bringing instances back from the suspended state.

**Comment by ricab** [comment] 2019-08-19 11:22
This may also work (did not try):
```
sudo timedatectl set-ntp off
sudo timedatectl set-ntp on
```

**Comment by Saviq** [comment] 2019-08-19 12:36
It's kinda weird… the clock should be set from the host, maybe we just need to pass a flag to qemu.

And/or maybe we can tell systemd to run pre/post suspend tasks.

**Comment by ricab** [comment] 2019-08-19 14:16
I have seen this a few times before, just now gathered a report.

> the clock should be set from the host

I am not sure exactly how that would go, but the timesync daemon does run in newly launched instances...

```console
multipass@holy-grubworm:~$ systemctl status systemd-timesyncd.service
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-08-19 15:11:32 WEST; 59s ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 591 (systemd-timesyn)
   Status: "Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com)."
    Tasks: 2 (limit: 1152)
   CGroup: /system.slice/systemd-timesyncd.service
           └─591 /lib/systemd/systemd-timesyncd

Aug 19 15:11:32 educated-akita systemd[1]: Starting Network Time Synchronization...
Aug 19 15:11:32 educated-akita systemd[1]: Started Network Time Synchronization.
Aug 19 15:11:35 holy-grubworm systemd-timesyncd[591]: Network configuration changed, trying to establish connection.
Aug 19 15:11:36 holy-grubworm systemd-timesyncd[591]: Network configuration changed, trying to establish connection.
Aug 19 15:11:36 holy-grubworm systemd-timesyncd[591]: Network configuration changed, trying to establish connection.
Aug 19 15:11:36 holy-grubworm systemd-timesyncd[591]: Network configuration changed, trying to establish connection.
Aug 19 15:12:16 holy-grubworm systemd-timesyncd[591]: Timed out waiting for reply from 91.189.89.198:123 (ntp.ubuntu.com).
Aug 19 15:12:17 holy-grubworm systemd-timesyncd[591]: Synchronized to time server 91.189.91.157:123 (ntp.ubuntu.com).
~
```

**Comment by Saviq** [comment] 2019-08-19 14:22
@ricab I mean the virtualized hardware clock. That should just follow the host's actual clock.

**Comment by ricab** [comment] 2019-08-19 14:39
@Saviq and it seems it does &ndash; see the line with `RTC clock` in the first post above. But that does not prevent the system time from being outdated.

**Comment by Saviq** [comment] 2019-08-19 14:54
Right, so we are just lacking something to kick `timesyncd` - I'd expect if we can tell the system we're going to sleep, and then that we've resumed, to DTRT.

**Comment by ricab** [comment] 2019-08-19 15:38
OK, it seems this really only happens when quitting and relaunching the daemon. To reproduce:

1. get vms into running state
2. `multipass shell` into them and check correct date and that `systemctl status systemd-timesyncd.service` did synchronize
3. `snap disable multipass`
4. wait for a couple of minutes
5. `snap enable multipass`
6. repeat 2 &ndash; the system time is now off by a couple of minutes and no further sync took place

I got this with both bionic and disco instances.

**Comment by Saviq** [comment] 2019-09-18 12:39
We should be able to do this via `systemctl` with the suspend / sleep targets.

**Comment by underrun** [comment] 2021-12-10 14:55
not sure if its the same issue but i landed here after searching for problems with multipass and time sync.

my vm's clock was just off by like 12 hours not just a few minutes. only noticed it because its so far outside of reality that auth tooling was not having it.

i'm on mac osx 11.6 running ubuntu 21.10 in multipass 1.8.1

**Comment by ricab** [comment] 2022-02-07 11:13
See https://github.com/canonical/multipass/issues/2430 for a workaround in cloud-init (thanks @dmarkey).

**Comment by ricab** [comment] 2023-05-02 08:09
This may also be relevant: https://github.com/canonical/multipass/issues/3019#issuecomment-1530965415

**Comment by jensb** [comment] 2023-09-27 09:51
This also seems to happen when stopping  & restarting the "multipass" snap process on Ubuntu 22.04.
I am experiencing severe timeshift in my VMs when stopping and restarting them. See also https://askubuntu.com/questions/1486977

**Comment by underrun** [comment] 2023-09-27 14:41
The issue isn't only when the daemon is exited, but also when a vm is running and the host suspends (on mac m1 anyway).

When I close the lid of my mac and the host suspends, my running vms clock is off by about how long the lid was closed. Whenever i open up my mac to use my vms i have to kick the clock.

I've gotten pretty used to it but it's not great. I keep thinking about putting something in cron or that runs when my prompt is rendered, but all that feels too wrong and i just manually do it all the time.

**Comment by jensb** [comment] 2023-09-30 11:27
This helps (in the VM):

echo "PollIntervalMinSec=10" >> /etc/systemd/timesyncd.conf
echo "PollIntervalMaxSec=30" >> /etc/systemd/timesyncd.conf

**Closed** 2024-01-10 04:31 UTC

**Comment by agmt** [comment] 2024-06-21 06:19
`PollIntervalMinSec` can't be less than 16: https://github.com/systemd/systemd/blob/main/src/timesync/timesyncd-conf.c#L114

```
sudo sed -i 's/^#*PollIntervalMinSec=.*$/PollIntervalMinSec=16/g' /etc/systemd/timesyncd.conf
sudo sed -i 's/^#*PollIntervalMaxSec=.*$/PollIntervalMaxSec=30/g' /etc/systemd/timesyncd.conf
```
