### ISSUE TITLE
cloud-init errors should be reported

### ISSUE THREAD

**Issue by freedge** [canonical/multipass#2327] opened 2021-11-06 14:02 UTC
It's more a feature request than a proper bug..

After launching minikube on my laptop

    multipass launch minikube

the VM appears fine and accessible, however due to unrelated issues the DNS service is not working within the VM. There are a lot of errors in cloud-init logs and minikube was not installed. Since the cloud-init runs only at the first boot, the VM is basically unusable and should be destroyed and rebuilt. However multipass still reports

    Launched: minikube                                                              

Is it possible to include some checks at the end of the workflow to validate that the VM is in a usable state?

(multipass v1.8.0 with libvirt driver,  Ubuntu 20.04.3 LTS (Focal Fossa), minikube "latest" - I don't know how to read the version of the workflow)

**Comment by Saviq** [comment] 2021-11-06 18:29
Thanks @freedge. I'll duplicate it to #1039 where we have a better design around cloud-init.

**Comment by Saviq** [comment] 2021-11-06 18:29
Duplicate of #1039

**Closed by Saviq** 2021-11-06 18:29 UTC

**Comment by freedge** [comment] 2021-11-06 22:22
>  due to unrelated issues the DNS service is not working within the VM

again, this is unrelated to this ticket but since I mentioned it, my problem was that dnsmasq picked up upstream DNS servers when starting and kept using these even if they are not available anymore (for example, after disconnecting a VPN). This can be fixed by adding in the network definition:

```
  <dns>
    <forwarder addr='127.0.0.53'/>
  </dns>
```
which will give an option ```server=127.0.0.53``` in dnsmasq.conf, pointing to the systemd-resolved stub listener, which is smart enough to find out which upstream server should be used. Cheers!
