### ISSUE TITLE
multipass disk full

### ISSUE THREAD

**Issue by gokhankocak** [canonical/multipass#1569] opened 2020-05-31 12:34 UTC
Hello,
Where does multipass store its data on Mac OS?
My disk is full and I want to move multipass data to another drive.
Thanks.

**Comment by Saviq** [comment] 2020-06-01 10:39
Hi @gokhankocak, unfortunately there's currently no easy way to move the data away.

It's stored in `/var/root/Library/Application Support/multipassd`, you would have to symlink / use bindfs to have it stored in another location.

**Comment by Saviq** [comment] 2020-06-01 10:39
Duplicate of #566

**Closed by Saviq** 2020-06-01 10:39 UTC
