### ISSUE TITLE
The name of network interface is garbled

### ISSUE THREAD

**Issue by skaifun** [canonical/multipass#1988] opened 2021-03-02 06:57 UTC
**Describe the bug**
The name listed using `multipass networks` is garbled

**To Reproduce**
1. Windows 10 using Chinese language
2. Install multipass for windows
3. Open cmd/powershell, run `multipass networks`
4. The chinese name of network interface is garbled

```
PS C:\Users\someone> multipass networks
Name            Type      Description
WLAN            wifi      Intel(R) Dual Band Wireless-AC 8260
��̫��         ethernet  Intel(R) Ethernet Connection (2) I219-V
```

**Expected behavior**
Expected display like:
```
PS C:\Users\someone> multipass networks
Name            Type      Description
WLAN            wifi      Intel(R) Dual Band Wireless-AC 8260
以太网           ethernet  Intel(R) Ethernet Connection (2) I219-V
```

**Logs**
N/A

**Additional info**
 - OS: Windows 10 - 2004
- `multipass version`
multipass  1.6.2+win
multipassd 1.6.2+win
- `multipass info --all`
Name:           primary
State:          Running
IPv4:           N/A
Release:        Ubuntu 20.04.2 LTS
Image hash:     c5f2f08c6a1a (Ubuntu 20.04 LTS)
Load:           1.21 0.28 0.09
Disk usage:     1.4G out of 4.7G
Memory usage:   118.5M out of 981.3M

**Additional context**
It display correctly in powershell using command `Get-NetAdapter`.
```
PS C:\Users\someone> Get-NetAdapter

Name                  InterfaceDescription                 ifIndex Status     MacAddress        LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
WLAN                      Intel(R) Dual Band Wireless-AC 8260          12 Disconnected A4-34-D9-54-1F-78          0 bps
以太网                    Intel(R) Ethernet Connection (2) I219-V       6 Up           88-88-88-88-87-88         1 Gbps
VirtualBox Host-Only N... VirtualBox Host-Only Ethernet Adapter         5 Up           0A-00-27-00-00-05         1 Gbps
```

**Comment by Saviq** [comment] 2021-03-02 07:44
Hi @skaifun, thanks for the report.

I'll put it under #1314, we have some general problems with Unicode on Windows.

**Comment by Saviq** [comment] 2021-03-02 07:44
Duplicate of #1314

**Closed by Saviq** 2021-03-02 07:44 UTC
Labels: bug
