### ISSUE TITLE
Macos virtualbox cannot connect to instance

### ISSUE THREAD

**Issue by naturedamends** [canonical/multipass#2855] opened 2022-12-13 22:50 UTC
**Describe the bug**
Unable to connect to instance with VirtualBox driver, after some usage. worked find initaly . But somethings went wrong.

I do have a vpn, which may be the culprit

I tried 
```
sudo route -nv add -net 192.168.64.0/24 -interface bridge100
u: inet 192.168.64.0; u: link bridge100:9a.10.e8.1f.b2.64; u: inet 255.255.255.0; RTM_ADD: Add Route: len 140, pid: 0, seq 1, errno 0, flags:<UP,STATIC>
locks:  inits: 
sockaddrs: <DST,GATEWAY,NETMASK>
 192.168.64.0 bridge100:9a.10.e8.1f.b2.64 255.255.255.0
route: writing to routing socket: Network is unreachable
add net 192.168.64.0: gateway bridge100: Network is unreachable
```

**To Reproduce**
How, and what happened?
- set driver VirtualBox
- multipass launch --cpus 2 --mem 10g --network en0
- works 
- something happends 

**Expected behavior**
To be able to connect

**Logs**
```
multipass shell main
shell failed: ssh connection failed: 'Socket error: Connection reset by peer'
```
```
[2022-12-13T22:38:31.550] [debug] [main] Got VMState: running
[2022-12-13T22:38:32.627] [debug] [main] Got VMState: running
[2022-12-13T22:38:33.761] [debug] [main] Got VMState: running
[2022-12-13T22:38:34.428] [debug] [main] Got VMState: running
[2022-12-13T22:38:35.441] [debug] [main] Got VMState: running
[2022-12-13T22:38:36.433] [debug] [main] Got VMState: running
[2022-12-13T22:38:37.628] [debug] [main] Got VMState: running
[2022-12-13T22:38:37.733] [debug] [main] Got VMState: running
[2022-12-13T22:38:57.735] [debug] [base_vm] Error getting extra IP addresses: ssh connection failed: 'Timeout connecting to 127.0.0.1'
[2022-12-13T22:38:58.590] [debug] [main] Got VMState: running
[2022-12-13T22:38:59.425] [debug] [main] Got VMState: running
[2022-12-13T22:39:00.430] [debug] [main] Got VMState: running
[2022-12-13T22:39:01.424] [debug] [main] Got VMState: running
[2022-12-13T22:39:02.440] [debug] [main] Got VMState: running
[2022-12-13T22:39:03.576] [debug] [main] Got VMState: running
[2022-12-13T22:39:04.429] [debug] [main] Got VMState: running

```

```
multipass version && multipass info --all && multipass get local.driver
multipass   1.10.1+mac
multipassd  1.10.1+mac
info failed: ssh connection failed: 'Socket error: Connection reset by peer'
```

**Additional context**

**Comment by naturedamends** [comment] 2022-12-13 22:55
For what ever reason. its just started working, 30 mins after restarting multipass -- ... erm. not sure, if it was booting in the background or whatnot.

**Comment by ricab** [comment] 2022-12-14 11:05
Hi @naturedamends, yes I am afraid VPNs have been known to interfere with Multipass. [This page](https://multipass.run/docs/troubleshoot-networking) may be helpful to pinpoint where the problem is, if you want to try to find a workaround for your particular VPN setup.

I am closing this now, please reopen if you find there is a problem in Multipass itself.

**Closed by ricab** 2022-12-14 11:05 UTC
