### ISSUE TITLE
Icon on mac menubar is squished on multiple displays

### ISSUE THREAD

**Issue by shu-ming** [canonical/multipass#2487] opened 2022-03-23 02:40 UTC
**Describe the bug**
When I connect an external monitor, multipass icon on mac menubar is squished on the inactive focus monitor.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/24264618/159613215-1d7a23c2-ec48-41ac-b9a1-7bdd7c9114f2.png">

The icon on the focused monitor display as normal.
![image](https://user-images.githubusercontent.com/24264618/159612861-42758d49-3d3f-4bdf-80a4-eebff33f01dc.png)

**To Reproduce**
How, and what happened?
Connect macbook to an external monitor
Observe the active and inactive display.

**Expected behavior**
The multipass icon should not be squished.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: mac os 12.2.1
- multipass   1.8.1+mac
- multipassd  1.8.1+mac

**Additional context**

**Comment by Saviq** [comment] 2022-03-23 09:42
Duplicate of #1837

**Closed by Saviq** 2022-03-23 09:42 UTC
Labels: bug
