### ISSUE TITLE
Lots of random "launch failed" errors

### ISSUE THREAD

**Issue by jasonmccallister** [canonical/multipass#1480] opened 2020-04-10 14:34 UTC
**Describe the bug**
I'm building a lot of machines use the same configuration for launch. I am also removing and launching those instances often. Recently I started to get a lot of the following errors, which happens randomly and without making any changes, it starts working as expected.

```
launch failed: The following errors occurred:                                   
timed out waiting for initialization to complete
Error: exit status 2
```

**To Reproduce**
How, and what happened?
1. `multipass launch --name nitro-global --cpus 4 --mem 4G --disk 60G --cloud-init -`
2. wait for the launch initialization to complete
3. See it randomly fails

**Expected behavior**
The instance to be created

**Logs**

```
[2020-04-10T10:20:00.083] [info] [nitro-global] hyperkit: [INFO] resize: adding available clusters (Node ((x 18317) (y 18828) (l Empty) (r Empty) (h 1) (cardinal 512)))
[2020-04-10T10:20:02.307] [info] [nitro-global] hyperkit: [INFO] Allocator: 18570 used; 0 junk; 0 erased; 255 available; 0 copies; 0 roots; 0 Copying; 0 Copied; 0 Flushed; 0 Referenced; max_cluster = 18573
[2020-04-10T10:20:02.307] [info] [nitro-global] hyperkit: [INFO] Allocator: file contains cluster 0 .. 18828 will enlarge file to 0 .. 19340
[2020-04-10T10:20:02.307] [info] [nitro-global] hyperkit: [INFO] resize: adding available clusters (Node ((x 18829) (y 19340) (l Empty) (r Empty) (h 1) (cardinal 512)))
[2020-04-10T10:20:02.411] [info] [nitro-global] hyperkit: [INFO] Allocator: 19082 used; 0 junk; 0 erased; 255 available; 0 copies; 0 roots; 0 Copying; 0 Copied; 0 Flushed; 0 Referenced; max_cluster = 19085
[2020-04-10T10:20:02.411] [info] [nitro-global] hyperkit: [INFO] Allocator: file contains cluster 0 .. 19340 will enlarge file to 0 .. 19852
[2020-04-10T10:20:02.411] [info] [nitro-global] hyperkit: [INFO] resize: adding available clusters (Node ((x 19341) (y 19852) (l Empty) (r Empty) (h 1) (cardinal 512)))
[2020-04-10T10:20:27.429] [warning] [nitro-global] [ssh proc] failed to open session channel: ''
[2020-04-10T10:20:48.591] [warning] [nitro-global] [ssh proc] failed to open session channel: ''
[2020-04-10T10:21:09.734] [warning] [nitro-global] [ssh proc] failed to open session channel: ''
```

**Additional info**
 - OS: macOS 10.15.4
- `multipass  1.1.0+mac`
- `multipassd 1.1.0+mac`

**Comment by jasonmccallister** [comment] 2020-04-13 22:17
This is most likely related to https://github.com/canonical/multipass/issues/1481

Setting the CPUs to 1 seemed to resolve it.

**Comment by Saviq** [comment] 2020-04-14 06:28
Yeah @jasonmccallister we'll work on fixing that ASAP. Thanks for the report.

**Comment by Saviq** [comment] 2020-04-14 06:28
Duplicate of #1481

**Closed by Saviq** 2020-04-14 06:28 UTC
