### ISSUE TITLE
[Multipass] [Network] [Port forwarding],...

### ISSUE THREAD

**Issue by letanloc1998** [canonical/multipass#1918] opened 2021-01-14 02:39 UTC
**Describe the bug**

1. Does Multipass support port forwarding on windows (Hyper-V)?
2. I try to change network in Hyper-V and  `C:\Windows\System32\drivers\etc\hosts.ics` => I can access from other real IP but cmd `multipass info <instance name>` show old IP before => Where Multipass save info instance on windows and how to change it?
3. Error file `C:\Windows\System32\drivers\etc\hosts.ics`. I think some code has bug because I usually see some line wrong format in file  `C:\Windows\System32\drivers\etc\hosts.ics`.
Eg:
```
172.22.27.17 docker-server.mshome.net # 2021 1 4 21 1 45 8 936
172.22.25.95 gcc.mshome.net # 2021 1 3 20 13 56 11 897
28
172.22.16.238 jenkins-server.mshome.net # 2021 1 3 20 13 56 11 881
881
```
> I think `28` `881` is wrong value in file (2 numbers is example)

**To Reproduce**

**Expected behavior**

**Logs**

**Additional info**

**Additional context**

Thank you a lot

**Comment by Saviq** [comment] 2021-01-14 12:26
1. Hi @letanloc1998, #309 is about port forwarding.

2. We're adding bridged networking in the upcoming release, see [the docs](https://multipass.run/docs/additional-networks) for it and you can pick up the release candidate in [the v1.6.0-rc pre-release](https://github.com/canonical/multipass/releases/tag/v1.6.0-rc).

3 . I'm afraid that's Windows's ICS feature going wrong when you use the same name when recreating instances. You're right that the two lines are wrong here. We mention that in [our docs on troubleshooting Windows](https://multipass.run/docs/troubleshooting-networking-on-windows).

I'll mark this as duplicate.

**Comment by Saviq** [comment] 2021-01-14 12:26
Duplicate of #309

**Closed by Saviq** 2021-01-14 12:26 UTC
Labels: bug
