### ISSUE TITLE
Unable to Launch an image using file:// and https:// option outside of Linux

### ISSUE THREAD

**Issue by SunilManika** [canonical/multipass#1029] opened 2019-09-07 02:36 UTC
We have re-used the example (template.json) mentioned in the below link and have created a custom multipass image with packer. 

https://discourse.ubuntu.com/t/building-multipass-images-with-packer/12361

template.json and user-data code
http://paste.ubuntu.com/p/rhmbMq5npN/?_ga=2.124493449.249100637.1567507457-743611631.1566190587
http://paste.ubuntu.com/p/6vbtNXttqZ/?_ga=2.133412493.249100637.1567507457-743611631.1566190587

The image (packer-qemu.img) was created successful with packer. 

When trying to launch the image, I get the below error. 

**`multipass launch file://packer-qemu.img
launch failed: http and file based images are not supported`**

Host Details:
My host OS is macOS Mojave Version: 10.14.6

multipass version
multipass  0.8.0+mac
multipassd 0.8.0+mac

**Comment by SunilManika** [comment] 2019-09-07 03:29
Also, tried with the image mentioned in the below link, however, this fails with the above message. 

https://discourse.ubuntu.com/t/new-way-to-launch-images-other-than-cloud-images-from-simplestreams/6282

`multipass launch http://cdimage.ubuntu.com/ubuntu-core/16/current/ubuntu-core-16-amd64.img.xz
launch failed: http and file based images are not supported`

**Comment by Saviq** [comment] 2019-09-07 17:07
Hi @SunilManika, launching local images is only currently supported on Linux, we're working on how to make this a supported feature cross-platform.

**Comment by Saviq** [comment] 2019-09-18 12:56
Duplicate of #1028

**Closed by Saviq** 2019-09-18 12:56 UTC

**Comment by AnwarShah** [comment] 2019-10-03 07:04
This is ridiculous! You should have made this clear, since you claim that multipass in cross-platform tool!

**Comment by polarapfel** [comment] 2020-03-06 09:14
I agree with some of the comments here.

The documentation mentions nowhere that http and file based images are not supported on certain platforms. This needs to be updated in the documentation.

**Comment by kd303** [comment] 2020-08-28 08:50
It is so frustrating when some of the basic features/bugs are not listed on the site when you download this stuff. If you combined this particular issue with the timeout issue (often default size being 500 MB) , you cant expect the download to complete in 10 sec! I wish these kind of defects which ends up wasting your time are listed upfront when you are download!

**Comment by Saviq** [comment] 2020-08-28 09:10
> It is so frustrating when some of the basic features/bugs are not listed on the site when you download this stuff. If you combined this particular issue with the timeout issue (often default size being 500 MB) , you cant expect the download to complete in 10 sec! I wish these kind of defects which ends up wasting your time are listed upfront when you are download!

Hi @kd303, sorry you're having troubles.

The timeout is _not_ for the whole file. It will time out if no data _at all_ is received in 10s. If you have a different experience, please [file a new issue](https://github.com/canonical/multipass/issues/new?template=bug_report.md).

If you're getting "Network timeout" errors, that suggests something isn't right with your network. If you can't improve that, you could use a proxy between you and the Internet, which Multipass would use.

**Comment by samjay001** [comment] 2020-10-05 08:43
> The timeout is _not_ for the whole file. It will time out if no data _at all_ is received in 10s. If you have a different experience, please [file a new issue](https://github.com/canonical/multipass/issues/new?template=bug_report.md).
> 
> If you're getting "Network timeout" errors, that suggests something isn't right with your network. If you can't improve that, you could use a proxy between you and the Internet, which Multipass would use.

Not everybody have perfect networks, What needs is flag to increase 10s default timeout limit, Something like _--timeout-seconds=30_.

**Comment by samjay001** [comment] 2020-10-05 08:49
Or 

> > The timeout is _not_ for the whole file. It will time out if no data _at all_ is received in 10s. If you have a different experience, please [file a new issue](https://github.com/canonical/multipass/issues/new?template=bug_report.md).
> > If you're getting "Network timeout" errors, that suggests something isn't right with your network. If you can't improve that, you could use a proxy between you and the Internet, which Multipass would use.
> 
> Not everybody have perfect networks, What needs is flag to increase 10s default timeout limit, Something like _--timeout-seconds=30_.

Or image download should resume where it stop, Not start image download from beginning.

**Comment by amzon-ex** [comment] 2020-10-12 08:01
I advocate including this information in the documentation, since it's quite frustrating to face such a situation after having downloaded 300MB+ image file!

**Comment by retr0h** [comment] 2021-05-04 17:19
> Hi @SunilManika, launching local images is only currently supported on Linux, we're working on how to make this a supported feature cross-platform.

@Saviq  Any update on this?  It has been a year.

**Comment by aojie654** [comment] 2021-11-08 01:45
@Saviq Any update on this? Does Multipass support local image now?

**Comment by Saviq** [comment] 2021-11-08 10:27
@aojie654 sorry, no news yet.

**Comment by retr0h** [comment] 2021-11-09 05:20
> @aojie654 sorry, no news yet.

@Saviq I'm starting to think [lima](https://github.com/lima-vm/lima) might be the path forward, esp on Mac OS.

**Comment by madalinignisca** [comment] 2021-12-23 08:49
Still happening on 1.8.0 and the documentation has removed the limitation mentioned.

**Comment by gamelife1314** [comment] 2024-03-21 15:56
does this feature enable in macos ?

**Comment by gonzaotc** [comment] 2024-05-06 22:03
mid 2024 and this still not work on MacOS :(
