### ISSUE TITLE
Failed to start instances

### ISSUE THREAD

**Issue by davehhm** [canonical/multipass#2453] opened 2022-02-21 16:15 UTC
**Describe the bug**
The multipass instances used to be running could not longer be started.

**To Reproduce**
How, and what happened?
1. Created 3 nodes/instances in Multipass and has been working and running for few days. Restarted the machine few time without issue.
2. Today without any multipass or OS update or configuration change. The instances can't be started. Only managed to start one instance once. But now, none of them could be started. It still can't work after I restarted the machine a few times.

**Expected behavior**
Instances should be started successfully.

**Logs**
multipass start node1 -v         
[2022-02-22T00:01:39.462] [warning] [Qt] QProcess: Destroyed while process ("qemu-system-x86_64") is still running.
[2022-02-22T00:02:39.535] [error] [node1] Qemu failed to start: program: qemu-system-x86_64; error: Process operation timed out
start failed: failed to start qemu instance: program: qemu-system-x86_64; error: Process operation timed out

Sometimes i get different errors like below
% multipass start node1 -v              
[2022-02-22T00:12:50.694] [warning] [Qt] QProcess: Destroyed while process ("qemu-system-x86_64") is still running.
[2022-02-22T00:12:50.696] [error] [node1] process error occurred Crashed program: qemu-system-x86_64; error: Process crashed
[2022-02-22T00:12:50.696] [error] [node1] error: program: qemu-system-x86_64; error: Process crashed
[2022-02-22T00:12:50.771] [warning] [Qt] QObject::connect(multipass::Process, Unknown): invalid null parameter
[2022-02-22T00:12:50.771] [warning] [Qt] QObject::connect(multipass::Process, Unknown): invalid null parameter
[2022-02-22T00:12:50.771] [warning] [Qt] QObject::connect(multipass::Process, Unknown): invalid null parameter
[2022-02-22T00:12:50.771] [warning] [Qt] QObject::connect(multipass::Process, Unknown): invalid null parameter
[2022-02-22T00:12:50.771] [warning] [Qt] QObject::connect(multipass::Process, Unknown): invalid null parameter
[2022-02-22T00:12:50.771] [warning] [Qt] QObject::connect(multipass::Process, Unknown): invalid null parameter
start failed: cannot connect to the multipass socket                            
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible

**Additional info**
 - OS: Ubuntu 21.10
 - multipass   1.8.0
 - multipassd  1.8.0

**Comment by Saviq** [comment] 2022-02-21 16:34
Hi @davehhm, could you try the `start` more verbosely, with `-vvvv` even? That would also give you the arguments the qemu process is started with. If the start still fails, could you try running qemu directly along with those arguments? Also, does `dmesg` show anything potentially relevant?

**Comment by davehhm** [comment] 2022-02-21 17:00
> Hi @davehhm, could you try the `start` more verbosely, with `-vvvv` even? That would also give you the arguments the qemu process is started with. If the start still fails, could you try running qemu directly along with those arguments? Also, does `dmesg` show anything potentially relevant?

Thank you @Saviq for your quick reply. Please see more detailed logs as you suggested.

 % multipass start node1 -vvvv
[2022-02-22T00:53:17.868] [debug] [/snap/multipass/6130/bin/check_kvm_support] [126802] started: /snap/multipass/6130/bin/check_kvm_support 
[2022-02-22T00:53:17.947] [trace] [daemon] Loading AppArmor policy:             

#include <tunables/global>
profile multipass.node1.qemu-system-x86_64 flags=(attach_disconnected) {
  #include <abstractions/base>
  #include <abstractions/consoles>
  #include <abstractions/nameservice>

  # required for reading disk images
  capability dac_override,
  capability dac_read_search,
  capability chown,

  # needed to drop privileges
  capability setgid,
  capability setuid,

  network inet stream,
  network inet6 stream,

  # Allow multipassd send qemu signals
  signal (receive) peer=snap.multipass.multipassd,

  /dev/net/tun rw,
  /dev/kvm rw,
  /dev/ptmx rw,
  /dev/kqemu rw,
  @{PROC}/*/status r,
  # When qemu is signaled to terminate, it will read cmdline of signaling
  # process for reporting purposes. Allowing read access to a process
  # cmdline may leak sensitive information embedded in the cmdline.
  @{PROC}/@{pid}/cmdline r,
  # Per man(5) proc, the kernel enforces that a thread may
  # only modify its comm value or those in its thread group.
  owner @{PROC}/@{pid}/task/@{tid}/comm rw,
  @{PROC}/sys/kernel/cap_last_cap r,
  owner @{PROC}/*/auxv r,
  @{PROC}/sys/vm/overcommit_memory r,

  # access to firmware's etc (selectively chosen for multipass' usage)
  /snap/multipass/6130/qemu/* r,

  # for save and resume
  /{usr/,}bin/dash rmix,
  /{usr/,}bin/dd rmix,
  /{usr/,}bin/cat rmix,

  # for restore
  /{usr/,}bin/bash rmix,

  # for file-posix getting limits since 9103f1ce
  /sys/devices/**/block/*/queue/max_segments r,

  # for gathering information about available host resources
  /sys/devices/system/cpu/ r,
  /sys/devices/system/node/ r,
  /sys/devices/system/node/node[0-9]*/meminfo r,
  /sys/module/vhost/parameters/max_mem_regions r,

  # binary and its libs
  /snap/multipass/6130/usr/bin/qemu-system-x86_64 ixr,
  /snap/multipass/6130/{,usr/}lib/{,@{multiarch}/}{,**/}*.so* rm,

  # CLASSIC ONLY: need to specify required libs from core snap
  /{,var/lib/snapd/}snap/core18/*/{,usr/}lib/@{multiarch}/{,**/}*.so* rm,

  # Disk images
  /home/multipass/data/vault/instances/node1/ubuntu-20.04-server-cloudimg-amd64.img rwk,  # QCow2 filesystem image
  /home/multipass/data/vault/instances/node1/cloud-init-config.iso rk,   # cloud-init ISO
}
    
[2022-02-22T00:53:17.947] [debug] [node1] process working dir '/snap/multipass/6130/qemu'
[2022-02-22T00:53:17.947] [info] [node1] process program 'qemu-system-x86_64'   
[2022-02-22T00:53:17.947] [info] [node1] process arguments '--enable-kvm, -cpu, host, -nic, tap,ifname=tap-9f0a4d14af6,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:93:80:5a, -device, virtio-scsi-pci,id=scsi0, -drive, file=/home/multipass/data/vault/instances/node1/ubuntu-20.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /home/multipass/data/vault/instances/node1/cloud-init-config.iso, -loadvm, suspend, -machine, pc-i440fx-focal'
[2022-02-22T00:53:17.947] [info] [node1] Resuming from a suspended state        
[2022-02-22T00:53:17.947] [debug] [daemon] Applied AppArmor policy: multipass.node1.qemu-system-x86_64
[2022-02-22T00:53:17.947] [info] [node1] process state changed to Starting      
[2022-02-22T00:53:17.949] [info] [node1] process state changed to Running       
[2022-02-22T00:53:17.949] [debug] [qemu-system-x86_64] [126819] started: qemu-system-x86_64 --enable-kvm -cpu host -nic tap,ifname=tap-9f0a4d14af6,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:93:80:5a -device virtio-scsi-pci,id=scsi0 -drive file=/home/multipass/data/vault/instances/node1/ubuntu-20.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /home/multipass/data/vault/instances/node1/cloud-init-config.iso -loadvm suspend -machine pc-i440fx-focal
[2022-02-22T00:53:17.949] [info] [node1] process started                        
start failed: The following errors occurred:                                    
node1: timed out waiting for response

**Comment by Saviq** [comment] 2022-02-21 17:06
@davehhm I believe you stumbled on #2374, could you please try with Multipass from edge (`sudo snap refresh multipass --edge`)? Our next release should be out in a few weeks and include this fix.

I'll duplicate to that one, please reopen if that's not the case.

**Comment by Saviq** [comment] 2022-02-21 17:06
Duplicate of #2374

**Closed by Saviq** 2022-02-21 17:06 UTC

**Comment by Saviq** [comment] 2022-02-21 17:07
@davehhm here is a detailed way out of the bind you're in:

https://github.com/canonical/multipass/issues/2371#issuecomment-989035709

**Comment by davehhm** [comment] 2022-02-21 17:11
> @davehhm I believe you stumbled on #2374, could you please try with Multipass from edge (`sudo snap refresh multipass --edge`)? Our next release should be out in a few weeks and include this fix.
> 
> I'll duplicate to that one, please reopen if that's not the case.

@Saviq  Nice. Your advice worked. Thanks. I will stick with edge version and wait for the fix in stable version. 
[2022-02-22T01:10:09.671] [info] [node1] process started
