### ISSUE TITLE
mac multipass lanch failed

### ISSUE THREAD

**Issue by X-777** [canonical/multipass#1874] opened 2020-12-07 09:24 UTC
multipass launch -c 2 -d 10G -m 2G -n podman file:///Users/l/Downloads/ubuntu-20.04-server-cloudimg-amd64.img
launch failed: http and file based images are not supported

**Comment by Saviq** [comment] 2020-12-07 10:39
Hi @X-777, we only currently support launching `file:///` and `http://` images on Linux, we'll have to improve the documentation on that.

I'll mark this as a duplicate of #1593.

**Comment by Saviq** [comment] 2020-12-07 10:39
Duplicate of #1593

**Closed by Saviq** 2020-12-07 10:39 UTC
