### ISSUE TITLE
Bad error message when failed to parse cloud-init YAML: "launch failed: operator[] call on a scalar…"

### ISSUE THREAD

**Issue by alexellis** [canonical/multipass#1237] opened 2019-12-16 19:11 UTC
I'm getting an issue when trying to use the --cloud-init flag on MacOS.

```
$ multipass version
multipass  0.10.0+mac
multipassd 0.10.0+mac
```

Works:

```sh
multipass launch --name openfaas
```

Fails:

```sh
multipass launch --name k3s-1 --cloud-init ./k3s.sh

cat k3s.sh | multipass launch --name k3s-1 --cloud-init -
```

k3s.sh

```sh
#!/bin/sh

curl -SLsf https://get.k3sup.dev | sh

k3sup install --local
```

**Comment by Saviq** [comment] 2019-12-16 19:20
Hi @alexellis, whatever you feed into `--cloud-init` has to be valid YAML, follow the format from [the `cloud-init` docs](http://cloudinit.readthedocs.io/en/latest/topics/examples.html#yaml-examples).

In your case something like this:
```yaml
#cloud-config
runcmd:
- curl -SLsf https://get.k3sup.dev | sh
- k3sub install --local
```

Refer to: [run commands on first boot](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot) in their docs.

Hope this helps! Will close this - please reopen if you think there's a problem still.

**Comment by alexellis** [comment] 2019-12-16 19:55
I think this needs to re-opened re: the error message is not at all helpful?

Do you have plans to allow user-data or a start-up script like most IaaS platforms would offer?

**Comment by townsend2010** [comment] 2019-12-16 20:04
Hi @alexellis,

The error you see comes from a third party submodule called yaml-cpp.  We have an open bug to try to make those exceptions more user friendly.  See #646.

As far as the other request to support user-data or a start-up script, I can't seem to find an enhancement request for this.  If you'd like, you could file one so we can track it :grin:

Thanks!

**Comment by Saviq** [comment] 2019-12-17 19:08
We do have #1040 for supplying files to user-data.

I will reopen this for improving the error message.

**Comment by townsend2010** [comment] 2019-12-17 19:10
@Saviq,

As I mentioned previously, #646 is opened to better handle the rather plain exceptions thrown from yamp-cpp, which is what the problem is here.

**Comment by Saviq** [comment] 2019-12-17 19:11
Oh missed that.

**Comment by Saviq** [comment] 2019-12-17 19:11
Duplicate of #646

**Closed by Saviq** 2019-12-17 19:11 UTC
Labels: help wanted, good first issue
