### ISSUE TITLE
[Apple Silicon M1] Ability to launch a new VM with x86_64 on M1

### ISSUE THREAD

**Issue by vleeuwenmenno** [canonical/multipass#2351] opened 2021-11-22 13:26 UTC
**What are you trying to do?**
I need to run a whole bunch of software that only works on x86_64 at the moment and would like to do this in a VM.
The reason for this is we don't have time to convert our software to aarch64 until 2022 so I have to stick with emulation for now.

But so far I don't see an option here to start a new VM with x86_64 instead of Apple Silicon.

**What's your proposed solution?**
It would be nice to just be able to specify the arch when setting up a new VM as follows:

```
multipass launch --name test --cpus 4 --mem 2G --cpu-architecture x86_64
```

And if you don't specify this it should just pick the host architecture.

**Comment by Saviq** [comment] 2021-11-22 13:30
I'll mark it as duplicate of #886. We have to look into how feasible this is. Don't believe Rosetta can help here, so there's a good chance the performance will be lower than anticipated.

And yeah, on macOS you can run apps with Rosetta 2, that may be a route?

**Comment by Saviq** [comment] 2021-11-22 13:30
Duplicate of #886

**Closed by Saviq** 2021-11-22 13:30 UTC

**Comment by vleeuwenmenno** [comment] 2021-11-22 13:33
@Saviq thnx for the suggestion but no somehow rosetta 2 causes a lot of weird issues with our powerdns setup.
The worst part is that I am the only person in a team of 40 who is using M1 so compatibility is low on the priority list. (The rest use Intel macs)

Anyway I'll go the easy route by just using a VPS for now then ...
