### ISSUE TITLE
segfault when deleting a vm

### ISSUE THREAD

**Issue by panlinux** [canonical/multipass#1272] opened 2019-12-25 19:56 UTC
Hello,

I'm getting this segfault when I delete an existing, stopped, vm:
```
Dec 25 16:54:40 nsnx kernel: [105209.899255] multipassd[21649]: segfault at 0 ip 000055c11bbefa14 sp 00007ffc9ab04f00 error 4 in multipassd[55c11b996000+736000]
Dec 25 16:54:40 nsnx kernel: [105209.899263] Code: 44 24 48 31 c0 8b 47 18 83 f8 07 0f 84 95 00 00 00 8d 50 fc 48 8b bf e8 01 00 00 83 fa 01 76 5e 83 f8 08 74 59 83 f8 02 74 44 <48> 8b 07 ff 90 90 00 00 00 48 8b bb e8 01 00 00 be 30 75 00 00 48
Dec 25 16:54:40 nsnx multipassd[21649]: No mounts to stop for instance "focal-autofs-merge"
Dec 25 16:54:40 nsnx systemd[1]: snap.multipass.multipassd.service: Main process exited, code=dumped, status=11/SEGV
```
The command was:
```
andreas@nsnx:~$ multipass list
Name                    State             IPv4             Image
focal-autofs-merge      Stopped           --               Ubuntu 20.04 LTS
x1                      Running           10.9.185.161     Ubuntu 16.04 LTS
andreas@nsnx:~$ multipass delete focal-autofs-merge 
delete failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible
andreas@nsnx:~$ 
```
This is on eoan:
```
multipass   1.0.1      1555   beta      canonical✓  classic
```

**Comment by OlegSmelov** [comment] 2019-12-26 15:11
Duplicate of https://github.com/canonical/multipass/issues/1266

**Comment by ricab** [comment] 2020-01-06 13:29
Thanks for reporting, looking into it.

**Closed** 2020-01-06 13:29 UTC
Labels: duplicate

**Comment by ricab** [comment] 2020-01-06 18:29
Hi @panlinux, this should fix it:

`snap refresh multipass --channel edge/pr1278`
