### ISSUE TITLE
Using the `ubuntu` group in cloud-init breaks instance access

### ISSUE THREAD

**Issue by hemna** [canonical/multipass#1460] opened 2020-04-01 19:36 UTC
**Describe the bug**
Launching a vm with multipass launch and a cloud-init.yml results in 
multipass launch timing out, even though the vm is up, and the launch
times out waiting for initialization to complete.

**To Reproduce**
How, and what happened?
1. multipass launch -n test --cloud-init ci.yml
 The vm starts up, then gets to the 
"Waiting for initialization to compete". Then it times out.

```
waboring@hpvirt1:~: $  multipass launch -v -v -v -n test -c4 --cloud-init cloud-init.yml bionic
launch failed: The following errors occurred:
timed out waiting for initialization to complete
```

```
waboring@hpvirt1:~: $  multipass info test
Name:           test
State:          Starting
IPv4:           --
Release:        --
Image hash:     fe3030939822 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
```

After I see the "Waiting for initialization to complete"
running multipass info test results in

```
waboring@hpvirt1:~: $  multipass info test
info failed: ssh failed to authenticate: 'Socket error: disconnected'
```

The vm is up, but multipass cannot talk to it.

```
waboring@hpvirt1:~: $  multipass list
Name                    State             IPv4             Image
test                    Running           192.168.122.156  Ubuntu 18.04 LTS
```

I can ssh to the vm
```
waboring@hpvirt1:~: $  ssh waboring@192.168.122.156
The authenticity of host '192.168.122.156 (192.168.122.156)' can't be established.
ECDSA key fingerprint is SHA256:rgCRPLfvUgIqILxbC+6PSnScf2jtQK2SkDDFYj1BpsU.
Are you sure you want to continue connecting (yes/no)? yes
```

My cloud-init.yml
```
waboring@hpvirt1:~: $  cat cloud-init.yml
#cloud-config
#
# Add groups to the system
# The following example adds the ubuntu group with members 'root' and 'sys'
# and the empty group cloud-users.
groups:
  - ubuntu: [root,sys]
  - cloud-users

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: waboring
    primary_group: waboring
    groups: users, ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: 
$6$rounds=4096$uoMTrZpJd$Y0E8aelD7xdb2JAxUwyjK6FHvC0729tj4tlFhnSaSaY2ZIcPPu1ntg5QTR4rrAJ4hg9aua6ZZTxMYZaktdIYp0
```

**Expected behavior**
I expect the cloud-init to complete and multipass to be able to communicate with the vm.

```
waboring@hpvirt1:~: $  multipass info test
info failed: ssh failed to authenticate: 'Socket error: disconnected'
waboring@hpvirt1:~: $  multipass shell test
shell failed: ssh failed to authenticate: 'Socket error: disconnected'
```

**Logs**

```
waboring@hpvirt1:~: $  sudo snap logs -f multipass
2020-04-01T19:29:18Z multipassd[14913]: ssh failed to authenticate: 'Socket error: disconnected'
2020-04-01T19:29:20Z multipassd[14913]: ssh failed to authenticate: 'Socket error: disconnected'
```

**Additional info**
```
waboring@hpvirt1:~: $  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

```
waboring@hpvirt1:~: $  multipass version
multipass  1.1.0
multipassd 1.1.0
waboring@hpvirt1:~: $  multipass info --all
info failed: ssh failed to authenticate: 'Socket error: disconnected'
```

**Additional context**
I have been able to reproduce this with the qemu and libvirt local.driver options.
I have also been able to reproduce this same behavior on mac os as well.

**Comment by Saviq** [comment] 2020-04-02 09:26
Hi @hemna - the problem is the `ubuntu` group you're using. The `default` user, required by Multipass to function, has `ubuntu` as its primary group, so cloud-init then fails to create this user:

```
2020-04-02 09:17:24,742 - __init__.py[DEBUG]: Adding user ubuntu
2020-04-02 09:17:24,742 - util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/bin/bash', '-m']
2020-04-02 09:17:24,747 - util.py[WARNING]: Failed to create user ubuntu
2020-04-02 09:17:24,747 - util.py[DEBUG]: Failed to create user ubuntu
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 481, in add_user
    util.subp(useradd_cmd, logstring=log_useradd_cmd)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2102, in subp
    cmd=args)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['useradd', 'ubuntu', '--comment', 'Ubuntu', '--groups', 'adm,audio,cdrom,dialout,dip,floppy,lxd,netdev,plugdev,sudo,video', '--shell', '/bin/bash', '-m']
Exit code: 9
Reason: -
Stdout: 
Stderr: useradd: group ubuntu exists - if you want to add this user to that group, use -g.
2020-04-02 09:17:24,755 - handlers.py[DEBUG]: finish: init-network/config-users-groups: FAIL: running config-users-groups with frequency once-per-instance
```

The solution (or well, workaround - I'll file an issue with cloud-init) is to remove any mention of the `ubuntu` group from your YAML. You also don't need the `default` user.

Additionally, you need a top-level `ssh_pwauth: true` (see [cloud-init docs on the ssh module](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#ssh)) if you want password authentication. I would recommend key-based authentication, like so:
```yaml
users:
  - name: waboring
    ssh_authorized_keys: ssh-rsa...
    # ...
```

The only thing we could do is to error out if we see the `ubuntu` group being used here. But I'd say what you originally wanted should still work, just that cloud-init can't deal with it.

**Comment by Saviq** [comment] 2020-04-02 09:45
I filed [LP#1870310](https://bugs.launchpad.net/cloud-init/+bug/1870310), will close this for now and reopen if they tell us we're doing it wrong ;)

**Closed by Saviq** 2020-04-02 09:45 UTC
Labels: question
