### ISSUE TITLE
Multipass gui options unreadable

### ISSUE THREAD

**Issue by popey** [canonical/multipass#2044] opened 2021-04-08 11:02 UTC
**Describe the bug**

Indicator GUI menu is unreadable.

**To Reproduce**
Run Kubuntu 21.04 with Breeze Dark theme.
Install multipass
Click the multipass-gui icon
Be unable to read menu items

**Expected behavior**
Be able to read menu items

**Additional info**
 - OS: Kubuntu 21.04
- `multipass version`
```
alan@robot:~$ multipass version
multipass  1.6.2
multipassd 1.6.2
```
- `multipass info --all`
```
alan@robot:~$ multipass info --all
Name:           snapcraft-heroic
State:          Stopped
IPv4:           --
Release:        --
Image hash:     7c5c8f24046c (Ubuntu Snapcraft builder for Core 18)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /home/alan/Source/popey/HeroicGamesLauncher/dist/__snap-amd64 => /root/project
                    UID map: 1000:0
                    GID map: 1000:0
```
![image](https://user-images.githubusercontent.com/1841272/114015914-2d59aa00-9862-11eb-8086-dbcdeb07efd7.png)

**Comment by Saviq** [comment] 2021-04-08 11:08
I'll put it under this umbrella: #2007

**Comment by Saviq** [comment] 2021-04-08 11:08
Duplicate of #2007

**Closed by Saviq** 2021-04-08 11:08 UTC
Labels: bug
