### ISSUE TITLE
multipass silently fails when the groups setting in the cloud-init config file includes the user primary group

### ISSUE THREAD

**Issue by brucejo75** [canonical/multipass#2379] opened 2021-12-23 05:15 UTC
**Describe the bug**
multipass silently fails when the `groups` setting in the cloud-init config file includes the user primary group.
Very frustrating!  Took me quite a while to narrow this down.

**To Reproduce**
1. Copied `/etc/cloud/cloud.cfg` to `fail.cfg` and made minor changes.  Which seem to work fine.
2. Added a new user in the `users:` section assigning itself to its primary group and it fails.

Here is the relevant section of `fail.cfg`:
```yaml
users:
   - default
   - name: fail
     groups: [fail]
```

`multipass launch -n fail --cloud-init fail.cfg`
**Console output**: stuck on:
```
Waiting for initialization to complete
```
**Windows Event Viewer**: full of repeated warnings:
```
[fail] ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'
```
If I try to `multipass shell` it fails with this error:
```
shell failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey
```

So I cannot look at the `config-init` logs on the vm.

Output from `-vvvv` flag, replicates what is dumped to the windows event log but does not include the error event?

<details>
<summary><code>multipass launch -n fail --cloud-init fail.cfg -vvvv</code> <strong>Output</strong></summary>

````
> multipass launch -n fail --cloud-init fail.cfg -vvvv
[2021-12-23T19:32:21.769] [trace] [Hyper-V Health Check] PowerShell arguments: -NoProfile, -NoExit, -Command, -
[2021-12-23T19:32:21.769] [trace] [Hyper-V Health Check] PowerShell working dir ''
[2021-12-23T19:32:21.769] [trace] [Hyper-V Health Check] PowerShell program 'powershell.exe'
[2021-12-23T19:32:21.769] [trace] [Hyper-V Health Check] [0] PowerShell state changed to Starting
[2021-12-23T19:32:21.773] [trace] [Hyper-V Health Check] [0] PowerShell state changed to Running
[2021-12-23T19:32:21.774] [debug] [powershell.exe] [23060] started: powershell.exe -NoProfile -NoExit -Command -
[2021-12-23T19:32:21.775] [debug] [Hyper-V Health Check] [23060] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty CurrentMajorVersionNumber'
[2021-12-23T19:32:22.472] [trace] [Hyper-V Health Check] 10
[2021-12-23T19:32:22.472] [trace] [Hyper-V Health Check] [23060] Output: 10
[2021-12-23T19:32:22.473] [debug] [Hyper-V Health Check] [23060] Cmdlet exit status is 'true'
[2021-12-23T19:32:22.474] [debug] [Hyper-V Health Check] [23060] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty ReleaseId'
[2021-12-23T19:32:22.503] [trace] [Hyper-V Health Check] 2009
[2021-12-23T19:32:22.503] [trace] [Hyper-V Health Check] [23060] Output: 2009
[2021-12-23T19:32:22.505] [debug] [Hyper-V Health Check] [23060] Cmdlet exit status is 'true'
[2021-12-23T19:32:22.506] [debug] [Hyper-V Health Check] [23060] Cmdlet: 'Get-CimInstance Win32_ComputerSystem | Select-Object -ExpandProperty HypervisorPresent'
[2021-12-23T19:32:22.694] [trace] [Hyper-V Health Check] True
[2021-12-23T19:32:22.694] [trace] [Hyper-V Health Check] [23060] Output: True
[2021-12-23T19:32:22.695] [debug] [Hyper-V Health Check] [23060] Cmdlet exit status is 'true'
[2021-12-23T19:32:22.696] [debug] [Hyper-V Health Check] [23060] Cmdlet: 'Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V | Select-Object -ExpandProperty State'
[2021-12-23T19:32:23.374] [trace] [Hyper-V Health Check] Enabled
[2021-12-23T19:32:23.374] [trace] [Hyper-V Health Check] [23060] Output: Enabled
[2021-12-23T19:32:23.375] [debug] [Hyper-V Health Check] [23060] Cmdlet exit status is 'true'
[2021-12-23T19:32:23.376] [debug] [Hyper-V Health Check] [23060] Cmdlet: 'Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor | Select-Object -ExpandProperty State'
[2021-12-23T19:32:24.063] [trace] [Hyper-V Health Check] Enabled
[2021-12-23T19:32:24.063] [trace] [Hyper-V Health Check] [23060] Output: Enabled
[2021-12-23T19:32:24.064] [debug] [Hyper-V Health Check] [23060] Cmdlet exit status is 'true'
[2021-12-23T19:32:24.065] [debug] [Hyper-V Health Check] [23060] Cmdlet: 'Get-Service -Name vmms | Select-Object -ExpandProperty Status'
[2021-12-23T19:32:24.095] [trace] [Hyper-V Health Check] Running
[2021-12-23T19:32:24.095] [trace] [Hyper-V Health Check] [23060] Output: Running
[2021-12-23T19:32:24.096] [debug] [Hyper-V Health Check] [23060] Cmdlet exit status is 'true'
[2021-12-23T19:32:24.132] [trace] [Hyper-V Health Check] [23060] PowerShell state changed to NotRunning
[2021-12-23T19:32:24.133] [debug] [Hyper-V Health Check] [23060] PowerShell finished successfully
[2021-12-23T19:32:28.359] [debug] [qemu-img] [20836] started: qemu-img info C:/WINDOWS/system32/config/systemprofile/AppData/Local/multipassd/cache/vault/images/focal-20211129/ubuntu-20.04-server-cloudimg-amd64.vhdx
[2021-12-23T19:32:28.552] [trace] [fail] PowerShell arguments: Resize-VHD, -Path, C:/WINDOWS/system32/config/systemprofile/AppData/Roaming/multipassd/vault/instances/fail/ubuntu-20.04-server-cloudimg-amd64.vhdx, -SizeBytes, 5368709120
[2021-12-23T19:32:28.552] [trace] [fail] PowerShell working dir ''
[2021-12-23T19:32:28.552] [trace] [fail] PowerShell program 'powershell.exe'
[2021-12-23T19:32:28.552] [trace] [fail] [0] PowerShell state changed to Starting
[2021-12-23T19:32:28.558] [trace] [fail] [0] PowerShell state changed to Running
[2021-12-23T19:32:28.558] [debug] [powershell.exe] [16488] started: powershell.exe Resize-VHD -Path C:/WINDOWS/system32/config/systemprofile/AppData/Roaming/multipassd/vault/instances/fail/ubuntu-20.04-server-cloudimg-amd64.vhdx -SizeBytes 5368709120
[2021-12-23T19:32:32.212] [trace] [fail] [16488] PowerShell state changed to NotRunning
[2021-12-23T19:32:32.213] [debug] [fail] [16488] PowerShell finished successfully
[2021-12-23T19:32:32.213] [trace] [fail] [16488] Output:

[2021-12-23T19:32:32.213] [trace] [fail] PowerShell arguments: -NoProfile, -NoExit, -Command, -
[2021-12-23T19:32:32.213] [trace] [fail] PowerShell working dir ''
[2021-12-23T19:32:32.213] [trace] [fail] PowerShell program 'powershell.exe'
[2021-12-23T19:32:32.214] [trace] [fail] [0] PowerShell state changed to Starting
[2021-12-23T19:32:32.217] [trace] [fail] [0] PowerShell state changed to Running
[2021-12-23T19:32:32.218] [debug] [powershell.exe] [25384] started: powershell.exe -NoProfile -NoExit -Command -
[2021-12-23T19:32:32.218] [debug] [fail] [25384] Cmdlet: 'Get-VM -Name fail'
[2021-12-23T19:32:33.437] [trace] [fail] Get-VM : Hyper-V was unable to find a virtual machine with name "fail".
At line:1 char:1
+ Get-VM -Name fail
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (fail:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
[2021-12-23T19:32:33.437] [trace] [fail] [25384] Output: Get-VM : Hyper-V was unable to find a virtual machine with name "fail".
At line:1 char:1
+ Get-VM -Name fail
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (fail:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
[2021-12-23T19:32:33.438] [debug] [fail] [25384] Cmdlet exit status is 'false'
[2021-12-23T19:32:33.439] [debug] [fail] [25384] Cmdlet: '$switch = Get-VMSwitch -Id C08CB7B8-9B3C-408E-8E30-5E16A3AEB444'
[2021-12-23T19:32:34.130] [trace] [fail]
[2021-12-23T19:32:34.130] [trace] [fail] [25384] Output:
[2021-12-23T19:32:34.131] [debug] [fail] [25384] Cmdlet exit status is 'true'
[2021-12-23T19:32:34.132] [debug] [fail] [25384] Cmdlet: 'New-VM -Name fail -Generation 1 -VHDPath "C:/WINDOWS/system32/config/systemprofile/AppData/Roaming/multipassd/vault/instances/fail/ubuntu-20.04-server-cloudimg-amd64.vhdx" -BootDevice VHD -SwitchName $switch.Name -MemoryStartupBytes 1073741824'
[2021-12-23T19:32:35.852] [trace] [fail] Name State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
---- ----- ----------- ----------------- ------   ------             -------
fail Off   0           0                 00:00:00 Operating normally 9.0
[2021-12-23T19:32:35.852] [trace] [fail] [25384] Output: Name State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
---- ----- ----------- ----------------- ------   ------             -------
fail Off   0           0                 00:00:00 Operating normally 9.0
[2021-12-23T19:32:35.853] [debug] [fail] [25384] Cmdlet exit status is 'true'
[2021-12-23T19:32:35.854] [debug] [fail] [25384] Cmdlet: 'Set-VMProcessor -VMName fail -Count 1'
[2021-12-23T19:32:36.215] [trace] [fail]
[2021-12-23T19:32:36.215] [trace] [fail] [25384] Output:
[2021-12-23T19:32:36.215] [debug] [fail] [25384] Cmdlet exit status is 'true'
[2021-12-23T19:32:36.216] [debug] [fail] [25384] Cmdlet: 'Add-VMDvdDrive -VMName fail -Path "C:/WINDOWS/system32/config/systemprofile/AppData/Roaming/multipassd/vault/instances/fail/cloud-init-config.iso"'
[2021-12-23T19:32:36.422] [trace] [fail]
[2021-12-23T19:32:36.422] [trace] [fail] [25384] Output:
[2021-12-23T19:32:36.422] [debug] [fail] [25384] Cmdlet exit status is 'true'
[2021-12-23T19:32:36.423] [debug] [fail] [25384] Cmdlet: 'Set-VMNetworkAdapter -VMName fail -StaticMacAddress "52:54:00:3f:2b:6e"'
[2021-12-23T19:32:37.115] [trace] [fail]
[2021-12-23T19:32:37.115] [trace] [fail] [25384] Output:
[2021-12-23T19:32:37.116] [debug] [fail] [25384] Cmdlet exit status is 'true'
[2021-12-23T19:32:37.118] [trace] [fail] [25384] Cmdlet: 'Get-VM -Name fail | Select-Object -ExpandProperty State'
[2021-12-23T19:32:37.210] [trace] [fail] Off
[2021-12-23T19:32:37.210] [trace] [fail] [25384] Output: Off
[2021-12-23T19:32:37.210] [trace] [fail] [25384] Cmdlet exit status is 'true'
[2021-12-23T19:32:37.212] [debug] [fail] [25384] Cmdlet: 'Start-VM -Name fail'
[2021-12-23T19:32:38.919] [trace] [fail]
[2021-12-23T19:32:38.919] [trace] [fail] [25384] Output:
[2021-12-23T19:32:38.919] [debug] [fail] [25384] Cmdlet exit status is 'true'
[2021-12-23T19:32:38.920] [debug] [fail] Waiting for SSH to be up
````
</details>

**Expected behavior**
I expect an error to be detected and for the user to be notified.  This case seems easy to detect.  Plus, it would be great if setting up the default user would not fail as a consequence of this.

**Additional info**
 - **OS**: Windows 10 20H2 (OS Build 19042.1415)
- **multipass**: `multipass   1.8.0+win`

**Comment by Saviq** [comment] 2022-01-04 16:34
Hi @brucejo75 we have a design in #1039 to help with this, so I'll duplicate there.

FWIW when extracted, the logs look like this:
```plain
2022-01-04 16:27:26,683 - __init__.py[INFO]: Created new group fail
2022-01-04 16:27:26,683 - __init__.py[DEBUG]: created group 'fail' for user 'fail'
2022-01-04 16:27:26,683 - __init__.py[DEBUG]: Adding user fail
2022-01-04 16:27:26,683 - subp.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'fail', '--groups', 'fail', '-m']
2022-01-04 16:27:26,691 - util.py[WARNING]: Failed to create user fail
2022-01-04 16:27:26,691 - util.py[DEBUG]: Failed to create user fail
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 527, in add_user
    subp.subp(useradd_cmd, logstring=log_useradd_cmd)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 293, in subp
    raise ProcessExecutionError(stdout=out, stderr=err,
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['useradd', 'fail', '--groups', 'fail', '-m']
Exit code: 9
Reason: -
Stdout: 
Stderr: useradd: group fail exists - if you want to add this user to that group, use -g.
2022-01-04 16:27:26,692 - handlers.py[DEBUG]: finish: init-network/config-users-groups: FAIL: running config-users-groups with frequency once-per-instance
2022-01-04 16:27:26,692 - util.py[WARNING]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) failed
2022-01-04 16:27:26,692 - util.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 976, in _run_modules
    ran, _r = cc.run(run_name, mod.handle, func_args,
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 186, in run
    results = functor(*args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py", line 172, in handle
    cloud.distro.create_user(user, **config)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 583, in create_user
    self.add_user(name, **kwargs)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 530, in add_user
    raise e
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 527, in add_user
    subp.subp(useradd_cmd, logstring=log_useradd_cmd)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 293, in subp
    raise ProcessExecutionError(stdout=out, stderr=err,
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['useradd', 'fail', '--groups', 'fail', '-m']
Exit code: 9
Reason: -
Stdout: 
Stderr: useradd: group fail exists - if you want to add this user to that group, use -g.
```

**Comment by Saviq** [comment] 2022-01-04 16:34
Duplicate of #1039

**Closed by Saviq** 2022-01-04 16:34 UTC
Labels: bug

**Comment by Saviq** [comment] 2022-01-04 16:37
It may be worth filing a bug with cloud-init:

https://bugs.launchpad.net/cloud-init/+filebug

Part of the problem is that cloud-init bails and fails to create the default user, rendering the system unreachable by Multipass :/
