### ISSUE TITLE
Unable to set passphrase after upgrading to 1.9.0

### ISSUE THREAD

**Issue by athenacykes** [canonical/multipass#2554] opened 2022-05-05 09:50 UTC
**Describe the bug**
Unable to set passphrase after upgrading to 1.9.0

**To Reproduce**
How, and what happened?
serenity@serenity-ubuntu:~ % sudo multipass set local.passphrase
[sudo] serenity's password:  
Please enter passphrase: 
Please re-enter passphrase: 
set failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.
serenity@serenity-ubuntu:~ % sudo multipass authenticate        
Please enter passphrase: 
authenticate failed: Passphrase is not set. Please `multipass set local.passphrase` with a trusted client.
serenity@serenity-ubuntu:~ % multipass version             
multipass   1.9.0
serenity@serenity-ubuntu:~ % 

**Expected behavior**
Multipass shall allow me to set passphrase after upgrading to 1.9.0.

**Logs**
serenity@serenity-ubuntu:~ % journalctl --unit snap.multipass*            
zsh: no matches found: snap.multipass*

**Additional info**
 - OS: Ubuntu 22.04
- multipass   1.9.0
serenity@serenity-ubuntu:~ % multipass info --all
info failed: The client is not authenticated with the Multipass service.
Please use 'multipass authenticate' before proceeding.

```
May  5 17:38:25 serenity-ubuntu systemd[1]: Started Service for snap application multipass.multipassd.
May  5 17:38:27 serenity-ubuntu multipassd[873]: Unable to determine subnet for the mpqemubr0 subnet
May  5 17:38:27 serenity-ubuntu multipassd[873]: Using AppArmor support
May  5 17:38:27 serenity-ubuntu multipassd[873]: Starting dnsmasq
May  5 17:38:27 serenity-ubuntu multipassd[873]: Applied AppArmor policy: multipass.dnsmasq
May  5 17:38:27 serenity-ubuntu kernel: [    5.856234] audit: type=1400 audit(1651743507.568:62): apparmor="STATUS" operation="profile_load" profile="snap.multipass.multipassd" name="multipass.dnsmasq" pid=1279 comm="apparmor_parser"
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1316] started: dnsmasq --keep-in-foreground --strict-order --bind-interfaces --pid-file --domain=multipass --local=/multipass/ --except-interface=lo --interface=mpqemubr0 --listen-address=10.230.188.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/snap/multipass/common/data/multipassd/network/dnsmasq.leases --dhcp-hostsfile=/var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts --dhcp-range 10.230.188.2,10.230.188.254,infinite --conf-file=/var/snap/multipass/common/data/multipassd/network/dnsmasq-OmkaNi.conf
May  5 17:38:27 serenity-ubuntu dnsmasq-dhcp[1316]: read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1329] started: iptables-nft --wait -t filter --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1384] started: iptables-nft --wait -t nat --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1408] started: iptables-nft --wait -t mangle --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1409] started: iptables-nft --wait -t raw --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1410] started: iptables-legacy --wait -t filter --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1415] started: iptables-legacy --wait -t nat --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1418] started: iptables-legacy --wait -t mangle --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1420] started: iptables-legacy --wait -t raw --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: Using iptables-nft for firewall rules.
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1422] started: iptables-nft --wait -t filter --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: # Warning: iptables-legacy tables present, use iptables-legacy to see them
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1423] started: iptables-nft --wait -t nat --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: # Warning: iptables-legacy tables present, use iptables-legacy to see them
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1424] started: iptables-nft --wait -t mangle --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: # Warning: iptables-legacy tables present, use iptables-legacy to see them
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1425] started: iptables-nft --wait -t raw --list-rules
May  5 17:38:27 serenity-ubuntu multipassd[873]: # Warning: iptables-legacy tables present, use iptables-legacy to see them
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1426] started: iptables-nft --wait -t filter --insert INPUT --in-interface mpqemubr0 --protocol udp --dport 67 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1431] started: iptables-nft --wait -t filter --insert INPUT --in-interface mpqemubr0 --protocol udp --dport 53 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1432] started: iptables-nft --wait -t filter --insert INPUT --in-interface mpqemubr0 --protocol tcp --dport 53 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1440] started: iptables-nft --wait -t filter --insert OUTPUT --out-interface mpqemubr0 --protocol udp --sport 67 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1441] started: iptables-nft --wait -t filter --insert OUTPUT --out-interface mpqemubr0 --protocol udp --sport 53 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1442] started: iptables-nft --wait -t filter --insert OUTPUT --out-interface mpqemubr0 --protocol tcp --sport 53 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1443] started: iptables-nft --wait -t mangle --insert POSTROUTING --out-interface mpqemubr0 --protocol udp --dport 68 --jump CHECKSUM --checksum-fill --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1447] started: iptables-nft --wait -t nat --insert POSTROUTING --source 10.230.188.0/24 --destination 224.0.0.0/24 --jump RETURN --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1448] started: iptables-nft --wait -t nat --insert POSTROUTING --source 10.230.188.0/24 --destination 255.255.255.255/32 --jump RETURN --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1449] started: iptables-nft --wait -t nat --insert POSTROUTING --source 10.230.188.0/24 ! --destination 10.230.188.0/24 --protocol tcp --jump MASQUERADE --to-ports 1024-65535 --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1451] started: iptables-nft --wait -t nat --insert POSTROUTING --source 10.230.188.0/24 ! --destination 10.230.188.0/24 --protocol udp --jump MASQUERADE --to-ports 1024-65535 --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1452] started: iptables-nft --wait -t nat --insert POSTROUTING --source 10.230.188.0/24 ! --destination 10.230.188.0/24 --jump MASQUERADE --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1453] started: iptables-nft --wait -t filter --insert FORWARD --destination 10.230.188.0/24 --out-interface mpqemubr0 --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1455] started: iptables-nft --wait -t filter --insert FORWARD --source 10.230.188.0/24 --in-interface mpqemubr0 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1457] started: iptables-nft --wait -t filter --insert FORWARD --in-interface mpqemubr0 --out-interface mpqemubr0 --jump ACCEPT --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:27 serenity-ubuntu multipassd[873]: [1458] started: iptables-nft --wait -t filter --append FORWARD --in-interface mpqemubr0 --jump REJECT --reject-with icmp-port-unreachable --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:28 serenity-ubuntu multipassd[873]: [1464] started: iptables-nft --wait -t filter --append FORWARD --out-interface mpqemubr0 --jump REJECT --reject-with icmp-port-unreachable --match comment --comment generated for Multipass network mpqemubr0
May  5 17:38:28 serenity-ubuntu multipassd[873]: Error getting https://cloud-images.ubuntu.com/releases/streams/v1/index.json: Host cloud-images.ubuntu.com not found - trying cache.
May  5 17:38:28 serenity-ubuntu multipassd[873]: Error getting https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json: Host cloud-images.ubuntu.com not found - trying cache.
May  5 17:38:28 serenity-ubuntu multipassd[873]: Error getting https://cloud-images.ubuntu.com/daily/streams/v1/index.json: Host cloud-images.ubuntu.com not found - trying cache.
May  5 17:38:28 serenity-ubuntu multipassd[873]: Error getting https://cloud-images.ubuntu.com/daily/streams/v1/com.ubuntu.cloud:daily:download.json: Host cloud-images.ubuntu.com not found - trying cache.
May  5 17:38:28 serenity-ubuntu multipassd[873]: Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz: Host cdimage.ubuntu.com not found
May  5 17:38:28 serenity-ubuntu multipassd[873]: Could not update manifest: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Host cdimage.ubuntu.com not found
May  5 17:38:28 serenity-ubuntu multipassd[873]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img: Host cloud-images.ubuntu.com not found
May  5 17:38:28 serenity-ubuntu multipassd[873]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img': Host cloud-images.ubuntu.com not found
May  5 17:38:28 serenity-ubuntu multipassd[873]: Error getting https://codeload.github.com/canonical/multipass-workflows/zip/refs/heads/main: Host codeload.github.com not found - trying cache.
May  5 17:38:28 serenity-ubuntu multipassd[873]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket
May  5 17:38:28 serenity-ubuntu multipassd[873]: [1663] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/worker2/ubuntu-20.04-server-cloudimg-amd64.img
May  5 17:38:28 serenity-ubuntu multipassd[873]: [1689] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/worker1/ubuntu-20.04-server-cloudimg-amd64.img
May  5 17:38:28 serenity-ubuntu multipassd[873]: [1692] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/rhsso/ubuntu-20.04-server-cloudimg-amd64.img
May  5 17:38:28 serenity-ubuntu multipassd[873]: [1695] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/keycloak/ubuntu-20.04-server-cloudimg-amd64.img
May  5 17:38:28 serenity-ubuntu multipassd[873]: [1698] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/kafka/ubuntu-20.04-server-cloudimg-amd64.img
May  5 17:38:29 serenity-ubuntu multipassd[873]: [1701] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/php/ubuntu-20.04-server-cloudimg-amd64.img
May  5 17:38:29 serenity-ubuntu multipassd[873]: [1704] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/nextcloud/nextcloud-core18-amd64.qcow2
May  5 17:38:29 serenity-ubuntu multipassd[873]: [1707] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/master/ubuntu-20.04-server-cloudimg-amd64.img
May  5 17:38:29 serenity-ubuntu multipassd[873]: [1710] started: qemu-img snapshot -l /var/snap/multipass/common/data/multipassd/vault/instances/jammy/ubuntu-22.04-server-cloudimg-amd64.img
May  5 17:38:29 serenity-ubuntu multipassd[873]: Starting Multipass 1.9.0
May  5 17:38:29 serenity-ubuntu multipassd[873]: Daemon arguments: /snap/multipass/6920/bin/multipassd --verbosity debug --logger platform

```

**Additional context**
I cannot access multipass since all commands are not authenticated anymore.

**Comment by townsend2010** [comment] 2022-05-05 11:13
Hey @athenacykes,

Sorry for the troubles :slightly_frowning_face: Could you please output the following details?

- `$ tree ~/snap/multipass`
- `$ find ~/snap/multipass/current/data/ -name multipass_cert.pem -type f | xargs awk 'FNR==1{print FILENAME; }{ print }'`
- `$ sudo cat /var/snap/multipass/common/data/multipassd/authenticated-certs/multipass_client_certs.pem`

Thanks!

**Comment by townsend2010** [comment] 2022-05-05 15:56
Duplicate of #2552

**Closed by townsend2010** 2022-05-05 15:56 UTC

**Comment by townsend2010** [comment] 2022-05-12 12:30
Anyone coming across this bug and need steps to recover, I have written up https://discourse.ubuntu.com/t/unable-to-authorize-the-client-and-cannot-set-a-passphrase-workaround/28321 that should make it work for you.
