### ISSUE TITLE
Multipass 1.14 is not compatible with MacOS Sequoia

### ISSUE THREAD

**Issue by lallini94** [canonical/multipass#3685] opened 2024-09-19 08:35 UTC
**Describe the bug**
The problem is that multipass doesn't work after the update to Sequoia.
My primary instance keeps staying on "starting"

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version 1.14`

**Comment by georgeliao** [comment] 2024-09-19 08:41
@lallini94 
Sorry that you encountered this. It is known problem and we are working on a solution. Meanwhile, the issue #3661 tracks this.

**Comment by georgeliao** [comment] 2024-09-19 08:42
Duplicate of https://github.com/canonical/multipass/issues/3661

**Closed by georgeliao** 2024-09-19 08:41 UTC
Labels: needs triage
