### ISSUE TITLE
[macos] Multipass app not showing in Spotlight search

### ISSUE THREAD

**Issue by thewoolleyman** [canonical/multipass#2388] opened 2022-01-10 19:56 UTC
**What are you trying to do?**
I quit the mac menu helper, and I want to restart it without rebooting.  But I can't figure out how - there's no .app file, and no docs I can find.

**What's your proposed solution?**
- Add a note to `multipass --help`, 
- or make the menu launch via an an `.app` file that is discoverable and runnable.
- Make some help page that is discoverable with a search: "multipass" "mac" "menu" "restart" or similar...

**Additional context**
None, all covered above.

**Comment by Saviq** [comment] 2022-01-11 07:53
Hi @thewoolleyman, Multipass should be available in your Launchpad as usual:

<img width="302" alt="Zrzut ekranu 2022-01-11 o 08 52 52" src="https://user-images.githubusercontent.com/231077/148902455-77bb64de-1088-4bd8-b8a6-084a5786c00f.png">

If not there, try reinstalling, something might've gone wrong with the registration of the app.

Please reopen if that doesn't help!

**Comment by thewoolleyman** [comment] 2022-01-17 00:46
I reinstalled, and now I find `MultiPass.app` in my ~/Applications folder
(maybe I just missed it before)

However, it still does not show up in my spotlight. You can see this in the
attached screenshot.

Maybe it's due to me being on an M1 Max Apple Silicon Macbook? I don't have
this problem with any other app, they all show up in spotlight immediately
after reinstall.

Not a big problem, I can launch it directly from Finder if needed, but you
might want to look into why it isn't showing up in Spotlight.

Thanks,
-- Chad

**Comment by Saviq** [comment] 2022-01-17 08:51
Thanks @thewoolleyman, I can reproduce that indeed. We'll look for a fix.

**Comment by pawelbura** [comment] 2022-03-16 12:49
+1 
I have exactly the same behaviour on may MacBook Air M1: Multipass is present in Launcher but cannot be found in Spotllight Search (which is much easier and faster way to start an app).

**Comment by smk4664** [comment] 2022-05-10 19:29
I have this issue, but I am not on Apple Silicon, it seems it happens for Intel based macs as well.

**Comment by huwshimi** [comment] 2022-09-29 01:17
It appears this might be happening because `/Applications/Multipass.app/Contents/Info.plist` is a symlink (I can't find docs to support this, only [anecdotal evidence](https://superuser.com/a/1065909). Changing that file to an alias fixes the issue for me.

**Comment by nilnullzip** [comment] 2023-02-12 02:48
Still a problem in 2023.

**Comment by akauppi** [comment] 2023-12-27 10:16
works for me; macOS 14.2.1 (Intel); multipass 1.13 RC

Decided to log my experience though I don't suffer from the reported lack of spotlight. I think I've seen it before though, so @nilnullzip once/if you have 14.x, is it still a case?

**Comment by nilnullzip** [comment] 2023-12-27 18:31
> works for me; macOS 14.2.1 (Intel); multipass 1.13 RC
> 
> Decided to log my experience though I don't suffer from the reported lack of spotlight. I think I've seen it before though, so @nilnullzip once/if you have 14.x, is it still a case?

@akauppi It seems to be working for me now. I'm on MacOS 14.1.2 (Sonoma) on 2018 MBP which is x86. Thanks for the followup!

**Comment by ricab** [comment] 2024-07-04 20:28
Fixed by #3504

**Closed by ricab** 2024-07-04 20:28 UTC

**Comment by majorproblem** [comment] 2024-11-04 10:19
I'm sad to say that I have this problem, even after a total uninstall and re-installation of Multipass. I am on macOS Ventura 13.7 (22H123). I can double-click on the Multipass icon in `Applications` but it will not appear when I search with Spotlight, nor with Alfred (an alternative quick-launcher similar to Spotlight)

Is it possible to re-open this issue or should I file a new one?

**Comment by ricab** [comment] 2024-11-05 19:09
Hi @majorproblem, please open a new one providing the info in the template, including the version of Multipass that you are using. You can link back to this one for reference. Thank you.
