### ISSUE TITLE
Multipass fails to launch an instance in OSX Bigsur (x86)

### ISSUE THREAD

**Issue by coterobarros** [canonical/multipass#3087] opened 2023-05-22 15:00 UTC
After installing Multipass using brew install multipass or directly from the Canonical website, a persistent error occurs when starting an instance:

```
multipass shell
start failed: The following errors occurred:                                    
Instance stopped while starting
```

OS signature is `Darwin Kernel Version 20.6.0: Mon Aug 29 04:31:06 PDT 2022; root:xnu-7195.141.39~2/RELEASE_X86_64 x86_64`

Inspecting the logs at `/Library/Logs/Multipass/multipassd.log` I found some errors I cannot understand:

```
[2023-05-22T16:27:27.687] [debug] [update] Latest Multipass release available is version 1.11.1
[2023-05-22T16:27:28.972] [warning] [daemon] Ignoring ghost instance in database: rapid-lionfish
[2023-05-22T16:27:28.972] [warning] [daemon] Ignoring ghost instance in database: successful-snake
[2023-05-22T16:27:28.975] [info] [rpc] gRPC listening on unix:/var/run/multipass_socket
[2023-05-22T16:27:28.976] [info] [daemon] Starting Multipass 1.11.1+mac
[2023-05-22T16:27:28.976] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.multipass/bin/multipassd --verbosity debug
[2023-05-22T16:27:48.741] [debug] [primary] Waiting for SSH to be up
[2023-05-22T16:27:48.741] [debug] [primary] process working dir ''
[2023-05-22T16:27:48.742] [info] [primary] process program '/Library/Application Support/com.canonical.multipass/bin/hyperkit'
[2023-05-22T16:27:48.742] [info] [primary] process arguments '-c, 1, -m, 1024M, -u, -A, -H, -U, 386bba5a-5dc4-3ac2-95c9-cf0b9a29b352, -s, 0:0,hostbridge, -s, 2:0,virtio-net, -s, 5,virtio-rnd, -s, 31,lpc, -l, com1,autopty=/var/root/Library/Application Support/multipassd/vault/instances/primary/pty,log=/Library/Logs/Multipass/primary-hyperkit.log, -s, 1:0,virtio-blk,file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-22.04-server-cloudimg-amd64.img?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false, -s, 1:1,ahci-cd,/var/root/Library/Application Support/multipassd/vault/instances/primary/cloud-init-config.iso, -f, kexec,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-22.04-server-cloudimg-amd64-vmlinuz-generic,/var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-22.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/vda1 rw panic=1 no_timer_check'
[2023-05-22T16:27:48.742] [info] [primary] process state changed to Starting
[2023-05-22T16:27:48.744] [info] [primary] process state changed to Running
[2023-05-22T16:27:48.749] [error] [primary] Using fd 5 for I/O notifications
[2023-05-22T16:27:48.751] [info] [primary] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-22.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None

[2023-05-22T16:27:48.769] [info] [primary] hyperkit: [INFO] Resized file to 24212 clusters (3099136 sectors)
[2023-05-22T16:27:48.769] [info] [primary] hyperkit: [INFO] block recycler starting with keep_erased = 2048
[2023-05-22T16:27:48.769] [info] [primary] hyperkit: [INFO] image has 0 free sectors and 24208 used sectors
[2023-05-22T16:27:48.769] [info] [primary] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-22.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None returning 0
mirage_block_stat

[2023-05-22T16:27:48.769] [info] [primary] /var/root/Library/Application Support/multipassd/vault/instances/primary/cloud-init-config.iso: fcntl(F_PUNCHHOLE) Operation not permitted: block device will not support TRIM/DISCARD
[2023-05-22T16:27:48.910] [error] [primary] vmx_set_ctlreg: cap_field: 4 bit: 12 unspecified don't care: bit is 0
[2023-05-22T16:27:48.910] [error] [primary] vmx_set_ctlreg: cap_field: 4 bit: 20 unspecified don't care: bit is 0
[2023-05-22T16:27:48.910] [error] [primary] vmx_set_ctlreg: cap_field: 3 bit: 13 unspecified don't care: bit is 0
[2023-05-22T16:27:48.910] [info] [primary] linkname /var/root/Library/Application Support/multipassd/vault/instances/primary/pty
COM1 connected to /dev/ttys002

[2023-05-22T16:27:48.910] [error] [primary] kexec: failed to load kernel /var/root/Library/Application Support/multipassd/vault/instances/primary/ubuntu-22.04-server-cloudimg-amd64-vmlinuz-generic
[2023-05-22T16:27:48.911] [error] [primary] process error occurred Crashed
[2023-05-22T16:27:48.911] [info] [primary] process state changed to NotRunning
[2023-05-22T16:27:48.911] [info] [primary] process finished with exit code 6
[2023-05-22T16:33:00.138] [debug] [primary] Waiting for SSH to be up
```

**Comment by townsend2010** [comment] 2023-05-22 15:51
Hi @coterobarros,

Yes, a recent update in macOS has broken Hyperkit.  We will be deprecating Hyperkit in the upcoming 1.12 release, but in the meantime, please switch to the `qemu` driver via:

`$ multipass set local.driver=qemu`

Duplicate of #3080

**Closed** 2023-05-22 15:52 UTC

**Comment by coterobarros** [comment] 2023-05-22 18:33
Thanks a lot @townsend2010
Multipass is so convenient for me that I was going mad on this error.
Interestingly, I can run multipass with no errors on another M1 mac. Don't know if it is the same version as in the x86 case.

**Comment by townsend2010** [comment] 2023-05-22 18:36
Hi @coterobarros!

Yes, Multipass on M1 has always used Qemu since we released support for it because Hyperkit *only* works on Intel Macs.

**Comment by coterobarros** [comment] 2023-05-22 18:40
Sure! sorry I forgot

**Comment by townsend2010** [comment] 2023-05-22 18:49
No worries, glad it's working for you now!
