### ISSUE TITLE
Multipass will not start with macOS Sequoia 

### ISSUE THREAD

**Issue by spartygw** [canonical/multipass#3678] opened 2024-09-17 17:56 UTC
**Describe the bug**

Since updating to macOS Sequoia I have been unable to launch multipass.

`spartygw:~:: multipass launch -vvv
[2024-09-17T13:45:26.599] [debug] [blueprint provider] Loading "anbox-cloud-appliance" v1
[2024-09-17T13:45:26.600] [debug] [blueprint provider] Loading "charm-dev" v1
[2024-09-17T13:45:26.601] [debug] [blueprint provider] Loading "docker" v1
[2024-09-17T13:45:26.601] [debug] [blueprint provider] Loading "jellyfin" v1
[2024-09-17T13:45:26.602] [debug] [blueprint provider] Loading "minikube" v1
[2024-09-17T13:45:26.602] [debug] [blueprint provider] Loading "ros-noetic" v1
[2024-09-17T13:45:26.603] [debug] [blueprint provider] Loading "ros2-humble" v1
[2024-09-17T13:45:26.606] [debug] [qemu-system-aarch64] [17969] started: qemu-system-aarch64 --version
[2024-09-17T13:45:26.619] [debug] [qemu-img] [17970] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/noble-20240911/ubuntu-24.04-server-cloudimg-arm64.img
[2024-09-17T13:45:26.631] [debug] [qemu-img] [17971] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img 5368709120
[2024-09-17T13:45:26.640] [debug] [qemu-img] [17972] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img
[2024-09-17T13:45:26.648] [debug] [qemu-img] [17973] started: qemu-img amend -o compat=1.1 /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img
[2024-09-17T13:45:26.655] [debug] [upbeat-slug] process working dir ''
[2024-09-17T13:45:26.655] [info] [upbeat-slug] process program 'qemu-system-aarch64'
[2024-09-17T13:45:26.656] [info] [upbeat-slug] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:2d:bd:7b, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/cloud-init-config.iso'
[2024-09-17T13:45:26.657] [debug] [qemu-system-aarch64] [17974] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.mNVpTE
[2024-09-17T13:45:26.694] [info] [upbeat-slug] process state changed to Starting
[2024-09-17T13:45:26.696] [info] [upbeat-slug] process state changed to Running
[2024-09-17T13:45:26.696] [debug] [qemu-system-aarch64] [17975] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:2d:bd:7b -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/cloud-init-config.iso
[2024-09-17T13:45:26.696] [info] [upbeat-slug] process started
launch failed: The following errors occurred:
upbeat-slug: timed out waiting for response`

**To Reproduce**
1. update macOS to sequoia
2. try to run multipass

**Expected behavior**
launch fails and expected it to start

**Logs**

[2024-09-17T13:45:26.599] [debug] [blueprint provider] Loading "anbox-cloud-appliance" v1
[2024-09-17T13:45:26.600] [debug] [blueprint provider] Loading "charm-dev" v1
[2024-09-17T13:45:26.600] [debug] [blueprint provider] Loading "docker" v1
[2024-09-17T13:45:26.601] [debug] [blueprint provider] Loading "jellyfin" v1
[2024-09-17T13:45:26.602] [debug] [blueprint provider] Loading "minikube" v1
[2024-09-17T13:45:26.602] [debug] [blueprint provider] Loading "ros-noetic" v1
[2024-09-17T13:45:26.602] [debug] [blueprint provider] Loading "ros2-humble" v1
[2024-09-17T13:45:26.606] [debug] [qemu-system-aarch64] [17969] started: qemu-system-aarch64 --version
[2024-09-17T13:45:26.619] [debug] [qemu-img] [17970] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/noble-20240911/ubuntu-24.04-server-cloudimg-arm64.img
[2024-09-17T13:45:26.631] [debug] [qemu-img] [17971] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img 5368709120
[2024-09-17T13:45:26.640] [debug] [qemu-img] [17972] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img
[2024-09-17T13:45:26.648] [debug] [qemu-img] [17973] started: qemu-img amend -o compat=1.1 /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img
[2024-09-17T13:45:26.655] [debug] [upbeat-slug] process working dir ''
[2024-09-17T13:45:26.655] [info] [upbeat-slug] process program 'qemu-system-aarch64'
[2024-09-17T13:45:26.656] [info] [upbeat-slug] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:2d:bd:7b, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/cloud-init-config.iso'
[2024-09-17T13:45:26.657] [debug] [qemu-system-aarch64] [17974] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.mNVpTE
[2024-09-17T13:45:26.694] [info] [upbeat-slug] process state changed to Starting
[2024-09-17T13:45:26.696] [info] [upbeat-slug] process state changed to Running
[2024-09-17T13:45:26.696] [debug] [qemu-system-aarch64] [17975] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:2d:bd:7b -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/ubuntu-24.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/upbeat-slug/cloud-init-config.iso
[2024-09-17T13:45:26.696] [info] [upbeat-slug] process started
[2024-09-17T13:45:26.696] [debug] [upbeat-slug] Waiting for SSH to be up
[2024-09-17T13:45:26.722] [debug] [upbeat-slug] QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 2, "major": 8}, "package": ""}, "capabilities": ["oob"]}}

[2024-09-17T13:45:26.738] [debug] [upbeat-slug] QMP: {"return": {}}

[2024-09-17T13:45:38.524] [debug] [upbeat-slug] QMP: {"timestamp": {"seconds": 1726595138, "microseconds": 524624}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]/virtio-backend"}}

[2024-09-17T13:46:22.990] [debug] [upbeat-slug] QMP: {"timestamp": {"seconds": 1726595182, "microseconds": 990184}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

[2024-09-17T13:47:42.032] [debug] [profound-flamingo] QMP: {"timestamp": {"seconds": 1726595262, "microseconds": 32233}, "event": "RTC_CHANGE", "data": {"offset": 0, "qom-path": "/machine/unattached/device[4]"}}

[2024-09-17T13:52:14.916] [debug] [soothing-osprey] QMP: {"timestamp": {"seconds": 1726595534, "microseconds": 916562}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

[2024-09-17T13:54:23.770] [debug] [daemon] Returning setting local.driver=qemu

**Additional info**
 - OS: macOS Sequoia 15.0
- multipass   1.14.0+mac
multipassd  1.14.0+mac

Name:           profound-flamingo
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           pure-firebrat
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           soothing-osprey
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           upbeat-slug
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     f40c93dde981 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

- qemu

**Additional context**
none

**Comment by ricab** [comment] 2024-09-17 17:59
Hi @spartygw, sorry that you are experiencing this. There was a change in Sequoia that breaks how we get IPs. The problem is already reported in #3661 and we are working on it.

Duplicate of #3661

**Comment by ricab** [comment] 2024-09-17 18:00
Duplicate of #3661

**Closed** 2024-09-17 18:00 UTC
Labels: needs triage

**Comment by yohoojoo** [comment] 2024-09-26 03:15
The update seemed to resolve the issue, but after restarting the system, the status of the created instance is unknown, and do not restart.
