### ISSUE TITLE
Publish windows installer source

### ISSUE THREAD

**Issue by qm3ster** [canonical/multipass#2609] opened 2022-06-07 18:49 UTC
I was unable to find any scripts to build the installer, allegedly it's made with NSIS in CanonicalLtd/multipass-private.
Is there a legal reason for that?

(In my case, I wanted to avoid the check for Windows edition to default to `hyperv`)

**Comment by ricab** [comment] 2022-07-26 10:17
Hi @qm3ster, yes, I'm afraid we keep Windows specifics closed source.

Duplicate of #1390.

**Closed by ricab** 2022-07-26 10:17 UTC
