### ISSUE TITLE
Raise minimal memory to 2GB

### ISSUE THREAD

**Issue by ikitayama** [canonical/multipass#2436] opened 2022-02-09 07:21 UTC
If there's no substantial reason to keep the min 1GB, please raise memory default to 2GB so we can clone some GitHub repo like Linux.

**Comment by Saviq** [comment] 2022-02-09 07:55
@ikitayama we try to keep the default resource consumption low. You can always use `--mem` when launching, and we'll soon allow changing that post-launch (#2353).

In time you'll also be able to change the defaults yourself (#756).

**Comment by Saviq** [comment] 2022-02-09 07:55
Duplicate of #756

**Closed by Saviq** 2022-02-09 07:55 UTC
Labels: enhancement
