### ISSUE TITLE
Multipass cannot start instance on macOS M2

### ISSUE THREAD

**Issue by cemakpolat** [canonical/multipass#3182] opened 2023-07-31 07:46 UTC
**Describe the bug**
Multipass was working just 2 weeks ago, somehow, it doesn't work any more. Once it is started it stucks at the starting instance phase. I cannot disable/enable firewall, therefore this options is not valid for me. 

**To Reproduce**
How, and what happened?
1. `multipass launch -vvv` downloads the image, then it cannot start the instance.
When it starts with the following command:   multipass launch  --name testvm -vvvv
```
[2023-07-31T09:33:35.569] [debug] [testvm] process working dir ''
[2023-07-31T09:33:35.569] [info] [testvm] process program 'qemu-system-aarch64'
[2023-07-31T09:33:35.569] [info] [testvm] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:b3:b7:2e, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/cloud-init-config.iso'
[2023-07-31T09:33:35.572] [debug] [qemu-system-aarch64] [4527] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.dQcaDP
[2023-07-31T09:33:35.611] [info] [testvm] process state changed to Starting
[2023-07-31T09:33:35.613] [info] [testvm] process state changed to Running
[2023-07-31T09:33:35.613] [debug] [qemu-system-aarch64] [4528] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:b3:b7:2e -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/cloud-init-config.iso
[2023-07-31T09:33:35.613] [info] [testvm] process started
Starting testvm -
```

**Expected behavior**
The instance should start properly. 

**Logs**
```
2023-07-31T09:33:35.540] [debug] [qemu-img] [4524] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/jammy-20230729/ubuntu-22.04-server-cloudimg-arm64.img
[2023-07-31T09:33:35.551] [debug] [qemu-img] [4525] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/ubuntu-22.04-server-cloudimg-arm64.img 5368709120
[2023-07-31T09:33:35.561] [debug] [qemu-img] [4526] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/ubuntu-22.04-server-cloudimg-arm64.img
[2023-07-31T09:33:35.569] [debug] [testvm] process working dir ''
[2023-07-31T09:33:35.569] [info] [testvm] process program 'qemu-system-aarch64'
[2023-07-31T09:33:35.569] [info] [testvm] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:b3:b7:2e, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/cloud-init-config.iso'
[2023-07-31T09:33:35.572] [debug] [qemu-system-aarch64] [4527] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.dQcaDP
[2023-07-31T09:33:35.611] [info] [testvm] process state changed to Starting
[2023-07-31T09:33:35.613] [info] [testvm] process state changed to Running
[2023-07-31T09:33:35.613] [debug] [qemu-system-aarch64] [4528] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:b3:b7:2e -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/testvm/cloud-init-config.iso
[2023-07-31T09:33:35.613] [info] [testvm] process started
[2023-07-31T09:33:35.614] [debug] [testvm] Waiting for SSH to be up
[2023-07-31T09:33:36.016] [debug] [testvm] QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 0, "major": 8}, "package": ""}, "capabilities": ["oob"]}}

[2023-07-31T09:33:36.065] [debug] [testvm] QMP: {"return": {}}

[2023-07-31T09:33:48.637] [debug] [testvm] QMP: {"timestamp": {"seconds": 1690788828, "microseconds": 637628}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]/virtio-backend"}}
```

**Additional info**
 - macOS 13.5 Ventura
- `multipass version`
` multipass   1.12.2+mac`
- `multipass info --all`
```
Name:           testvm
State:          Unknown
IPv4:           --
Release:        --
Image hash:     5ecab49ff44f (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver`
`qemu`

**Comment by cemakpolat** [comment] 2023-08-01 12:24
https://github.com/canonical/multipass/issues/3171 defines the same issue

**Comment by townsend2010** [comment] 2023-08-01 12:43
Hi @cemakpolat!

Looking at the log in the Description, I see this:
```
[2023-07-31T09:33:48.637] [debug] [testvm] QMP: {"timestamp": {"seconds": 1690788828, "microseconds": 637628}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]/virtio-backend"}}
```

This tells me that the instance has booted to the point where networking is active.  It's looking like you may be hitting the [dreaded firewall issue](https://github.com/canonical/multipass/issues/2387). :slightly_frowning_face: 

You say you cannot disable/enable the firewall.  Does this mean you are using a managed Mac?

**Comment by georgeliao** [comment] 2023-08-01 12:44
Hi @cemakpolat , based on your log, it looks like a typical firewall issue. https://github.com/canonical/multipass/issues/2387 this issue's discussion has something about that. Maybe you can try something there and see if it can make a difference?

**Comment by cemakpolat** [comment] 2023-08-01 12:49
@townsend2010 yes, I have a managed Mac, I cannot disable/enable the firewall. For this reason, I couldn't see whether the proposed solution can be also appliable for my case. For me, the interesting part, I hadn't such an issue 2 weeks ago. The last Mac update was 3-4 days ago. If this is a firewall issue, is there way to see the logs.

**Comment by townsend2010** [comment] 2023-08-01 12:55
@cemakpolat, unfortunately, there are zero logs for this.  As you can see from #2387, this is a very frustrating issue.

The only thing I can suggest is you try to convince your Mac administrator(s) to add the `bootpd` exception for your firewall.  There really isn't anything else we can do short of changing virtual networking technologies (and that is a big task we are considering) since Apple seems unwilling to fix this.

As such, I'm going to dup this bug to #2387.  Sorry, I wish I had better news about this.

**Comment by townsend2010** [comment] 2023-08-01 12:55
Duplicate of #2387

**Closed by townsend2010** 2023-08-01 12:55 UTC
