### ISSUE TITLE
Strongly recommend a container replication function

### ISSUE THREAD

**Issue by kekekekekeshi** [canonical/multipass#2833] opened 2022-11-23 12:26 UTC
As for why I need such a function, I usually don't want to use docker when doing cluster deployment, because I want to experience the whole process of building and configuring, but I don't want to repeat the same configuration content, it will It wastes a lot of time. For example, I want to build a mysql cluster. Usually, the difference between them is the specification of the mysql service id and the execution of cluster-related configuration in the mysql client. Then the difference is that the id is different. At this time, I don't want to install mysql repeatedly. I want to clone the container and simply change the configuration.

*I apologize for the use of translator*

**Comment by Saviq** [comment] 2022-11-23 12:52
Duplicate of #208

**Closed by Saviq** 2022-11-23 12:52 UTC
Labels: enhancement
