### ISSUE TITLE
Directory sequence error

### ISSUE THREAD

**Issue by PiCoPress** [canonical/multipass#2821] opened 2022-11-12 12:27 UTC
**Describe the bug**
Multipass cannot start.

**To Reproduce**
How, and what happened?
Didn't work.

**Expected behavior**
PS C:\> multipass launch --name name
[error] [client] Caught an unhandled exception: failed to open file 'C:/Users/議곗쑄??AppData/Local/multipass-client-certificate/multipass_cert_key.pem': Illegal byte sequence(42)

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**

- `multipass version` : PS C:\> multipass --version
[error] [client] Caught an unhandled exception: failed to open file 'C:/Users/議곗쑄??AppData/Local/multipass-client-certificate/multipass_cert_key.pem': Illegal byte sequence(42)

- `multipass info --all` : multipass info --all
[error] [client] Caught an unhandled exception: failed to open file 'C:/Users/議곗쑄??AppData/Local/multipass-client-certificate/multipass_cert_key.pem': Illegal byte sequence(42)

- `multipass get local.driver` 

**Additional ntext**

**Comment by sharder996** [comment] 2022-11-14 15:29
Duplicate of #1314

**Closed** 2022-11-14 15:29 UTC
