### ISSUE TITLE
[Big Sur] Toolbar icon is squashed when not screen is not focussed

### ISSUE THREAD

**Issue by barrymcgee** [canonical/multipass#1844] opened 2020-11-18 15:38 UTC
Multipass icon is squashed on toolbars where the screen is not in focus;

Screen in focus:

<img width="891" alt="Screenshot 2020-11-18 at 14 23 39" src="https://user-images.githubusercontent.com/505570/99551676-0cc4ac80-29b4-11eb-8122-509d112e47f0.png">

Screen not in focus:

<img width="885" alt="Screenshot 2020-11-18 at 14 24 03" src="https://user-images.githubusercontent.com/505570/99551714-16e6ab00-29b4-11eb-98db-ed77162268ad.png">

**Additional info**
 - OS: `11.0.1`
- multipass version: `1.5.0+mac`

**Comment by Saviq** [comment] 2020-11-18 15:39
Hey, we have it already in #1837.

**Comment by Saviq** [comment] 2020-11-18 15:39
Duplicate of #1837

**Closed by Saviq** 2020-11-18 15:39 UTC
Labels: bug
