### ISSUE TITLE
How can I change memory (RAM) size of existing Multipass virtual machine?

### ISSUE THREAD

**Issue by tom055** [canonical/multipass#2461] opened 2022-03-01 05:37 UTC
I want to change memory,modified the multipassd-vm-instances.json file,reboot, but which is invalid

multipassd-vm-instances.json 
The file is in this directory C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\multipassd-vm-instances.json 

so i try to stop all instance,
run PsExec.exe -s -i $env:VBOX_MSI_INSTALL_PATH\VirtualBox.exe
i want to change by VirtualBox,but VirtualBox can't change memory. Cannot open a new task for the virtual machine

 - OS: windows 10
- `multipass 1.8.0+win
![55](https://user-images.githubusercontent.com/17687356/156111270-fb39e03f-a060-4eb7-8c72-98c11ad33e1f.png)

**Comment by Saviq** [comment] 2022-03-01 08:40
@tom055 for VirtualBox you'll need to do it through VBoxManage or in the VirtualBox GUI.

We're working on this feature, proper, right now, so you can `multipass set…` the desired amount.

**Comment by Saviq** [comment] 2022-03-01 08:40
Duplicate of #1158

**Closed by Saviq** 2022-03-01 08:40 UTC
Labels: bug
