### ISSUE TITLE
[regression] Multipass exec command does not work with "" 

### ISSUE THREAD

**Issue by albertlorente-aimsun** [canonical/multipass#3119] opened 2023-06-12 13:59 UTC
**Describe the bug**
Before the 1.12.0 version I can execute this command without problems:

`multipass exec test -- ssh-keygen -b 2048 -t ed25519 -f /home/ubuntu/.ssh/id_rsa -N '' -q`

But with the last update, all after '' are not executed (the '' either). If I run the command inside the multipass instance, it works fine!

The command does not work because the answer is: "option requires an argument -- N"

**To Reproduce**
How, and what happened?
1. Try to execute `multipass exec test -- ssh-keygen -b 2048 -t ed25519 -f /home/ubuntu/.ssh/id_rsa -N '' -q` and see that the -q option is not take in care

**Additional info**
 - OS: 
Ubuntu 18.04

- `multipass version` 
multipass   1.12.0
multipassd  1.12.0

- `multipass info --all`
Name:           test
State:          Running
IPv4:           10.56.33.196
Release:        Ubuntu 18.04.6 LTS
Image hash:     8dd2e6b5e5aa (Ubuntu 18.04 LTS)
CPU(s):         5
Load:           0.00 0.03 0.02
Disk usage:     1.2GiB out of 29.0GiB
Memory usage:   130.9MiB out of 15.7GiB
Mounts:         --

- `multipass get local.driver`
qemu

**Comment by luis4a0** [comment] 2023-06-12 15:31
Hi @albertlorente-aimsun, I am not able to reproduce your bug. Executing the command you mentioned in Linux, with the `qemu` driver, on a 18.04.6 instance is working for me. Can you specify what shell are you using, in the host and in the instance? Thanks!

**Comment by luis4a0** [comment] 2023-06-12 16:50
@albertlorente-aimsun Another thing: you mention in the title that the issue is about double quotes, and also use double quotes in the description of the bug after the command-line you execute. Can you please clarify where are the double quotes in the command? Thanks!

**Comment by albertlorente-aimsun** [comment] 2023-06-13 07:25
Hi Luis! Sorry for the bad explanation. Here I attach some snapshots to explain the bug more accurancy

The spec of the machine are:
![image](https://github.com/canonical/multipass/assets/126189170/3c7a009b-4840-4d04-a740-807d491bda75)

Then, if I run the following command, you can see that the -q option is not take in care (appear some text in the terminal). The "" of the -N argument either
`multipass exec test-machine -- ssh-keygen -b 2048 -t ed25519 -f /home/ubuntu/.ssh/id_rsa -N "" -q`
![image](https://github.com/canonical/multipass/assets/126189170/6eb45ad6-bb26-48f7-923c-f5b7806f30b4)

But, if I set a passphrase (-N) like "QA", then the -q option works fine
`multipass exec test-machine -- ssh-keygen -b 2048 -t ed25519 -f /home/ubuntu/.ssh/id_rsa -N "QA" -q`
![image](https://github.com/canonical/multipass/assets/126189170/91448ea0-d21b-46cc-98d2-c23acd08e4e7)

**Comment by luis4a0** [comment] 2023-06-13 13:03
Hi @albertlorente-aimsun, thanks a lot for clarifying! This gives us a much better idea of what's happening and we are aiming to provide a fix for this as soon as possible.

**Comment by albertlorente-aimsun** [comment] 2023-06-13 14:33
Hi Luis! one question, I can return to the RC version? I've tried to remove multipass 1.12.0 and install again with `snap install multipass --beta` but 1.12.0 version is installed. Thanks!

**Comment by luis4a0** [comment] 2023-06-13 15:03
@albertlorente-aimsun All the snap channels are set to retrieve Multipass 1.12.0. You can try with `snap revert multipass` to go back to the previously installed version.

**Closed** 2023-06-16 01:17 UTC
Labels: regression
