### ISSUE TITLE
Multipass launch times out

### ISSUE THREAD

**Issue by melias77** [canonical/multipass#1704] opened 2020-08-23 13:23 UTC
I have problems provisioning with this command and params on windows 10 and with latest version of multipass:

$ multipass launch bionic --name developer-machine --cpus 4  --mem 16G --disk 70G --cloud-init ./cloud-init.yml

output: developer-machine: timed out waiting for response

Is there way to set/configure timeout for the launch command?

cloud-init.yml installs docker and docker-compose so it could take some time to initialize.

Thanks in advance.

Morten

**Comment by Saviq** [comment] 2020-08-23 17:36
Hey, we're tracking this in #1039.

**Comment by Saviq** [comment] 2020-08-23 17:36
Duplicate of #1039

**Closed by Saviq** 2020-08-23 17:36 UTC
