### ISSUE TITLE
multiple cpus issue on MacOS Mojave

### ISSUE THREAD

**Issue by gino-code** [canonical/multipass#1481] opened 2020-04-10 14:39 UTC
ON MacOS Mojave, launching a new multipass instance with cpus > 1 produce unusable vm (no way to connect to the vm shell).

Here the execution trace:

```
MBP01:~ user$ multipass list 
No instances found.
MBP01:~ user$ multipass launch --cpus 2 -n test    
Launched: test                                                                  
MBP01:~ user$ multipass list                                                
Name                    State             IPv4             Image
test                    Running           192.168.64.10    Ubuntu 18.04 LTS
MBP01:~ user$ 
MBP01:~ user$ multipass shell test
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Apr 10 16:22:09 CEST 2020

  System load:  0.24              Processes:             125
  Usage of /:   21.0% of 4.67GB   Users logged in:       0
  Memory usage: 12%               IP address for enp0s2: 192.168.64.10
  Swap usage:   0%


0 packages can be updated.
0 updates are security updates.


-bash: /usr/bin/groups: Input/output error
-bash: /home/ubuntu/.bash_profile: Input/output error
MBP01:~ user$ multipass info test 
Name:           test
State:          Running
IPv4:           192.168.64.10
Release:        Ubuntu 18.04.4 LTS
Image hash:     2f6bc5e7d9ac (Ubuntu 18.04 LTS)
Load:           0.06 0.70 0.44
Disk usage:     --
Memory usage:   --
MBP01:~ user$ 
```

the same doesn't happen with --cpus 1.

- OS: MacOS Mojave 10.14.6
-  multipass:  1.1.0+mac

**Comment by Saviq** [comment] 2020-04-10 15:14
Confirmed, will fix ASAP.

**Comment by Saviq** [comment] 2020-04-10 15:59
When using more than one CPU, it looks like the qcow2 implementation in hyperkit is failing… We'll have to dig more.

```
[   80.677684] ata1.00: exception Emask 0x0 SAct 0x70 SErr 0x0 action 0x6 frozen
[   80.679242] ata1.00: failed command: READ FPDMA QUEUED
[   80.680270] ata1.00: cmd 60/90:20:10:2f:0d/00:00:00:00:00/40 tag 4 ncq dma 73728 in
[   80.680270]          res 40/00:00:00:00:00/00:00:00:00:00/00 Emask 0x4 (timeout)
[   80.683416] ata1.00: status: { DRDY }
[   80.684175] ata1.00: failed command: WRITE FPDMA QUEUED
[   80.686551] ata1.00: cmd 61/68:28:18:7e:23/00:00:00:00:00/40 tag 5 ncq dma 53248 out
[   80.686551]          res 40/00:00:00:00:00/00:00:00:00:00/00 Emask 0x4 (timeout)
[   80.690097] ata1.00: status: { DRDY }
[   80.691481] ata1.00: failed command: WRITE FPDMA QUEUED
[   80.692564] ata1.00: cmd 61/01:30:01:28:00/00:00:00:00:00/40 tag 6 ncq dma 512 out
[   80.692564]          res 40/00:00:00:00:00/00:00:00:00:00/00 Emask 0x4 (timeout)
[   80.695603] ata1.00: status: { DRDY }
[   86.275830] ata1.00: revalidation failed (errno=-5)
```

**Comment by townsend2010** [comment] 2020-04-10 18:29
I wonder if adding `-o lazy_refcounts=on` as done in https://github.com/cfergeau/snc/commit/b85d8945a5b61120a6e3a3b21123412e406ba22a will help?

**Comment by robwatkin** [comment] 2020-04-11 06:55
Also happens on macOS Catalina 10.15.4

However
```
multipass exec test -- cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
stepping	: 9
cpu MHz		: 3100.000
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch pti fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 6192.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
stepping	: 9
cpu MHz		: 3100.000
cache size	: 4096 KB
physical id	: 1
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch pti fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 21456.37
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

**Comment by alexxed** [comment] 2020-04-14 15:48
I tried setting lazy refcounts on directly on the image multipass uses, then do a multipass launch that uses that cached image, but the problem persists.

{code}
//Library/Application\ Support/com.canonical.multipass/bin/qemu-img info ubuntu-18.04-server-cloudimg-amd64.img
image: ubuntu-18.04-server-cloudimg-amd64.img
file format: qcow2
virtual size: 40G (42949672960 bytes)
disk size: 1.1G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: true
    refcount bits: 16
    corrupt: false
{code}

**Comment by Saviq** [comment] 2020-04-14 16:21
> I tried setting lazy refcounts on directly on the image multipass uses, then do a multipass launch that uses that cached image, but the problem persists.

Yeah, I think the `lazy_refcounts` was actually a way to reproduce, not to fix…

**Comment by townsend2010** [comment] 2020-04-14 19:21
Well, according to https://github.com/moby/hyperkit/issues/221#issuecomment-499431737, it says enabling`lazy_refcounts' yields: 
> I no longer get the freeze:

so it was worth trying.  But since that didn't fix it here, then it appears this issue is different than what is causing https://github.com/moby/hyperkit/issues/221.

**Comment by wslab** [comment] 2020-04-16 01:26
Also hitting this issue with Multipass 1.0.0 and 1.1.0 on Mojave 10.14.6.

**Comment by townsend2010** [comment] 2020-04-16 20:12
Hey all,

https://github.com/canonical/multipass/pull/1490#issuecomment-614865608 has a link to a test package that addresses this issue.  You may have to delete/purge the broken instance and relaunch a new instance.  Let us know if this works or not.  Thanks!

**Comment by giaino** [comment] 2020-04-16 21:35
Hi all, 

I tested the new package with 2 and 4 cpus checking also the produced VMs with lscpu and now, for me, all it's OK.

- OS: MacOS Mojave 10.14.6
- multipass: 1.2.0-dev.192.pr1490+gfe18a2e8.mac

Thanks

**Comment by alexxed** [comment] 2020-04-17 07:31
That build works for me with 8 cpus on 10.15.4

**Comment by townsend2010** [comment] 2020-04-17 12:34
Closed by https://github.com/canonical/multipass-private/commit/51bc9e88e52bbe8d1a62118ff9dc9776f293890b.

**Closed by townsend2010** 2020-04-17 12:34 UTC
