### ISSUE TITLE
Support PCI passthrough

### ISSUE THREAD

**Issue by weironz** [canonical/multipass#3057] opened 2023-04-26 04:08 UTC
**What are you trying to do?**

Support PCI passthrough to multipass vm , the PCI maybe PF NIC or sriov VF.

kvm have same feature
```
virsh attach-device vm1 pci_0.xml  --live --config
```

**What's your proposed solution?**
```
multipass attach-device 0000:08:00.0 
```

**Additional context**

this feature can let user create dpdk or vpp application in multipass vm use multiple PF NIC

**Comment by ricab** [comment] 2023-04-26 12:03
Duplicate of #1897

**Comment by ricab** [comment] 2023-04-26 12:03
And #2503 is a particular version of this.

**Closed by ricab** 2023-04-26 12:03 UTC
