### ISSUE TITLE
Multipass private IP changes over some days which makes kubernetes cluster 

### ISSUE THREAD

**Issue by akshay004** [canonical/multipass#3792] opened 2024-11-24 07:34 UTC
**Describe the bug**
I am using MacOS on Macbook M1

For some days my IP range was 192.168.71.*
then eventually changes to 192.168.72.*
now it is in 192.168.73.*

**Expected behavior**
I was expecting the same IP for VM till their lifetime as they were private IP 

**Additional info**
The below data is from /var/db/dhcpd_leases I have removed other details in the file 
 {
	name=knode1
	ip_address=192.168.72.18
}
{
	name=kmaster
	ip_address=192.168.72.17
}

now its 
{
	name=kmaster
	ip_address=192.168.73.13
}
{
	name=knode1
	ip_address=192.168.73.12
}

How do we solve this issue? Is there a way to keep IP the same till the end of VM so that clusters won't break? Need to change IPs in config files while testing other proxy services as well

**Comment by ricab** [comment] 2024-11-26 11:52
Hi @akshay004, as you've found, Multipass relies on external DHCP for the default interface (using vmnet on macOS, which in turn uses bootp). You could try your hand at something [like this](https://multipass.run/docs/configure-static-ips). 

Let's continue tracking this in https://github.com/canonical/multipass/issues/3582

Duplicate of #3582

**Comment by ricab** [comment] 2024-11-26 11:52
Duplicate of https://github.com/canonical/multipass/issues/3582

**Closed by ricab** 2024-11-26 11:52 UTC
Labels: needs triage
