### ISSUE TITLE
Not working on arm64 ?

### ISSUE THREAD

**Issue by nikita-fuchs** [canonical/multipass#3331] opened 2023-12-14 12:56 UTC
**Describe the bug**
Instances can neither be launched nor stopped. The initial download of the image took place, but after that nothing worked:

**To Reproduce**
Commands I ran in order:
```
$ multipass launch --name aereplweb

launch failed: The following errors occurred:
aereplweb: timed out waiting for response
```

```
 $ multipass launch --name aereplweb
launch failed: instance "aereplweb" already exists
```
```
$ multipass start aereplweb
Starting aereplweb -
start failed: The following errors occurred:
Instance 'aereplweb' is already running, but in an unknown stateaereplweb: timed out waiting for response
```
```
$ multipass list
Name                    State             IPv4             Image
aereplweb               Unknown           --               Ubuntu 22.04 LTS
```
trying again with verbosity:

```
$multipass start aereplweb -vvvv
[2023-12-14T13:44:49.002] [warning] [daemon] Instance 'aereplweb' is already running, but in an unknown state
start failed: The following errors occurred:
Instance 'aereplweb' is already running, but in an unknown stateaereplweb: timed out waiting for response
```

**Expected behavior**
A VM would start

**Additional info**
 - OS: MacOS 14.1.2 (23B2091)
- `multipass version` multipass   1.12.2+mac
- `multipass info --all`: 
```
multipass info --all
Name:           aereplweb
State:          Unknown
IPv4:           --
Release:        --
Image hash:     f885a8e8f62a (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver` : qemu

**Additional context**
Thanks for any help, I like the idea behind multipass and would love to use it!

**Comment by townsend2010** [comment] 2023-12-14 13:33
Hi @nikita-fuchs!

Sorry you are having issues.  I wonder if you are hitting the [dreaded firewall issue](#2387), but I would need to see [you're logs](https://multipass.run/docs/accessing-logs#heading--macos) in order to better to determine if that is the case.  Do you have the firewall turned on on your Mac?

Thank you for trying Multipass and hopefully we can figure out what is happening.

**Comment by nikita-fuchs** [comment] 2023-12-14 18:31
Hey, thanks for coming back so quickly ! 
Funny how this is the first time I hear of a built-in firewall existing in mac, but no, I'm using Little Snitch and it's not blocking anything. 

The Logs: 

```
[2023-12-14T13:13:55.252] [warning] [Qt] Empty filename passed to function
[2023-12-14T13:14:00.687] [debug] [update] Latest Multipass release available is version 1.12.2
[2023-12-14T13:14:05.110] [warning] [url downloader] Error getting https://cloud-images.ubuntu.com/releases/streams/v1/index.json: Network timeout - trying cache.
[2023-12-14T13:14:06.112] [warning] [VMImageHost] Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/releases/streams/v1/index.json': Error opening https://cloud-images.ubuntu.com/releases/streams/v1/index.json
[2023-12-14T13:14:09.223] [info] [VMImageHost] Did not find any supported products in "appliance"
[2023-12-14T13:14:09.223] [warning] [url downloader] Error getting https://codeload.github.com/canonical/multipass-blueprints/zip/refs/heads/main: Network timeout - trying cache.
[2023-12-14T13:14:09.224] [error] [blueprint provider] Error fetching Blueprints: failed to download from 'https://codeload.github.com/canonical/multipass-blueprints/zip/refs/heads/main': Error opening https://codeload.github.com/canonical/multipass-blueprints/zip/refs/heads/main
[2023-12-14T13:14:09.234] [info] [rpc] gRPC listening on unix:/var/run/multipass_socket
[2023-12-14T13:14:09.234] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Caches/multipassd/qemu/vault/multipassd-image-records.json"): device not open
[2023-12-14T13:14:09.235] [info] [daemon] Starting Multipass 1.12.2+mac
[2023-12-14T13:14:09.235] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.multipass/bin/multipassd --verbosity debug
[2023-12-14T13:14:53.056] [debug] [blueprint provider] Loading "anbox-cloud-appliance" v1
[2023-12-14T13:14:53.059] [debug] [blueprint provider] Loading "charm-dev" v1
[2023-12-14T13:14:53.061] [debug] [blueprint provider] Loading "docker" v1
[2023-12-14T13:14:53.062] [debug] [blueprint provider] Loading "jellyfin" v1
[2023-12-14T13:14:53.064] [debug] [blueprint provider] Loading "minikube" v1
[2023-12-14T13:14:53.066] [debug] [blueprint provider] Loading "ros-noetic" v1
[2023-12-14T13:14:53.068] [debug] [blueprint provider] Loading "ros2-humble" v1
[2023-12-14T13:14:54.291] [info] [VMImageHost] Did not find any supported products in "appliance"
[2023-12-14T13:14:54.300] [debug] [qemu-system-aarch64] [82685] started: qemu-system-aarch64 --version
[2023-12-14T13:16:02.721] [debug] [image vault] Verifying hash "f885a8e8f62ab2c39ab0442ea182b69d49ccd990d24791acb4f1724573d8120f"
[2023-12-14T13:16:06.286] [debug] [qemu-img] [82709] started: qemu-img info --output=json /var/root/Library/Caches/multipassd/qemu/vault/images/jammy-20231211/ubuntu-22.04-server-cloudimg-arm64.img
[2023-12-14T13:16:06.422] [debug] [qemu-img] [82710] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/jammy-20231211/ubuntu-22.04-server-cloudimg-arm64.img
[2023-12-14T13:16:06.427] [debug] [qemu-img] [82711] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/aereplweb/ubuntu-22.04-server-cloudimg-arm64.img 5368709120
[2023-12-14T13:16:06.434] [debug] [qemu-img] [82712] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/aereplweb/ubuntu-22.04-server-cloudimg-arm64.img
[2023-12-14T13:16:06.437] [debug] [aereplweb] process working dir ''
[2023-12-14T13:16:06.437] [info] [aereplweb] process program 'qemu-system-aarch64'
[2023-12-14T13:16:06.437] [info] [aereplweb] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:d4:b7:3a, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/aereplweb/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/aereplweb/cloud-init-config.iso'
[2023-12-14T13:16:06.438] [debug] [qemu-system-aarch64] [82713] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.oKCHoy
[2023-12-14T13:16:06.464] [info] [aereplweb] process state changed to Starting
[2023-12-14T13:16:06.466] [info] [aereplweb] process state changed to Running
[2023-12-14T13:16:06.466] [debug] [qemu-system-aarch64] [82714] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:d4:b7:3a -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/aereplweb/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/aereplweb/cloud-init-config.iso
[2023-12-14T13:16:06.466] [info] [aereplweb] process started
[2023-12-14T13:16:06.466] [debug] [aereplweb] Waiting for SSH to be up
[2023-12-14T13:16:06.766] [debug] [aereplweb] QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 0, "major": 8}, "package": ""}, "capabilities": ["oob"]}}

[2023-12-14T13:16:06.814] [debug] [aereplweb] QMP: {"return": {}}

[2023-12-14T13:25:47.206] [debug] [blueprint provider] Loading "anbox-cloud-appliance" v1
[2023-12-14T13:25:47.206] [debug] [blueprint provider] Loading "charm-dev" v1
[2023-12-14T13:25:47.206] [debug] [blueprint provider] Loading "docker" v1
[2023-12-14T13:25:47.206] [debug] [blueprint provider] Loading "jellyfin" v1
[2023-12-14T13:25:47.206] [debug] [blueprint provider] Loading "minikube" v1
[2023-12-14T13:25:47.207] [debug] [blueprint provider] Loading "ros-noetic" v1
[2023-12-14T13:25:47.207] [debug] [blueprint provider] Loading "ros2-humble" v1
[2023-12-14T13:25:47.516] [info] [VMImageHost] Did not find any supported products in "appliance"
[2023-12-14T13:26:22.674] [warning] [daemon] Instance 'aereplweb' is already running, but in an unknown state
[2023-12-14T13:26:22.674] [debug] [aereplweb] Waiting for SSH to be up
[2023-12-14T13:32:51.777] [warning] [daemon] Instance 'aereplweb' is already running, but in an unknown state
[2023-12-14T13:32:51.777] [debug] [aereplweb] Waiting for SSH to be up
[2023-12-14T13:35:13.874] [info] [daemon] Cannot open ssh session on "aereplweb" shutdown: failed to determine IP address
[2023-12-14T13:35:13.875] [debug] [aereplweb] QMP: {"return": {}}

[2023-12-14T13:35:13.875] [debug] [aereplweb] QMP: {"timestamp": {"seconds": 1702557313, "microseconds": 875021}, "event": "POWERDOWN"}

[2023-12-14T13:35:13.875] [info] [aereplweb] VM powering down
[2023-12-14T13:44:49.002] [warning] [daemon] Instance 'aereplweb' is already running, but in an unknown state
[2023-12-14T13:44:49.002] [debug] [aereplweb] Waiting for SSH to be up
[2023-12-14T13:52:46.495] [debug] [daemon] Returning setting local.driver=qemu
```

Seeing the failed connections, could it be though that the seconds it took me to permit the connections in little snitch already triggered a timeout, that somehow broke things eternally? If so, a quick connectivity check might be a good idea to solve this issue ? 

I'm trying to re-setup a new vm, but doing `multipass delete --all` gets stuck forever, the logs hang at 
```
[2023-12-14T19:09:34.167] [debug] [aereplweb] QMP: {"timestamp": {"seconds": 1702577374, "microseconds": 167855}, "event": "POWERDOWN"}

[2023-12-14T19:09:34.167] [info] [aereplweb] VM powering down

```

Firing up another VM like 
```
$ multipass launch --name ubuntu1
launch failed: The following errors occurred:
ubuntu1: timed out waiting for response
```
also didn't help. 

I'm on a MBP M3 Max, `multipass info --all` not showing hardware specs smells like there is some issue with the arch ?

**Comment by townsend2010** [comment] 2023-12-14 18:57
Oh, you're on an M3 Mac!  Yes, this is currently [not working](#3308).  We are closely tracking upstream and will hopefully have a fix in place when we release the 1.13 version of Multipass in January.  Sorry for your troubles :slightly_frowning_face:

**Comment by townsend2010** [comment] 2023-12-14 18:59
Duplicate of #3308

**Closed by townsend2010** 2023-12-14 18:59 UTC

**Comment by townsend2010** [comment] 2023-12-14 19:00
Also, someone reported that v1.11.1 does work and that can be downloaded at https://github.com/canonical/multipass/releases/download/v1.11.1/multipass-1.11.1+mac-Darwin.pkg.

**Comment by nikita-fuchs** [comment] 2023-12-18 16:32
Hey, thank you, version 1.11.1 seems to work! But why closed as not planned though, if you actually plan to support it? Especially when this is a regression.

**Comment by ricab** [comment] 2024-01-02 15:51
Hey @nikita-fuchs, it's just that there is already an open issue to track it (#3308). No point having more than one.
