### ISSUE TITLE
Failed to start Flutter renderer: Unable to create a GL context

### ISSUE THREAD

**Issue by xypron** [canonical/multipass#3743] opened 2024-10-18 08:39 UTC
**Describe the bug**
multipass.gui shows an empty window

**To Reproduce**
In the console I entered the multipass.gui command and see this console output:

```
$ multipass.gui
Gtk-Message: 10:23:43.088: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(multipass_gui:10637): Gdk-CRITICAL **: 10:23:43.127: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

** (multipass_gui:10637): WARNING **: 10:23:43.160: Failed to start Flutter renderer: Unable to create a GL context

** (multipass_gui:10637): WARNING **: 10:23:43.164: Unable to retrieve framework response: No engine to send to

** (multipass_gui:10637): WARNING **: 10:23:48.531: Unable to retrieve framework response: No engine to send to

** (multipass_gui:10637): WARNING **: 10:24:08.173: atk-bridge: get_device_events_reply: unknown signature

** (multipass_gui:10637): WARNING **: 10:24:13.004: Unable to retrieve framework response: No engine to send to

** (multipass_gui:10637): WARNING **: 10:26:24.216: Unable to retrieve framework response: No engine to send to

** (multipass_gui:10637): WARNING **: 10:26:39.617: Unable to retrieve framework response: No engine to send to

** (multipass_gui:10637): WARNING **: 10:27:45.523: Unable to retrieve framework response: No engine to send to
```

A new window with title 'Muiltipass' is opened. It only displays a white plane.

No message is written to ~/snap/multipass/current/data/multipass_gui/multipass_gui.log.

glxgears just runs fine. So OpenGL is available on the system.

**Expected behavior**

I expected a functional interface.

**Logs**

No message is written to ~/snap/multipass/current/data/multipass_gui/multipass_gui.log.

**Additional info**

- multipass snap 1.14.1
 - OS: Ubuntu 24.10 using KDE

```
$ loginctl show-session 4 -p Type      
Type=x11
```

```
$ multipass version
multipass   1.14.1
multipassd  1.14.1
```
```
$ multipass info
Name:           chic-hornet
State:          Deleted
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     500a4be0e6dd (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           delicious-mouflon
State:          Running
Snapshots:      0
IPv4:           10.174.94.120
Release:        Ubuntu 24.04.1 LTS
Image hash:     fad101d50b06 (Ubuntu 24.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     2.0GiB out of 4.8GiB
Memory usage:   342.7MiB out of 956.1MiB
Mounts:         --
```

```
$ multipass get local.driver
qemu
```

**Comment by xypron** [comment] 2024-10-18 08:43
The problem is reproducible with
```
multipass   1.15.0-dev.411+gbf3719d1e
multipassd  1.15.0-dev.411+gbf3719d1e
```
Only difference: A text 'Unable to create a GL context' is written in the pop-up window.

**Comment by andrei-toterman** [comment] 2024-10-18 10:38
Hey, @xypron! Are you perhaps on X11 and not on Wayland? It seems there are some issues with 24.10 not working properly on X11, for example https://forum.snapcraft.io/t/ubuntu-24-10-security-center-unable-to-create-gl-context/43431.

**Comment by andrei-toterman** [comment] 2024-10-18 10:41
I am also on KDE with X11, but on 24.04, and I do not encounter this issue, but I will try to reproduce it on 24.10. If the issue is indeed caused by something being broken in 24.10, then unfortunately I think we can only wait for that to be fixed, but I'll keep an eye on it.

**Comment by andrei-toterman** [comment] 2024-10-18 11:42
@xypron, what graphics card do you have?

**Comment by xypron** [comment] 2024-10-18 12:00
Am 18. Oktober 2024 12:38:43 MESZ schrieb Andrei Toterman ***@***.***>:
>Hey, @xypron! Are you perhaps on X11 and not on Wayland? It seems there are some issues with 24.10 not working properly on X11, for example https://forum.snapcraft.io/t/ubuntu-24-10-security-center-unable-to-create-gl-context/43431.
>

As already mentioned in the issue I am using X11. As snaps are meant to be usable across multiple distros, this problem should be fixed

**Comment by andrei-toterman** [comment] 2024-10-18 12:11
I understand, I just wanted to let you know that this problem might have a deeper cause that is outside of our particular snap, as other people seem to experience issues with snaps on X11 on 24.10, so a fix might not be able to come directly from us. Unfortunately, I tried both 1.14.1 and edge on 24.10 and I cannot reproduce the issue, as the GUI seems to work fine. So at the moment my suspicion is that the issue is either from 24.10 itself or from something specific to your setup. Can you tell me if you're using an nvidia graphics card?

**Comment by Christopher-Hayes** [comment] 2024-10-20 03:10
As a user, I'm seeing that error on snaps after upgrading to ubuntu 24.10. Running X11 with `nvidia-driver-560`.

Seems to affect all snaps - App Center has the error mentioned, other snaps like Security Center have the same error. Firefox thinks WebGL is in some way disabled. get.webgl.org shows:

> "Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card."

I'd guess an nvidia driver 560 bug.

**Comment by ricab** [comment] 2024-10-21 09:46
Thanks for the valuable input @Christopher-Hayes!

**Comment by andrei-toterman** [comment] 2024-10-21 10:00
Given that this seems to be an issue that affects all snaps, unfortunately the Multipass team cannot do anything about it. So I will close this now.

**Closed by andrei-toterman** 2024-10-21 10:00 UTC
Labels: needs triage
