### ISSUE TITLE
Consider a different location for Multipass files on Windows 10

### ISSUE THREAD

**Issue by tatroc** [canonical/multipass#1267] opened 2019-12-22 12:25 UTC
When I create a VM via Multipass the VM gets created in the following location
C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\foo

Consider using the default location setting for Hyper-V to store the files Hyper-V VM files
C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks
C:\ProgramData\Microsoft\Windows\Hyper-V
![image](https://user-images.githubusercontent.com/8890530/71321725-73c7a180-2483-11ea-8076-c80d91dc694c.png)

![image](https://user-images.githubusercontent.com/8890530/71321729-85a94480-2483-11ea-81a7-0e0c61b7cd59.png)

**Comment by Saviq** [comment] 2020-01-10 07:18
Duplicate of #1112

**Closed by Saviq** 2020-01-10 07:18 UTC
