### ISSUE TITLE
Boot errors not surfaced to users

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#807] opened 2019-05-29 17:01 UTC
I have an image that has run out of disk space and is failing to boot. 

It's showing an error: 
`Starting work \[2019-05-29T10:21:26.075] [error] [work] Unable to determine IP address` 

but not the true error in the logs (`/Library/Logs/Multipass`) about why it's failed to boot: 
`[  546.901033] cloud-init[1458]: OSError: [Errno 28] No space left on device`

**Comment by Saviq** [comment] 2019-05-30 07:46
While this feels wrong, we can probably apply a filter on the boot output of the instance and bubble some things up.

Not sure if it would have helped your case, as it wasn't booting any more…

**Comment by hatched** [comment] 2019-05-30 17:51
I've seen this error before so I knew that the `Unable to determine IP address` is a red herring. But I could see others in similar situations wasting time trying to track down that issue and not the root issue that may be in the real logs.

I'm not sure what the best approach to a fix might be, but my knee-jerk idea would be to "simply" ;) filter on error tags and present those in the output.

**Comment by townsend2010** [comment] 2023-11-03 13:23
This is in essence #136 and going to mark it as such.

**Comment by townsend2010** [comment] 2023-11-03 13:23
Duplicate of #136

**Closed by townsend2010** 2023-11-03 13:23 UTC
