### ISSUE TITLE
launch failed: Downloaded image hash does not match

### ISSUE THREAD

**Issue by d762** [canonical/multipass#2419] opened 2022-01-31 16:54 UTC
When installed on Windows 10 the error occurs when installing 18/20/21 ubuntu version:

launch failed: Downloaded image hash does not match

to reproduce it just download multipass, install the latest version of Virtualbox and run multipass launch 20.04

[2022-01-31T17:51:26.144] [warning] [benevolent-drongo] Could not find the cloud-init ISO path for removal.
launch failed: Downloaded image hash does not match
[2022-01-31T17:51:26.153] [warning] [winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.

OS: Windows 10 Pro latest update

**Comment by Saviq** [comment] 2022-01-31 16:57
@d762 if you have instances, you can stop the service (`Stop-Service Multipass`), clear `C:\Windows\system32\config\systemprofile\AppData\LocalLow\multipassd` and start the service again (`Start-Service Multipass`).

If you don't, it'll be easier to just uninstall, asking it to remove all data, then reinstall again.

**Comment by Saviq** [comment] 2022-01-31 16:57
Duplicate of #1714

**Closed by Saviq** 2022-01-31 16:57 UTC
Labels: bug

**Comment by d762** [comment] 2022-01-31 18:11
Of course i did do  if you have instances, you can stop the service (Stop-Service Multipass), clear C:\Windows\system32\config\systemprofile\AppData\Local\multipassd and start the service again (Start-Service Multipass).

Locallow is emtpy. Local is not.

Roaming has files.

And it did not solve the issue.
