### ISSUE TITLE
launch failed: Instance stopped while starting

### ISSUE THREAD

**Issue by francomile** [canonical/multipass#3091] opened 2023-05-23 13:46 UTC
**Describe the bug**
Instance stops while launching it.
It tried to fecth the cloud images but they seem to have been removed or replaced by a different name ones:  

__https://cloud-images.ubuntu.com/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic__

These are now:

__https://cloud-images.ubuntu.com/releases/focal/release-20230522/unpacked/focal-server-cloudimg-amd64-vmlinuz-generic__

![Screenshot 2023-05-23 at 15 53 24](https://github.com/canonical/multipass/assets/3858567/f250d48b-6678-4121-be62-7a05140bc7c1)

```shell
 multipass launch -n vcl3 -c 2 -m 6G -d 30G 20.04 -v                                                                                                        ✔ │ 28s
[2023-05-23T15:27:14.397] [warning] [image vault] Cannot create instance image: /var/root/Library/Caches/multipassd/vault/images/focal-20230522/ubuntu-20.04-server-cloudimg-amd64.img missing
[2023-05-23T15:28:58.388] [warning] [url downloader] Error getting https://cloud-images.ubuntu.com/releases/server/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic: Error transferring https://cloud-images.ubuntu.com/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic - server replied: Not Found - trying cache.
[2023-05-23T15:28:58.635] [warning] [url downloader] Error getting https://cloud-images.ubuntu.com/releases/server/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-initrd-generic: Error transferring https://cloud-images.ubuntu.com/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-initrd-generic - server replied: Not Found - trying cache.
launch failed: The following errors occurred:
Instance stopped while starting
```

**To Reproduce**
How, and what happened?
1. `multipass launch -n vcl3 -c 2 -m 6G -d 30G 20.04 -v`
After having the same error launching the image I've removed the cached image`rm -rf /var/root/Library/Caches/multipassd/vault/images/focal-20230522`, and retried, having the same errors.
The same happens when using Ubuntu 22.04 image. 

**Expected behavior**
Expected to launch and start correctly the instance.

**Logs**

```shell
[2023-05-23T15:27:14.397] [warning] [image vault] Cannot create instance image: /var/root/Library/Caches/multipassd/vault/images/focal-20230522/ubuntu-20.04-server-cloudimg-amd64.img missing
[2023-05-23T15:28:58.388] [warning] [url downloader] Error getting https://cloud-images.ubuntu.com/releases/server/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic: Error transferring https://cloud-images.ubuntu.com/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic - server replied: Not Found - trying cache.
[2023-05-23T15:28:58.635] [warning] [url downloader] Error getting https://cloud-images.ubuntu.com/releases/server/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-initrd-generic: Error transferring https://cloud-images.ubuntu.com/releases/focal/release-20230522/unpacked/ubuntu-20.04-server-cloudimg-amd64-initrd-generic - server replied: Not Found - trying cache.
[2023-05-23T15:28:58.636] [debug] [hyperkit factory] app path '/Library/Application Support/com.canonical.multipass/bin'
[2023-05-23T15:28:58.636] [debug] [hyperkit factory] qemu-img-hyperkit convert, -p, -O, qcow2, /var/root/Library/Caches/multipassd/vault/images/focal-20230522/ubuntu-20.04-server-cloudimg-amd64.img, /var/root/Library/Caches/multipassd/vault/images/focal-20230522/ubuntu-20.04-server-cloudimg-amd64.qcow2
[2023-05-23T15:29:00.718] [debug] [qemu-img] [2356] started: qemu-img info /var/root/Library/Caches/multipassd/vault/images/focal-20230522/ubuntu-20.04-server-cloudimg-amd64.img
[2023-05-23T15:29:00.756] [debug] [vcl3] Waiting for SSH to be up
[2023-05-23T15:29:00.756] [debug] [vcl3] process working dir ''
[2023-05-23T15:29:00.756] [info] [vcl3] process program '/Library/Application Support/com.canonical.multipass/bin/hyperkit'
[2023-05-23T15:29:00.756] [info] [vcl3] process arguments '-c, 2, -m, 6144M, -u, -A, -H, -U, 9bc5e7c8-eb2c-37bf-b237-edefd469c40e, -s, 0:0,hostbridge, -s, 2:0,virtio-net, -s, 5,virtio-rnd, -s, 31,lpc, -l, com1,autopty=/var/root/Library/Application Support/multipassd/vault/instances/vcl3/pty,log=/Library/Logs/Multipass/vcl3-hyperkit.log, -s, 1:0,virtio-blk,file:///var/root/Library/Application Support/multipassd/vault/instances/vcl3/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false, -s, 1:1,ahci-cd,/var/root/Library/Application Support/multipassd/vault/instances/vcl3/cloud-init-config.iso, -f, kexec,/var/root/Library/Application Support/multipassd/vault/instances/vcl3/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic,/var/root/Library/Application Support/multipassd/vault/instances/vcl3/ubuntu-20.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/vda1 rw panic=1 no_timer_check'
[2023-05-23T15:29:00.757] [info] [vcl3] process state changed to Starting
[2023-05-23T15:29:00.759] [info] [vcl3] process state changed to Running
[2023-05-23T15:29:00.767] [error] [vcl3] Using fd 5 for I/O notifications
[2023-05-23T15:29:00.770] [info] [vcl3] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/vcl3/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None

[2023-05-23T15:29:00.770] [info] [vcl3] hyperkit: [INFO] rounding up file to a whole number of clusters (= 3096704 sectors)
[2023-05-23T15:29:00.798] [info] [vcl3] hyperkit: [INFO] Resized file to 24193 clusters (3096704 sectors)
[2023-05-23T15:29:00.798] [info] [vcl3] hyperkit: [INFO] block recycler starting with keep_erased = 2048
[2023-05-23T15:29:00.798] [info] [vcl3] hyperkit: [INFO] discard requested and lazy_refcounts is disabled: erasing refcount table and enabling lazy_refcounts
[2023-05-23T15:29:00.801] [info] [vcl3] hyperkit: [INFO] image has 0 free sectors and 24189 used sectors
[2023-05-23T15:29:00.801] [info] [vcl3] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/vcl3/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None returning 0
mirage_block_stat

[2023-05-23T15:29:00.802] [info] [vcl3] /var/root/Library/Application Support/multipassd/vault/instances/vcl3/cloud-init-config.iso: fcntl(F_PUNCHHOLE) Operation not permitted: block device will not support TRIM/DISCARD
[2023-05-23T15:29:01.007] [error] [vcl3] vmx_set_ctlreg: cap_field: 2 bit: 22 unspecified don't care: bit is 0
[2023-05-23T15:29:01.007] [error] [vcl3] vmx_set_ctlreg: cap_field: 4 bit: 12 unspecified don't care: bit is 0
[2023-05-23T15:29:01.007] [error] [vcl3] vmx_set_ctlreg: cap_field: 4 bit: 20 unspecified don't care: bit is 0
[2023-05-23T15:29:01.007] [error] [vcl3] vmx_set_ctlreg: cap_field: 3 bit: 13 unspecified don't care: bit is 0
[2023-05-23T15:29:01.007] [info] [vcl3] linkname /var/root/Library/Application Support/multipassd/vault/instances/vcl3/pty
COM1 connected to /dev/ttys007

[2023-05-23T15:29:01.007] [error] [vcl3] kexec: failed to load kernel /var/root/Library/Application Support/multipassd/vault/instances/vcl3/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic
[2023-05-23T15:29:01.008] [error] [vcl3] process error occurred Crashed
[2023-05-23T15:29:01.008] [info] [vcl3] process state changed to NotRunning
[2023-05-23T15:29:01.008] [info] [vcl3] process finished with exit code 6
```

**Additional info**
 - OS: MacOS 13.3.1 (a) 
- `multipass version`
```shell
multipass   1.11.1+mac
multipassd  1.11.1+mac
```
- `multipass info --all`
```shell
Name:           vcl1
State:          Stopped
IPv4:           --
Release:        --
Image hash:     eb20cd25da5d (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           vcl2
State:          Running
IPv4:           192.168.64.24
Release:        Ubuntu 20.04.6 LTS
Image hash:     5c55155af93c (Ubuntu 20.04 LTS)
CPU(s):         2
Load:           1.39 0.31 0.10
Disk usage:     3.5GiB out of 28.9GiB
Memory usage:   183.8MiB out of 5.8GiB
Mounts:         --

Name:           vcl3
State:          Stopped
IPv4:           --
Release:        --
Image hash:     ba2c18b8eb43 (Ubuntu 20.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver`
```shell
hyperkit
```
**Additional context**
multipass installation done with homebrew cask.

**Comment by townsend2010** [comment] 2023-05-23 13:57
Hi @francomile!

Yes, Hyperkit is broken on the latest version(s) of macOS.  The `qemu` driver works well though.  We are deprecating Hyperkit in our upcoming 1.12 release and that release has the ability to migrate Hyperkit instances to QEMU instances.  If you would like to try the latest release candidate in order to migrate your existing instances, you can find that at https://github.com/canonical/multipass/releases/tag/v1.12.0-rc.

Duplicate of #3080.

**Closed by townsend2010** 2023-05-23 13:57 UTC
