### ISSUE TITLE
multipass 1.6.2 hangs forever while trying to create a instance

### ISSUE THREAD

**Issue by toabctl** [canonical/multipass#2107] opened 2021-05-17 09:13 UTC
**Describe the bug**
I'm trying to create a instance with multipass:
```
$ multipass -v launch
Creating excellent-greenling - 
```

That process hangs forever (at least for 20 min). And `multipass list` does not show anything.

I'm using Ubuntu hirsute (latest updates installed, no proposed enabled). snap is:
```
$ snap info multipass|grep 'snap-id\|tracking'
snap-id:      mA11087v6dR3IEcQLgICQVjuvhUUBUKM
tracking:     latest/stable
```
Looking at `sudo journalctl -x -u snap.multipass.multipassd.service -f` while starting a instance does not print anything new. But the latest entries are:
```
Mai 17 10:58:49 thymian multipassd[28241]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
Mai 17 10:58:49 thymian multipassd[28241]: Starting Multipass 1.6.2
Mai 17 10:58:49 thymian multipassd[28241]: Daemon arguments: /snap/multipass/4458/bin/multipassd --verbosity debug --logger platform
Mai 17 10:58:49 thymian multipassd[28241]: propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.225\" (uid=0 pid=28241 comm=\"/snap/multipass/4458/bin/multipassd --verbosity de\" label=\"snap.multipass.multipassd (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1453 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
Mai 17 10:58:49 thymian multipassd[28241]: nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.225\" (uid=0 pid=28241 comm=\"/snap/multipass/4458/bin/multipassd --verbosity de\" label=\"snap.multipass.multipassd (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1453 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
Mai 17 10:58:49 thymian multipassd[28241]: "Object path cannot be empty"

```

**Additional info**
```
$ multipass --version
multipass  1.6.2
multipassd 1.6.2
```
```
$ multipass info --all

```

**Comment by Saviq** [comment] 2021-05-17 09:16
Hi @toabctl, you'll need to disconnect from the VPN :)

**Comment by Saviq** [comment] 2021-05-17 09:16
Duplicate of #2104

**Closed by Saviq** 2021-05-17 09:16 UTC
Labels: bug
