### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by github348** [canonical/multipass#2241] opened 2021-09-16 09:49 UTC
**Describe the bug**
Describe what your problem is.
Microsoft Windows [Version 10.0.19044.1237]
(c) Microsoft Corporation. All rights reserved.

C:\windows\system32>multipass sh
launch failed: Multipass support for Hyper-V requires Windows 10

C:\windows\system32>multipass sh -vvv
[2021-09-16T15:14:26.514] [debug] [powershell.exe] [3676] started: powershell.exe -NoProfile -NoExit -Command -
[2021-09-16T15:14:26.515] [debug] [Hyper-V Health Check] [3676] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty CurrentMajorVersionNumber'
[2021-09-16T15:14:28.596] [debug] [Hyper-V Health Check] [3676] Cmdlet exit status is 'true'
[2021-09-16T15:14:28.647] [debug] [Hyper-V Health Check] [3676] PowerShell finished successfully
launch failed: Multipass support for Hyper-V requires Windows 10
[2021-09-16T15:14:28.688] [warning] [winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.

C:\windows\system32>
**To Reproduce**
How, and what happened?
1. `multipass sh`
1.

**Expected behavior**
What did you expect to happen?
vm starts 
**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS:  windows 10
- `multipass version`
- 
C:\windows\system32>multipass version
multipass  1.7.0+win
multipassd 1.7.0+win

- `multipass info --all`

C:\windows\system32>multipass info --all

C:\windows\system32>
**Additional context**

**Comment by Saviq** [comment] 2021-09-16 10:19
Hi @github348, what does this say in powershell?

```powershell
Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty CurrentMajorVersionNumber
```

**Comment by github348** [comment] 2021-09-16 10:49
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6


PS C:\windows\system32> Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty CurrentMajorVersionNumber
10
PS C:\windows\system32>

**Comment by Saviq** [comment] 2021-09-16 10:53
OK that should be good, can you please run `multipass launch -vvvv` (4 "v"s) so we get a bit more verbose logging?

**Comment by github348** [comment] 2021-09-16 10:56
Microsoft Windows [Version 10.0.19044.1237]
(c) Microsoft Corporation. All rights reserved.

C:\windows\system32>multipass launch -vvvv
[2021-09-16T16:26:05.114] [trace] [url downloader] Found https://codeload.github.com/canonical/multipass-workflows/zip/refs/heads/main in cache: true
[2021-09-16T16:26:06.506] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/SHA256SUMS in cache: true
[2021-09-16T16:26:07.433] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/18/stable/current/SHA256SUMS in cache: true
[2021-09-16T16:26:08.772] [trace] [url downloader] Found https://cloud-images.ubuntu.com/buildd/releases/bionic/release/SHA256SUMS in cache: true
[2021-09-16T16:26:10.006] [trace] [url downloader] Found https://cloud-images.ubuntu.com/buildd/releases/focal/release/SHA256SUMS in cache: true
[2021-09-16T16:26:10.965] [trace] [url downloader] Found https://cloud-images.ubuntu.com/minimal/releases/xenial/release/SHA256SUMS in cache: true
[2021-09-16T16:26:11.830] [trace] [url downloader] Found https://cloud-images.ubuntu.com/releases/streams/v1/index.json in cache: false
[2021-09-16T16:26:14.934] [trace] [url downloader] Found https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json in cache: false
[2021-09-16T16:26:15.171] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/appliances/streams/v1/index.json in cache: true
[2021-09-16T16:26:15.177] [trace] [url downloader] Found https://cdimage.ubuntu.com/ubuntu-core/appliances/streams/v1/com.ubuntu.appliances:released:download.json in cache: true
[2021-09-16T16:26:15.183] [trace] [Hyper-V Health Check] PowerShell arguments: -NoProfile, -NoExit, -Command, -
[2021-09-16T16:26:15.183] [trace] [Hyper-V Health Check] PowerShell working dir ''
[2021-09-16T16:26:15.183] [trace] [Hyper-V Health Check] PowerShell program 'powershell.exe'
[2021-09-16T16:26:15.183] [trace] [Hyper-V Health Check] [0] PowerShell state changed to Starting
[2021-09-16T16:26:15.344] [trace] [Hyper-V Health Check] [0] PowerShell state changed to Running
[2021-09-16T16:26:15.373] [debug] [powershell.exe] [6200] started: powershell.exe -NoProfile -NoExit -Command -
[2021-09-16T16:26:15.374] [debug] [Hyper-V Health Check] [6200] Cmdlet: 'Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' | Select-Object -ExpandProperty CurrentMajorVersionNumber'
[2021-09-16T16:26:17.451] [trace] [Hyper-V Health Check] Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

10
[2021-09-16T16:26:17.451] [trace] [Hyper-V Health Check] [6200] Output: Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

10
[2021-09-16T16:26:17.451] [debug] [Hyper-V Health Check] [6200] Cmdlet exit status is 'true'
[2021-09-16T16:26:17.551] [trace] [Hyper-V Health Check] [6200] PowerShell state changed to NotRunning
[2021-09-16T16:26:17.552] [debug] [Hyper-V Health Check] [6200] PowerShell finished successfully
launch failed: Multipass support for Hyper-V requires Windows 10
[2021-09-16T16:26:17.624] [warning] [winterm] Could not find Windows Terminal's settings; location: ""; reason: File not found.

C:\windows\system32>

**Comment by Saviq** [comment] 2021-09-16 11:28
@github348 hey, so the screen reader is the problem here, we've not yet worked out how to best deal with that.

Duplicate of #1632

**Closed by Saviq** 2021-09-16 11:28 UTC
Labels: bug
