### ISSUE TITLE
Multipass app not showing up in MacOS Spotlight launcher

### ISSUE THREAD

**Issue by bithavoc** [canonical/multipass#3188] opened 2023-08-08 13:43 UTC
**Describe the bug**

Multipass app not showing up in MacOS Spotlight searches

**To Reproduce**
How, and what happened?
1. Press CMD+Space in MacOS, spotlight opens up
2. type "multipass"

**Expected behavior**
multipass should show up as any other app in MacOS, it does not.

**Logs**

**Additional info**
 - `OS`: `MacOS Ventura 13.5 (22G74)`
- `multipass version`: `1.12.2`

**Additional context**

This is what pops up for `multipass` in spotlight (**NOT OK**):

<img width="787" alt="image" src="https://github.com/canonical/multipass/assets/219289/1b36ad9c-26c7-40d4-915d-9f056ea0939d">

Example launch of visual studio code by just typing `visual` in spotlight (**OK**):
<img width="787" alt="image" src="https://github.com/canonical/multipass/assets/219289/9da53fcb-56d8-4b79-a25e-5cbd7cff45b5">

**Comment by townsend2010** [comment] 2023-08-08 14:23
Hi @bithavoc!

This is a duplicate of #2388.  This does remind me that this should be fixed, so I'll add that bug to the 1.13 Milestone.

**Comment by townsend2010** [comment] 2023-08-08 14:24
Duplicate of #2388

**Closed by townsend2010** 2023-08-08 14:24 UTC
