### ISSUE TITLE
MacOS Big Sur

### ISSUE THREAD

**Issue by dougreid72** [canonical/multipass#1780] opened 2020-10-05 15:11 UTC
Virtualization on MacOS seems to be having issues for multiple virtualization applications.   How close is Multipass to being available on Big Sur.  I just found Multipass the other day and it will help me in my new job.

**Comment by Saviq** [comment] 2020-10-05 15:18
Hi @dougreid72, have a look at #1664 - our upcoming release (next week) will have Big Sur support.

You can try the pre-release package from https://github.com/canonical/multipass/issues/1664#issuecomment-693644951.

**Comment by Saviq** [comment] 2020-10-05 15:18
Duplicate of #1664

**Closed by Saviq** 2020-10-05 15:18 UTC
