### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by seanomal666777** [canonical/multipass#3025] opened 2023-04-08 13:35 UTC
When launching Multipass for the first time, I get the following output from "Multipass launch --name foo"

launch failed: Remote "release" is unknown or unreachable. If image mirror is enabled, please confirm it is valid.

**Logs**

2023-04-08T09:17:07.725] [warning] [Qt] Execution of PAC script at "http%3A%2F$
[2023-04-08T09:17:07.725] [warning] [Qt] Execution of PAC script at "http%3A%2F$
[2023-04-08T09:17:07.726] [warning] [Qt] Execution of PAC script at "http%3A%2F$
[2023-04-08T09:17:17.490] [warning] [url downloader] Error getting https://clou$
[2023-04-08T09:17:17.491] [warning] [VMImageHost] Could not update manifest: fa$
[2023-04-08T09:17:17.496] [warning] [Qt] Execution of PAC script at "http%3A%2F$
[2023-04-08T09:17:27.490] [warning] [url downloader] Error getting https://cdim$
[2023-04-08T09:17:27.491] [warning] [VMImageHost] Could not update manifest: fa$
[2023-04-08T09:17:27.511] [info] [rpc] gRPC listening on unix:/var/run/multipas$
[2023-04-08T09:17:27.511] [warning] [Qt] QIODevice::write (QFile, "/var/root/Li$
[2023-04-08T09:17:27.511] [info] [daemon] Starting Multipass 1.11.1+mac
[2023-04-08T09:17:27.512] [info] [daemon] Daemon arguments: /Library/Applicatio$
[2023-04-08T09:18:07.489] [warning] [url downloader] Error getting https://mult$
[2023-04-08T09:18:07.492] [info] [update] Failed to fetch update info: failed t$
[2023-04-08T09:18:10.057] [warning] [Qt] Execution of PAC script at "http%3A%2F$
[2023-04-08T09:18:20.489] [warning] [url downloader] Error getting https://clou$
[2023-04-08T09:18:20.490] [warning] [VMImageHost] Could not update manifest: fa$
[2023-04-08T09:18:20.493] [warning] [Qt] Execution of PAC script at "http%3A%2F$
[2023-04-08T09:18:30.490] [warning] [url downloader] Error getting https://cdim$
[2023-04-08T09:18:30.490] [warning] [VMImageHost] Could not update manifest: fa$

**Additional info**
 - OS: macOS 13.4
`

**Comment by townsend2010** [comment] 2023-04-10 12:06
Hi @seanomal666777!

Sorry about this.  It looks like you are a victim of https://github.com/canonical/multipass/issues/2325.  The Multipass 1.13 release will update to Qt6, but unfortunately we do not have a date for when this will be released.

**Comment by townsend2010** [comment] 2023-04-10 12:06
Duplicate of #2325.

**Closed by townsend2010** 2023-04-10 12:06 UTC
