### ISSUE TITLE
Installation fails on macOS Big Sur DB5

### ISSUE THREAD

**Issue by flying-sausages** [canonical/multipass#1717] opened 2020-09-02 20:06 UTC
**Describe the bug**
The installation fails on macos 11

**To Reproduce**
- run `brew cask install multipass`
- returns failure

**Expected behavior**
successful install

**Logs**
Let me know if there is anything else that might prove useful in this, I'm not too well acquainted with macOS logging and troubleshooting

Brew output:
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
baidunetdisk                                       dcp-o-matic-batch-converter                        odrive                                             skype
bria                                               final-cut-library-manager                          quip                                               supercollider

==> Downloading https://github.com/CanonicalLtd/multipass/releases/download/v1.4.0/multipass-1.4.0+mac-Darwin.pkg
Already downloaded: /Users/mrsausage/Library/Caches/Homebrew/downloads/b2c7d462ebee4501315c211fe288aa8d954afe0b0ba0d60777fe2552ee2985cc--multipass-1.4.0+mac-Darwin.pkg
==> Verifying SHA-256 checksum for Cask 'multipass'.
==> Installing Cask multipass
==> Running installer for multipass; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is multipass
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “multipass-1.4.0 mac-Darwin.pkg”.)
==> Purging files for version 1.4.0 of Cask multipass
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=mrsausage USER=mrsausage USERNAME=mrsausage /usr/sbin/installer -pkg /usr/local/Caskroom/multipass/1.4.0/multipass-1.4.0\ mac-Darwin.pkg -target /` exited with 1. Here's the output:
installer: Package name is multipass
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “multipass-1.4.0 mac-Darwin.pkg”.)
```

`/var/log/install.log`:
```
[...]
2020-09-02 21:23:58+02 hOsTnAmE package_script_service[3387]: PackageKit: Executing script "preinstall" in /tmp/PKInstallSandbox.A08IoH/Scripts/com.canonical.multipass.multipassd.SaOw4E
2020-09-02 21:23:58+02 hOsTnAmE package_script_service[3387]: Set responsibility to pid: 441, responsible_path: /Applications/iTerm.app/Contents/MacOS/iTerm2
2020-09-02 21:23:58+02 hOsTnAmE install_monitor[3386]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2020-09-02 21:23:59+02 hOsTnAmE package_script_service[3387]: ./preinstall: Multipass currently requires macOS 10.12 or newer
2020-09-02 21:23:59+02 hOsTnAmE package_script_service[3387]: Responsibility set back to self.
2020-09-02 21:23:59+02 hOsTnAmE install_monitor[3386]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2020-09-02 21:23:59+02 hOsTnAmE installd[627]: PackageKit: releasing backupd
2020-09-02 21:23:59+02 hOsTnAmE installd[627]: PackageKit: allow user idle system sleep
2020-09-02 21:23:59+02 hOsTnAmE installd[627]: PackageKit: Cleared responsibility for install from 3383.
2020-09-02 21:23:59+02 hOsTnAmE installd[627]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package <E2><80><9C>multipass-1.4.0 mac-Darwin.pkg<E2><80><9D>." UserInfo={NSFilePath=./preinstall, NSURL=file:///usr/local/Caskroom/multipass/1.4.0/multipass-1.4.0%20mac-Darwin.pkg#multipass-1.4.0+mac-Darwin-multipassd.pkg, PKInstallPackageIdentifier=com.canonical.multipass.multipassd, NSLocalizedDescription=An error occurred while running scripts from the package <E2><80><9C>multipass-1.4.0 mac-Darwin.pkg<E2><80><9D>.} {
            NSFilePath = "./preinstall";
            NSLocalizedDescription = "An error occurred while running scripts from the package \U201cmultipass-1.4.0 mac-Darwin.pkg\U201d.";
            NSURL = "file:///usr/local/Caskroom/multipass/1.4.0/multipass-1.4.0%20mac-Darwin.pkg#multipass-1.4.0+mac-Darwin-multipassd.pkg";
            PKInstallPackageIdentifier = "com.canonical.multipass.multipassd";
        }
2020-09-02 21:23:59+02 hOsTnAmE installd[627]: PackageKit: Running idle tasks
2020-09-02 21:23:59+02 hOsTnAmE installer[3383]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package <E2><80><9C>multipass-1.4.0 mac-Darwin.pkg<E2><80><9D>." UserInfo={NSFilePath=./preinstall, NSURL=file:///usr/local/Caskroom/multipass/1.4.0/multipass-1.4.0%20mac-Darwin.pkg#multipass-1.4.0+mac-Darwin-multipassd.pkg, PKInstallPackageIdentifier=com.canonical.multipass.multipassd, NSLocalizedDescription=An error occurred while running scripts from the package <E2><80><9C>multipass-1.4.0 mac-Darwin.pkg<E2><80><9D>.}
2020-09-02 21:23:59+02 hOsTnAmE installd[627]: PackageKit: Removing client PKInstallDaemonClient pid=3383, uid=0 (/usr/sbin/installer)
2020-09-02 21:23:59+02 hOsTnAmE installd[627]: PackageKit: Done with sandbox removals
2020-09-02 21:23:59+02 hOsTnAmE installer[3383]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```

**Additional info**
- OS: macOS 11 (DB5)
- 2015 MBP 13"

**Additional context**
https://blogs.vmware.com/teamfusion/2020/07/fusion-big-sur-tech-preview.html

**Comment by Saviq** [comment] 2020-09-02 20:13
Duplicate of #1664

**Comment by Saviq** [comment] 2020-09-02 20:13
Hey @flying-sausages, we have a bug for this already ↑.

**Closed by Saviq** 2020-09-02 20:13 UTC
Labels: bug
