### ISSUE TITLE
Unable to transfer files with names starting with dot "."

### ISSUE THREAD

**Issue by guilford** [canonical/multipass#2421] opened 2022-01-31 18:34 UTC
**Describe the bug**
Transferring files with names starting with `.` fail with `transfer failed: [sftp push] error opening file for reading: Permission denied`. If this behaviour is intended then perhaps that could be reported instead of the permission denied error.

**To Reproduce**
How, and what happened?
1. touch foo
1. `multipass transfer foo primary:/home/ubuntu/foo` this is fine
2. touch .foo
3. `multipass transfer .foo primary:/home/ubuntu/foo` this fails

**Expected behavior**
The file to transfer normally

**Logs**
No data from either `journalctl --unit snap.multipass*` or `multipass -v` when the issue occurs.

**Additional info**
 - OS: Ubuntu 21.10 
     - `uname -a` `Linux 5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- `multipass version`
    -`multipass   1.8.0`
    -`multipassd  1.8.0`
 
- `multipass info --all`
```Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     e1264d4cca6c (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /home/dlg/src/foo => /home/dlg/src/foo
                    UID map: 1000:default
                    GID map: 1000:default
```

**Additional context**
None

**Comment by Saviq** [comment] 2022-02-01 17:53
Duplicate of #1783

**Closed** 2022-02-01 17:52 UTC
Labels: bug
