### ISSUE TITLE
Data loss on Windows upgrade

### ISSUE THREAD

**Issue by Alan-Jowett** [canonical/multipass#1463] opened 2020-04-02 16:18 UTC
**Describe the bug**
Multipass stores it's VM's under %Windir%\System32\config\systemprofile\AppData\Roaming\multipassd

After upgrading to a newer version of Windows 10, all my VMs are gone.

**To Reproduce**
Install multipass
Create VMs
Upgrade Windows

**Expected behavior**
VMs show up after upgrade.

**Logs**
Gone.

**Additional info**
Windows 10 Insider

**Additional context**
Data is still present in Windows.old\Windows\System32\config\systemprofile\AppData\Roaming\multipassd after upgrade, but VM's don't launch.

**Comment by Saviq** [comment] 2020-04-02 16:54
Duplicate of #1112

Hi @Alan-Jowett, we have a report about this already and will move out from there soon.

**Comment by Saviq** [comment] 2020-04-02 16:54
Duplicate of #1112

**Closed by Saviq** 2020-04-02 16:54 UTC
