### ISSUE TITLE
19.04 image

### ISSUE THREAD

**Issue by matti** [canonical/multipass#1410] opened 2020-03-07 11:19 UTC
multipass 1.1.0 on mac:

```
$ multipass find
Image                   Aliases           Version          Description
snapcraft:core          core16            20200221         Snapcraft builder for Core 16
snapcraft:core18                          20200221         Snapcraft builder for Core 18
16.04                   xenial            20200218.1       Ubuntu 16.04 LTS
18.04                   bionic,lts        20200218         Ubuntu 18.04 LTS
```

where's the 19.04 image as shown in the README.md?

**Comment by Saviq** [comment] 2020-03-09 09:59
Hi @matti, we only support a subset of images on macOS and Windows at the moment.

**Comment by Saviq** [comment] 2020-03-09 09:59
Duplicate of #1028

**Closed by Saviq** 2020-03-09 09:59 UTC
