### ISSUE TITLE
Network is unreachable when booting new instance

### ISSUE THREAD

**Issue by davidlane-iteratec** [canonical/multipass#1866] opened 2020-11-30 17:46 UTC
I have the same problem in the same context as https://github.com/canonical/multipass/issues/1088

I just installed snapcraft on an ubuntu 20.10 which installs multipass 1.5.0 automatically.
After this, networking does not work in the snapcraft VM or in a test VM.

```
$ multipass launch --name test
Launched: test     
$ multipass shell test        
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-54-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Nov 30 18:39:31 CET 2020

  System load:  0.01              Processes:             99
  Usage of /:   26.4% of 4.67GB   Users logged in:       0
  Memory usage: 18%               IPv4 address for ens4: 10.51.155.132
  Swap usage:   0%


1 update can be installed immediately.
0 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings


Last login: Mon Nov 30 18:36:04 2020 from 10.51.155.1
ubuntu@test:~$ sudo apt-get update
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease                                                                
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out
Err:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                                        
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable)
Err:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease                                                      
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable)
Err:4 http://security.ubuntu.com/ubuntu focal-security InRelease                                                      
  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.38), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.142), connection timed out
Reading package lists... Done                             
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::15). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::18). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.38), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.142), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
ubuntu@test:~$ 

```

Here are the iptables:
```
sudo iptables-legacy -S 
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -i mpqemubr0 -p tcp -m tcp --dport 53 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A INPUT -i mpqemubr0 -p udp -m udp --dport 53 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A INPUT -i mpqemubr0 -p udp -m udp --dport 67 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A FORWARD -i mpqemubr0 -o mpqemubr0 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A FORWARD -s 10.51.155.0/24 -i mpqemubr0 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A FORWARD -d 10.51.155.0/24 -o mpqemubr0 -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A FORWARD -i mpqemubr0 -m comment --comment "generated for Multipass network mpqemubr0" -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -o mpqemubr0 -m comment --comment "generated for Multipass network mpqemubr0" -j REJECT --reject-with icmp-port-unreachable
-A OUTPUT -o mpqemubr0 -p tcp -m tcp --sport 53 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A OUTPUT -o mpqemubr0 -p udp -m udp --sport 53 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
-A OUTPUT -o mpqemubr0 -p udp -m udp --sport 67 -m comment --comment "generated for Multipass network mpqemubr0" -j ACCEPT
```
I even tried removing the 2 Reject Rules as mentioned in the previous ticket but the problem persists:
$ sudo iptables -D FORWARD -o mpqemubr0 -m comment --comment "generated for Multipass network mpqemubr0" -j REJECT --reject-with icmp-port-unreachable
$ sudo iptables -D FORWARD -i mpqemubr0 -m comment --comment "generated for Multipass network mpqemubr0" -j REJECT --reject-with icmp-port-unreachable

Has the fix above actually been released?

**Comment by townsend2010** [comment] 2020-11-30 18:01
Hi @davidlane-iteratec,

Yes, the aforementioned fix has been released for some time now.  Are you using a proxy or any other special networking setup on your host such as a VPN or a firewall?

**Comment by davidlane-iteratec** [comment] 2020-11-30 18:45
Hi Chris: no I'm directly connected to the internet

**Comment by townsend2010** [comment] 2020-11-30 19:10
@davidlane-iteratec,

Hmm, ok.  This is strange.  Your host can see and connect to the Multipass instance, so no problems there.  Even DNS is working properly inside the Multipass instance.  It's when the Multipass instance tries to go outside the host which is problematic.  In my experience, this is caused by *something* set on the host that blocks access from the Multipass subnet, which is `10.51.155.x` in your case.

Could you also provide the output of `ifconfig -a`?

**Comment by davidlane-iteratec** [comment] 2020-11-30 20:01
```
ifconfig -a         
br-34a94e353c50: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:75ff:fe9b:3c16  prefixlen 64  scopeid 0x20<link>
        ether 02:42:75:9b:3c:16  txqueuelen 0  (Ethernet)
        RX packets 9194  bytes 21931684 (21.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 80603  bytes 11681564 (11.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:1aff:fe80:e16c  prefixlen 64  scopeid 0x20<link>
        ether 02:42:1a:80:e1:6c  txqueuelen 0  (Ethernet)
        RX packets 196841  bytes 13760180 (13.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 223181  bytes 2318347761 (2.3 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enxa0cec8d39223: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether a0:ce:c8:d3:92:23  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 304737  bytes 75997362 (75.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 304737  bytes 75997362 (75.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mpqemubr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.51.155.1  netmask 255.255.255.0  broadcast 10.51.155.255
        inet6 fe80::5054:ff:fe29:9e7b  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:29:9e:7b  txqueuelen 1000  (Ethernet)
        RX packets 5575  bytes 518700 (518.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3039  bytes 375317 (375.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mpqemubr0-dummy: flags=130<BROADCAST,NOARP>  mtu 1500
        ether 52:54:00:29:9e:7b  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tap-d1d16a4a0a7: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::90c3:32ff:fe31:3cc9  prefixlen 64  scopeid 0x20<link>
        ether 92:c3:32:31:3c:c9  txqueuelen 1000  (Ethernet)
        RX packets 5575  bytes 596750 (596.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3078  bytes 381371 (381.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth1e8a658: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::c8f8:d1ff:fe59:3e0c  prefixlen 64  scopeid 0x20<link>
        ether ca:f8:d1:59:3e:0c  txqueuelen 0  (Ethernet)
        RX packets 15334  bytes 1290487 (1.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 74093  bytes 9500714 (9.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth62b762e: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a846:7aff:fec7:41a6  prefixlen 64  scopeid 0x20<link>
        ether aa:46:7a:c7:41:a6  txqueuelen 0  (Ethernet)
        RX packets 22091  bytes 7526219 (7.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 68967  bytes 8959728 (8.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth8a9ca62: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a86b:faff:fe9b:761f  prefixlen 64  scopeid 0x20<link>
        ether aa:6b:fa:9b:76:1f  txqueuelen 0  (Ethernet)
        RX packets 311  bytes 28765 (28.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 53261  bytes 7634738 (7.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp59s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.178.33  netmask 255.255.255.0  broadcast 192.168.178.255
        inet6 fe80::1a6:cc81:59:ab2  prefixlen 64  scopeid 0x20<link>
        ether 5c:87:9c:fa:db:1f  txqueuelen 1000  (Ethernet)
        RX packets 18069108  bytes 14567045819 (14.5 GB)
        RX errors 0  dropped 602483  overruns 0  frame 0
        TX packets 5974207  bytes 4910027754 (4.9 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by andreyfedoseev** [comment] 2020-12-03 13:30
I'm having exactly the same issue with multipass 1.5.0 rev. 2907

I'm also directly connected to the internet. I also tried to remove the aforementioned iptables rules to no result.

This was a fresh install of multipass made by snapcraft, I haven't used it before.

`ifconfig -a` is

```
br-180ad4a1d1c1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.20.0.1  netmask 255.255.0.0  broadcast 172.20.255.255
        ether 02:42:69:cc:3b:12  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br-2c295201e523: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:9eff:fe3c:deb4  prefixlen 64  scopeid 0x20<link>
        ether 02:42:9e:3c:de:b4  txqueuelen 0  (Ethernet)
        RX packets 464  bytes 236656 (236.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3765  bytes 2169871 (2.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br-ffda2ec2d9b5: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.19.0.1  netmask 255.255.0.0  broadcast 172.19.255.255
        ether 02:42:99:9e:f9:ea  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:a2:7a:bc:cc  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.3  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::821a:839:c5d8:20be  prefixlen 64  scopeid 0x20<link>
        ether a8:a1:59:10:34:21  txqueuelen 1000  (Ethernet)
        RX packets 7293969  bytes 8112519293 (8.1 GB)
        RX errors 0  dropped 2364  overruns 0  frame 0
        TX packets 6616979  bytes 5491464446 (5.4 GB)
        TX errors 4  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 225895  bytes 32623576 (32.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 225895  bytes 32623576 (32.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mpqemubr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.65.154.1  netmask 255.255.255.0  broadcast 10.65.154.255
        inet6 fe80::4c6a:b2ff:fe1a:ba08  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:92:4e:c7  txqueuelen 1000  (Ethernet)
        RX packets 6630  bytes 1026919 (1.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7104  bytes 1038374 (1.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mpqemubr0-dummy: flags=130<BROADCAST,NOARP>  mtu 1500
        ether 52:54:00:92:4e:c7  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tap-9b2cc108e50: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::c4d2:bff:fe1c:b878  prefixlen 64  scopeid 0x20<link>
        ether c6:d2:0b:1c:b8:78  txqueuelen 1000  (Ethernet)
        RX packets 1671  bytes 280430 (280.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1626  bytes 253609 (253.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth6943580: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::1415:84ff:fe0e:7db0  prefixlen 64  scopeid 0x20<link>
        ether 16:15:84:0e:7d:b0  txqueuelen 0  (Ethernet)
        RX packets 54  bytes 20269 (20.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4766  bytes 2973322 (2.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth2faf530: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::10e7:b2ff:fe0c:1f  prefixlen 64  scopeid 0x20<link>
        ether 12:e7:b2:0c:00:1f  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4715  bytes 2959246 (2.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethf7981a1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::e3:7bff:fe08:489a  prefixlen 64  scopeid 0x20<link>
        ether 02:e3:7b:08:48:9a  txqueuelen 0  (Ethernet)
        RX packets 17  bytes 1033 (1.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4728  bytes 2961283 (2.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethfe5baaa: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::6ca4:b3ff:fea1:81f  prefixlen 64  scopeid 0x20<link>
        ether 6e:a4:b3:a1:08:1f  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4716  bytes 2959316 (2.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by townsend2010** [comment] 2020-12-03 13:34
Hi @andreyfedoseev and @davidlane-iteratec,

Now that there is a bit more data, it's curious both of you have docker installed.  I wonder if their networking is somehow blocking our `dnsmasq` from operating properly.

Could either or both of you provide the output of `ps -aef | grep dnsmasq`?  Also, if you are willing and able, try uninstalling or disabling docker and see if it helps.

**Comment by andreyfedoseev** [comment] 2020-12-03 13:54
@townsend2010 thank you for the swift response

I do have docker installed

`ps -aef | grep dnsmasq` output is 

```
nobody    280173  279901  0 17:37 ?        00:00:00 /snap/multipass/2907/usr/sbin/dnsmasq --keep-in-foreground --strict-order --bind-interfaces --pid-file --domain=multipass --local=/multipass/ --except-interface=lo --interface=mpqemubr0 --listen-address=10.65.154.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/snap/multipass/common/data/multipassd/network/dnsmasq.leases --dhcp-hostsfile=/var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts --dhcp-range 10.65.154.2,10.65.154.254,infinite --conf-file=/var/snap/multipass/common/data/multipassd/network/dnsmasq-279901.conf
andrey    298370  295292  0 18:49 pts/0    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox dnsmasq
```

I stopped all running docker containers and removed all docker networks with `docker system prune`. Then I stopped the docker service with `sudo service docker stop`

Unfortunately, that didn't help.

In `ifconfig -a` I see that the `br-...` interfaces created for docker networks are now gone but I still see `docker0`.

**Comment by townsend2010** [comment] 2020-12-03 14:07
@andreyfedoseev,

Thanks.  I'll need to think about this some more.  Are you on Ubuntu 20.10 as well?

**Comment by andreyfedoseev** [comment] 2020-12-03 14:09
@townsend2010 Yes, it's Ubuntu 20.10

**Comment by townsend2010** [comment] 2020-12-03 14:18
@andreyfedoseev,

Ok.  One other thing...did you try rebooting your machine after disabling Docker just to be sure no cruft is left around?

**Comment by townsend2010** [comment] 2020-12-03 14:39
Ok, I think I have a theory on what is going on.  We include legacy `iptables` in our snap, but that doesn't play nicely with if anything else is using the new `nftables` introduced in 20.10, and I bet Docker is using the new `nftables`.

What we need to do is include legacy `iptables` and `nftables`-compatible `iptables` in our snap and at runtime, detect which tables are being used and then use the correct binary.  See https://forum.snapcraft.io/t/do-we-have-a-snap-for-iptables-which-works-as-expected/18302/4 for more info.

I will begin working on this and hopefully have a usable solution next week.

**Comment by andreyfedoseev** [comment] 2020-12-03 14:45
@townsend2010 

It seems that docker is using the new `nftables` indeed:

```
sudo iptables -S             
```

```
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-USER
-N DOCKER-ISOLATION-STAGE-2
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-USER -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
```

**Comment by townsend2010** [comment] 2020-12-03 14:47
Ok, thanks, that pretty much confirms my theory. If`nftables` are being used, then the legacy tables are not used which is why the Multipass instances cannot reach the Internet.

**Comment by KHIT93** [comment] 2020-12-08 10:35
I just ran into this issue the other day and can confirm that this also happens with multipass 1.5.0 on Pop_OS 20.10
Once I install docker in a VM, all my VM's loose network upon next host reboot

**Comment by andreyfedoseev** [comment] 2020-12-24 13:30
@townsend2010 Sorry to bother you, but is there any progress on this issue? Or is there any workaround for it that we could use now?

**Comment by townsend2010** [comment] 2021-01-04 14:14
Hi @andreyfedoseev,

I will work on coming up with a manual workaround and post it here and on Discourse while working on the full solution.

**Comment by townsend2010** [comment] 2021-01-04 19:52
Hey all,

Those affected by this, here is a script that will fix the issue:
```
#!/bin/bash

IFS=$'\n'

for table in filter nat mangle; do
  nftables=(`sudo iptables-legacy -S -t ${table} | grep "Multipass"`)

  for line in "${nftables[@]}"; do
    echo $line | xargs sudo iptables-nft -t ${table}
  done
done
```
**Note that it will need to run at each boot of the instance.**

**Comment by rkhyd** [comment] 2021-03-21 12:39
Hi,
When i run this script on the instance that is not connecting to the internet, it gives error 
`iptables v1.8.4 (nf_tables): no command specified
Try `iptables -h' or 'iptables --help' for more information.`

**Comment by Saviq** [comment] 2021-03-22 14:51
> `iptables v1.8.4 (nf_tables): no command specified Try `iptables -h' or 'iptables --help' for more information.`

This means that this: `iptables-legacy -t $table -S` gave no results - which means Multipass never created any (?).

Are there any lines containing Multipass in `iptables-legacy -t nat -S`? Are you running Multipass with the `qemu` driver? What's your Multipass version?

**Comment by Saviq** [comment] 2021-03-22 15:33
@rkhyd @ricab pointed out to me — you need to run this on your host, not in an instance!

**Comment by rkhyd** [comment] 2021-03-26 04:46
@Saviq @ricab ,
I have ran this on both the host and the instance as well. In both cases the output was the same
I am running multipass in ubuntu 20.10
multipass version is 1.6.2
![image](https://user-images.githubusercontent.com/15903310/112580051-1ce61000-8e1c-11eb-8ece-6cbc0bdd4f9b.png)
This is the output when i run the above script in the host itself.
the command `iptables-legacy -t nat -S` gave the following output
![image](https://user-images.githubusercontent.com/15903310/112580733-4acb5480-8e1c-11eb-81df-fded709fe248.png)

**Comment by ricab** [comment] 2021-03-26 11:23
Hi @rkhyd, that script tries to workaround `iftables-nft` clashing with `iptables-legacy`, by transporting Multipass's rules from legacy to nft. Those rules are created by Multipass on the host (when using the `qemu` backend), so the script has no effect inside instances. It should be run on the host, with Multipass installed and its daemon running.

If your instances still have no network after that, then there must be another reason. Do you have your own firewall config perhaps? Or are you using a VPN? Do you have the same issue if you try the [`libvirt`](https://multipass.run/docs/using-libvirt) backend (or `lxd` if you prefer)?

**Comment by jonathanbossenger** [comment] 2021-05-13 07:37
@townsend2010 thank you for finding a workaround, I've spent hours trying to figure out why my multipass instances can't run updates.

**Comment by tacticz** [comment] 2021-05-14 01:22
For your info, I experienced the exact same issue running multipass on a Debain 10 (buster) host...
The workaround script provided by @townsend2010 also fixed the problem, thank you!

**Closed** 2021-06-02 21:03 UTC

**Comment by santiagosoares80** [comment] 2021-07-06 12:50
> Hey all,
> 
> Those affected by this, here is a script that will fix the issue:
> 
> ```
> #!/bin/bash
> 
> for table in filter nat mangle; do
>   sudo iptables-legacy -t $table -S | grep Multipass | xargs -L1 sudo iptables-nft -t $table
> done
> ```
> 
> **Note that it will need to run at each boot of the host.**
> 
> Edit: I've updated the script. Thanks @Saviq!

It worked for me, thank you!!!

**Comment by krisstern** [comment] 2021-12-14 07:54
I had a similar problem too, turns out it was my `iptables` settings. It worked after I have "reset" / "flushed" the iptable rules to the basic ones. After which I was able to connect to to network (especially the snap store) through the `multipass` VM I started with `snapcraft`.

**Comment by lktslionel** [comment] 2022-02-16 16:26
Hello,

I have the same issue but I'm on macos and I use VirtualBox as a backend.

Any idea? 
Thanks
