### ISSUE TITLE
Lost ONE instance after power-lost (windows 8.1 within virtualbox)

### ISSUE THREAD

**Issue by PdrNG** [canonical/multipass#1832] opened 2020-11-06 08:57 UTC
**Describe the bug**
having 4 instance, 3 down, 1 up, working within it, 
power went off (building failure)

as I restart computer, multipass list did not list that instance, seems no problem with the other 3

Oracle VM VirtualBox manager loaded with & $env:USERPROFILE\Desktop\PSTools\PsExec.exe -s -i  $env:VBOX_MSI_INSTALL_PATH\VirtualBox.exe shows the four instance, but storage inaccesible

open folder: C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances
no trace of that fourth instance
seeem whole folder of instance went gone

**To Reproduce**
How, and what happened?
just power went off while working on a instance

**Expected behavior**
after power-on, instance exist, at least

**Logs**
before turn-off, all logs just informative
(lost instance called i2)

just after reboot: (one line per log entry)

[i2] Running: VBoxManage, showvminfo, i2, --machinereadable

[i2] VBoxManage failed - errorString: Process operation timed out, exitStatus: 0, exitCode: 0

[i2] Could not get instance info: Process operation timed out

[Qt] QProcess: Destroyed while process ("VBoxManage") is still running.

[i2] Running: VBoxManage, createvm, --name, i2, --groups, /Multipass, --ostype, ubuntu_64, --register

[i2] VBoxManage failed - errorString: Unknown error, exitStatus: 0, exitCode: 1

[daemon] Removing instance i2: Could not create VM: VBoxManage.exe: error:  Machine settings file 'C:\Windows\system32\config\systemprofile\VirtualBox  VMs\Multipass\i2\i2.vbox' already exists VBoxManage.exe: error: Details: code  VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine,  callee IUnknown VBoxManage.exe: error: Context:  "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(),  ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(),  machine.asOutParam())" at line 280 of file VBoxManageMisc.cpp
--

**Additional info**
 - OS: windows 8
- `multipass version` 1.4.0+ win

**Comment by ricab** [comment] 2020-11-06 12:14
Hi @PdrNG, thanks for reporting, I am sorry you experienced this.

I believe this is another case of #1658. Although the trigger for the failure will differ, the issue in Multipass seems to be the same, namely that the daemon removes the VM if it can't create it upon startup. 

I am marking this as duplicate. Please tune-in/comment on the other one.

**Closed by ricab** 2020-11-06 12:14 UTC
Labels: duplicate

**Comment by Saviq** [comment] 2020-11-06 12:19
Duplicate of 1658

**Comment by Saviq** [comment] 2020-11-06 12:19
Duplicate of #1658
