### ISSUE TITLE
[Question] How to increase memory size after creation? Failed from Kubespray-Ansible

### ISSUE THREAD

**Issue by scheung38** [canonical/multipass#1881] opened 2020-12-11 21:54 UTC
**Describe the bug**
How to increase memory size after creation? From multipass info --all below it seems already sufficient at 4.7GB and 981.4MB?

I could multipass launch --name -c XX -m XX ubuntu-1 but this would undo all config

**To Reproduce**
How, and what happened?
1. `multipass launch --name ubuntu-lts` (ie. didn't use -c -m flags)
2. ~ /kubespray$ ansible-playbook -b -v -i inventory/prod/hosts.ini cluster.yml 

**Expected behavior**
What did you expect to happen?
Success

**Logs**
![Screenshot 2020-12-11 at 21 54 40](https://user-images.githubusercontent.com/1273014/101958565-7cb50400-3bfb-11eb-8b45-19cb323aacaa.png)

**Additional info**
 - OS: macOS 11.0.1

- `multipass version` 
multipass  1.5.0+mac
multipassd 1.5.0+mac

- `multipass info --all`
![Screenshot 2020-12-11 at 21 53 02](https://user-images.githubusercontent.com/1273014/101958452-411a3a00-3bfb-11eb-9238-a82a35e7454a.png)

**Comment by Saviq** [comment] 2020-12-12 07:23
Hi @scheung38, here's a workaround while we work on allowing this on the CLI (#756):

https://github.com/canonical/multipass/issues/1158#issuecomment-548073024

**Comment by Saviq** [comment] 2020-12-12 07:23
Duplicate of #756

**Closed by Saviq** 2020-12-12 07:23 UTC
