### ISSUE TITLE
Monochrome toolbar icon

### ISSUE THREAD

**Issue by flying-sausages** [canonical/multipass#2199] opened 2021-08-12 09:15 UTC
**What are you trying to do?**
It would be nice if the multipass icon stood out a little less in default environments and offer to "blend in" by abstaining from colour.

**What's your proposed solution?**
A choice in the GUI to use  monochrome versions of the icon, and probably adapt those for light/dark modes too. I suppose that the padding of the icon could be adjusted too.

**Additional context**
Here's a screenshot of my menu bar, I suppose that the situation is the same on Gnome, Windows, and whatever else you have.
<img width="546" alt="afbeelding" src="https://user-images.githubusercontent.com/23618693/129171450-ab588bbc-85b7-4e21-a0b6-779f64d2fcd0.png">

**Comment by Saviq** [comment] 2021-08-12 09:53
Duplicate of #1240

**Closed by Saviq** 2021-08-12 09:53 UTC
Labels: enhancement
