### ISSUE TITLE
Could multipass on MacOS (M3/M4 chip) support to mapping the UART port from Macos to Ubuntu instance ?

### ISSUE THREAD

**Issue by 125yyh** [canonical/multipass#3801] opened 2024-11-30 12:27 UTC
I am refactoring an algo on Ubuntu 20.04 instance on MacOS for embedded platfrom, I want to verify the function firstly before porting it to the embedded platfrom, so I insert a external USB device (a GNSS rover) to my Macbook Air (M3), it can be identifed on MacOS, but I have no idea how to redirect it to Ubuntu instance.
When I plug in a USB device, is it possible to redirect it to the Ubuntu instance, just similar to how VMware does it? (I chose not to use VMware because it is less lightweight compared to Multipass.)

Thanks
Ray

**Comment by giuliazanchi** [comment] 2024-12-02 10:01
Hi @125yyh , if I understand your question correctly you'd like to map a USB device to your Multipass VM. Unfortunately, the USB passthrough feature is not currently supported. You can find additional context and discussion on a similar request here: https://github.com/canonical/multipass/issues/1897.

**Comment by giuliazanchi** [comment] 2024-12-02 10:08
Duplicate of #1897

**Closed by giuliazanchi** 2024-12-02 10:08 UTC
Labels: duplicate

**Comment by 125yyh** [comment] 2024-12-02 12:29
Hi, @giuliazanchi 
Thanks for your response, I got the tips from the page you provide.
