### ISSUE TITLE
Launch failed when Firewall is on

### ISSUE THREAD

**Issue by eveli909** [canonical/multipass#2781] opened 2022-10-17 09:52 UTC
It is possible to launch an Ubuntu virtual machine on Mac only when the Firewall is turned off. Otherwise the start fails and "timed out waiting for response" error shows up.

OS: macOS Monterey 12.5.1
multipass version: 1.10.1

Is there a solution how to run the VM with Firewall turned on?

**Comment by luis4a0** [comment] 2022-10-17 11:03
Hi @eveli909! We are having issues with MacOS firewall. Unfortunately, we don't have control of the firewall. One solution could be to enable debug mode on the firewall, that works sometimes but we cannot guarantee it always does. You can follow the discussion on this topic [here](https://github.com/canonical/multipass/issues/2387). Thanks!

Duplicate of #2387

**Closed by luis4a0** 2022-10-17 11:03 UTC
Labels: duplicate
