### ISSUE TITLE
Multipass 1.4.0 won't install on macOS Big Sur (11.0)

### ISSUE THREAD

**Issue by byronrode** [canonical/multipass#1699] opened 2020-08-20 09:16 UTC
**Describe the bug**

The follow error is received when installing the package.

```
The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “multipass-1.4.0 mac-Darwin.pkg”.
```

**To Reproduce**

1. Try the `.pkg` download from github.
2. Try install via `homebrew` -- `brew cask install multipass`

**Expected behavior**

Expect to install version 1.4.0 successfully.

**Logs**

```
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=redacted USER=redacted USERNAME=redacted /usr/sbin/installer -pkg /usr/local/Caskroom/multipass/1.4.0/multipass-1.4.0\ mac-Darwin.pkg -target /` exited with 1. Here's the output:
installer: Package name is multipass
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “multipass-1.4.0 mac-Darwin.pkg”.)
```

**Additional info**
 - OS: macOS 11.0 (Big Sur Beta 20A5343j)
- `multipass version` 1.2.1+mac (trying to update to 1.4.0)
- `multipass info --all`

```
Name:           nitro-dev
State:          Stopped
IPv4:           --
Release:        --
Image hash:     19f9b7067557 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         redacted                   => /home/ubuntu/sites/redacted.test
                    UID map: 501:default
                    GID map: 20:default
                redacted => /home/ubuntu/sites/redacted-2
                    UID map: 501:default
                    GID map: 20:default
```

**Additional context**

**Comment by Saviq** [comment] 2020-08-20 09:21
I'll collect all the macOS 11 issues under this one: #1664

**Comment by Saviq** [comment] 2020-08-20 09:21
Duplicate of #1664

**Closed by Saviq** 2020-08-20 09:21 UTC
Labels: bug
