### ISSUE TITLE
instances lossing after windows updated

### ISSUE THREAD

**Issue by cpu100** [canonical/multipass#1698] opened 2020-08-19 15:45 UTC
These directories `C:\Windows\System32\config\systemprofile\AppData\*\multipassd\` will be removed after windows big-updates, so it's a bad idea to store related data at there.

**Comment by Saviq** [comment] 2020-08-19 15:47
Hi, we are tracking this here:

Duplicate of #1119

**Comment by Saviq** [comment] 2020-08-19 15:47
Duplicate of #1119

**Comment by Saviq** [comment] 2020-08-19 15:48
FWIW they're not getting removed, they get moved to `C:\Windows.old…`, but that doesn't change the fact we need a better place.

**Closed by Saviq** 2020-08-19 15:47 UTC
Labels: bug
