### ISSUE TITLE
Multipass instances won't start on M1 Max MacBook Pro

### ISSUE THREAD

**Issue by tarbs** [canonical/multipass#2625] opened 2022-06-20 20:18 UTC
Hi,
I have been using Multipass until recently when - after a multipass upgrade - instances will no longer start and report the error "launch failed: The following errors occurred:                                   
<instance>: timed out waiting for response".

I have deleted all the instances, uninstalled multipass & reinstalled, but still get the error.

I have tried both direct install and install via homebrew.  I have most recently tested with version 1.9.2+mac .

Andy

**Comment by luis4a0** [comment] 2022-06-21 12:21
Hi @tarbs, did you update MacOS recently? We had some problems with the firewall on updates.

**Comment by tarbs** [comment] 2022-06-21 12:49
I've updated MacOS as releases come out (currently on v12.4) - I don't recall if Multipass stopped working at a particular MacOS update.

**Comment by luis4a0** [comment] 2022-06-21 12:54
MacOS update makes changes in the firewall. We cannot unfortunately control them, but there are some fixes to this [here](https://github.com/canonical/multipass/issues/2387).

I close this as duplicate of #2387. Thanks!

**Closed by luis4a0** 2022-06-21 12:54 UTC
Labels: duplicate
