### ISSUE TITLE
Multipass doesn't work (until restart) if stopped while retrieving images

### ISSUE THREAD

**Issue by 3v1n0** [canonical/multipass#2534] opened 2022-04-22 00:54 UTC
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?

```
❯ snapcraft                        
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-notify-send-test-snap" does not exist
'SNAPCRAFT_BUILD_ENVIRONMENT_CPU' was set to '8' in the environment. Changing the default allocation upon user request
'SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY' was set to '4G' in the environment. Changing the default allocation upon user request
Retrieving image: 4%^C                                                          
Aborted!

❯ snapcraft                        
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-notify-send-test-snap" does not exist
'SNAPCRAFT_BUILD_ENVIRONMENT_CPU' was set to '8' in the environment. Changing the default allocation upon user request
'SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY' was set to '4G' in the environment. Changing the default allocation upon user request
launch failed: Operation canceled                                               
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

After doing `snap restart multipass.multipass`, it works again.

**Expected behavior**
What did you expect to happen?

It resumes working without the need of restarting it.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

Don't say much:

```
apr 22 02:40:59 tricky multipassd[3953]: [1625519] started: /snap/multipass/6130/bin/check_kvm_support                                                     apr 22 02:40:59 tricky multipassd[3953]: [1625525] started: qemu-system-x86_64 --version                                                                   apr 22 02:41:39 tricky multipassd[3953]: [1625781] started: /snap/multipass/6130/bin/check_kvm_support                                                     apr 22 02:41:39 tricky multipassd[3953]: [1625786] started: qemu-system-x86_64 --version   
```

**Additional info**
- `multipass version`

```
multipass version                                   
multipass   1.8.0
multipassd  1.8.0
```

- `multipass info --all`

```
Name:           snapcraft-notify-send-test-snap
State:          Delayed Shutdown
IPv4:           10.140.55.110
Release:        Ubuntu 18.04.6 LTS
Image hash:     7c5c8f24046c (Ubuntu Snapcraft builder for Core 18)
Load:           0.13 0.38 0.20
Disk usage:     1.5G out of 247.9G
Memory usage:   89.3M out of 3.9G
Mounts:         --
```

**Comment by Saviq** [comment] 2022-04-22 07:53
Duplicate of #2288

**Comment by Saviq** [comment] 2022-04-22 07:53
Thanks @3v1n0, that's fixed in the next release:

https://github.com/canonical/multipass/releases/tag/v1.9.0-rc

**Closed by Saviq** 2022-04-22 07:53 UTC
Labels: bug

**Comment by Obasoro** [comment] 2023-08-05 11:44
``An error occurred with the instance when trying to start with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.```

I am getting this error when trying to install microk8s

**Comment by townsend2010** [comment] 2023-08-08 12:34
Hi @Obasoro!

Could you please [open a new bug report](https://github.com/canonical/multipass/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) and include the logs as requested in the bug report template?
