### ISSUE TITLE
multipass transfer fails with a dir as target

### ISSUE THREAD

**Issue by arashkaffamanesh** [canonical/multipass#1165] opened 2019-10-31 20:43 UTC
multipass transfer doesn't work by the the latest version multipassd 0.9.0-rc.425+g37fa4305.mac.

I'm getting this SFTP server: Failure after running multipass transfer:

```
$ multipass launch --name rke1
Launched: rke1
$ touch test
$ multipass transfer test rke1:/home/ubuntu/
transfer failed: [sftp push] open failed: 'SFTP server: Failure'
```

I guess this issue is related to the fact that the multipass standart user doesn't exist in v 0.9.0-rc anymore and ununtu is now the standard user:

```
ubuntu@rke1:~$ id multipass
id: ‘multipass’: no such user
```

Thanks in advance for any hint.

**Comment by townsend2010** [comment] 2019-11-01 11:54
@arashkaffamanesh,

Thanks for the report!  I'll look into this as I believe this would affect all platforms.

**Comment by townsend2010** [comment] 2019-11-01 11:56
@arashkaffamanesh,

Could you also try this?
```
$ multipass launch --name rke1
Launched: rke1
$ touch test
$ multipass transfer test rke1:test
```
I'm wondering if specify the home directory is what is messing this up.  Also, the error message leaves much to be desired :grin:

**Comment by arashkaffamanesh** [comment] 2019-11-01 12:03
WOW!
This works, thanks so much for the brilliant support!

**Comment by townsend2010** [comment] 2019-11-01 12:07
@arashkaffamanesh,

Awesome!  So I'll look into the other issues (specify $HOME and the error message), but I'm glad you at least have a working way to do this.

**Comment by townsend2010** [comment] 2019-11-01 13:59
I will note this isn't a regression in 0.9.  `transfer` in 0.8 would also fail when specifying the path, but it had a different error message.  That is due to using the `scp` protocol then vs. using the `sftp` protocol now.  The error message with `scp` was also cryptic, so we need to do something better although this error comes from `libssh` in both cases.

The real fix will be to allow not specifying the target file name and just use the same source file name.

**Comment by jasonmccallister** [comment] 2020-03-17 21:20
I have a few questions on how to utilize transfer, or more accurately two scenarios. We we building a tool that setups development machines and we using cloud-init files to `write_files` into `/opt/vendor/db/files.sh`. There are scenarios where we want to keep these scripts up to date so we would like to use `transfer` but we ran into a couple of problems.

1. Permissions issues is the first issue, we could update the cloud-init to grant the `ubuntu` permissions to modify those directories
2. Instead of copying the files into `/opt` I thought about copying them into `/home/ubuntu` but that returns an error of "file does not exist"

Any thoughts on the best approach here?

**Comment by Saviq** [comment] 2020-03-18 09:10
Hi @jasonmccallister I filed #1433 for the permissions issue.

On the second issue, did you create the folder where you wanted to push the file to, first?

I expect your problem was this:
```
$ multipass transfer file primary:missing/file
transfer failed: [sftp push] open failed: 'SFTP server: No such file'
$ multipass exec primary mkdir missing
$ multipass transfer file primary:missing/file
$ # worked
```

I filed #1434 to track this.

**Comment by jasonmccallister** [comment] 2020-03-18 16:25
Thank you @Saviq! I will give that a try by creating the directory first, and then transferring the files from a tmp directory.

**Comment by oussjarrousse** [comment] 2021-02-16 16:55
Adding a `-p ` option to `multipass transfer` would be nice...

`multipass transfer -p file primary:missing/path/file`

**Comment by zrml** [comment] 2021-08-25 10:45
Also it would be useful to be able to copy a full directory into an instance directory :-) 
Thanks to all for this wonderful tool!

**Closed** 2022-06-10 22:17 UTC
