### ISSUE TITLE
Support addressing instances by their hostnames / instance names

### ISSUE THREAD

**Issue by leighmcculloch** [canonical/multipass#2234] opened 2021-09-12 04:37 UTC
**What are you trying to do?**
I'm using multipass on mac. When I create an instance that works successfully, but the only method for referencing the instance is via its IP address. The instance name is not useable as its address.

For example if I run the command `multipass launch -n host`, and once it is up attempt to ping it with `ping host` or `ping host.local` neither work. If I ping the IP, it works.

I use a few instances with consistent names, but their IPs change which is inconvenient.

**What's your proposed solution?**
It would be convenient if instances were addressable using their hostnames or their instance names.

**Additional context**
```
% multipass version
multipass  1.7.0+mac
multipassd 1.7.0+Mac
```

**Comment by Saviq** [comment] 2021-09-12 09:01
Duplicate of #1830

**Closed by Saviq** 2021-09-12 09:01 UTC
Labels: enhancement

**Comment by Saviq** [comment] 2021-09-12 09:02
@leighmcculloch there are pointers on how to enable mDNS resolving (`.local` suffix) in #1830.
