### ISSUE TITLE
Windows Build Instructions

### ISSUE THREAD

**Issue by surahman** [canonical/multipass#2087] opened 2021-05-05 15:04 UTC
I have been searching for build instructions for Windows but have been unable to find them. There must be some setup instructions for the build environment which is used to build the Windows release. I am developing in Ubuntu 21.04 LTS on my laptop but it would be nice to work on a larger display on my Windows desktop.

**Comment by Saviq** [comment] 2021-05-05 15:29
Hi @surahman, I'm afraid those bits are currently closed source.

I'll dupe this to #1851.

**Comment by Saviq** [comment] 2021-05-05 15:29
Duplicate of #1851

**Closed by Saviq** 2021-05-05 15:29 UTC
