### ISSUE TITLE
emacs Display confusion

### ISSUE THREAD

**Issue by hengaini2055** [canonical/multipass#2131] opened 2021-06-01 22:30 UTC
**Describe the bug**
When I use emacs edit el file, the text display confusion. such as code text occupy line number postion, etc.

**To Reproduce**
How, and what happened?
1. `multipass launch` on windows 10
2. `multipass shell `
3. `sudo apt install emacs 27` on multipass' ubuntu
4. git clone doom-emacs or spacemacs configuration
5. emacs edit some el file
6. sometime as normal
![image](https://user-images.githubusercontent.com/20587475/120397411-df958580-c36a-11eb-806a-f0a9f5f95d0b.png)

7. sometime as abnormal
![image](https://user-images.githubusercontent.com/20587475/120397451-ef14ce80-c36a-11eb-9c8a-717fc866dd02.png)

**Expected behavior**
Using emacs in a multipass shell should be normal.

**Logs**
no

**Additional info**
 - OS: Windows 10 pro
- `multipass version` : multipass  1.6.2+win
- `multipass info --all`
Name:           u2004h
State:          Running
IPv4:           172.31.61.66
                172.17.0.1
                172.19.0.1
Release:        Ubuntu 20.04.2 LTS
Image hash:     04aabbbd5964 (Ubuntu 20.04 LTS)
Load:           0.22 0.28 0.28
Disk usage:     12.0G out of 19.2G
Memory usage:   8.2G out of 14.2G
Mounts:         C:/Users/hengaini2055/ub2004 => /home/ubuntu/u2004h
                    UID map: -2:default
                    GID map: -2:default
                C:/Users/hengaini2055/ub2004 => /home/ubuntu/ub2004
                    UID map: -2:default
                    GID map: -2:default

**Additional context**
I think this may be an interface refresh problem.

**Comment by hengaini2055** [comment] 2021-06-01 22:37
When I open multipass ubuntu shell using hotkey, that's normal; when I open in powershell using command, that's abnormal.
![image](https://user-images.githubusercontent.com/20587475/120398377-b4139a80-c36c-11eb-8552-b317d7d3768a.png)

**Comment by Saviq** [comment] 2021-06-02 09:36
Hi @hengaini2055 this is most likely #1314, we didn't get around to it yet, I'm afraid.

Will dupe to that one, then.

**Comment by Saviq** [comment] 2021-06-02 09:36
Duplicate of #1314

**Closed by Saviq** 2021-06-02 09:36 UTC
