### ISSUE TITLE
Change Storage Location: Option to set where Multipass VM's are Stored

### ISSUE THREAD

**Issue by tkedwards** [canonical/multipass#1681] opened 2020-08-13 11:07 UTC
**What are you trying to do?**
Ability to set the storage location of Multipass VMs

**What's your proposed solution?**
An option in the multipass command to set the storage location and  move existing VM's there

**Additional context**
The first time I used multipass it caused my root (/) partition to run out of space. I have 30GB for my root partition, which is plenty on Ubuntu 18.04 even with KDE and lots of snaps and flatpaks installed. However one Multipass VM weighed in at 6.4GiB. Not realising that root was full I rebooted, but Ubuntu didn't come up. Had to go into rescue mode, in the end spent nearly an hour working out what was wrong and fixing it.

Unfortunately I've had to give up on using multipass because of this.

**Comment by Saviq** [comment] 2020-08-13 11:12
Duplicate of #1215

**Closed** 2020-08-13 11:12 UTC
Labels: duplicate

**Comment by Saviq** [comment] 2020-10-08 08:15
Hi @tkedwards, I've described a workaround in https://github.com/canonical/multipass/issues/1215#issuecomment-705408845.
