### ISSUE TITLE
Multipass Launch Timed out waiting for response

### ISSUE THREAD

**Issue by jamap** [canonical/multipass#2911] opened 2023-02-02 22:45 UTC
**Describe the bug**
Every time I try to launch a VM I receive a timeout error and the instance stays in an unknown state and unusable

**To Reproduce**
How, and what happened?
1. just issue a "multipass launch -n primary" or "multipass launch -n primary -v"

**Expected behavior**
I expect to have a machine launched and started normally

**Logs**
[2023-02-02T18:40:31.645] [debug] [update] Latest Multipass release available is version 1.11.0
[2023-02-02T18:40:35.979] [info] [VMImageHost] Did not find any supported products in "appliance"
[2023-02-02T18:40:36.044] [info] [rpc] gRPC listening on unix:/var/run/multipass_socket
[2023-02-02T18:40:36.044] [warning] [Qt] QIODevice::write (QFile, "/var/root/Library/Caches/multipassd/qemu/vault/multipassd-image-records.json"): device not open
[2023-02-02T18:40:36.044] [info] [daemon] Starting Multipass 1.11.0+mac
[2023-02-02T18:40:36.044] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.multipass/bin/multipassd --verbosity debug
[2023-02-02T18:43:47.469] [debug] [qemu-system-aarch64] [5798] started: qemu-system-aarch64 --version
[2023-02-02T18:44:41.052] [debug] [qemu-img] [5903] started: qemu-img info --output=json /var/root/Library/Caches/multipassd/qemu/vault/images/jammy-20230107/ubuntu-22.04-server-cloudimg-arm64.img
[2023-02-02T18:44:41.361] [debug] [qemu-img] [5905] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/jammy-20230107/ubuntu-22.04-server-cloudimg-arm64.img
[2023-02-02T18:44:41.381] [debug] [qemu-img] [5906] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-22.04-server-cloudimg-arm64.img 5368709120
[2023-02-02T18:44:41.399] [debug] [qemu-img] [5907] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-22.04-server-cloudimg-arm64.img
[2023-02-02T18:44:41.409] [debug] [primary] process working dir ''
[2023-02-02T18:44:41.409] [info] [primary] process program 'qemu-system-aarch64'
[2023-02-02T18:44:41.409] [info] [primary] process arguments '-machine, virt,highmem=off, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, cortex-a72, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:2b:5e:ee, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/cloud-init-config.iso'
[2023-02-02T18:44:41.412] [debug] [qemu-system-aarch64] [5908] started: qemu-system-aarch64 -machine virt,highmem=off -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.XgsRov
[2023-02-02T18:44:41.456] [info] [primary] process state changed to Starting
[2023-02-02T18:44:41.459] [info] [primary] process state changed to Running
[2023-02-02T18:44:41.459] [debug] [qemu-system-aarch64] [5909] started: qemu-system-aarch64 -machine virt,highmem=off -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu cortex-a72 -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:2b:5e:ee -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/ubuntu-22.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/primary/cloud-init-config.iso
[2023-02-02T18:44:41.459] [info] [primary] process started
[2023-02-02T18:44:41.460] [debug] [primary] Waiting for SSH to be up
[2023-02-02T18:44:41.519] [debug] [primary] QMP: {"QMP": {"version": {"qemu": {"micro": 0, "minor": 1, "major": 7}, "package": ""}, "capabilities": ["oob"]}}

[2023-02-02T18:44:41.546] [debug] [primary] QMP: {"return": {}}

[2023-02-02T18:44:52.347] [debug] [primary] QMP: {"timestamp": {"seconds": 1675374292, "microseconds": 347585}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/device[6]/virtio-backend"}}

[2023-02-02T18:45:35.850] [debug] [primary] QMP: {"timestamp": {"seconds": 1675374335, "microseconds": 850182}, "event": "RTC_CHANGE", "data": {"offset": 1, "qom-path": "/machine/unattached/device[4]"}}

**Additional info**
- OS: MacOS Ventura 13.2 - Chip M1

- `multipass version`
multipass   1.11.0+mac
multipassd  1.11.0+mac

- `multipass info --all`
Name:           primary
State:          Unknown
IPv4:           --
Release:        --
Image hash:     8593ce1c6bbd (Ubuntu 22.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

- `multipass get local.driver`
qemu

**Comment by townsend2010** [comment] 2023-02-03 14:09
Hi @jamap,

It seems you are being afflicted by #2387.

I have a [test package](https://multipass-ci.s3.amazonaws.com/pr502/multipass-1.12.0-dev.189.pr502%2Bgd9314d80.mac-Darwin.pkg) that hopefully fixes this.  If you can try that, I would appreciate it.

For now, I'm going to close this as a duplicate of that other bug.

Duplicate of #2387.

**Closed by townsend2010** 2023-02-03 14:09 UTC

**Comment by ananyaaaaww** [comment] 2024-07-16 13:39
I had previously installed multipass in my system yesterday. It worked well for some minutes, and then again after opening it today, it was not working, When launching the instance this is the error i am getting even after repetitive trails :
launch failed: The following errors occurred:
primary: timed out waiting for response

Things which I have tried doing are :

uninstalled and reinstalled multipass some 3-4 times using brew as well as package installer.
checked with firewall settings
tallied the system settings with others whereas all the other peers are able to work in multipass smoothly.
did some network troubleshooting which some of the links said.
Please can you suggest a proper fixing to this. Thankyou in advance!

![IMG20240716190830](https://github.com/user-attachments/assets/e8434e48-642e-4e36-a474-6b213fcae7eb)

**Comment by tho-nguyen** [comment] 2024-07-30 13:54
> I had previously installed multipass in my system yesterday. It worked well for some minutes, and then again after opening it today, it was not working, When launching the instance this is the error i am getting even after repetitive trails : launch failed: The following errors occurred: primary: timed out waiting for response
> 
> Things which I have tried doing are :
> 
> uninstalled and reinstalled multipass some 3-4 times using brew as well as package installer. checked with firewall settings tallied the system settings with others whereas all the other peers are able to work in multipass smoothly. did some network troubleshooting which some of the links said. Please can you suggest a proper fixing to this. Thankyou in advance!
> 
> ![IMG20240716190830](https://private-user-images.githubusercontent.com/134645478/349106861-e8434e48-642e-4e36-a474-6b213fcae7eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDc3NTMsIm5iZiI6MTcyMjM0NzQ1MywicGF0aCI6Ii8xMzQ2NDU0NzgvMzQ5MTA2ODYxLWU4NDM0ZTQ4LTY0MmUtNGUzNi1hNDc0LTZiMjEzZmNhZTdlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxMzUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWFmM2E3NzRiOGZkNmI2Zjc1YmRiYjc2OTMwOWYyYjZiNjdiNjIyYWI1N2UyOTc5ZGYyYzkxNWIxOGFjYjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vpiX6FOHL54-e7SjAbFyuaDsUQnz7Et73TxSCxGUqHs)


I got the same.
After re-install  1.14 ver, even can not start after launch the VM.
