### ISSUE TITLE
 transfer failed: Cannot push files to root owned directories

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#698] opened 2019-03-27 16:23 UTC
This was reported on our [Discourse](https://community.ubuntu.com/t/copy-files-failed-scp-push-failed-scp-status-code-1d-not-valid/10389) spot.  Here is the report:

```
$ multipass copy-files snap/local/scriptlets/selective-pull snapcraft-simplescreenrecorder:/root/stage/scriptlets
copy-files failed: [scp push] failed: 'scp status code 1d not valid'
```
>That’s all I got, `--verbose` doesn’t make more output to the terminal.

**Comment by Lin-Buo-Ren** [comment] 2019-03-27 17:18
I'm currently using `0.6.0-dev.218+g3febdd7`

**Comment by Saviq** [comment] 2019-04-10 11:49
@Lin-Buo-Ren did you see this again since? Any idea how to reproduce?

**Comment by Lin-Buo-Ren** [comment] 2019-04-10 13:40
@Saviq I didn't use this feature since then :-/.

Here's the reproduce instructions:

1. `git clone --branch patch/impl-snap-packaging --depth=1 https://github.com/Lin-Buo-Ren/ssr.git`
1. `snapcraft stage`
1. `multipass copy-files snap/local/scriptlets/main-adopt-info snapcraft-simplescreenrecorder:/root/stage/scriptlets`

```
$ multipass version
multipass  0.6.0
multipassd 0.6.0
$ snapcraft version
snapcraft, version 3.3+git17.g1b29058
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by Lin-Buo-Ren** [comment] 2019-04-10 13:46
I've refined the reproducer even more:

1. `touch test`
1. `multipass launch release:18.04 --name multipass-issue-698`
1. `multipass copy-files test multipass-issue-698:/root`

```
$ snap info multipass

...stripped...

channels:
  stable:           –                                             
  candidate:        –                                             
  beta:             0.6.0                  2019-04-02 (716) 113MB classic
  edge:             0.6.0-rc.43+gf5cd3c1   2019-04-10 (726) 113MB classic
  core16/stable:    –                                             
  core16/candidate: –                                             
  core16/beta:      0.6.0                  2019-04-02 (716) 113MB classic
  core16/edge:      0.7.0-dev.236+gcd11605 2019-03-29 (712) 113MB classic
installed:          0.6.0                             (716) 113MB classic
```

**Comment by townsend2010** [comment] 2019-04-10 13:55
Hi @Lin-Buo-Ren,

I just looked into this and the error is that the `multipass` user in the instance doesn't have permission to write files to those directories, which are owned by `root`.  I agree that the error is cryptic, but this is what `libssh` is bubbling up to us and we print it verbatim.

**Comment by Lin-Buo-Ren** [comment] 2019-04-10 14:27
Can the operation be done by the `root` user instead?  I thought it is common to modify system files in a testing environment.

**Comment by townsend2010** [comment] 2019-04-10 14:34
The `copy-files` operation is basically `scp` so it's through `ssh`.  In `multipass`, we default all `ssh` operations to use the `multipass` user.  Adding support for `root` to `ssh` into the instance is probably not a good solution.

For this, I think the easiest solution is to add the `root` group to the `multipass` user in the instance and then it should have permission to write to directories unless the directory's group permissions aren't set.

**Comment by Saviq** [comment] 2020-03-18 09:00
Duplicate of #1433

**Comment by Saviq** [comment] 2020-03-18 09:00
I've made this a duplicate to keep that other issue focused.

**Closed by Saviq** 2020-03-18 09:00 UTC
Labels: duplicate

**Comment by Lin-Buo-Ren** [comment] 2020-03-18 09:55
Got it, thanks!
