### ISSUE TITLE
Multipass fails to install composer dependencies at mounted path

### ISSUE THREAD

**Issue by sfx101** [canonical/multipass#2369] opened 2021-12-08 06:39 UTC
**Describe the bug**
Multipass is failing to install composer dependencies at the mounted path

**To Reproduce**
1. login to a Multipass instance
2. cd to a path which is mounted by Multipass
3. Install PHP
4. Install composer by running
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer
```
5. Run `composer --ignore-platform-reqs create-project laravel/laravel .`

**Expected behavior**
Composer should be able to install its dependencies on mounted path

**Logs**
```
[2021-12-08T11:48:24.401] [debug] [ssh session] Executing 'id -g'
[2021-12-08T11:48:24.403] [debug] [ssh process] /Users/cibot/actions-runner-2/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:118 read_stream(type = 0, timeout = -1): 
[2021-12-08T11:48:24.403] [debug] [ssh process] /Users/cibot/actions-runner-2/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 5
[2021-12-08T11:48:24.404] [debug] [ssh process] /Users/cibot/actions-runner-2/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:136 read_stream(): num_bytes = 0
[2021-12-08T11:48:24.404] [debug] [ssh process] /Users/cibot/actions-runner-2/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:118 read_stream(type = 1, timeout = -1): 
[2021-12-08T11:48:24.404] [debug] [ssh process] /Users/cibot/actions-runner-2/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:124 read_stream(): channel closed
[2021-12-08T11:48:24.404] [debug] [sshfs mount] /Users/cibot/actions-runner-2/_work/multipass-private/multipass-private/src/sshfs_mount/sshfs_mount.cpp:188 make_sftp_server(): `id -g` = 1000

[2021-12-08T11:48:24.404] [debug] [ssh session] Executing 'sudo env LD_LIBRARY_PATH=/snap/multipass-sshfs/147/lib /snap/multipass-sshfs/147/bin/sshfs -o slave -o transform_symlinks -o allow_other -o Compression=no -o dcache_timeout=3 :"/Users/sfx101/deck-projects" "/deck-projects/."'
```

**Additional info**
 - OS: macOS 11.2.3 (tested on M1 + Intel)
- `multipass version 1.8.1`
- `Name:           deck-app
State:          Running
IPv4:           192.168.64.15
                172.17.0.1
                172.18.0.1
Release:        Ubuntu 20.04.3 LTS
Image hash:     f83575f6791e (Ubuntu 20.04 LTS)
Load:           0.00 0.06 0.22
Disk usage:     3.9G out of 9.5G
Memory usage:   270.6M out of 3.8G
Mounts:         /Users/sfx101/deck-projects => /deck-projects
                    UID map: 501:default
                    GID map: 20:default`

**Additional context**
The issue doesn't happen when I unmount the path & run composer again

**Comment by Saviq** [comment] 2021-12-08 08:21
Hi @sfx101, the problem is likely that there's a filesystem feature that the composer uses (is there any error you can share?) that doesn't work through the mount. Lock files or other permissions that can't be mapped between the host and the instance come to mind.

**Comment by sfx101** [comment] 2021-12-08 10:05
Hi @Saviq , appreciate the speedy response. I am getting more data on the error & running a few more test cases for a better understanding.

Here's what Composer logs out in the event of the issue

```
 - Installing laravel/sail (v1.12.10): Extracting archive
  - Installing laravel/sanctum (v2.12.2): Extracting archive
  - Installing nikic/php-parser (v4.13.2): Extracting archive
  - Installing psy/psysh (v0.10.12): Extracting archive
  - Installing laravel/tinker (v2.6.3): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing mockery/mockery (1.4.4): Extracting archive
  - Installing filp/whoops (2.14.4): Extracting archive
  - Installing nunomaduro/collision (v5.10.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.5.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.3): Extracting archive
  - Installing sebastian/exporter (4.0.4): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.10): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (1.14.0): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phpunit/phpunit (9.5.10): Extracting archive
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/265d8f31'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/faeff72f'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/378987db'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/127eb4d6'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/e9b9bc92'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/51f67d16'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/daef3cee'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/0795ba59'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/d90ed29a'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/90e9e1d4'
    Install of doctrine/inflector failed
    Install of doctrine/lexer failed
    Install of symfony/polyfill-ctype failed
    Install of webmozart/assert failed
    Install of dragonmantank/cron-expression failed
    Install of symfony/polyfill-php80 failed
    Install of symfony/polyfill-mbstring failed
    Install of symfony/var-dumper failed
    Install of symfony/polyfill-intl-normalizer failed
    Install of symfony/polyfill-intl-grapheme failed
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-35a21fd7c63528d0c3b3cd4a4c46e47d' -d '/deck-projects/new-test/vendor/composer/de15a66a'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-9dca99e78324ebef1acdbf4b1a701d10' -d '/deck-projects/new-test/vendor/composer/49242340'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-c48256256f9762957b50d03cc20580de' -d '/deck-projects/new-test/vendor/composer/d1e91751'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-5df0f4c593c4e5fe891901ff50298b55' -d '/deck-projects/new-test/vendor/composer/23b0a747'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-53f77efea33f1f31caa7c1f45c8a9480' -d '/deck-projects/new-test/vendor/composer/4afeb4e7'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-4c788a2aca0f7642858b5597f62a1623' -d '/deck-projects/new-test/vendor/composer/39885005'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-ef4c450d7b8e32ccb0dab54f42f039b0' -d '/deck-projects/new-test/vendor/composer/08b0015a'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-746eddacdfc6de5ad2050578ac0e0479' -d '/deck-projects/new-test/vendor/composer/e22943b1'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-e44f0b9259dff7c1d3464b83f5943a7f' -d '/deck-projects/new-test/vendor/composer/1ab856fd'
Executing async command (CWD): '/usr/bin/unzip' -qq '/deck-projects/new-test/vendor/composer/tmp-10b0cedf6b6ccad58c483610446e0541' -d '/deck-projects/new-test/vendor/composer/104beeb2'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/4afeb4e7'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/49242340'
Executing async command (CWD): rm -rf '/deck-projects/new-test/vendor/composer/104beeb2'
```
The interesting part is, it starts the usual way & keeps installing stuff and then all of a sudden the error messages come. The nature of behavior makes me think, it has to do something with sshfs due to the high i/o (couldn't find relevant logs in multipassd.log)? Unmounting the path fixes the issue as I said before. On the other hand, npm seems to be handling this well & I do not see any issues with npm install on the mounted path

**Comment by Saviq** [comment] 2022-02-09 07:52
@sfx101 we found a problem handling symlinks #2407, that may well have been what tripped you.

You could try the latest dev build here:

https://github.com/canonical/multipass/runs/5112154180

I'll mark this duplicate, please report back if it doesn't help you.

**Comment by Saviq** [comment] 2022-02-09 07:52
Duplicate of #2407

**Closed by Saviq** 2022-02-09 07:52 UTC
Labels: question

**Comment by sfx101** [comment] 2022-02-18 07:47
Hi @Saviq appreciate the efforts, ty. I tried it out but it still has the issue. I am very sure it's the same issue in Virtualbox as well https://www.virtualbox.org/ticket/18776

Do we have support for Multipass to do NFS file sync rather than sshfs?

**Comment by Saviq** [comment] 2022-02-18 07:57
@sfx101 not internally (yet). We've looked into that and @luis4a0 documented his findings here:

https://discourse.ubuntu.com/t/improving-mounts-performance-in-multipass/26638

For now we'll document the exact recommended steps and we'll see about integration at least some of them into Multipass across platforms.

**Comment by sfx101** [comment] 2022-02-20 22:08
Hi @Saviq , thank you for the document. I have followed it and made nfs sync work correctly in the VM.
I've used autofs following this article here https://theredblacktree.wordpress.com/2015/08/06/export-nfs-shares-from-os-x-10-10-4-to-ubuntu-debian-and-mount-using-autofs/ which made the process clean and simple

Also, this article shows is helpful https://blog.docksal.io/nfs-access-issues-on-macos-10-15-catalina-75cd23606913

The PHP composer issue is resolved, in case you need any help to document the process for others let me know.

Appreciate your constant support, tysm.
