### ISSUE TITLE
macos: unable to find newer images

### ISSUE THREAD

**Issue by daviehh** [canonical/multipass#1028] opened 2019-09-06 20:56 UTC
On macos, `multipass find` only returns
```
Image                   Aliases           Version          Description
snapcraft:core          core16            20190819         Snapcraft builder for Core 16
snapcraft:core18                          20190820         Snapcraft builder for Core 18
16.04                   xenial            20190814         Ubuntu 16.04 LTS
18.04                   bionic,lts        20190813.1       Ubuntu 18.04 LTS
```
newer releases, e.g. Ubuntu 19/disco, is not found. Is it expected (or only LTS on mac for now)? I captured the traffic of `multipassd` since it appears to be http, I can see requests made to e.g. `HEAD /releases/streams/v1/com.ubuntu.cloud:released:download.json HTTP/1.1\r\n` so possibly not a network issue? Thanks!

**Comment by Saviq** [comment] 2019-09-07 17:06
Hi @daviehh, indeed we currently only support LTS releases on macOS, we're looking into how to enable that on all platforms.

**Comment by diclophis** [comment] 2019-09-18 02:55
where exactly are these images hosted... I haven't been able to really find any details on how to set the repo for custom images yet.

**Comment by Saviq** [comment] 2019-09-18 09:02
Hi @diclophis, we pull the images from http://cloud-images.ubuntu.com/ directly. There's no support yet for custom image repositories, but it is a planned feature.

**Comment by 0902horn** [comment] 2019-11-15 03:52
Hi @Saviq, is there any update on this issue and #1029 ? 

BTW, I don't think #1029 is a duplicate of #1028. They might have the same root cause, but they are different use cases -- `multipass find` in #1028 and `multipass launch` in #1029 . Actually **`multipass launch` with local images** is what I'm really care about currently.

**Comment by Saviq** [comment] 2019-11-15 19:39
HI @0902horn, we will definitely enable this in due course, just didn't have time to make the whole experience around it solid.

Both this, and support for non-LTS images is roughly in the same bucket for us, which is why the duplicate was marked as such.

**Comment by townsend2010** [comment] 2023-11-03 13:27
I believe this has been resolved for some time now.

**Closed by townsend2010** 2023-11-03 13:27 UTC
