### ISSUE TITLE
multipass launch --name dotrun command failing

### ISSUE THREAD

**Issue by bethcollins92** [canonical/multipass#2054] opened 2021-04-14 15:04 UTC
**Describe the bug**

I'm seeing this error: 
`launch failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible`
When I try and run `multipass launch --name dotrun`

**To Reproduce**
see above

**Expected behavior**
To create and start an Ubuntu instance

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/6311743/multipassd.log)

**Additional info**
 - OS: macOS 11.2.3 Apple M1 chip
- `multipass version`: multipass  1.6.2+mac
- `multipass info --all`: `info failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible`

**Comment by Saviq** [comment] 2021-04-14 15:06
Hi @bethcollins92, that'd be #1935, please see there for how to fix.

**Comment by Saviq** [comment] 2021-04-14 15:06
Duplicate of #1935

**Closed by Saviq** 2021-04-14 15:06 UTC
Labels: bug
