### ISSUE TITLE
multipass mount not working with encrypted home

### ISSUE THREAD

**Issue by fmaste** [canonical/multipass#2013] opened 2021-03-18 13:04 UTC
**Describe the bug**
Cant mount folders inside the encrypted home

**To Reproduce**
On a user with encrypted home (adduser --encrypt-home) create a folder and some files inside the encrypted home:
```
user@server:~$ mkdir mount-sshfs-test
user@server:~$ touch mount-sshfs-test/test1
user@server:~$ touch mount-sshfs-test/test2
user@server:~$ ls mount-sshfs-test/
test1  test2
```
Mount the folder:
```
user@server:~$ multipass mount mount-sshfs-test mount-sshfs-test:/home/ubuntu/mount-sshfs-test
```
When you try to use the files on the instance the following errors appear on the log:
```
user@server:~$ multipass shell mount-sshfs-test
ubuntu@mount-sshfs-test:~$ ls -la mount-sshfs-test/
total 0
```
```
Mar 18 12:01:08 server audit[6217]: AVC apparmor="DENIED" operation="open" profile="multipass.mount-sshfs-test.fdf347d7.sshfs_server" name="/home/.ecryptfs/user/.Private/ECRYPTFS_ABCD_ENCRYPTED.ABCdqwertyuiopRHEKSUFMGPW90iS32V3DiOqMdZskMpi7ObUJasdfghjklzsriGdKEJhgty876KJHGyhg7tR-/" pid=6217 comm="sshfs_server" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000
Mar 18 12:01:08 server kernel: ecryptfs_dir_open: Error attempting to initialize the lower file for the dentry with name [mount-sshfs-test]; rc = [-13]
Mar 18 12:01:08 server kernel: audit: type=1400 audit(1616068868.828:131): apparmor="DENIED" operation="open" profile="multipass.mount-sshfs-test.fdf347d7.sshfs_server" name="/home/.ecryptfs/user/.Private/ECRYPTFS_ABCD_ENCRYPTED.ABCdqwertyuiopRHEKSUFMGPW90iS32V3DiOqMdZskMpi7ObUJasdfghjklzsriGdKEJhgty876KJHGyhg7tR-/" pid=6217 comm="sshfs_server" requested_mask="r" denied_mask="r" fsuid=0 ouid=1000
```

**Expected behavior**
If I create the same folder on /home/user2 (not encrypted), it works as expected!
```
user@server:~$ sudo mkdir /home/user2/
user@server:~$ sudo chown user:user /home/user2/
user@server:~$ cd /home/user2/
user@server:/home/user2$ mkdir mount-sshfs-test
user@server:/home/user2$ touch mount-sshfs-test/test1
user@server:/home/user2$ touch mount-sshfs-test/test2
user@server:/home/user2$ cd ~
user@server:~$ multipass mount /home/user2/mount-sshfs-test/ mount-sshfs-test:/home/ubuntu/mount-sshfs-test-ok
user@server:~$ multipass shell mount-sshfs-test
ubuntu@mount-sshfs-test:~$ ls -la mount-sshfs-test-ok/
total 8
drwxrwxr-x 1 ubuntu ubuntu   20 Mar 18 12:18 .
drwxr-xr-x 6 ubuntu ubuntu 4096 Mar 18 12:54 ..
-rw-rw-r-- 1 ubuntu ubuntu    0 Mar 18 12:18 test1
-rw-rw-r-- 1 ubuntu ubuntu    0 Mar 18 12:18 test2

```

**Additional info**
- `multipass version`
```
multipass  1.6.2
multipassd 1.6.2
```
- `multipass info --all`
```
Name:           mount-sshfs-test
State:          Running
IPv4:           10.252.182.189
Release:        Ubuntu 20.04.2 LTS
Image hash:     e344f0e84019 (Ubuntu 20.04 LTS)
Load:           0.07 0.02 0.00
Disk usage:     1.3G out of 4.7G
Memory usage:   150.5M out of 981.2M
Mounts:         /home/user/mount-sshfs-test  => /home/ubuntu/mount-sshfs-test
                    UID map: 1000:default
                    GID map: 1000:default
                /home/user2/mount-sshfs-test => /home/ubuntu/mount-sshfs-test-ok
                    UID map: 1000:default
                    GID map: 1000:default
```
- `snap --version`
```
snap    2.49
snapd   2.49
series  16
ubuntu  20.04
kernel  5.8.0-45-generic
```

**Comment by Saviq** [comment] 2021-03-18 13:05
Hi @fmaste, we already have #1825 for this.

**Comment by Saviq** [comment] 2021-03-18 13:05
Duplicate of #1825.

**Closed by Saviq** 2021-03-18 13:05 UTC
Labels: bug
