### ISSUE TITLE
deadlock running `multipass exec ... -- sudo -i ...` without tty/pty

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1214] opened 2019-12-10 17:25 UTC
beta channel multipass is OK, edge channel multipass is problematic:
multipass 0.10.0-dev.421+g20d04c0
multipassd 0.10.0-dev.421+g20d04c0

This is easily reproduced using python's check_output() to trigger the hang:

python -c "import subprocess;subprocess.check_output(['multipass', 'exec', '<multipass-vm-name>', '--', 'sudo', '-i', 'echo', 'hi'])"

If I instead either execute the command on the shell, or use Python's `pty.openpty()` to create the pipes for stdin/stdout, it works fine.

**Comment by Saviq** [comment] 2019-12-10 17:25
Tested 18.04, snapcraft:core18 with failures:

```
multipass launch 18.04 -n test1804
python -c "import subprocess;subprocess.check_output(['multipass', 'exec', 'test1804', '--', 'sudo', '-i', 'echo', 'hi'])"
```
```
multipass launch 18.04 -n testcore18
python -c "import subprocess;subprocess.check_output(['multipass', 'exec', 'testcore18', '--', 'sudo', '-i', 'echo', 'hi'])"
```
Test 19.10, OK:
```
multipass launch 19.10 -n test1910
python -c "import subprocess;subprocess.check_output(['multipass', 'exec', 'test1910', '--', 'sudo', '-i', 'echo', 'hi'])"
```

**Comment by Saviq** [comment] 2019-12-10 17:26
I can confirm both `lxc` and `ssh` seem to be OK with `sudo -i`, so something's wrong on our side.

**Comment by townsend2010** [comment] 2019-12-12 21:43
After some debugging, `libssh` is getting hung up because there is data to be read in `stderr`.  Going into `gdb` and dumping the contents of the internal `stderr` buffer, this is what is contained in it:
`mesg: ttyname failed: Inappropriate ioctl for device\nlibc.mo`

The problem is, there is nothing reading `stderr` so `libssh` won't go through it's handling of closing the channel because of the outstanding data.  I'm still experimenting to see if there is some way to handle this without reverting #1179.  The only reason it worked before is because it forced a TTY.

**Comment by Saviq** [comment] 2019-12-13 11:01
Oh, we should probably be forwarding stderr to the outside, no?

**Comment by townsend2010** [comment] 2019-12-13 12:55
@Saviq,

We are set up to for that unless there is some underlying `libssh` bug.  I still have to do some more experimenting, but I think if there is no TTY and nothing reading from `stderr` such as `subprocess.check_output()` in this case, then `libssh` just gets hung up wanting *something* to read that `stderr` buffer before it will close the channel.

I'm not convinced this is correct behavior in `libssh` since the `remote_eof` flag is set indicating that remote is complete.  I saw this same type of behavior in Windows when I was working on the output redirection to a file when the remote process would write to `stderr` but nothing on the host to read from it.

**Comment by townsend2010** [comment] 2019-12-13 18:29
We've reverted 56faa0c and thus, bug #667, so this issue will no longer occur.  I will look into how best to fix both bugs simultaneously.

**Closed by townsend2010** 2019-12-13 18:29 UTC
