### ISSUE TITLE
Time Sync issues on Apple Silicon/Qemu

### ISSUE THREAD

**Issue by dmarkey** [canonical/multipass#2430] opened 2022-02-06 17:30 UTC
**Describe the bug**
After sleep/resume cycles, time is out of sync.

**To Reproduce**
bring up a VM, suspend your mac, resume, observe that time is out of sync and wont correct itself.

**Expected behaviour**
What did you expect to happen?

Time should stay in sync

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - MacOS on a Apple Silicon MBA
- 1.8.1

**Additional context**

Tried installing qemu guest tools, but required control channels are missing.

Workaround cloud init:

```

  - content: |
      [Time]
      PollIntervalMinSec=10
      PollIntervalMaxSec=30
    path: /etc/systemd/timesyncd.conf


runcmd:
  - [ timedatectl, set-ntp, true ]
  - [ systemctl, restart, systemd-timesyncd ]

```

**Comment by ricab** [comment] 2022-02-07 11:12
Thanks for reporting @dmarkey. Yeah this is something we've been aware of for a while, just didn't manage to get to yet. Glad you could work around. I am marking this as duplicate of the other issue we have for this.

**Comment by ricab** [comment] 2022-02-07 11:12
Duplicate of #982

**Closed** 2022-02-07 11:12 UTC
