### ISSUE TITLE
multipass find not work on windows11

### ISSUE THREAD

**Issue by bettswang** [canonical/multipass#3820] opened 2024-12-06 14:06 UTC
**Describe the bug**
multipass find not work on windows11

**To Reproduce**
How, and what happened?
1. `multipass find`

**Expected behavior**
What did you expect to happen?
normal output
**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.
![image](https://github.com/user-attachments/assets/8e4a1651-016a-49ea-8c69-936594127b2c)

**Additional info**
 - OS: windows11 pro
- `multipass version` 
    multipass   1.14.1+win
    multipassd  1.14.1+win
- `multipass info` 
- `multipass get local.driver` 
   hyperv

**Additional context**

**Comment by giuliazanchi** [comment] 2024-12-06 16:00
Hi @bettswang , I'm sorry to hear you've experienced this. 

Unfortunately, this type of issue sometimes happens randomly and depends on the remote image repository. Have you been able to run the `multipass find` successfully in the past? My first suggestion would be to try again after a few hours, or tomorrow, and it might resolve on its own. 

If you want, you can also look at our troubleshooting topics, for example the [How to troubleshoot networking](https://multipass.run/docs/troubleshoot-networking) documentation page or our new topic on how to [Troubleshoot launch/start issues](https://discourse.ubuntu.com/t/troubleshoot-launch-start-issues/48104) on the Discourse forum.

**Comment by giuliazanchi** [comment] 2024-12-06 17:12
Hi again @bettswang , I forgot to ask the obvious, that is, can you access the image link in a regular browser? If this error is due to network issues, it may also depend on your firewall settings, so that would be relevant info that you can share to help us diagnose what's happening. Let us know!

**Comment by bettswang** [comment] 2024-12-07 16:24
I've got three machines: one host and two VMs. The host OS is Windows 11 Home. One VM is Windows 10 Pro, and the other is Windows 11 Pro. All of the VMs are pure systems.
When I first set up the VMs, I installed Multipass with Hyper-V. They all gave me an error when I ran the 'multipass find' command. The error said the network was having problems, but I'm sure there's nothing wrong with my network. However, when I I found that disabling IPv6 did the trick.
On the other hand, the host machine installed Multipass with Oracle VirtualBox v5.2.44. It always shows the same error, and I'm not sure where the issue is coming from.
![image](https://github.com/user-attachments/assets/11243b0f-7d00-4d68-bf15-eb810f13b180)

**Comment by bettswang** [comment] 2024-12-07 16:29
I also downloaded the URL using cmd and the browser, and everything worked fine.
![image](https://github.com/user-attachments/assets/9a22096d-b3ac-46e2-aca0-268ff09e4203)

**Comment by bettswang** [comment] 2024-12-09 06:36
I am trying to use a vm with pure win11 home os that is the same as the host machine. And it also work with oralce virtualbox v5.2.44, there is no problem with network. but there is another problem, the latest multipass seem not to be compatible with the v5.2.44 virtualbox, replace with v7, it work fine.

**Comment by giuliazanchi** [comment] 2024-12-11 13:38
Hi @bettswang , your issue seems to be a duplicate of https://github.com/canonical/multipass/issues/3662 , especially considering your remark on IPv6. Please check the comments under that issue, you'll find some more insights and an experimental patch. For now, I'll close this issue and mark it as duplicate.

**Closed** 2024-12-11 13:39 UTC
Labels: needs triage

**Comment by Hepengzhou** [comment] 2025-03-02 05:40
当我关闭掉 ipv6 时我的可以正常使用了，其他人可以可以试试

![Image](https://github.com/user-attachments/assets/f6d0da78-2183-49f5-af0b-b3505bf2f6be)

**Comment by Hepengzhou** [comment] 2025-03-02 06:07
但是当我重启电脑的时候  又出现这个问题

![Image](https://github.com/user-attachments/assets/500dd40c-5aee-4d50-aa75-65a3affe891b)
