### ISSUE TITLE
Can't open instance, stuck in `Starting` phase

### ISSUE THREAD

**Issue by Ishaangandhi** [canonical/multipass#2062] opened 2021-04-17 01:38 UTC
**Describe the bug**
I created an instance, and can no longer "start" it. It is stuck in the "starting phase".

**To Reproduce**
I started an instance yesterday, and by today, I could no longer start the instance. I restarted my host at one point in the intermediate time.

**Logs**

```
[2021-04-16T20:55:49.483] [debug] [nurtured-mayfly] Trying SSH on 192.168.64.3:22
[2021-04-16T20:55:52.451] [debug] [nurtured-mayfly] Trying SSH on 192.168.64.3:22
[2021-04-16T20:55:58.624] [debug] [utils] executing 'ip -brief -family inet address show scope global'
[2021-04-16T20:55:58.624] [debug] [ssh session] Executing 'ip -brief -family inet address show scope global'
[2021-04-16T20:55:59.550] [debug] [ssh process] /Users/cibot/actions-runner/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:117 read_stream(type = 0, timeout = -1):
[2021-04-16T20:55:59.550] [debug] [ssh process] /Users/cibot/actions-runner/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:135 read_stream(): num_bytes = 49
[2021-04-16T20:55:59.550] [debug] [ssh process] /Users/cibot/actions-runner/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:135 read_stream(): num_bytes = 0
[2021-04-16T20:58:24.492] [info] [daemon] Cannot open ssh session on "nurtured-mayfly" shutdown: ssh connection failed: 'Timeout connecting to 192.168.64.3'
[2021-04-16T20:58:24.495] [debug] [sshfs-mounts] No mounts to stop for instance "nurtured-mayfly"
[2021-04-16T20:58:32.768] [debug] [utils] executing 'ip -brief -family inet address show scope global'
[2021-04-16T20:58:32.769] [debug] [ssh session] Executing 'ip -brief -family inet address show scope global'
[2021-04-16T20:58:33.621] [debug] [ssh process] /Users/cibot/actions-runner/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:117 read_stream(type = 0, timeout = -1):
[2021-04-16T20:58:33.621] [debug] [ssh process] /Users/cibot/actions-runner/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:135 read_stream(): num_bytes = 49
[2021-04-16T20:58:33.621] [debug] [ssh process] /Users/cibot/actions-runner/_work/multipass-private/multipass-private/src/ssh/ssh_process.cpp:135 read_stream(): num_bytes = 0
```
**Additional info**
 - OS: macOS 11.1
- `multipass version`
`multipassd 1.6.2+mac`
- `multipass info --all`
```
Name:           primary
State:          Running
IPv4:           192.168.64.4
Release:        Ubuntu 20.04.2 LTS
Image hash:     607ed98d40de (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.3G out of 4.7G
Memory usage:   141.9M out of 981.3M
Mounts:         /Users/ishaangandhi => Home
                    UID map: 501:default
                    GID map: 20:default

Name:           lavish-angler
State:          Stopped
IPv4:           --
Release:        --
Image hash:     607ed98d40de (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           nurtured-mayfly
State:          Starting
IPv4:           --
Release:        --
Image hash:     607ed98d40de (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
```

**Comment by felixkasza** [comment] 2021-04-17 20:10
I am curious: After a minute or so, "Starting" should have switched to "Waiting for initialization to finish", and after five more minutes that should have stopped with a timeout error. Did it?

And did you (manually or through cloud-init) mess with the ubuntu user, its permissions, its authorized SSH keys, or the sshd settings? I learned the hard way that this is counterproductive. :)

**Comment by Ishaangandhi** [comment] 2021-04-17 20:20
> I am curious: After a minute or so, "Starting" should have switched to "Waiting for initialization to finish", and after five more minutes that should have stopped with a timeout error. Did it?

In fact, it still says "starting" (its been 2 days.)

> And did you (manually or through cloud-init) mess with the ubuntu user, its permissions, its authorized SSH keys, or the sshd settings? I learned the hard way that this is counterproductive. :)

Yes, I did! Is this why it crashed? I needed to SSH into the machine, is there some other way to authorize myself?

**Comment by felixkasza** [comment] 2021-04-17 20:50
Here is what my `user-data` cloud-init file says about users, SSH and suchlike:

[user-data.REDACTED.txt](https://github.com/canonical/multipass/files/6330008/user-data.REDACTED.txt)

As you can see, I want my own keys in there; this particular configuration is intended for a known-good Raspberry Pi 4 configuration so when I muck things up and re-image the Pi's SSD, I want all keys and whatnot to be as before. That means that after a fresh multipass install, I either have to update the "ubuntu" SSH keys in the user-data, or I have to replace the multipass id_rsa with a copy of the old one.

**Comment by felixkasza** [comment] 2021-04-17 20:54
> Is there some other way to SSH in?

I forgot to answer: There is not, unless you did one of the following:

* add a second, SSH-capable and sudo-capable user
* allowed password logins and assigned a known password to ubuntu (or another user)

You can still mount the virtual disk on some other OS instance and fix the authorized_keys file, of course. Or fix a password and enable passworded SSH logins for that user.

**Comment by Saviq** [comment] 2021-04-18 09:02
Hi @Ishaangandhi, if you just need SSH, you can use a cloud-config like so:

```yaml
ssh_authorized_keys:
- <your public key>
```

This will not mess with Multipass's own setup, and will include your key for the `ubuntu` user.

Thanks @felixkasza for helping out!

I'm gonna close this as a dupe of #1523.

**Comment by Saviq** [comment] 2021-04-18 09:02
Duplicate of #1523

**Closed by Saviq** 2021-04-18 09:02 UTC
Labels: bug

**Comment by Ishaangandhi** [comment] 2021-05-09 02:10
Actually, even after I made an instance with cloud config (not changing ssh myself) I ran into the same issue...

**Comment by felixkasza** [comment] 2021-05-09 11:43
> Actually, even after I made an instance with cloud config (not changing ssh myself) I ran into the same issue...

The issue is not with the mechanism; the issue is whether multipass still can SSH in as user "ubuntu" and gain root privilege. For that it needs the public key from the key pair that multipass has stashed in its data directory on the host, and the key has to be assigned to ubuntu. Saviq's easy solution works on the assumption that you have not prevented the creation of the default user, or if you have, that you are creating ubuntu in your user-data; and that you have not done something like ssh_delete_keys without manually assigning the key to ubuntu.

I'd be happy to look at your (anonymized) user-data file just in case I see something that was missed before.
