### ISSUE TITLE
[QUESTION] Select different default Terminal in OSX when using "Open Shell"

### ISSUE THREAD

**Issue by rjsears** [canonical/multipass#1421] opened 2020-03-11 02:22 UTC
I am running multipass under OSX. When I go to the status menu at top of my screen in OSX and click on the "Multipass" icon and select "Open Shell", it opens the pretty worthless (IMHO) Terminal program. 

How can I set Multipass to use the terminal program that I use for everything else (Termius or iTerm in my case)?

Thank You

**Comment by Saviq** [comment] 2020-03-11 07:43
Hi @rjsears we have an improvement for that in the works: #1347.

**Comment by Saviq** [comment] 2020-03-11 07:43
Duplicate of #1347

**Closed by Saviq** 2020-03-11 07:43 UTC
