### ISSUE TITLE
[macos] multipass how to find xenial  , I want use xenial by multipass 

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [canonical/multipass#2734] opened 2022-09-03 07:51 UTC
**Describe the bug**
Describe what your problem is.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`
- `multipass get local.driver`

**Additional context**

**Comment by andrei-toterman** [comment] 2022-09-03 12:42
Hi @wangwenqiangGitHub!
```
multipass launch xenial
```
should do the trick.
You may not see Xenial in the output of
```
multipass find
```
but it's in
```
multipass find --show-unsupported
```

**Comment by wangwenqiangGitHub** [comment] 2022-09-03 12:57
> Hi @wangwenqiangGitHub!
> 
> ```
> multipass launch xenial
> ```
> 
> should do the trick. You may not see Xenial in the output of
> 
> ```
> multipass find
> ```
> 
> but it's in
> 
> ```
> multipass find --show-unsupported
> ```
I run `multipass launch xenial` but 
output this

> aunch failed: The following errors occurred:
> ubuntu1604: timed out waiting for response

**Comment by andrei-toterman** [comment] 2022-09-03 13:05
Can you please specify all the required information from the issue template i.e. version,  platform, driver, and most importantly logs + any other relevant information?

**Comment by wangwenqiangGitHub** [comment] 2022-09-03 13:09
> Can you please specify all the required information from the issue template i.e. version, platform, driver, and most importantly logs + any other relevant information?

multipass --version
multipass   1.10.1+mac
multipassd  1.10.1+mac

**Comment by andrei-toterman** [comment] 2022-09-03 16:55
The more information you provide, the higher the chance we can figure out how we can help. Usually the most useful information can be found in the logs, which you can access by following this guide https://multipass.run/docs/accessing-logs

**Comment by wangwenqiangGitHub** [comment] 2022-09-03 23:17
> The more information you provide, the higher the chance we can figure out how we can help. Usually the most useful information can be found in the logs, which you can access by following this guide https://multipass.run/docs/accessing-logs

[2022-08-18T19:45:01.303] [info] [ubuntu1804] process state changed to Starting
[2022-08-18T19:45:01.360] [info] [ubuntu1804] process state changed to Running
...skipping...
[2022-09-03T21:28:36.959] [debug] [sshfs-mounts] No mounts to stop for instance "ubuntu1604"
[2022-09-03T21:28:36.963] [debug] [ubuntu1604] QMP: {"return": {}}
{"timestamp": {"seconds": 1662211716, "microseconds": 963216}, "event": "POWERDOWN"}

[2022-09-03T21:29:06.973] [debug] [ubuntu1604] QMP: {"return": {}}

[2022-09-03T21:29:06.974] [debug] [ubuntu1604] QMP: {"timestamp": {"seconds": 1662211746, "microseconds": 973688}, "event": "POWERDOWN"}

[2022-09-03T21:29:06.974] [info] [ubuntu1604] VM powering down
[2022-09-03T21:29:36.973] [warning] [Qt] QProcess: Destroyed while process ("qemu-system-aarch64") is still running.
[2022-09-03T21:29:36.983] [info] [ubuntu1604] process state changed to NotRunning

**Comment by townsend2010** [comment] 2022-09-04 13:53
Hi @wangwenqiangGitHub!

Ok, now that we can see the logs, you are running into https://github.com/canonical/multipass/issues/2588.  This is fixed in the main line code and will be available in the next release which we are currently getting ready.

Duplicate of #2588

**Comment by townsend2010** [comment] 2022-09-04 13:54
Duplicate of #2588

**Closed by townsend2010** 2022-09-04 13:54 UTC
