### ISSUE TITLE
Lost access to multipass ubuntu vm when vpn in

### ISSUE THREAD

**Issue by joseanda** [canonical/multipass#1914] opened 2021-01-10 06:16 UTC
Hello, I have a multipass ubuntu vm 20.04 running in my macos. The issue is that when I vpn in to my office's network, I lost access to the multipass vm

Can you please assist me with a solution to my issue?

**Comment by Saviq** [comment] 2021-01-10 10:56
Hi @joseanda, unfortunately it's your VPN that needs reconfiguration to allow networking to the instance. Have a look at [our docs on network troubleshooting](https://multipass.run/docs/troubleshooting-networking-on-macos), but there's little that Multipass can do.

If the VPN is essential, you may have better luck with Multipass [using VirtualBox](https://multipass.run/docs/using-virtualbox-in-multipass-macos) due to how it handles networking. You won't get direct networking between your host and the VM, though.

We're close to [releasing support for bridging](https://github.com/canonical/multipass/issues/118#issuecomment-734426114) with VirtualBox, which could give you the best of both worlds.

**Comment by Saviq** [comment] 2021-01-10 10:56
Duplicate of #1121

**Closed by Saviq** 2021-01-10 10:56 UTC

**Comment by joseanda** [comment] 2021-05-11 05:42
thanks for the update
