### ISSUE TITLE
Multipass.app GUI steals CMD+OPTION+U shortcut

### ISSUE THREAD

**Issue by bartaz** [canonical/multipass#1329] opened 2020-01-30 19:37 UTC
On macOS Cmd+Option+U shortcut is used by browsers as a shortcut for view source (both in Chrome and Firefox, possibly others as well).

Multipass.app GUI seems to be stealing this shortcut for opening terminal in primary instance.

**Comment by townsend2010** [comment] 2020-01-30 20:03
Hey @bartaz,

Yep, this is a duplicate of #1311.  We're thinking how best to address this.

Thanks!

**Closed by townsend2010** 2020-01-30 20:03 UTC
