### ISSUE TITLE
configurable instances directory location

### ISSUE THREAD

**Issue by marosg42** [canonical/multipass#247] opened 2018-05-14 13:55 UTC
It would be nice to have a config option which allows to specify a path where multipass would allocate instances

**Comment by Saviq** [comment] 2020-01-10 07:17
I'll mark this as a duplicate of one that has more details:

Duplicate of #1215

**Comment by Saviq** [comment] 2020-01-10 07:17
Duplicate of #1215

**Closed** 2020-01-10 07:18 UTC

**Comment by Saviq** [comment] 2020-10-08 08:16
Hi @marosg42, I've described a workaround in https://github.com/canonical/multipass/issues/1215#issuecomment-705408845.
