### ISSUE TITLE
qemu-img timing out when resizing image

### ISSUE THREAD

**Issue by polarapfel** [canonical/multipass#1408] opened 2020-03-06 11:01 UTC
Hey there,

I was going through these steps:

https://discourse.ubuntu.com/t/building-multipass-images-with-packer/12361

The build host is Ubuntu 18.04 LTS, fully patched (qemu is the latest stable from Ubuntu).

I am using the latest packer binary.

I tried multipass from snap with the latest stable, edge/pr1120 and just edge.

When I try to launch the packer built image, it fails:

```
multipass launch file://$PWD/output-qemu/packer-qemu --disk 5G
launch failed: Cannot resize instance image: qemu-img failed (program: qemu-img; error: Process operation timed out) with output:
```

I tried much larger disk sizes and smaller disk sizes for `--disk` and it does not make a difference.

The output from qemu is missing. I have no idea what's going on.

thanks for looking into this.

Tobias W.

**Comment by Saviq** [comment] 2020-03-06 11:11
Hi @polarapfel, could you please supply the output from `journalctl -u snap.multipass*`? See [our logging docs](https://multipass.run/docs/accessing-logs) for a bit more info on that.

**Comment by polarapfel** [comment] 2020-03-10 08:32
Here is the part relevant by time frame for when executing

```
multipass launch file://$PWD/output-qemu/packer-qemu --disk 5G -vvvvv
```

```
Mar 10 08:21:04 server multipassd[1583]: QMP: {"timestamp": {"seconds": 1583828464, "microseconds": 516064}, "event": "RTC_CHANGE", "data": {"offset": 1}}        Mar 10 08:23:44 server multipassd[82822]: Applying AppArmor policy: multipass.qemu-img
Mar 10 08:23:44 server multipassd[82831]: Applying AppArmor policy: multipass.qemu-img
Mar 10 08:23:44 server multipassd[82837]: Applying AppArmor policy: multipass.qemu-img
Mar 10 08:24:14 server multipassd[1583]: Process operation timed out
Mar 10 08:24:14 server multipassd[1583]: QProcess: Destroyed while process ("qemu-img") is still running.
```
That's the last line.

**Comment by Saviq** [comment] 2020-03-10 10:09
Hi @polarapfel we unfortunately have a hard 30s timeout on image resizing, which must be too low in your case.

You should be able to use [`qemu-img convert`](http://manpages.ubuntu.com/manpages/trusty/man1/qemu-img.1.html) to shrink and compress the image so that it's "easier" to resize afterwards. Just convert it to `qcow2` so that any unused sectors are cleared out.

I'll close this as duplicate of #1187 and we'll fix this in the upcoming release.

**Comment by Saviq** [comment] 2020-03-10 10:10
Duplicate of #1187

**Closed by Saviq** 2020-03-10 10:10 UTC
Labels: question

**Comment by polarapfel** [comment] 2020-03-10 23:06
Thanks! Being able to specify a timeout on the command line with multipass would be great.

**Comment by polarapfel** [comment] 2020-03-11 00:40
Yeah, that did the trick.

`qemu-img convert -O qcow2 -c output-qemu/packer-qemu output-qemu/packer-qemu-compressed`
