### ISSUE TITLE
launch failed: Remote "" is unknown or unreachable.

### ISSUE THREAD

**Issue by CastilhosR** [canonical/multipass#2780] opened 2022-10-15 20:38 UTC
**Describe the bug**
When I try to launch a new instance ... the command aborts with this message: launch failed: Remote "" is unknown or unreachable.

**To Reproduce**
1. `multipass launch 22.04 --name test_instance`

**Expected behavior**
The expected result is self-explanatory, but yes, I intended to have a new instance of Ubuntu for testing

**Logs**
ut 15 17:18:16 rodrigo-s145 systemd[1]: snap.multipass.multipass.aefeefcd-ac00-4295-b858-51b8c0757f29.scope: Deactivated successfully.
out 15 17:18:40 rodrigo-s145 systemd[1]: Started snap.multipass.multipass.8d37179b-3966-49c7-8086-ea470ef5b4ad.scope.
out 15 17:18:40 rodrigo-s145 systemd[1]: snap.multipass.multipass.8d37179b-3966-49c7-8086-ea470ef5b4ad.scope: Deactivated successfully.
out 15 17:19:25 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.>
out 15 17:19:25 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/curre>
out 15 17:19:25 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-c>
out 15 17:19:25 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic>
out 15 17:23:31 rodrigo-s145 multipassd[1210]: Error getting https://codeload.github.com/canonical/multipass-blueprints/zip/refs/heads/main: Network acce>
out 15 17:23:31 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.>
out 15 17:23:31 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/curre>
out 15 17:23:31 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-c>
out 15 17:23:31 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic>
out 15 17:26:05 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.>
out 15 17:26:05 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/curre>
out 15 17:26:05 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-c>
out 15 17:26:05 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/curre>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-c>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Error getting https://cloud-images.ubuntu.com/releases/streams/v1/index.json: Network access is disabled. >
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Error getting https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json:>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Error getting https://cloud-images.ubuntu.com/daily/streams/v1/index.json: Network access is disabled. - t>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Error getting https://cloud-images.ubuntu.com/daily/streams/v1/com.ubuntu.cloud:daily:download.json: Netwo>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Error getting https://cdimage.ubuntu.com/ubuntu-core/appliances/streams/v1/index.json: Network access is d>
out 15 17:26:17 rodrigo-s145 multipassd[1210]: Error getting https://cdimage.ubuntu.com/ubuntu-core/appliances/streams/v1/com.ubuntu.appliances:released:>
out 15 17:26:29 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.>
out 15 17:26:29 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cdimage.ubuntu.com/ubuntu-core/16/stable/curre>
out 15 17:26:29 rodrigo-s145 multipassd[1210]: Cannot retrieve headers for https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-c>
out 15 17:26:29 rodrigo-s145 multipassd[1210]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic>

**Additional info**
 - OS: Ubuntu Linux 22.04
- `multipass version: 1.10.1
- `multipass info --all: <<nothing>>
- `multipass get local.driver: qemu

**Comment by luis4a0** [comment] 2022-10-17 11:05
Hi @CastilhosR! It is likely you are being hit by the firewall issue in #2387. You can try disabling the firewall or enabling it in debug mode. I am closing this as duplicate of #2387, but don't hesitate in reopening the ticket if the firewall is not the issue you are having. Thanks!

**Closed by luis4a0** 2022-10-17 11:05 UTC
Labels: duplicate
