### ISSUE TITLE
Multipass not showing instances after upgrading windows 10

### ISSUE THREAD

**Issue by Bigphiri** [canonical/multipass#2483] opened 2022-03-18 05:10 UTC
**Describe the bug**
Describe what your problem is.
So I was before I updated my windows system multipass was working just fine but just after it updated , trying to get a hold of the instances using multipass list says there are no instances .
I can see the instance in hyper v but can't access them using Multipass. Apparently trying launch other instances tells me "the remote host "" is not available, but my wifi is working fine. I tried checking the windows old folder but its empty for some reason. Please I really need help.

**Comment by Saviq** [comment] 2022-03-18 06:43
@Bigphiri this is #1119, we're working on a fix and our next release will change the default location of instances.

**Comment by Saviq** [comment] 2022-03-18 06:43
Duplicate of #1119

**Closed by Saviq** 2022-03-18 06:43 UTC
Labels: bug
