### ISSUE TITLE
chmod +x not working

### ISSUE THREAD

**Issue by brujah** [canonical/multipass#1803] opened 2020-10-16 20:54 UTC
I am trying to run a mud which is started by the following command:
sudo ./startup &

But when I do I get:
sudo: ./startup: command not found

When I do ls -l startup i get:
-rw-rw-rw- 1 ubuntu ubuntu 1528 Oct 16 22:20 startup

When I do chmod +x startup and then ls -l startup i get the same:
-rw-rw-rw- 1 ubuntu ubuntu 1528 Oct 16 22:20 startup

So it does not seem to be able to set the x flag and make it executable?

This is on Ubuntu 20.04.1 LTS

**Comment by ricab** [comment] 2020-10-19 11:51
Hi @brujah,

I am afraid I can't reproduce that, neither for files in mounts nor in the instance proper. Perhaps you can elaborate on the situation a bit? Steps to reproduce? What host (or instance) OS are you in?

**Comment by vrogalsk** [comment] 2020-10-21 13:58
I have similar issue on the Windows 10 on mounted partitions only.
![image](https://user-images.githubusercontent.com/47318172/96729969-62f6fd80-13be-11eb-81c4-ce3d3374f67e.png)
![image](https://user-images.githubusercontent.com/47318172/96730177-9cc80400-13be-11eb-9c12-a008cdd90083.png)

**Comment by ricab** [comment] 2020-10-21 16:18
Hi @vrogalsk, you're right, this is an issue on windows because there isn't an executable bit we can map to. However, with a shell script you can use `sh <script>` instead.

Marking as duplicate as this is already tracked in #1252 (which mentions other workarounds as well).

**Closed by ricab** 2020-10-21 16:18 UTC
Labels: duplicate, question
