### ISSUE TITLE
Windows: Multipass instance location and user (VirtualBox)

### ISSUE THREAD

**Issue by mydoghasworms** [canonical/multipass#2027] opened 2021-03-31 10:01 UTC
**What are you trying to do?**

Trying to understand the rationale, when running Multipass in Windows 10 with VirtualBox, of:

1. Running Multipass instances as Administrator rather than the local user
2. Locating Multipass instances in `C:\Windows\System32\config\systemprofile\VirtualBox VMs\Multipass`, if it must be run as Administrator.

**What's your proposed solution?**

Preferably, if possible, run Multipass instances as the local user, rather than Administrator and locate the VMs in `%USERPROFILE%\VirtualBox VMs` or a suitable subfolder. It would be nice if you can administer your Multipass instances with your own user (e.g. to add additional network interfaces or whatever).

Failing that, if they must run as Administrator, it would be nice if the Multipass instances could be stored in `C:\ProgramData\Multipass` or a suitable subfolder.

**Additional context**

I am running Multipass on Windows 10 with VirtualBox.

**Comment by Saviq** [comment] 2021-04-02 10:49
@mydoghasworms Multipass is (currently) a system-wide service. It doesn't know which user is issuing `multipass` commands. So running as the System user makes sense (we're planning to use a dedicated user in time). Data location can be changed using `MULTIPASS_STORAGE` environment variable.

#1112 has more info, so I'll close this as duplicate.

**Comment by Saviq** [comment] 2021-04-02 10:49
Duplicate of #1112.

**Comment by Saviq** [comment] 2021-04-02 10:50
Duplicate of #1112

**Closed by Saviq** 2021-04-02 10:50 UTC
Labels: enhancement
