### ISSUE TITLE
My vm disappeared on Windows10

### ISSUE THREAD

**Issue by sherkxuan** [canonical/multipass#2458] opened 2022-02-25 03:58 UTC
I recently used Multipass via Hyper-V on Windows 10, downloaded and used ubuntu, and it worked fine for the first two days (can be opened and connected in the system tray or powerShell). Now running `Multipass list` in powerShell gives an error: No instances found.

- OS: [Windows 10]
- multipass version
- multipass 1.8.0+win
- multipassd 1.8.0+win

**Comment by Saviq** [comment] 2022-02-25 11:06
@sherkxuan did you upgrade Windows recently?

You likely fell victim of #1119 - do you still have your `C:\Windows.old` folder? If so, please see this comment for help:

https://github.com/canonical/multipass/issues/1119#issuecomment-803675750

**Comment by Saviq** [comment] 2022-02-25 11:06
Duplicate of #1119

**Comment by sherkxuan** [comment] 2022-02-25 11:06
这是来自Google邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。sherk

**Closed by Saviq** 2022-02-25 11:06 UTC
