### ISSUE TITLE
macos M1 every now and then kernel panic

### ISSUE THREAD

**Issue by dotupNET** [canonical/multipass#2339] opened 2021-11-13 09:36 UTC
**Describe the bug**
very sporadically kernel panic. no shell or any other  interaction with the virtual machine.

**To Reproduce**
How, and what happened?
1. `multipass launch 21.10 --name dotup --cpus 2 --mem 2G`

**Logs**

```
panic(cpu 2 caller 0xfffffe0020ef55e8): No more room to grow table: 0x0xfffffe002494f560 size:258048, used:866, requested elem:524288 @ltable.c:485
Debugger message: panic
Memory ID: 0xff
OS release type: User
OS version: 21A559
Kernel version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
Fileset Kernelcache UUID: 39AE122AC7508C4798C8CF27369575F7
Kernel UUID: 65055A0F-950D-365E-BE19-6B3D6230C622
iBoot version: iBoot-7429.41.5
secure boot?: YES
Paniclog version: 13
KernelCache slide: 0x000000001957c000
KernelCache base:  0xfffffe0020580000
Kernel slide:      0x0000000019da0000
Kernel text base:  0xfffffe0020da4000
Kernel text exec slide: 0x0000000019e84000
Kernel text exec base:  0xfffffe0020e88000
mach_absolute_time: 0x14134c4cd4
Epoch Time:        sec       usec
  Boot    : 0x618f7527 0x0001f63a
  Sleep   : 0x618f7eeb 0x000f0527
  Wake    : 0x618f7fb6 0x0009d3f3
  Calendar: 0x618f83f3 0x00062a32

Zone info:
Foreign   : 0xfffffe002952c000 - 0xfffffe0029540000
Native    : 0xfffffe1000800000 - 0xfffffe3000800000
Readonly  : 0 - 0
Metadata  : 0xfffffe7df4c38000 - 0xfffffe7e00b98000
Bitmaps   : 0xfffffe7e00b98000 - 0xfffffe7e06658000
CORE 0 recently retired instr at 0xfffffe0021010640
CORE 1 recently retired instr at 0xfffffe0021010640
CORE 2 recently retired instr at 0xfffffe002100ef90
CORE 3 recently retired instr at 0xfffffe0021010640
CORE 4 recently retired instr at 0xfffffe0021010644
CORE 5 recently retired instr at 0xfffffe0021010644
CORE 6 recently retired instr at 0xfffffe0021010644
CORE 7 recently retired instr at 0xfffffe0021010644
CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 0: PC=0xfffffe0020f0eb5c, LR=0xfffffe0020f0eb5c, FP=0xfffffe609b2d3ef0
CORE 1: PC=0xfffffe0020f0eb60, LR=0xfffffe0020f0eb5c, FP=0xfffffe609c1ebef0
CORE 2 is the one that panicked. Check the full backtrace for details.
CORE 3: PC=0xfffffe0020f0eb5c, LR=0xfffffe0020f0eb5c, FP=0xfffffe609c1abef0
CORE 4: PC=0xfffffe0020f0eb5c, LR=0xfffffe0020f0eb5c, FP=0xfffffe608e24bef0
CORE 5: PC=0xfffffe0020f0eb60, LR=0xfffffe0020f0eb5c, FP=0xfffffe609bfdbef0
CORE 6: PC=0xfffffe0020f0eb60, LR=0xfffffe0020f0eb5c, FP=0xfffffe609bf6bef0
CORE 7: PC=0xfffffe0020f0eb60, LR=0xfffffe0020f0eb5c, FP=0xfffffe600c6dbef0
Panicked task 0xfffffe1515d90fe0: 23158 pages, 21 threads: pid 11331: FreeRDPSandboxed
Panicked thread: 0xfffffe1514b6d398, backtrace: 0xfffffe60305d3190, tid: 65793
		  lr: 0xfffffe0020eda464  fp: 0xfffffe60305d3200
		  lr: 0xfffffe0020eda134  fp: 0xfffffe60305d3270
		  lr: 0xfffffe0021015c30  fp: 0xfffffe60305d3290
		  lr: 0xfffffe0021008e84  fp: 0xfffffe60305d3310
		  lr: 0xfffffe002100684c  fp: 0xfffffe60305d33d0
		  lr: 0xfffffe0020e8f7f8  fp: 0xfffffe60305d33e0
		  lr: 0xfffffe0020ed9dac  fp: 0xfffffe60305d3780
		  lr: 0xfffffe0020ed9dac  fp: 0xfffffe60305d37f0
		  lr: 0xfffffe00216d7c5c  fp: 0xfffffe60305d3810
		  lr: 0xfffffe0020ef55e8  fp: 0xfffffe60305d38c0
		  lr: 0xfffffe0020f3bac4  fp: 0xfffffe60305d3950
		  lr: 0xfffffe0020f3b970  fp: 0xfffffe60305d39b0
		  lr: 0xfffffe0020f3c4a0  fp: 0xfffffe60305d3a50
		  lr: 0xfffffe00214401c8  fp: 0xfffffe60305d3a80
		  lr: 0xfffffe00214415f4  fp: 0xfffffe60305d3aa0
		  lr: 0xfffffe0021442620  fp: 0xfffffe60305d3cb0
		  lr: 0xfffffe002143d7e4  fp: 0xfffffe60305d3d50
		  lr: 0xfffffe002143d64c  fp: 0xfffffe60305d3db0
		  lr: 0xfffffe0021524e1c  fp: 0xfffffe60305d3e50
		  lr: 0xfffffe0021006b24  fp: 0xfffffe60305d3f10
		  lr: 0xfffffe0020e8f7f8  fp: 0xfffffe60305d3f20

last started kext at 856985149: com.apple.driver.driverkit.serial	6.0.0 (addr 0xfffffe0020c82690, size 3432)
loaded kexts:
com.apple.filesystems.autofs	3.0
com.apple.fileutil	20.036.15
com.apple.driver.AppleBiometricServices	1
com.apple.driver.CoreKDL	1
com.apple.driver.AppleTopCaseHIDEventDriver	5010.1
com.apple.driver.BCMWLANFirmware4378.Hashstore	1
com.apple.driver.SEPHibernation	1
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.filesystems.apfs	1933.41.2
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	100.1
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.filesystems.lifs	1
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	582.40.4
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.AppleSmartIO2	1
com.apple.driver.ApplePMP	1
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.AppleCS42L83Audio	502.6
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleTAS5770LAmp	502.6
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.AudioDMAController-T8103	100.51
com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
com.apple.driver.AppleSerialShim	1
com.apple.driver.AppleT8020SOCTuner	1
com.apple.driver.AppleT8103CLPCv3	1
com.apple.AGXG13G	187.57
com.apple.driver.AppleAVD	415
com.apple.driver.AppleAVE2	501.6.9
com.apple.driver.AppleJPEGDriver	4.7.8
com.apple.driver.AppleMobileDispH13G-DCP	140.0
com.apple.driver.AppleEventLogHandler	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleT8103PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleInterruptController	1.0.0d1
com.apple.driver.AppleT8020DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleT8101	1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	126.40.1
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	402
com.apple.kec.InvalidateHmac	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.driverkit.serial	6.0.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOAVBFamily	1010.2
com.apple.plugin.IOgPTPPlugin	1000.11
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.AppleHIDKeyboard	228
com.apple.driver.AppleActuatorDriver	5400.25
com.apple.driver.AppleMultitouchDriver	5400.25
com.apple.driver.AppleHSBluetoothDriver	5010.1
com.apple.driver.IOBluetoothHIDDriver	9.0.0
com.apple.driver.AppleTrustedAccessory	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleXsanScheme	3
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleThunderboltDPInAdapter	8.5.0
com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.0
com.apple.driver.AppleAOPAudio	102.2
com.apple.driver.AppleHIDTransportSPI	5400.30
com.apple.driver.AppleHIDTransport	5400.30
com.apple.driver.AppleInputDeviceSupport	5400.30
com.apple.nke.ppp	1.9
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.driver.AppleBSDKextStarter	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.AGXFirmwareKextG13GRTBuddy	187.57
com.apple.AGXFirmwareKextRTBuddy64	187.57
com.apple.driver.AppleSPU	1
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleCSEmbeddedAudio	502.6
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleEmbeddedAudio	502.6
com.apple.iokit.AppleARMIISAudio	100.1
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleSPMI	1.0.1
com.apple.driver.AppleSART	1
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleSynopsysUSBXHCI	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.iokit.IOGPUFamily	35.11
com.apple.driver.AppleH11ANEInterface	5.33.0
com.apple.driver.AppleH13CameraInterface	4.79.0
com.apple.driver.AppleH10PearlCameraInterface	17.0.3
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.DCPAVFamilyProxy	1
com.apple.driver.AppleFirmwareKit	1
com.apple.driver.ApplePMGR	1
com.apple.driver.AppleARMWatchdogTimer	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.8
com.apple.driver.AppleT8103PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.2
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT8103PCIe	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211Family	1200.12.2b1
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleOLYHAL	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleMCA2-T8103	600.95
com.apple.driver.AppleEmbeddedAudioLibs	100.9.1
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMobileApNonce	1
com.apple.iokit.IOTimeSyncFamily	1000.11
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	593
com.apple.iokit.IOBluetoothSerialManager	9.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.driver.FairPlayIOKit	68.13.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	532.40.7
com.apple.iokit.IOUSBMassStorageDriver	209.40.6
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	452.30.4
com.apple.iokit.IOSCSIArchitectureModelFamily	452.30.4
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleIISController	100.1
com.apple.driver.AppleAudioClockLibs	100.9.1
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	302.9
com.apple.driver.IODARTFamily	1
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.security.AppleImage4	4.1.0
com.apple.kext.CoreTrust	1
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	12.0



** Stackshot Succeeded ** Bytes Traced 368962 (Uncompressed 912320) **

```

**Additional info**
 - OS: macOS 12.0.1
 - MacBook Air (M1, 2020)

- `multipass version`
```
multipass   1.8.1+mac
multipassd  1.8.1+mac
```

- `multipass info --all`
```
Name:           primary
State:          Running
IPv4:           192.168.64.3
Release:        Ubuntu 20.04.3 LTS
Image hash:     a83b747df657 (Ubuntu 20.04 LTS)
Load:           0.12 0.10 0.04
Disk usage:     1.4G out of 4.7G
Memory usage:   141.4M out of 974.8M
Mounts:         /Users/peterullrich => Home
                    UID map: 501:default
                    GID map: 20:default

Name:           dotup-vml002
State:          Running
IPv4:           192.168.64.5
Release:        Ubuntu 21.10
Image hash:     063fa690f56b (Ubuntu 21.10)
Load:           0.05 0.07 0.02
Disk usage:     3.9G out of 4.8G
Memory usage:   202.7M out of 1.9G
Mounts:         --
```

**Comment by townsend2010** [comment] 2021-11-13 16:49
Hi @dotupNET,

Looking at the panic output, this line seems to indicate that `FreeRDPSandboxed` is the task running when the panic occurred and is most likely the culprit of the panic:
`Panicked task 0xfffffe1515d90fe0: 23158 pages, 21 threads: pid 11331: FreeRDPSandboxed`

I think you ought to look more into that and see what's going with that process, but I don't think this is caused by Multipass.  I'm going to close this for now, but please reopen if you find more evidence that Multipass is at fault.

**Closed by townsend2010** 2021-11-13 16:49 UTC

**Comment by dotupNET** [comment] 2021-11-16 09:31
@townsend2010 thank you for your help. I'll test it with microsoft remote desktop
