### ISSUE TITLE
Multipass on Win10 lost container - cannot re-add

### ISSUE THREAD

**Issue by mgaerber** [canonical/multipass#2166] opened 2021-07-06 08:05 UTC
The container (anais) is still running and accessible via ssh/shell. Just not via multipass.

![Screenshot](https://i.stack.imgur.com/3i4sD.png)

Tried to add to `C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\multipassd-vm-instances.json` but this file seems to be generated automatically.

```
λ multipass version
multipass  1.6.2+win
multipassd 1.6.2+win
```

**Comment by townsend2010** [comment] 2021-07-06 11:41
Hi @mgaerber,

Sorry you are having issues.  Could you please provide logs?  Please see https://multipass.run/docs/accessing-logs on how to do this.

Thanks!

**Comment by mgaerber** [comment] 2021-07-06 15:34
Oddly, there is nothing special in the event log, only INFO level entries for Multipass, such as below.

But there are almost 50k entries like this, only for today. Is it normal to have that many Cmdlet statements executed?


```
Protokollname: Application
Quelle:        Multipass
Datum:         06.07.2021 17:26:35
Ereignis-ID:   1
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      LAPTOP-
Beschreibung:
[gumball] [8920] Cmdlet: 'Get-VM -Name gumball | Select-Object -ExpandProperty State'
```

**Comment by townsend2010** [comment] 2021-07-06 16:09
Hi @mgaerber,

Hmm...so, just to make sure I understand what happened here, you created an instance called `anais` using Multipass and then at some point, Multipass lost track of this instance and you can't get it back under Multipass control.  Is this correct?  You didn't try to delete the instance using Multipass or anything?

**Comment by townsend2010** [comment] 2021-07-06 16:10
Oh, regarding the Powershell spam, this will be fixed in the next Multipass release.

**Comment by mgaerber** [comment] 2021-07-06 16:17
Correct, nothing deleted or moved. I am just wondering if there is some script or re-init procedure to tell Multipass it is still there.

`recover` says instance does not exist and now I am stuck.

I guess there is a way to push the required metadata back to some DB or config file but a pointer to where to go from here would be great.

**Comment by townsend2010** [comment] 2021-07-06 16:22
Ok, I am totally baffled how Multipass totally lost track of an instance it created, but not all instances.  I have seen where an upgrade of Windows will move instances to a place where Multipass doesn't expect them, so it looses track of *all* instances, but losing track of just one out of multiple instance, I have not heard of.

At any rate, I'm going to experiment a bit to see if there is some way to "import" this instance back into Multipass.

**Comment by townsend2010** [comment] 2021-07-06 17:17
Hey @mgaerber,

I found the easiest way to do this would be to do the following:
```
multipass launch -n anais
```

In this case, `multipassd` should query the Hyper-V Manager if there is an existing instance with this name, and if so, it will just use it.

**Comment by mgaerber** [comment] 2021-07-06 17:21
Ok, now that was really easy!

Fun fact: it also started the previously suspended gumball instance.

![grafik](https://user-images.githubusercontent.com/1120707/124641790-5bfe1580-de8f-11eb-9d24-561240004705.png)

**Comment by townsend2010** [comment] 2021-07-06 17:24
:man_shrugging: Not sure why that would start a suspended instance.  At any rate, since there are no logs for shedding light on the root cause of why a single instance went missing, I'm going to close this.

Feel free to reopen or open a new issue if this happens again and there is more info as to why it happened.

**Closed by townsend2010** 2021-07-06 17:24 UTC
Labels: question
