### ISSUE TITLE
cloud-init: Support TLS / HTTP for bootstrapping instances.

### ISSUE THREAD

**Issue by joshti** [canonical/multipass#1763] opened 2020-09-28 21:28 UTC
**What are you trying to do?**
For usability / transparent updates (similar to how multipass queries for the latest Ubuntu LTS image) I'd like to be able to ship a cloud-init file that is perpetually supported without shipping archives to users. I'm cross-platform testing right now and would very much like to lower the barrier to entry for using multipass.

**What's your proposed solution?**
Joshuas-MacBook-Pro:Downloads josh$ multipass launch -n host --cloud-init https://g.co/cloud-init.yaml

**Additional context**
It's all about lowering the barrier to entry for brand new (and also experienced) users who just want an easy solution that works. I believe the mission statement is the same for multipass as the request so I'm hoping we're aligned on this one. 😃

**Comment by Saviq** [comment] 2020-09-29 05:35
Hi @joshti, there's already #1461 that deals with this, and a partial implementation contributed by community (#1499). Would you be willing to pick it up and drive it through the finish gates?

I'll mark this duplicate for now.

**Comment by Saviq** [comment] 2020-09-29 05:35
Duplicate of #1461

**Closed by Saviq** 2020-09-29 05:35 UTC
Labels: enhancement
