### ISSUE TITLE
Can't launch VM on Raspberry Pi 4 arm64

### ISSUE THREAD

**Issue by anonymouse64** [canonical/multipass#1466] opened 2020-04-03 17:26 UTC
**Describe the bug**

Multipass should work on arm64.

**To Reproduce**
```
$ multipass launch bionic
launch failed: Internal error: qemu-system-x86_64 failed getting vmstate (Process returned exit code: 1) with output:
qemu-system-aarch64: -nographic: No machine specified, and there is no default
Use -machine help to list supported machines
```

**Expected behavior**
The VM would start

**Logs**

<details>

```
$ sudo snap logs -n=all multipass
2020-04-02T13:36:13Z systemd[1]: Started Service for snap application multipass.multipassd.
2020-04-02T13:36:16Z multipassd[2018]: Unable to determine subnet for the mpqemubr0 subnet
2020-04-02T13:36:16Z multipassd[2018]: Using AppArmor support
2020-04-02T13:36:17Z multipassd[2124]: Applying AppArmor policy: multipass.dnsmasq
2020-04-02T13:36:17Z dnsmasq[2126]: started, version 2.79 cachesize 150
2020-04-02T13:36:17Z dnsmasq[2126]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
2020-04-02T13:36:17Z dnsmasq-dhcp[2126]: DHCP, IP range 10.52.171.2 -- 10.52.171.254, lease time infinite
2020-04-02T13:36:17Z dnsmasq-dhcp[2126]: DHCP, sockets bound exclusively to interface mpqemubr0
2020-04-02T13:36:17Z dnsmasq[2126]: using local addresses only for domain multipass
2020-04-02T13:36:17Z dnsmasq[2126]: reading /etc/resolv.conf
2020-04-02T13:36:17Z dnsmasq[2126]: using local addresses only for domain multipass
2020-04-02T13:36:17Z dnsmasq[2126]: using nameserver 127.0.0.53#53
2020-04-02T13:36:17Z dnsmasq[2126]: read /etc/hosts - 7 addresses
2020-04-02T13:36:17Z dnsmasq[2126]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
2020-04-02T13:36:18Z multipassd[2018]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
2020-04-02T13:36:18Z multipassd[2018]: QIODevice::write (QFile, "/var/snap/multipass/common/cache/multipassd/vault/multipassd-image-records.json"): device not open
2020-04-02T13:38:50Z multipassd[2240]: Applying AppArmor policy: multipass.qemu-img
2020-04-02T13:38:50Z multipassd[2247]: Applying AppArmor policy: multipass.qemu-img
2020-04-02T13:39:20Z multipassd[2018]: Process operation timed out
2020-04-02T13:39:20Z multipassd[2018]: QProcess: Destroyed while process ("qemu-img") is still running.
2020-04-02T13:46:12Z dnsmasq[2126]: reading /etc/resolv.conf
2020-04-02T13:46:12Z dnsmasq[2126]: using local addresses only for domain multipass
2020-04-02T13:46:12Z dnsmasq[2126]: using nameserver 127.0.0.53#53
2020-04-02T13:46:12Z dnsmasq[2126]: reading /etc/resolv.conf
2020-04-02T13:46:12Z dnsmasq[2126]: using local addresses only for domain multipass
2020-04-02T13:46:12Z dnsmasq[2126]: using nameserver 127.0.0.53#53
2020-04-02T13:46:12Z dnsmasq[2126]: reading /etc/resolv.conf
2020-04-02T13:46:12Z dnsmasq[2126]: using local addresses only for domain multipass
2020-04-02T13:46:12Z dnsmasq[2126]: using nameserver 127.0.0.53#53
2020-04-02T13:49:47Z systemd[1]: Started Service for snap application multipass.multipassd.
2020-04-02T14:16:58Z multipassd[1257]: Unable to determine subnet for the mpqemubr0 subnet
2020-04-02T14:16:58Z multipassd[1257]: Using AppArmor support
2020-04-02T14:16:58Z multipassd[1569]: Applying AppArmor policy: multipass.dnsmasq
2020-04-02T14:16:59Z dnsmasq[1576]: started, version 2.79 cachesize 150
2020-04-02T14:16:59Z dnsmasq[1576]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
2020-04-02T14:16:59Z dnsmasq-dhcp[1576]: DHCP, IP range 10.52.171.2 -- 10.52.171.254, lease time infinite
2020-04-02T14:16:59Z dnsmasq-dhcp[1576]: DHCP, sockets bound exclusively to interface mpqemubr0
2020-04-02T14:16:59Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T14:16:59Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T14:16:59Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T14:16:59Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T14:16:59Z dnsmasq[1576]: read /etc/hosts - 7 addresses
2020-04-02T14:16:59Z dnsmasq[1576]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
2020-04-02T14:16:59Z multipassd[1257]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
2020-04-02T14:17:03Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T14:17:03Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T14:17:03Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T14:17:03Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T14:17:03Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T14:17:03Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T14:17:03Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T14:17:03Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T14:17:03Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T14:17:03Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T14:17:03Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T14:17:03Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T15:48:27Z multipassd[1257]: Received signal 15 (Terminated)
2020-04-02T15:48:27Z multipassd[1257]: Goodbye!
2020-04-02T15:48:27Z systemd[1]: Stopping Service for snap application multipass.multipassd...
2020-04-02T15:48:27Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T15:48:27Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T15:48:27Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T15:48:27Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T15:48:27Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T15:48:27Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T15:48:28Z dnsmasq[1576]: reading /etc/resolv.conf
2020-04-02T15:48:28Z dnsmasq[1576]: using local addresses only for domain multipass
2020-04-02T15:48:28Z dnsmasq[1576]: using nameserver 127.0.0.53#53
2020-04-02T15:48:28Z multipass.multipassd[1257]: [trace] [daemon] Removing AppArmor policy:
2020-04-02T15:48:28Z multipass.multipassd[1257]: #include <tunables/global>
2020-04-02T15:48:28Z multipass.multipassd[1257]: profile multipass.dnsmasq flags=(attach_disconnected) {
2020-04-02T15:48:28Z multipass.multipassd[1257]:   #include <abstractions/base>
2020-04-02T15:48:28Z multipass.multipassd[1257]:   #include <abstractions/nameservice>
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability chown,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability net_bind_service,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability setgid,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability setuid,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability dac_override,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability dac_read_search,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability net_admin,         # for DHCP server
2020-04-02T15:48:28Z multipass.multipassd[1257]:   capability net_raw,           # for DHCP server ping checks
2020-04-02T15:48:28Z multipass.multipassd[1257]:   network inet raw,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   network inet6 raw,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   # Allow multipassd send dnsmasq signals
2020-04-02T15:48:28Z multipass.multipassd[1257]:   signal (receive) peer=snap.multipass.multipassd,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   # access to iface mtu needed for Router Advertisement messages in IPv6
2020-04-02T15:48:28Z multipass.multipassd[1257]:   # Neighbor Discovery protocol (RFC 2461)
2020-04-02T15:48:28Z multipass.multipassd[1257]:   @{PROC}/sys/net/ipv6/conf/*/mtu r,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   # binary and its libs
2020-04-02T15:48:28Z multipass.multipassd[1257]:   /snap/multipass/1910/usr/sbin/dnsmasq ixr,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   /snap/multipass/1910/{usr/,}lib/@{multiarch}/{,**/}*.so* rm,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   # CLASSIC ONLY: need to specify required libs from core snap
2020-04-02T15:48:28Z multipass.multipassd[1257]:   /{,var/lib/snapd/}snap/core18/*/{,usr/}lib/@{multiarch}/{,**/}*.so* rm,
2020-04-02T15:48:28Z multipass.multipassd[1257]:   /var/snap/multipass/common/data/multipassd/network/dnsmasq.leases rw,           # Leases file
2020-04-02T15:48:28Z multipass.multipassd[1257]:   /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts r,             # Hosts file
2020-04-02T15:48:28Z multipass.multipassd[1257]:   /var/snap/multipass/common/data/multipassd/network/dnsmasq.pid w,     # pid file
2020-04-02T15:48:28Z multipass.multipassd[1257]: }
2020-04-02T15:48:28Z multipass.multipassd[1257]:     
2020-04-02T15:48:28Z systemd[1]: snap.multipass.multipassd.service: Succeeded.
2020-04-02T15:48:28Z systemd[1]: Stopped Service for snap application multipass.multipassd.
2020-04-02T15:49:07Z systemd[1]: Started Service for snap application multipass.multipassd.
2020-04-02T15:49:13Z multipassd[2284]: Unable to determine subnet for the mpqemubr0 subnet
2020-04-02T15:49:13Z multipassd[2284]: Using AppArmor support
2020-04-02T15:49:14Z multipassd[2380]: Applying AppArmor policy: multipass.dnsmasq
2020-04-02T15:49:14Z dnsmasq[2382]: started, version 2.79 cachesize 150
2020-04-02T15:49:14Z dnsmasq[2382]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
2020-04-02T15:49:14Z dnsmasq-dhcp[2382]: DHCP, IP range 10.52.171.2 -- 10.52.171.254, lease time infinite
2020-04-02T15:49:14Z dnsmasq-dhcp[2382]: DHCP, sockets bound exclusively to interface mpqemubr0
2020-04-02T15:49:14Z dnsmasq[2382]: using local addresses only for domain multipass
2020-04-02T15:49:14Z dnsmasq[2382]: reading /etc/resolv.conf
2020-04-02T15:49:14Z dnsmasq[2382]: using local addresses only for domain multipass
2020-04-02T15:49:14Z dnsmasq[2382]: using nameserver 127.0.0.53#53
2020-04-02T15:49:14Z dnsmasq[2382]: read /etc/hosts - 7 addresses
2020-04-02T15:49:14Z dnsmasq[2382]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
2020-04-02T15:49:14Z multipassd[2284]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
2020-04-02T15:49:34Z multipassd[2284]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/releases/streams/v1/index.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
2020-04-02T15:49:54Z multipassd[2284]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
2020-04-02T15:50:15Z multipassd[2284]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/daily/streams/v1/index.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
2020-04-02T15:50:35Z multipassd[2284]: Cannot retrieve last modified date for https://cloud-images.ubuntu.com/daily/streams/v1/com.ubuntu.cloud:daily:download.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
2020-04-02T15:50:35Z multipassd[2284]: Could not update manifest: failed to download from 'http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Host cdimage.ubuntu.com not found
2020-04-02T15:50:55Z multipassd[2284]: Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/minimal/releases/xenial/release/ubuntu-16.04-minimal-cloudimg-amd64-disk1.img': Host cloud-images.ubuntu.com not found
2020-04-02T16:34:33Z systemd[1]: Started Service for snap application multipass.multipassd.
2020-04-03T17:12:28Z multipassd[1263]: Unable to determine subnet for the mpqemubr0 subnet
2020-04-03T17:12:28Z multipassd[1263]: Using AppArmor support
2020-04-03T17:12:29Z multipassd[2123]: Applying AppArmor policy: multipass.dnsmasq
2020-04-03T17:12:29Z dnsmasq[2168]: started, version 2.79 cachesize 150
2020-04-03T17:12:29Z dnsmasq[2168]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
2020-04-03T17:12:29Z dnsmasq-dhcp[2168]: DHCP, IP range 10.52.171.2 -- 10.52.171.254, lease time infinite
2020-04-03T17:12:29Z dnsmasq-dhcp[2168]: DHCP, sockets bound exclusively to interface mpqemubr0
2020-04-03T17:12:29Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:12:29Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:12:29Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:12:29Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:12:29Z dnsmasq[2168]: read /etc/hosts - 7 addresses
2020-04-03T17:12:29Z dnsmasq[2168]: cannot read /var/snap/multipass/common/data/multipassd/network/dnsmasq.hosts: No such file or directory
2020-04-03T17:12:30Z multipassd[1263]: gRPC listening on unix:/var/snap/multipass/common/multipass_socket, SSL:on
2020-04-03T17:12:46Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:12:46Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:12:46Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:12:46Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:12:46Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:12:46Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:19:55Z multipassd[4197]: Applying AppArmor policy: multipass.qemu-img
2020-04-03T17:19:56Z multipassd[4204]: Applying AppArmor policy: multipass.qemu-img
2020-04-03T17:20:37Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:20:37Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:20:38Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:20:38Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:20:38Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:20:38Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:20:38Z multipassd[1263]: process working dir '/snap/multipass/1920/qemu'
2020-04-03T17:20:38Z multipassd[1263]: process program 'qemu-system-aarch64'
2020-04-03T17:20:38Z multipassd[1263]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/maternal-grunt/ubuntu-18.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:87:df:bd, -netdev, tap,id=hostnet0,ifname=tap-bf0d9d66ab9,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/maternal-grunt/cloud-init-config.iso'
2020-04-03T17:20:38Z multipassd[1263]: qemu-system-aarch64: -nographic: No machine specified, and there is no default
Use -machine help to list supported machines
2020-04-03T17:20:38Z multipassd[1263]: attempting to release non-existant addr: 52:54:00:87:df:bd
2020-04-03T17:20:38Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:20:38Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:20:38Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:20:38Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:20:38Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:20:38Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:22:59Z multipassd[4287]: Applying AppArmor policy: multipass.qemu-img
2020-04-03T17:23:21Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:23:21Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:23:21Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:23:22Z multipassd[1263]: process working dir '/snap/multipass/1920/qemu'
2020-04-03T17:23:22Z multipassd[1263]: process program 'qemu-system-aarch64'
2020-04-03T17:23:22Z multipassd[1263]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/advisable-stingray/ubuntu-18.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:58:9e:31, -netdev, tap,id=hostnet0,ifname=tap-97f4e728d2c,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/advisable-stingray/cloud-init-config.iso'
2020-04-03T17:23:22Z multipassd[1263]: qemu-system-aarch64: -nographic: No machine specified, and there is no default
Use -machine help to list supported machines
2020-04-03T17:23:22Z multipassd[1263]: attempting to release non-existant addr: 52:54:00:58:9e:31
2020-04-03T17:23:22Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:23:22Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:23:22Z dnsmasq[2168]: using nameserver 127.0.0.53#53
2020-04-03T17:23:22Z dnsmasq[2168]: reading /etc/resolv.conf
2020-04-03T17:23:22Z dnsmasq[2168]: using local addresses only for domain multipass
2020-04-03T17:23:22Z dnsmasq[2168]: using nameserver 127.0.0.53#53
```

</details>

Ubuntu 19.10 Server for arm64 on Raspberry Pi
```
$ multipass version
multipass  1.2.0-dev.103+g9148960
multipassd 1.2.0-dev.103+g9148960
```

**Comment by Saviq** [comment] 2020-04-03 17:29
Duplicate of #1376

**Comment by Saviq** [comment] 2020-04-03 17:30
Hey @anonymouse64 it's unclear why there isn't a default `-machine` value, see #1376 and please let us know if you think it's "our" fault.

**Closed by Saviq** 2020-04-03 17:29 UTC
