### ISSUE TITLE
GPG verify streams

### ISSUE THREAD

**Issue by xnox** [canonical/multipass#2009] opened 2021-03-16 14:49 UTC
https://bugs.launchpad.net/cloud-images/+bug/1919339

Please check if above bug report affects multipass. I.e. if gpg signed streams are available, please check that you do verify GPG signatures on those streams.

And if more streams add gpg signing do verify them too.

**Comment by Saviq** [comment] 2021-03-16 14:56
Duplicate of #276

**Closed by Saviq** 2021-03-16 14:56 UTC
Labels: enhancement
