### ISSUE TITLE
Improve performance of the mountpoints using virtiofs on MacOS

### ISSUE THREAD

**Issue by stefreak** [canonical/multipass#2735] opened 2022-09-03 23:56 UTC
**What are you trying to do?**
Some tools require better directory sharing performance than sshfs

**What's your proposed solution?**
multipass could support virtiofs on some platforms, e.g. if it uses [qemu](https://virtio-fs.gitlab.io/) or the [macos virtualization framework
](https://developer.apple.com/documentation/virtualization/vzvirtiofilesystemdevice)

**Additional context**
This would enable to use multipass for tasks that require high performance,e.g. when using development tools that walk huge directory trees.

**Comment by stefreak** [comment] 2022-09-04 00:02
The documentation mentions `virtio-fs is also available in qemu and libvirt backends, though at an extra setup cost.` but does not go into detail of what needs to be done to set it up

**Comment by townsend2010** [comment] 2022-09-07 19:27
Hi @stefreak,

We are currently in the process of adding more performant mounts in Multipass.  Since we are a multi-platform solution, we have to take care of making sure most new features work on all platforms.  That said, our first iteration of this will be 9p on macOS/Linux with the `qemu` driver and SMB on Windows with the `hyperv` driver.  We are tracking this in #1759, so I'm going to mark this a duplicate of that.

Duplicate of #1759

**Closed by townsend2010** 2022-09-07 19:27 UTC
