### ISSUE TITLE
Static ip address

### ISSUE THREAD

**Issue by bahram-hodjaev** [canonical/multipass#1545] opened 2020-05-20 06:50 UTC
**What are you trying to do?**
I would like to use a multipass machine with vs code during development.
But from time to time the ip address of the virtual machine is changing.

**What's your proposed solution?**
Offer static ip address for virtual machines

**Additional context**
![Annotation 2020-05-20 094859](https://user-images.githubusercontent.com/3465733/82414084-2e81bd00-9a7f-11ea-8429-27ff91282278.png)

**Comment by Saviq** [comment] 2020-05-20 07:26
Hi @bahram-hodjaev, is this on Windows? If that's the case, you can use `<instance name>.mshome.net` instead of straight IP address.

And you're right, the IP changes because Windows does not keep a static subnet over reboots, unfortunately.

**Comment by Saviq** [comment] 2020-05-20 07:27
That said, with bridged networking we'll be adding soon (#118) you'll be able to use a static IP, too.

**Comment by Saviq** [comment] 2020-05-20 07:27
Duplicate of #1293

**Closed by Saviq** 2020-05-20 07:27 UTC
Labels: question

**Comment by bahram-hodjaev** [comment] 2020-05-20 08:09
@Saviq thank you very much!!

**Comment by bahram-hodjaev** [comment] 2020-05-20 08:09
> Hi @bahram-hodjaev, is this on Windows? If that's the case, you can use `<instance name>.mshome.net` instead of straight IP address.
> 
> And you're right, the IP changes because Windows does not keep a static subnet over reboots, unfortunately.

Yeah, this is happening on Windows
