### ISSUE TITLE
snapcraft command fails with message "Could not find snap/snapcraft.yaml" even when file exists

### ISSUE THREAD

**Issue by sanathusk** [canonical/multipass#1899] opened 2020-12-26 05:39 UTC
-Issue
running the snapcraft command results in following error message:
_Launching a VM.
Could not find snap/snapcraft.yaml. Are you sure you are in the right directory?
To start a new project, use `snapcraft init`_

The snapcraft.yaml exists and has been created using snapcraft init command.
please refer below discussion,Its is the exact issue described in the link below;
https://forum.snapcraft.io/t/could-not-find-snap-snapcraft-yaml-when-it-is-there/10503/5

**Additional info**
-snap version
snap    2.48.1
snapd   2.48.1
series  16
ubuntu  20.04
kernel  5.4.0-58-generic

 - OS: Ubuntu 20.04
- `multipass version`:
 multipass  1.5.0
multipassd 1.5.0

- `multipass info --all`
Name:           snapcraft-utqemu
State:          Running
Release:        Ubuntu 18.04.5 LTS
Disk usage:     2.3G out of 247.9G
Memory usage:   171.7M out of 1.9G
Mounts:         /home/sanath/git-view/utqemu => /root/project
                    UID map: 1000:0
                    GID map: 1000:0

**Additional context**
It worked after following workaround :
multipass list
note which instances exist, if any delete with
multipass delete --purge snapcraft-instance-name
reinstall multipass
sudo snap remove multipass
snapcraft (will install multipass automatically)

**Comment by kinekt4** [comment] 2022-04-07 07:03
This issue popped up for me after an incomplete build.

I resolved it with `multipass delete --purge snapcraft-instance-name`. I didn't need to reinstall multipass.

---
snap: v2.54.4
snapcraft: v6.1
multipass: v1.8.0

**Comment by Saviq** [comment] 2022-04-07 10:00
I believe this to be a duplicate of #2407 - when the mount crashed, the source of the snap couldn't be seen inside the instance.

**Comment by Saviq** [comment] 2022-04-07 10:01
Duplicate of #2407

**Closed by Saviq** 2022-04-07 10:01 UTC
Labels: bug
