### ISSUE TITLE
multipass transfer results in SFTP server: Failure

### ISSUE THREAD

**Issue by jasonmccallister** [canonical/multipass#1432] opened 2020-03-17 15:27 UTC
**Describe the bug**
I am getting an SFTP error when using `multipass transfer`. The error happens on each machine: 

```
transfer failed: [sftp push] open failed: 'SFTP server: Failure'
```

**To Reproduce**
How, and what happened?
1. `multipass launch --name stfptest`
1. `multipass transfer file sftptest:/home/ubuntu/`

**Expected behavior**
the file should have transferred into the instance.

**Additional info**
 - OS: macOS 10.15.3
- multipass  1.1.0+mac
- multipassd 1.1.0+mac

```
Name:           nitro-dev
State:          Running
IPv4:           192.168.64.21
Release:        Ubuntu 18.04.4 LTS
Image hash:     3c3a67a14257 (Ubuntu 18.04 LTS)
Load:           0.06 0.18 0.11
Disk usage:     1.5G out of 4.7G
Memory usage:   168.5M out of 1.9G
```

**Comment by Saviq** [comment] 2020-03-17 16:10
Hi @jasonmccallister, the problem is that if you provide a path, it expects to be a _file_ target, i.e.:
```
multipass transfer file sftptest:/home/ubuntu/file
```

We can definitely improve that - and have issue #1165 to track this.

**Comment by Saviq** [comment] 2020-03-17 16:10
Duplicate of #1165

**Closed by Saviq** 2020-03-17 16:10 UTC
Labels: bug
