### ISSUE TITLE
VM crash - qemu driver - macOS 12.6

### ISSUE THREAD

**Issue by sebschlue** [canonical/multipass#2749] opened 2022-09-17 12:25 UTC
**Describe the bug**
After updating to macOS 12.6, VMs crash after a couple of minutes of runtime.

**To Reproduce**
```
$ multipass launch --cpus 4 --mem 16G --disk 100G --name k3s 20.04
```

**Expected behavior**
VM should not crash.

**Logs**
```
[2022-09-17T14:07:41.506] [debug] [k3s] QMP: vmx_write_mem: mmu_gva_to_gpa ffff9de916a00000 failed
[2022-09-17T14:07:41.507] [error] [k3s] process error occurred Crashed program: qemu-system-x86_64; error: Process crashed
[2022-09-17T14:07:41.507] [info] [k3s] process state changed to NotRunning
[2022-09-17T14:07:41.507] [error] [k3s] error: program: qemu-system-x86_64; error: Process crashed
```

**Additional info**

 OS:  macOS 12.6

```
$ multipass version
multipass   1.10.1+mac
multipassd  1.10.1+Mac

$ multipass info --all
Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     77f2f05e39e5 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /Users/sschlueter => Home
                    UID map: 502:default
                    GID map: 20:default

Name:           k3s
State:          Stopped
IPv4:           --
Release:        --
Image hash:     77f2f05e39e5 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

$ multipass get local.driver
qemu

$ /Library/Application\ Support/com.canonical.multipass/bin/qemu-system-x86_64 -version                
QEMU emulator version 6.2.0


```

**Comment by sebschlue** [comment] 2022-09-17 12:56
I have tried to change qemu host cpu model from "host" to "Haswell-v4" in file

`/private/var/root/Library/Application Support/multipassd/qemu/multipassd-vm-instances.json`

but the file gets automatically overwritten, so manually modifying it does not work. 

Changing the cpu host model is potential workaround described here:


https://github.com/lima-vm/lima#qemu-crashes-with-vmx_write_mem-mmu_gva_to_gpa-xxxxxxxxxxxxxxxx-failed

**Comment by gilbahat** [comment] 2023-04-03 18:27
being bitten by this too, any progress on this bug perhaps?

**Comment by srudolph-credera** [comment] 2023-04-13 22:03
I can report the same with the latest version just by running a large apt upgrade or launching a larger app via X Windows (via SSH forwarding). The easily most reproducible crash is running `x-www-browser` and trying to use it. Interestingly, qemu seems more stable when I drop the CPU core count down from 4 to 2.

Config:
```
multipass launch kinetic --cpus 4 --memory 12G --disk 42G --name primary
```

Logs:
```
[2023-04-13T16:45:16.634] [debug] [primary] QMP: vmx_write_mem: mmu_gva_to_gpa ffff911f80177000 failed

[2023-04-13T16:45:16.634] [error] [primary] process error occurred Crashed program: qemu-system-x86_64; error: Process crashed
[2023-04-13T16:45:16.635] [info] [primary] process state changed to NotRunning
[2023-04-13T16:45:16.635] [error] [primary] error: program: qemu-system-x86_64; error: Process crashed
```

Additional Info (after restarting):
macOS 13.3 on a 2.4 GHz 8-Core Intel Core i9 (2019 16" MacBook Pro)

```
multipass version
multipass   1.11.1+mac
multipassd  1.11.1+Mac

multipass info --all
Name:           primary
State:          Running
IPv4:           192.168.205.5
Release:        Ubuntu 22.10
Image hash:     f618c68e5510 (Ubuntu 22.10)
CPU(s):         4
Load:           1.60 0.40 0.13
Disk usage:     6.9GiB out of 40.5GiB
Memory usage:   467.5MiB out of 11.7GiB
Mounts:         --

multipass get local.driver
qemu

/Library/Application\ Support/com.canonical.multipass/bin/qemu-system-x86_64 -version
QEMU emulator version 7.1.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

**Comment by mszpala** [comment] 2023-06-07 14:21
I can reproduce the same issue on macOS 13.4 on Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (2019 16" MacBook Pro) with same versions as post above. Is there any possibility to change qemu parameters on my own? It seems that for this type of CPU there's no dedicated QEMU target, so I'd like to try to use qemu64 CPU.

**Comment by srudolph-credera** [comment] 2023-06-09 15:50
It's early still, but the 1.12.0 Multipass update that upgrades QEMU to v8 is so far completely stable, even with 4 CPU cores that I had trouble with before. @sebschlue  - are you seeing any improvement?

**Comment by townsend2010** [comment] 2023-06-09 15:53
Hi @srudolph-credera!

Thank you for your preliminary findings.  I hoped the QEMU update would fix this particular issue, but I wasn't completely sure since I don't have a machine that is affected by this particular problem.  Please report again when you've had more time with the new release and for anyone else to report as well so we can close this bug.

Thanks!

**Comment by srudolph-credera** [comment] 2023-06-12 22:44
@townsend2010 - happy to report that I haven't been able to crash Multipass since the update, even running Ubuntu + Desktop for a full workday. I was also able to run the recently-launched 23.04 image all day today with no issues. Hope this is working just as well for everyone else!

**Comment by sebschlue** [comment] 2023-06-13 10:04
I do no longer work with a MacBook on a regular/daily basis, but I can do some testing next weekend and then report back here in this ticket.

**Comment by townsend2010** [comment] 2023-06-28 13:28
As we've had no more reports of this issue after the 1.12.0 release and have had positive feedback, I'm going to close this.  If anyone does hit this issue, we can either reopen this issue or create a new one.  Thanks!

**Closed by townsend2010** 2023-06-28 13:28 UTC
