### ISSUE TITLE
ERROR: permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by BigBoulard** [canonical/multipass#3316] opened 2023-11-24 12:39 UTC
Hi,

I'm trying to create a Docker Swarm using Multipass but the Docker daemon is not running.
OS: darwin (macOS Sonoma 14.1.1)
Arch: arm64 (M2)

Here are the steps:

1. From the `~/.ssh` folder, create an ECDSA key named `multipass_id_ecdsa`

```sh
ssh-keygen ecdsa
```

2. In `~/.ssh/config` add the key to the `manager.local` host

```sh
Host manager.local
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/multipass_id_ecdsa

Host *
...
```
 
4. Create the `docker.yml` cloud-init file

```sh
#cloud-config
users:
  - name: boulard
    ssh-authorized-keys:
      - ecdsa-sha2-nistp256 PUBLIC_KEY me@mymac
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
package_update: true
packages:
  - docker
  - avahi-daemon
  - apt-transport-https
  - ca-certificates # see https://docs.docker.com/engine/swarm/how-swarm-mode-works/pki/
  - curl
  - gnupg
  - lsb-release
runcmd:
  - sudo curl -fsSL https://get.docker.com | sudo bash
  - sudo systemctl enable docker # initialize docker at startup
  - sudo systemctl enable -s HUP ssh
  - sudo groupadd docker
  - sudo usermod -aG docker ubuntu
```

5. Launch a `manager` instance

```sh
multipass launch -c 2 -m 2G -d 2.5G -n manager 22.04 --cloud-init docker.yml
```

6. ssh into the `manager` instance

```sh
ssh boulard@manager.local  
```

7. check that `docker daemon` is running using `docker info`

```sh
boulard@manager:~$ docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
Server:
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by luis4a0** [comment] 2023-11-24 13:18
Hi @BigBoulard, thanks for reporting. Did you try with our Docker Blueprint? Something like `multipass launch docker`, adding your parameters.

**Comment by BigBoulard** [comment] 2023-11-24 13:34
Hi @luis4a0, thanks for getting back to me.

Just tried but nothing happens, once I `ssh` into the `docker instance`, I have no session and no error message is displayed.

```sh
> multipass launch docker                                                     
Folder "/Users/me/multipass/docker" already exists.
Mounted '/Users/me/multipass/docker' into 'docker:docker'
Launched: docker

> ssh boulard@docker.local
```

**Comment by luis4a0** [comment] 2023-11-24 13:42
Try to access the instance through Multipass, using the command `multipass shell docker`. If that works, we continue from there.

**Comment by BigBoulard** [comment] 2023-11-24 13:50
I can open a shell using `multipass shell docker`

**Comment by luis4a0** [comment] 2023-11-24 13:57
Alright, so the issue is that you cannot access your instance. The original issue should be the same you had with the `docker` Blueprint. Note that the `docker` instance has two IP addresses, so there might be a routing problem with `docker.local`. Can you check that? You can try to access through SSH using both addresses (from the shell message or from `multipass info docker`). Thanks!

**Comment by BigBoulard** [comment] 2023-11-24 14:24
I just uninstalled `multipass` and other configuration. 
I did the same operations once again: creation of the `manager` node and the `docker` node as well.
I can `multipass shell manager` or `ssh boulard@manager.local` but I can only `multipass shell docker`
## `manager` instance test

```sh
ssh boulard@manager.local
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-87-generic aarch64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Nov 24 15:14:31 CET 2023

  System load:              0.21240234375
  Usage of /:               88.7% of 2.25GB
  Memory usage:             13%
  Swap usage:               0%
  Processes:                109
  Users logged in:          0
  IPv4 address for docker0: 172.17.0.1
  IPv4 address for enp0s1:  192.168.72.11
  IPv6 address for enp0s1:  fdf5:c375:4ce0:d61e:5054:ff:fe10:dbb4

  => / is using 88.7% of 2.25GB


Expanded Security Maintenance for Applications is not enabled.

34 updates can be applied immediately.
19 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


Last login: Fri Nov 24 15:13:22 2023 from 192.168.72.1
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
```

```sh
$ docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

## `docker` instance test

```sh
> multipass shell docker
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-87-generic aarch64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Nov 24 15:21:38 CET 2023

  System load:              0.0556640625
  Usage of /:               6.4% of 38.59GB
  Memory usage:             8%
  Swap usage:               0%
  Processes:                118
  Users logged in:          0
  IPv4 address for docker0: 172.17.0.1
  IPv4 address for enp0s1:  192.168.72.12
  IPv6 address for enp0s1:  fdf5:c375:4ce0:d61e:5054:ff:fe4d:4dd2


Expanded Security Maintenance for Applications is not enabled.

34 updates can be applied immediately.
19 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status
```

```sh
> ubuntu@docker:~$ docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-87-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 3.819GiB
 Name: docker
 ID: 6a772c46-c467-4a15-ad79-05195916dcdb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by luis4a0** [comment] 2023-11-24 14:37
`multipass shell` connects to the instance as the default `ubuntu` user, using the control IP address (in your case, the address in the `192.168.72.0` network). No magic, it's just an SSH connection.

My question is, where are you executing `docker info`?

**Comment by BigBoulard** [comment] 2023-11-24 14:46
Thanks for the explanations. I'm executing `docker info` from within each instance.

**Comment by luis4a0** [comment] 2023-11-24 14:49
My concern is `docker info` failing in the `manager` instance. What happens if you run it as root, with `sudo docker info`.

**Comment by BigBoulard** [comment] 2023-11-24 14:52
Once I `ssh` into the manager instance, if I `sudo docker info` I see no particular issue:

```sh
sudo docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-87-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 1.921GiB
 Name: manager
 ID: 2a121109-813a-481f-884b-bb3dd87c89a1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by luis4a0** [comment] 2023-11-24 14:56
Ok, so that solves the last issue. I am far from being an expert in Docker, but as far as I remember it must be run as root.

**Comment by BigBoulard** [comment] 2023-11-24 15:03
I stumble upon this article form the doc:
<https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user> I need to did into it 

I guess the issue is in the cloud-init file here:
`sudo usermod -aG docker ubuntu`

Cause it adds the already existing ubuntu user (I assume there's a ubuntu user on each freshly installed ubuntu distro but I really don't know)... and I guess I just need to add the `boulard` user created at the beginning of the file:

```sh
#cloud-config
users:
  - name: boulard
```

I need to test this out...

**Comment by BigBoulard** [comment] 2023-11-24 15:36
I works! the issue was in the `docker.yml` cloud-init file

```sh
  - sudo usermod -aG docker boulard # replaced "ubuntu" with "boulard" or the user you specify in the "users" section 
```

```sh
> ssh boulard@manager.local
...
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

> boulard@manager:~$ docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-87-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 1.921GiB
 Name: manager
 ID: 88b8ff19-0538-4269-9799-91207ed393ef
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```sh
> docker context create multipass --description "Multipass Docker" --docker "host=ssh://boulard@manager.local"        
multipass
Successfully created context "multipass"

> docker context use multipass 
multipass
Current context is now "multipass"

> docker info 
Client:
 Version:    24.0.6
 Context:    multipass
 Debug Mode: false
...
```

**Comment by luis4a0** [comment] 2023-11-24 17:05
Glad to hear that! I'm closing the issue. Thanks!

**Closed by luis4a0** 2023-11-24 17:05 UTC
