### ISSUE TITLE
`multipass start primary` changes home directory ownership to uid:1000/gid:1000

### ISSUE THREAD

**Issue by BenWibking** [canonical/multipass#1346] opened 2020-02-10 04:43 UTC
When starting up my "primary" container on macOS 10.15, multipass changes the uid of my home directory to 1000 and gid to 1000. I can fix the problem by chown/chgrp'ing my home directory back to myself, but each time I start the container it changes the ownership again.

**Comment by ricab** [comment] 2020-02-10 11:16
Hi @BenWibking, do you mean your home directory outside the VM gets ownership changed? Could it be that you are observing your home inside primary? How are you examining this? Could you please provide steps to reproduce?

Notice that the VMs that multipass launches have their own user(s). The user named "ubuntu" is the one you get by default in the instance. Its uid and gid are both 1000. This user has its own home dir inside the instance (`/home/ubuntu`).

Additionally, multipass automatically mounts your outside home inside the "primary" VM when launching it, for convenience. The mount is in `/home/ubuntu/Home`. It gets its ownership mapped to the "ubuntu" user, so that you can access the files from within the VM. IOW, if you inspect the files in the mount from the VM, you will see their owner listed as ubuntu/1000. But the actual owner outside the VM should remain untouched.

**Comment by BenWibking** [comment] 2020-02-10 11:52
Yes, I mean the ownership on my real home directory on the host (i.e. outside the VM) gets changed to uid 1000.

To reproduce:
- `multipass start primary`
- `cd /Users`
- `ls -l`
- observe ownership of home directory

**Comment by ricab** [comment] 2020-02-10 12:46
OK, at this point I could not reproduce this. even after adding a user with UID 1000. 

Could you share what you get from:
- `sudo dscl . -list /Users UniqueID | grep 1000`? 
- `id -P`
- `ls -l /Users` when the problem occurs
- `sudo multipass get local.driver`
- `multipass version`

**Comment by ricab** [comment] 2020-02-10 12:53
And can you think of anything out of the ordinary that could be causing or related to this? Thank you for you feedback!

**Comment by BenWibking** [comment] 2020-02-11 02:22
```
➜  /Users ls -l
total 0
drwxrwxrwt    6 root        wheel   192 Aug 26 10:26 Shared
drwxr-xr-x+ 127 benwibking  staff  4064 Feb 11 13:17 benwibking
drwxr-xr-x+  11 sysman      staff   352 Sep  3 14:46 sysman
➜  /Users cd
➜  ~ sudo dscl . -list /Users UniqueID | grep 1000
➜  ~ id -P
benwibking:********:503:20::0:0:Ben Wibking:/Users/benwibking:/bin/zsh
➜  ~ sudo multipass get local.driver
hyperkit
➜  ~ multipass version
multipass  1.0.0+mac
multipassd 1.0.0+mac
➜  ~ multipass start
➜  ~ cd /Users
➜  /Users ls -l
total 0
drwxrwxrwt    6 root    wheel   192 Aug 26 10:26 Shared
drwxr-xr-x+ 127 1000    1000   4064 Feb 11 13:19 benwibking
drwxr-xr-x+  11 sysman  staff   352 Sep  3 14:46 sysman
```

`sysman` is an admin account installed by the IT department. I have FUSE for macOS 3.10.3 installed, also I have VirtualBox 6.1.2 installed. Nothing else that seems obviously related to virtualization or filesystems comes to mind.

**Comment by Saviq** [comment] 2020-02-11 12:01
Hi @BenWibking, can you confirm whether this also happens for manual mounts with `multipass mount`? Thanks!

**Comment by BenWibking** [comment] 2020-02-12 03:16
This does not happen for manual mounts that I've set up with `multipass mount`.

**Comment by BenWibking** [comment] 2020-02-12 03:17
The ownership is also changed for any file I create or modify within the default `~/Home` mount, e.g.

```
➜  ~ multipass shell
ubuntu@primary:~$ cd Home
ubuntu@primary:~/Home$ touch my_modified_file_example.txt
ubuntu@primary:~/Home$ exit
logout
➜  ~ ls -l my_modified_file_example.txt 
-rw-rw-r--  1 1000  1000  0 Feb 12 14:15 my_modified_file_example.txt
```

**Comment by BenWibking** [comment] 2020-02-12 03:37
Furthermore, if I create an alternate mount manually for my home directory, e.g.
` multipass mount /Users/benwibking primary:/home/ubuntu/my_home_dir`
then everything works fine, as long as I don't modify any files in primary:/home/ubuntu/Home.

**Comment by ricab** [comment] 2020-02-12 13:03
Hi @BenWibking, thanks again for your efforts. Elusive business this...

I tried some more stuff to reproduce, but still no luck. I have the same version of virtual box and tried going back from osxfuse 3.10.4 to 3.10.3. Installed with and without the "compatibility layer". It did not make any difference :/

What do you get from the following?

- `ps aux | grep sshfs`
- `multipass exec primary -- bash -c 'ps aux | grep sshfs'`
- do you happen to have a `/etc/fuse.conf` on your system?
- I wonder if we could be picking up something from `~/.ssh/config`. Do you have anything suspicious in there? Does the problem occur if you stop primary, `mv ~/ssh/config{,.bkp}`, start primary again? (don't forget to move `config.bkp` back)

Any special config in primary? What happens if you try it in a new instance? 

```
multipass launch -n foo
multipass mount $HOME foo:Home
multipass restart foo
```

> Furthermore, if I create an alternate mount manually for my home directory, e.g.
multipass mount /Users/benwibking primary:/home/ubuntu/my_home_dir
then everything works fine

So if you `multipass umount primary` and then `multipass mount $HOME primary:Home`, does the issue persist (after a `multipass restart`)?

**Comment by BenWibking** [comment] 2020-02-13 06:34
I've upgraded FUSE for macOS to 3.10.4 and I no longer have this issue.

If it helps in further debugging the root cause:
```
➜  ~ ps aux |grep sshfs
root               933 100.0  0.0  4357144   6516   ??  R    12:00PM 329:57.72 /Library/Application Support/com.canonical.multipass/bin/sshfs_server 192.168.64.4 22 ubuntu /tmp/.X11-unix /tmp/.X11-unix 503:-1, 20:-1,
root               934   0.0  0.1  4392012   9736   ??  S    12:00PM   0:06.55 /Library/Application Support/com.canonical.multipass/bin/sshfs_server 192.168.64.4 22 ubuntu /Users/benwibking Home 503:-1, 20:-1,
benwibking        2162   0.0  0.0  4268296    656 s002  R+    5:31PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn sshfs
➜  ~ multipass exec primary -- bash -c 'ps aux | grep sshfs'
root      1842  0.0  0.0  63972  4144 ?        Ss   12:00   0:00 sudo sshfs -o slave -o nonempty -o transform_symlinks -o allow_other :/Users/benwibking Home
root      1843  0.0  0.0 314392  3520 ?        Sl   12:00   0:04 sshfs -o slave -o nonempty -o transform_symlinks -o allow_other :/Users/benwibking Home
ubuntu    3531  0.0  0.0  13312  3120 pts/2    Ss+  17:31   0:00 bash -c ps aux | grep sshfs
ubuntu    3533  0.0  0.0  14856  1060 pts/2    S+   17:31   0:00 grep sshfs
➜  ~ ls /etc/fuse.conf
ls: /etc/fuse.conf: No such file or directory
```

My .ssh/config has an entry for my primary instance:
```
Host *
     XAuthLocation /opt/X11/bin/xauth

Host ubuntu-vm
     HostName 192.168.64.4
     User ubuntu
     Compression no
```

and no special cloud-init config for my primary instance.

**Comment by BenWibking** [comment] 2020-02-13 06:49
Is `sshfs_server` supposed to be running as root? That seems unnecessary and also a bit concerning security-wise if so.

**Comment by Saviq** [comment] 2020-02-13 10:35
@BenWibking yes, it's by design at the moment (but we have a plan to change that in the long run).

We will have to keep it running as root for "server-side" mounts, but we'll default to a "client-side" mount that will be managed by the system menu icon (so it runs longer than your `multipass` calls).

I'm going to close this issue, thanks for reporting! That said, it's unclear how macOS's fuse could cause this…

**Comment by ricab** [comment] 2020-02-13 10:42
Thanks @BenWibking. Still puzzling, but I am glad this does not affect you anymore. I wondered if a different `sshfs_server` binary could be picked up, but I just looked at the code and that does not seem likely. 

Please let us know if you experience this issue again or if you come by pertinent info.

**Comment by BenWibking** [comment] 2020-02-26 04:24
I'm experiencing this issue again. No idea what (if anything) is different now on my system.

**Comment by ricab** [comment] 2020-02-26 10:43
Hi @BenWibking, sorry to hear that. Have you tried removing your `.ssh/config`? And if you `multipass umount primary` and then `multipass mount $HOME primary:Home`, does the issue persist (after `multipass restart primary`)?

Something seems strange with your system. I have the same filesystem as you, the same VirtualBox installed, have tried the same fuse versions. I would very much like to know what is causing this and how, but we have no way to reproduce nor any other such report. Maybe some race condition in fuse. I am going to reopen this and leave it pending for more info.

**Comment by BenWibking** [comment] 2020-03-30 04:34
The issue persists after stopping primary, fixing permissions, removing my `.ssh/config` and then starting primary again.

However, if I follow your second suggestion and do `multipass umount primary`, then fix permissions, then `multipass mount $HOME primary:Home`, everything appears to be fine (i.e. it doesn't modify the permissions of $HOME).

**Comment by ricab** [comment] 2020-03-30 09:19
Hi @BenWibking, I am sorry you're still experiencing this. Did you try a new primary launch after removing `.ssh/config`? If you're willing to do that, could you also attach the logs? `/Library/Logs/Multipass/multipassd.log` and `primary.log`.

**Comment by BenWibking** [comment] 2020-03-31 05:32
Yes, I did a new primary launch after removing `.ssh/config`. Since doing suggestion 2, however, I have been unable to replicate the permissions problems, regardless of whether `.ssh/config` is present or not. However, my `multipassd.log` file includes the launches where the permissions problems were happening, so it might still be useful. There are several log messages related to mounting `~/Home` or related to `sshfs` crashing.
[multipassd.log](https://github.com/canonical/multipass/files/4406931/multipassd.log)
[primary-hyperkit.log](https://github.com/canonical/multipass/files/4406932/primary-hyperkit.log)

**Comment by ricab** [comment] 2020-03-31 11:53
That log does not appear to contain a `primary` launch. Notice that `multipass launch` means creating (and starting) a new instance. `multipass start` does create `primary` if it does not exist, but that is just a shortcut.

The first time a primary start is recorded, it was the daemon coming up and seeing a previously existing primary:

```
[2020-03-25T15:09:37.716] [info] [daemon] primary needs starting. Starting now...
```

Side note: this ends in a SIGABRT 2 min later, before any mount is attempted. That could have been caused by manual intervention or something else. You appeared to be offline at that time, I wonder if it could be related. It could signal a problem, but it would be a different bug.

At 21pm the following day, primary is started again and three mounts are put in place:

```
/Users/benwibking => /home/ubuntu/Home
/tmp/.X11-unix => /tmp/.X11-unix
/Users/benwibking => Home
```

These must have been previously established. As expected, there is no indication of sshfs being installed in the instance (that would have happened upon automounting at launch). The arguments to sshfs are the usual.

The next time `primary` is recorded as shutting down and starting again was yesterday. The same mounts remain. The instance is stopped right away, which stops the mounts. 

Some sshfs_server crashes are reported among the stop/starts. I was able to reproduce the same thing with the same overlapping mounts, but that never changed my home permissions.

Other than that, there is some more activity: more stop/starts, daemon relaunch, mounting and unmounting... but I found nothing to explain or reproduce the problem.

**Comment by BenWibking** [comment] 2020-03-31 12:53
My apologies, I misunderstood 'launch' to just mean starting the instance. I can create a new instance from scratch, but I need to save the disk image elsewhere - how can I do that?

**Comment by ricab** [comment] 2020-03-31 14:02
Hi @BenWibking, no worries, I should have explained. You can keep your instance as is and test the default by just changing the name of the instance that is considered primary:

```
multipass stop --all  # to avoid other mounts influencing results
multipass set client.primary-name=test  # you can revert to primary when you want
multipass start  # will launch test and automount there
```

You can revert it to `primary` when you want.

**Comment by BenWibking** [comment] 2020-04-01 03:02
Ok, I tried this (both with and without having my `.ssh/config` present) but in neither case do I get permissions problems. I have no explanation for why this might be.

Just in case,  I've attached the logs again.
[multipassd.log](https://github.com/canonical/multipass/files/4412543/multipassd.log)
[test-hyperkit.log](https://github.com/canonical/multipass/files/4412544/test-hyperkit.log)

**Comment by ricab** [comment] 2020-04-01 09:11
Thanks, looked through the logs but I didn't find anything suggestive.

**Comment by BenWibking** [comment] 2020-06-16 09:39
I am no longer experiencing the permissions issue, but the mount does disappear after waking from sleep on my laptop (#1531). It doesn't look like anyone from the development team has taken a look at that issue? Can you take a look?

**Comment by ricab** [comment] 2020-06-16 11:41
Hi @BenWibking, we all monitor the issues and that one in particular is not unnoticed. It will require investigation, but we have other things on our hands and can't always reply right away. 

I am glad to hear this issue isn't affecting you any more! I am going to close it now, but please write back if you find any more clues.

**Comment by nadav-lavy-exa** [comment] 2020-07-15 12:45
Issue is happening to me. 
macos 10.15.5; multipass  1.3.0+mac
had FUSE, removed it. issue persists.
the mounted volume changes its permission while a k8s cluster is running in it

**Comment by ricab** [comment] 2020-07-15 14:41
Hi @nadav-lavy-exa, could you please open a new issue and fill in as much detail as you can on your own situation? This has been a very elusive issue, which we could not reproduce so far, and so it is very difficult to get a handle on. Feel free to try the suggestions above and share your ideas of what could be triggering the problem. Thanks.

**Comment by ricab** [comment] 2020-08-07 17:30
I experienced this once! And then not again... No recipe to reproduce. I'm reopening this to see if we give our sftp server a good inspection.

**Comment by Saviq** [comment] 2020-09-04 05:43
I believe #1718 explain this issue, so will duplicate this to that one.

**Comment by Saviq** [comment] 2020-09-04 05:43
Duplicate of #1718

**Closed by Saviq** 2020-09-04 05:43 UTC
