### ISSUE TITLE
Make Multipass GUI respect x-terminal-emulator from update-alternatives

### ISSUE THREAD

**Issue by flying-sausages** [canonical/multipass#1517] opened 2020-04-30 21:54 UTC
**Describe the bug**
I would like it if multipass launched new shells from the GUI in my preferred terminal and not `xterm`,

**To Reproduce**
How, and what happened?
1. Install multipass on a Ubuntu Gnome dektop environment
1. Open the notification bar applet
1. Open any shell
1. See `xterm` launch 

**Expected behavior**
Have my default terminal emulator launch

**Logs**
None really apply

**Additional info**
- OS: Ubuntu 19.10
-  Gnome 3.34
- multipass  1.2.0
- multipassd 1.2.0

**Additional context**
There is no configuration option for this. If not use x-terminal-emulator, at least allow user to specify the path of the terminal emulator to use or something of the likes.

**Comment by Saviq** [comment] 2020-05-01 13:11
Hey, we'll be working on this real soon.

**Comment by Saviq** [comment] 2020-05-01 13:11
Duplicate of #899

**Closed by Saviq** 2020-05-01 13:11 UTC
