### ISSUE TITLE
multipass ignores cloud init configuration

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [canonical/multipass#1404] opened 2020-03-05 09:02 UTC
I'm using multipass with hyper-v driver on windows.
I have created VM with multipass with the cloud-init configuration:
`multipass launch --name mpass-14 --cpus 2 --mem 2G --disk 20G --cloud-init .\custom-netwosrking.cfg`  

``` yaml
network:
  ethernets:
    eth0:
      addresses:
      - 172.16.110.<xxx>/24
      gateway4: 172.16.110.1
      nameservers:
        addresses:
        - 127.0.0.53
  version: 2
```

The problem is that the ip of the newely create VM does not change.  
I have tried other configuration from
[cloudinit.readthecos.io](https://cloudinit.readthedocs.io/en/latest/topics/examples.html)
but the configuration does not seem to be accepted.

**Comment by jasonmccallister** [comment] 2020-03-05 22:33
@Samet-MohamedAmin from first glance, you are missing the required `#cloud-config` from the top of your file. DO has a really nice tutorial here: https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting.

I'm not too familiar with cloud-init and I find the documentation rather lacking, but I'm pretty sure that you cannot set the IP as it is assigned by the hypervisor on boot and is not user controlled. This ticket has more information on the IP assignment https://github.com/canonical/multipass/issues/1293#issuecomment-572643496

**Comment by Saviq** [comment] 2020-03-10 13:42
Hi @Samet-MohamedAmin @jasonmccallister hit it exactly. It won't be considered cloud-init data unless it has the `#cloud-config` header. But also - you can't currently take ownership of the networking, as Multipass relies on it to contact the instances.

When dealing with #118, we'll add a way for you to specify a bridge (or interface) to hook the instance to and you'll be able to use its DHCP or static addresses for those virtual NICs.

**Comment by Saviq** [comment] 2020-03-10 13:42
Duplicate of #118

**Closed by Saviq** 2020-03-10 13:42 UTC
