### ISSUE TITLE
How to fix ip when launching instance?

### ISSUE THREAD

**Issue by lqllife** [canonical/multipass#2566] opened 2022-05-13 06:33 UTC
**What are you trying to do?**
The instance is changed when launching,I'd like to fix it,in order to testing.

**What's your proposed solution?**
Fix the ip by cli or I can edit in some config files.

**Comment by luis4a0** [comment] 2022-05-13 12:10
Duplicate of https://github.com/canonical/multipass/issues/567.

**Closed by luis4a0** 2022-05-13 12:10 UTC
