### ISSUE TITLE
multipass find fails with "find failed: Operation canceled"

### ISSUE THREAD

**Issue by santiagozky** [canonical/multipass#2378] opened 2021-12-21 09:07 UTC
**Describe the bug**
When trying to find the list of available images with multipass find. I get the following error:
`find failed: Operation canceled`

using -vvvv didn't output anything else

**To Reproduce**
I installed multipass yesterday in a M1 MacBook Pro and managed to launch a 21.10 image with no issues. This morning I tried multipass find and started getting the error.

**Expected behavior**
Multipass find correctly lists the available images

**Logs**
https://pastebin.com/JPXhHHUF

**Additional info**
 - OS: MacOS 12.0.1 (ARM)
- `multipass 1.8.1+Mac`
- `multipass info --all`:
Name:           childlike-akita
State:          Running
IPv4:           192.168.64.4
                172.17.0.1
Release:        Ubuntu 21.10
Image hash:     429d0242a776 (Ubuntu 21.10)
Load:           0.13 0.11 0.04
Disk usage:     1.9G out of 4.8G
Memory usage:   159.0M out of 964.7M
Mounts:         --

**Comment by wu-champion** [comment] 2021-12-30 10:03
I installed multipass few minutes later，using follow command ：
1. `multipass launch Ubuntu_21.04 -n cp -c 1 -m 2G -d 20G`
2.  then immediately used ctr+c to stop the installation
then use `multipass find` to prompt  `find failed: Operation canceled` ,but  `multipass help` and `multipass purge` does not return failure info

**Comment by Saviq** [comment] 2022-01-04 16:18
@wu-champion yours would be #2288

**Comment by Saviq** [comment] 2022-01-04 16:20
@santiagozky are you still affected by this? Does restarting Multipass help, similarly to https://github.com/canonical/multipass/issues/2288#issuecomment-963583241?

**Comment by santiagozky** [comment] 2022-01-11 09:05
hi @Saviq. the problem seems to have disappeared kinda randomly after rebooting my laptop (I had done it before and didn't fix it. not sure why it worked later)

**Comment by Saviq** [comment] 2022-01-11 09:06
I'll mark it as dupe of that one, then.

Duplicate of #2288

**Comment by Saviq** [comment] 2022-01-11 09:06
Duplicate of #2288

**Closed by Saviq** 2022-01-11 09:06 UTC
Labels: question
