### ISSUE TITLE
Cannot quit mulipass when image is downloading

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#1032] opened 2019-09-09 16:13 UTC
We need a way to stop an in progress download if `multipassd` needs to exit.  Currently, it will block until the download finishes.  When the client initiates the download, the download can be canceled if the client exits.  however, when an updated image is being downloaded via the "background updater", there is not way to stop it.

**Comment by Saviq** [comment] 2019-10-04 09:59
Duplicate of #1109

**Closed by Saviq** 2019-10-04 09:59 UTC
