### ISSUE TITLE
[qemu] `/dev/net/tun: Operation not permitted` on Arch Linux

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1610] opened 2020-06-22 06:53 UTC
**Describe the bug**
We had an IRC report that Multipass fails to start instances on Arch:

```
launch failed: The following errors occurred:
qemu-system-x86_64: -netdev tap,id=hostnet0,ifname=tap-58393fac130,script=no,downscript=no: could not open /dev/net/tun: Operation not permitted
snapcraft-project: shutdown called while starting
```
There's a chance we're missing some AppArmor for Arch.

**To Reproduce**
1. `multipass launch` on Arch

**Expected behavior**
Instances should launch.

**Additional info**
 - OS: Arch Linux
- `multipass version`: 1.3.0

**Comment by Saviq** [comment] 2020-06-22 06:54
CC @kenvandine @cjp256.

**Comment by kenvandine** [comment] 2020-06-22 13:11
He was also having a similar issue with lxd.  Snapcraft with lxd had been working fine for him before, it was a new issue last week.  Maybe something in Arch changed, kernel?

**Comment by bboozzoo** [comment] 2020-06-23 07:34
TBH, multipass seems to work just fine out of the box here with snapd 2.45.1. The kernel is up to date as well:
```
$ uname -r
5.7.4-arch1-1
```

I see that /dev/net/tun permissions is 666, but I don't recall ever tweaking that. AFAICT, after a reboot it just comes up with 666.

**Comment by kenvandine** [comment] 2020-06-23 14:41
I was able to reproduce this yesterday, but when booting the VM again today to debug it works fine.  Snapd version is 2.44.3

**Comment by Saviq** [comment] 2020-06-23 16:57
OK, please reopen if you get this again.

**Comment by dundee** [comment] 2020-12-31 20:19
The problem occurs when you upgrade the kernel and then try to start the VM. Reboot solves it.

**Comment by anonymouse64** [comment] 2021-09-30 20:06
I'm now hitting this consistently on 21.04, tried rebooting and also tried using both candidate and stable versions of multipass. 

```
$ multipass shell potent-ant
start failed: The following errors occurred:                                    
qemu-system-x86_64: could not open /dev/net/tun: Operation not permitted
```

**Comment by Saviq** [comment] 2021-10-01 06:24
@anonymouse64 can you please check permissions / apparmor denials on this, anything that you can think could be the reason for the ENOPERM?

**Comment by anonymouse64** [comment] 2021-10-01 13:37
Yeah there's a few denials, not sure if they are related:

```
Oct 01 08:34:37 audit[359505]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 audit[359505]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/i386-linux-gnu/libGL.so.1.7.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.002:6188): apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.002:6189): apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/i386-linux-gnu/libGL.so.1.7.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.002:6190): apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.006:6191): apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/i386-linux-gnu/libGLdispatch.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.006:6192): apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.006:6193): apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/i386-linux-gnu/libGLX.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 audit[359505]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 audit[359505]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/i386-linux-gnu/libGLdispatch.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 audit[359505]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 audit[359505]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipass" name="/var/lib/snapd/hostfs/usr/lib/i386-linux-gnu/libGLX.so.0.0.0" pid=359505 comm="multipass" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Oct 01 08:34:37 audit[359551]: AVC apparmor="DENIED" operation="capable" profile="snap.multipass.multipassd" pid=359551 comm="ip" capability=16  capname="sys_module"
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.034:6194): apparmor="DENIED" operation="capable" profile="snap.multipass.multipassd" pid=359551 comm="ip" capability=16  capname="sys_module"
Oct 01 08:34:37 audit[359561]: AVC apparmor="DENIED" operation="capable" profile="snap.multipass.multipassd" pid=359561 comm="ip" capability=16  capname="sys_module"
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.042:6195): apparmor="DENIED" operation="capable" profile="snap.multipass.multipassd" pid=359561 comm="ip" capability=16  capname="sys_module"
Oct 01 08:34:37 audit[359564]: AVC apparmor="DENIED" operation="capable" profile="snap.multipass.multipassd" pid=359564 comm="ip" capability=16  capname="sys_module"
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.050:6196): apparmor="DENIED" operation="capable" profile="snap.multipass.multipassd" pid=359564 comm="ip" capability=16  capname="sys_module"
Oct 01 08:34:37 audit[359568]: AVC apparmor="DENIED" operation="open" profile="snap.multipass.multipassd" name="/sys/bus/nd/devices/" pid=359568 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.194:6198): apparmor="DENIED" operation="open" profile="snap.multipass.multipassd" name="/sys/bus/nd/devices/" pid=359568 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Oct 01 08:34:37 audit[359571]: AVC apparmor="DENIED" operation="open" profile="multipass.potent-ant.qemu-system-x86_64" name="/snap/multipass/5726/qemu/" pid=359571 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Oct 01 08:34:37 audit[359571]: AVC apparmor="DENIED" operation="open" profile="multipass.potent-ant.qemu-system-x86_64" name="/sys/bus/nd/devices/" pid=359571 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.250:6199): apparmor="DENIED" operation="open" profile="multipass.potent-ant.qemu-system-x86_64" name="/snap/multipass/5726/qemu/" pid=359571 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Oct 01 08:34:37 kernel: audit: type=1400 audit(1633095277.250:6200): apparmor="DENIED" operation="open" profile="multipass.potent-ant.qemu-system-x86_64" name="/sys/bus/nd/devices/" pid=359571 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

and logs for multipassd from around this time:

```
2021-10-01T08:34:37-05:00 multipassd[4464]: [359548] started: /snap/multipass/5726/bin/check_kvm_support
2021-10-01T08:34:37-05:00 multipassd[4464]: process working dir '/snap/multipass/5726/qemu'
2021-10-01T08:34:37-05:00 multipassd[4464]: process program 'qemu-system-x86_64'
2021-10-01T08:34:37-05:00 multipassd[4464]: process arguments '--enable-kvm, -cpu, host, -nic, tap,ifname=tap-d29c2ac271a,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:4c:93:6a, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/potent-ant/ubuntu-core-18-amd64.img.qcow2,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/potent-ant/cloud-init-config.iso'
2021-10-01T08:34:37-05:00 multipassd[4464]: [359568] started: qemu-system-x86_64 -nographic -dump-vmstate /tmp/multipassd.LzrLKD
2021-10-01T08:34:37-05:00 multipassd[4464]: Applied AppArmor policy: multipass.potent-ant.qemu-system-x86_64
2021-10-01T08:34:37-05:00 multipassd[4464]: process state changed to Starting
2021-10-01T08:34:37-05:00 multipassd[4464]: process state changed to Running
2021-10-01T08:34:37-05:00 multipassd[4464]: [359571] started: qemu-system-x86_64 --enable-kvm -cpu host -nic tap,ifname=tap-d29c2ac271a,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:4c:93:6a -device virtio-scsi-pci,id=scsi0 -drive file=/var/snap/multipass/common/data/multipassd/vault/instances/potent-ant/ubuntu-core-18-amd64.img.qcow2,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/snap/multipass/common/data/multipassd/vault/instances/potent-ant/cloud-init-config.iso
2021-10-01T08:34:37-05:00 multipassd[4464]: process started
2021-10-01T08:34:37-05:00 multipassd[4464]: Waiting for SSH to be up
2021-10-01T08:34:37-05:00 multipassd[4464]: Failed to open /dev/null for OFD lock probing: Operation not permitted
2021-10-01T08:34:37-05:00 multipassd[4464]: 
2021-10-01T08:34:37-05:00 multipassd[4464]: qemu-system-x86_64: could not open /dev/net/tun: Operation not permitted
2021-10-01T08:34:37-05:00 multipassd[4464]: 
2021-10-01T08:34:37-05:00 multipassd[4464]: process state changed to NotRunning
2021-10-01T08:34:37-05:00 multipassd[4464]: process finished with exit code 1

```

```
$ snap list multipass
Name       Version                 Rev   Tracking          Publisher   Notes
multipass  1.8.0-rc.663+gcea87e49  5726  latest/candidate  canonical✓  -
$ snap connections multipass 
Interface          Plug                         Slot                Notes
firewall-control   multipass:firewall-control   :firewall-control   -
home               multipass:all-home           :home               -
home               multipass:home               :home               -
kvm                multipass:kvm                :kvm                -
libvirt            multipass:libvirt            -                   -
lxd                multipass:lxd                lxd:lxd             -
multipass-support  multipass:multipass-support  :multipass-support  -
network            multipass:network            :network            -
network-bind       multipass:network-bind       :network-bind       -
network-control    multipass:network-control    :network-control    -
network-manager    multipass:network-manager    :network-manager    -
network-observe    multipass:network-observe    :network-observe    -
removable-media    multipass:removable-media    -                   -
system-observe     multipass:system-observe     :system-observe     -
unity7             multipass:unity7             :unity7             -
wayland            multipass:wayland            :wayland            -
x11                multipass:x11                :x11                -
$ multipass get local.driver
qemu
```

**Comment by anonymouse64** [comment] 2021-10-01 17:53
FWIW the issue went away for me when I switched to using the lxd driver instead of the QEMU driver

**Comment by anonymouse64** [comment] 2021-10-05 04:05
For $REASONS I had to switch back to using the QEMU driver, and ran into this again immediately. I did a little bit of debugging and found that essentially the /dev/net/tun device which has major/minor of 10:200 is present in the multipassd's devices cgroup before running a command which causes multipassd to do things, but that device disappears from the device cgroup at some point while executing commands which are run as part of i.e. `multipass start ...`.

The issue went away when I switched snapd versions and disabled/re-enabled the multipass snap which is very suspicious, but we are also investigating a recently found problem with the device cgroup, so I'm inclined to believe that this may actually be a snapd bug. @townsend2010 also reported that he couldn't reproduce with a fresh 21.04 VM as well so it's possible this is something with snapd. After our fix (see https://github.com/snapcore/snapd/pull/10847 for part of this) has landed it would be good to test again to see if this happens, I have a hunch it is more likely to happen when one is using edge snapd, `snap refresh snapd --edge`.

**Comment by bboozzoo** [comment] 2021-10-05 05:54
Slight correction, https://github.com/snapcore/snapd/pull/10847 is only relevant if you're using cgroup v2, which shouldn't be the case on 21.04. There's https://github.com/snapcore/snapd/pull/10860 which may help, but not necessarily. FWIW if this involves dynamically adding a device node which is immediately accessed, then it may be a manifestation of:  https://bugs.launchpad.net/snapd/+bug/1892895

**Comment by anonymouse64** [comment] 2021-10-05 11:36
@bboozzoo no I observed the specific device rule present in the device cgroup after the process had started, and after the process tried to do something it lost a bunch of allow rules, actually not just the rule for /dev/net/tun but a number of other devices as well. I'll try and see if I can reproduce again to show you

**Comment by townsend2010** [comment] 2023-11-03 13:52
There have been no more reports if this in ~ 2 years, so I'm assuming it is no longer an issue.

**Closed by townsend2010** 2023-11-03 13:52 UTC
Labels: invalid
