### ISSUE TITLE
Any plans to support bridge network on Apple silicon

### ISSUE THREAD

**Issue by JCzz** [canonical/multipass#2424] opened 2022-02-01 19:44 UTC
Hi

I would love to use Multipass, I am just waiting on being able to bridge to network adapter to give each server an IP address.

I get this on apple silicon

```
multipass networks
networks failed: The networks feature is not implemented on this backend.
```

**Comment by Saviq** [comment] 2022-02-02 08:18
Hi @JCzz, yes, we'll be closing that gap with other drivers soon.

**Comment by txthinking** [comment] 2022-02-22 05:19
If this, we can create Transparent Proxy  on macos as router gate way via TPROXY mod by https://txthinking.github.io/brook/#/brook-tproxy

**Comment by JCzz** [comment] 2022-03-11 14:31
Thanks @txthinking 

I am betting on this to be included in multipass.

Hi @Saviq 
Do you have any information on progress on this issue, with all respect to the work on this? 
I am looking forward.

**Comment by Saviq** [comment] 2022-03-11 17:16
@JCzz in progress here: #2462, will be included in our next release.

**Comment by Saviq** [comment] 2022-03-31 10:47
Duplicate of #2364

**Closed by Saviq** 2022-03-31 10:47 UTC
Labels: enhancement
