### ISSUE TITLE
Multipass doesn't find the file multipass_cert_key.pem

### ISSUE THREAD

**Issue by semiromid** [canonical/multipass#2023] opened 2021-03-23 01:06 UTC
**Describe the bug**
Multipass doesn't find the file - multipass_cert_key.pem

I checked the path where this file should be but it was not there. It is possible that my computer name is written in Cyrillic and that is why such a problem arises.

**To Reproduce**
How, and what happened?
I've tried use `multipass info` and `multipass ls` or `multipass list`

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: Win 10 x64 last build
- `multipass version` multipass-1.6.2+win-win64.exe
- `multipass info --all`

**Comment by Saviq** [comment] 2021-03-23 09:06
Hi @semiromid yes, that's most likely it - #1314.

You can [use the `MULTIPASS_STORAGE` variable](https://github.com/canonical/multipass/pull/1789#issuecomment-705403501) to point Multipass at a different place, that should help.

I'll mark this one as duplicate, then.

**Comment by Saviq** [comment] 2021-03-23 09:06
Duplicate of #1314

**Closed by Saviq** 2021-03-23 09:06 UTC
Labels: bug
