### ISSUE TITLE
Instance stopped while starting. Sudden corrupt (?) multipass instance.

### ISSUE THREAD

**Issue by MattWilcox** [canonical/multipass#1929] opened 2021-01-18 22:40 UTC
Multipass crashed(?) and no longer able to start.

I'm using Nitro, but [have a problem](https://github.com/craftcms/nitro/issues/229) that seems to actually be a Multipass issue (Nitro uses Multipass to set up a local web development server).

I had a stable working VM, set up (via Nitro) to act as a local development web server. It worked fine for weeks. It suddenly stopped working one day, as I was using it. Requests to the web server began timing out. It is possible that my Mac had gone to sleep briefly while I made a coffee - but without making any changes to the VM in any way it went from "fine" to "not working, not bootable".

Digging deep, the underlying issue seems to be:
```
[2021-01-18T09:31:06.072] [info] [daemon] Received signal 15 (Terminated: 15)
[2021-01-18T09:31:06.073] [info] [daemon] Goodbye!
[2021-01-18T09:31:38.756] [info] [rpc] gRPC listening on unix:/var/run/multipass_socket, SSL:on
[2021-01-18T09:31:38.827] [info] [daemon] Starting Multipass 1.5.0+mac
[2021-01-18T09:31:38.827] [info] [daemon] Daemon arguments: /Library/Application Support/com.canonical.multipass/bin/multipassd --verbosity debug
[2021-01-18T09:31:39.020] [warning] [url downloader] Cannot retrieve last modified date for https://cloud-images.ubuntu.com/releases/streams/v1/index.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
[2021-01-18T09:31:39.020] [info] [update] Failed to fetch update info: failed to download from 'https://multipass.run/static/latest-release.json': Host multipass.run not found
[2021-01-18T09:31:39.094] [warning] [url downloader] Cannot retrieve last modified date for https://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
[2021-01-18T09:31:39.827] [warning] [url downloader] Cannot retrieve last modified date for https://cloud-images.ubuntu.com/daily/streams/v1/index.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
[2021-01-18T09:31:39.855] [warning] [url downloader] Cannot retrieve last modified date for https://cloud-images.ubuntu.com/daily/streams/v1/com.ubuntu.cloud:daily:download.json: Host cloud-images.ubuntu.com not found. Using cached data instead.
[2021-01-18T09:31:39.941] [warning] [url downloader] Cannot retrieve last modified date for http://cdimage.ubuntu.com/ubuntu-core/appliances/streams/v1/com.ubuntu.appliances:released:download.json: Host cdimage.ubuntu.com not found. Using cached data instead.
[2021-01-18T09:31:39.959] [warning] [VMImageHost] Could not update manifest: failed to download from 'http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz': Host cdimage.ubuntu.com not found
[2021-01-18T09:31:39.967] [warning] [VMImageHost] Could not update manifest: failed to download from 'https://cloud-images.ubuntu.com/buildd/releases/bionic/release/bionic-server-cloudimg-amd64-disk.img': Host cloud-images.ubuntu.com not found
[2021-01-18T09:39:31.494] [debug] [nitro-dev] Trying SSH on 192.168.64.2:22
[2021-01-18T09:39:31.499] [debug] [nitro-dev] process working dir ''
[2021-01-18T09:39:31.499] [info] [nitro-dev] process program '/Library/Application Support/com.canonical.multipass/bin/hyperkit'
[2021-01-18T09:39:31.499] [info] [nitro-dev] process arguments '-c, 2, -m, 4096M, -u, -A, -H, -U, df8e2271-b049-3a59-a915-19e2daf625bf, -s, 0:0,hostbridge, -s, 2:0,virtio-net, -s, 5,virtio-rnd, -s, 31,lpc, -l, com1,autopty=/var/root/Library/Application Support/multipassd/vault/instances/nitro-dev/pty,log=/Library/Logs/Multipass/nitro-dev-hyperkit.log, -s, 1:0,virtio-blk,file:///var/root/Library/Application Support/multipassd/vault/instances/nitro-dev/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1,format=qcow,qcow-config=discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false, -s, 1:1,ahci-cd,/var/root/Library/Application Support/multipassd/vault/instances/nitro-dev/cloud-init-config.iso, -f, kexec,/var/root/Library/Application Support/multipassd/vault/instances/nitro-dev/ubuntu-20.04-server-cloudimg-amd64-vmlinuz-generic,/var/root/Library/Application Support/multipassd/vault/instances/nitro-dev/ubuntu-20.04-server-cloudimg-amd64-initrd-generic,earlyprintk=serial console=ttyS0 root=/dev/vda1 rw panic=1 no_timer_check'
[2021-01-18T09:39:31.499] [info] [nitro-dev] process state changed to Starting
[2021-01-18T09:39:31.555] [info] [nitro-dev] process state changed to Running
[2021-01-18T09:39:35.999] [error] [nitro-dev] Using fd 5 for I/O notifications
[2021-01-18T09:39:36.121] [info] [nitro-dev] mirage_block_open: block_config = file:///var/root/Library/Application Support/multipassd/vault/instances/nitro-dev/ubuntu-20.04-server-cloudimg-amd64.img?sync=os&buffered=1 and qcow_config = discard=true;compact_after_unmaps=262144;keep_erased=262144;runtime_asserts=false and stats_config = None

[2021-01-18T09:39:37.586] [error] [nitro-dev] hyperkit: [ERROR] Found a reference to cluster 103715 outside the file (max cluster 103714) from cluster 101745.2050
[2021-01-18T09:39:37.586] [error] [nitro-dev] hyperkit: [ERROR] Mirage block device raised exception: Qcow.Make(Base)(Time).Reference_outside_file(_, _)
[2021-01-18T09:39:37.587] [error] [nitro-dev] Mirage-block error: Block device is disconnected
[2021-01-18T09:39:37.587] [error] [nitro-dev] Could not open mirage-block device: Invalid argument
[2021-01-18T09:39:37.587] [error] [nitro-dev] Could not open backing file: Invalid argument
[2021-01-18T09:39:37.588] [info] [nitro-dev] process state changed to NotRunning
[2021-01-18T09:39:37.589] [info] [nitro-dev] process finished with exit code 1
```

I have no idea what to do to get it back, why this would suddenly happen, or how to restore the databases that are inside that machine?

**Additional info**
 - OS: OSX 10.13.6
- `multipass version 1.5.0+mac`
- `multipass info --all`

```
$ multipass info --all
Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     36403f956294 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           nitro-dev
State:          Starting
IPv4:           --
Release:        --
Image hash:     36403f956294 (Ubuntu 20.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /Users/matt/nitro => /home/ubuntu/sites
                    UID map: 501:default
                    GID map: 20:default
```

**Comment by Saviq** [comment] 2021-01-19 06:55
Hi @MattWilcox, please have a look at #1924, hopefully it will help — we just went through this problem with another user.

Indeed, the suspicion is that suspend/resume is not safe with hyperkit at the moment.

**Comment by Saviq** [comment] 2021-01-19 06:55
Duplicate of #1924

**Closed by Saviq** 2021-01-19 06:55 UTC
