### ISSUE TITLE
multiple network interfaces, map interface to bridges

### ISSUE THREAD

**Issue by a1git** [canonical/multipass#1352] opened 2020-02-12 22:02 UTC
How to launch a VM with multiple interfaces, where the additonal interfaces will map to user-provided bridges ?

**Comment by Saviq** [comment] 2020-02-13 08:06
Hi @a1git, it's not possible just yet, but on our roadmap: #118

**Comment by Saviq** [comment] 2020-02-13 08:06
Duplicate of #118

**Closed by Saviq** 2020-02-13 08:06 UTC
