### ISSUE TITLE
Rename COPYING.GPL.txt to LICENSE

### ISSUE THREAD

**Issue by yogurtearl** [canonical/multipass#2642] opened 2022-06-30 20:00 UTC
Your license is here https://github.com/canonical/multipass/blob/main/COPYING.GPL.txt

If you rename that file to `LICENSE`, then GitHub should be able to detect it.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license
> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

But GitHub is not currently detecting the license:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1195562/176767172-54cb2b58-ddfc-43b2-9c2c-8c25e3e28155.png">

**Comment by townsend2010** [comment] 2022-07-15 16:21
Duplicate of https://github.com/canonical/multipass/issues/2136.

**Comment by townsend2010** [comment] 2022-07-15 16:22
Duplicate of https://github.com/canonical/multipass/issues/2136.

**Closed by townsend2010** 2022-07-15 16:22 UTC
