### ISSUE TITLE
x86_64 VMs on Apple Silicon

### ISSUE THREAD

**Issue by johalun** [canonical/multipass#2486] opened 2022-03-21 20:27 UTC
**What are you trying to do?**
At $work we develop, maintain and test a lot of software running on Ubuntu 20.04 on x86_64 architecture. On local devices we use VMs for this. However, with the new Apple Silicon MacBooks becoming more common among developers we lack tools to easily manage the VMs.

**What's your proposed solution?**
Like you can currently do with Docker, add a --platform option or similar where you can choose between aarch64 and x86_64 architecture for the VM.

**Additional context**
As proven with Docker and UTM, qemu is able to provide required emulation so with qemu as backend for multipass I guess it shouldn't be that much work required to make this possible. I'd love to be able to use multipass for this but until then, I think we'll have to make do with bash scripts and running qemu directly.

**Comment by Saviq** [comment] 2022-03-22 10:52
Hi @johalun, we have that in mind, we'll post updates on this on #886

**Comment by Saviq** [comment] 2022-03-22 10:52
Duplicate of #886

**Closed by Saviq** 2022-03-22 10:52 UTC
Labels: enhancement
