### ISSUE TITLE
Multipass can't start or launch a new instance

### ISSUE THREAD

**Issue by MozkaGit** [canonical/multipass#3762] opened 2024-10-31 21:21 UTC
**Describe the bug**
I recently installed Multipass on my laptop but can't get it to work. When I try to launch or start a instance I get this error message: 

```
start failed: The following errors occurred:
<instance_name>: timed out waiting for response
```

**To Reproduce**
How, and what happened?
1. multipass launch or multipass start <instance_name>

**Logs**
[multipass.log](https://github.com/user-attachments/files/17593540/multipass.log)

**Additional info**
 - OS: Fedora 41
- `multipass version` : 1.14.1
- `multipass info` : 
```
Name:           fish
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     fad101d50b06 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver` : qemu

**Additional context**
What I tried:
- start primary
- create another instance
- reinstall multipass

**Comment by MozkaGit** [comment] 2024-11-06 22:55
Hi @ricab thanks for your response. It's the first time I'm using multipass on my PC, it never worked. It affect all instances even primary.
 
I followed the case 3 and 4 of the troubleshooting guide. I can see "NIC_RX_F ILTER_CHANGE" on the multipass log but regarding the DHCP request, this is what I get:

```
22:41:41.925775 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:41:46.259006 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:41:49.530484 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:41:58.481895 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:42:13.830493 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:42:45.374122 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:43:49.329072 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:44:52.584122 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:45:56.818987 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:46:59.848947 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:48:03.390482 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
22:49:07.320661 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 52:54:00:33:9d:65 (oui Unknown), length 291
```

Seems that my instance can't get an ip address. I tried to delete the network stale but same issue. But disabling the firewall resolved the issue.

I reactivated my firewall and added these commands, which solved the problem rm :

```
sudo firewall-cmd --zone=trusted --add-interface=mpqemubr0 --permanent
sudo firewall-cmd --reload
```

**Comment by ricab** [comment] 2024-11-07 11:30
Hi @MozkaGit, OK so you were affected by the [dreaded firewall issue](#2387). Interesting how you worked around it, thanks for sharing.

**Comment by ricab** [comment] 2024-11-07 11:31
Duplicate of #2387

**Closed by ricab** 2024-11-07 11:31 UTC
Labels: needs triage
