### ISSUE TITLE
Unable to start Multipass VMs after upgrade to MacOS 14.0 on M1

### ISSUE THREAD

**Issue by fynntang** [canonical/multipass#3249] opened 2023-10-08 05:13 UTC
**Describe the bug**
I am unable to download and start VM after upgrading to MacOS 14.0

**To Reproduce**
How, and what happened?
1. `multipass launch 23.04 -n develop -vvvv`

**Expected behavior**
Can be installed and started normally

**Logs**
```
[2023-10-08T12:58:42.405] [debug] [qemu-system-aarch64] [58754] started: qemu-system-aarch64 --version
[2023-10-08T12:58:42.433] [debug] [qemu-img] [58755] started: qemu-img info /var/root/Library/Caches/multipassd/qemu/vault/images/lunar-20230926/ubuntu-23.04-server-cloudimg-arm64.img
[2023-10-08T12:58:42.444] [trace] [client cert store] Verifying cert:
-----BEGIN CERTIFICATE-----
MIIBjDCCATECBFwJtCowCgYIKoZIzj0EAwIwUDELMAkGA1UEBhMCVVMxEjAQBgNV
BAoMCUNhbm9uaWNhbDEtMCsGA1UEAwwkMjNlNjI3NTItN2E1ZS00OTBhLTlmN2Yt
NGM0NWVjMzhmOTU4MB4XDTIyMDYyNTEwMTc1NFoXDTIzMDYyNTEwMTc1NFowUDEL
MAkGA1UEBhMCVVMxEjAQBgNVBAoMCUNhbm9uaWNhbDEtMCsGA1UEAwwkMjNlNjI3
NTItN2E1ZS00OTBhLTlmN2YtNGM0NWVjMzhmOTU4MFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAE033gKOi9rF5JY2D1KNMi2AOZkEzosY+rerhZ8CaAI/zcbbYmKeeq
jqQDhXPxaPvcbj+u2l1qzDgy/PwvSQ0JCzAKBggqhkjOPQQDAgNJADBGAiEAtQ7a
X/Lj+7KqmQAb1SxBEeUylf5BSZVEiwOq1ijW0YYCIQCN0hcor+OhpD83/RlNcqpT
e6oPa5dgQCiawEXxIN1uKg==
-----END CERTIFICATE-----

[2023-10-08T12:58:42.445] [debug] [qemu-img] [58756] started: qemu-img resize /var/root/Library/Application Support/multipassd/qemu/vault/instances/develop/ubuntu-23.04-server-cloudimg-arm64.img 5368709120
[2023-10-08T12:58:42.470] [debug] [qemu-img] [58757] started: qemu-img snapshot -l /var/root/Library/Application Support/multipassd/qemu/vault/instances/develop/ubuntu-23.04-server-cloudimg-arm64.img
[2023-10-08T12:58:42.476] [debug] [develop] process working dir ''
[2023-10-08T12:58:42.476] [info] [develop] process program 'qemu-system-aarch64'
[2023-10-08T12:58:42.476] [info] [develop] process arguments '-machine, virt,gic-version=3, -accel, hvf, -drive, file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on, -cpu, host, -nic, vmnet-shared,model=virtio-net-pci,mac=52:54:00:0a:bf:6c, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/develop/ubuntu-23.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -qmp, stdio, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/root/Library/Application Support/multipassd/qemu/vault/instances/develop/cloud-init-config.iso'
[2023-10-08T12:58:42.479] [debug] [qemu-system-aarch64] [58758] started: qemu-system-aarch64 -machine virt,gic-version=3 -nographic -dump-vmstate /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/multipassd.DpsFtP
[2023-10-08T12:58:42.514] [info] [develop] process state changed to Starting
[2023-10-08T12:58:42.517] [info] [develop] process state changed to Running
[2023-10-08T12:58:42.517] [debug] [qemu-system-aarch64] [58759] started: qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:0a:bf:6c -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application Support/multipassd/qemu/vault/instances/develop/ubuntu-23.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -nographic -cdrom /var/root/Library/Application Support/multipassd/qemu/vault/instances/develop/cloud-init-config.iso
[2023-10-08T12:58:42.517] [info] [develop] process started
launch failed: The following errors occurred:
develop: timed out waiting for response

```

**Additional info**
- OS: macOS 14.0 M1
- `multipass version`
```
multipass   1.12.2+mac
multipassd  1.12.2+mac
```
- `multipass info --all`
```
Name:           develop
State:          Unknown
IPv4:           --
Release:        --
Image hash:     46d4f3874831 (Ubuntu 23.04)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```
- `multipass get local.driver`
```
qemu
```

**Additional context**
![de4ael.png](https://files.catbox.moe/de4ael.png)

**Comment by ricab** [comment] 2023-10-09 11:38
Hi @fynntang, although there have been people reporting the same difficulties on Sonoma, we haven't been able to reproduce them and, more importantly, they have always turned out to be unrelated to the macOS version itself. See #3209. Here are a few pointers to help you troubleshot:
  - You can try to go through our [troubleshooting docs](https://multipass.run/docs/troubleshoot-networking#heading--troubleshoot-networking-on-macos).
  - If that doesn't work, please note that there is a long-standing [issue with Apple's firewall](#2387) blocking its own `bootp` service. The workaround for that one is to [add an exclusion for bootp](https://github.com/canonical/multipass/issues/2387#issuecomment-1515004315). 
  - Finally, unfortunately DHCP leases get duplicated and go stale on macOS, particularly if you repeat VM names. Here's [how you can reset them](https://apple.stackexchange.com/a/196236). If you have any leases that you don't want to loose, you can instead edit `/var/db/dhcpd_leases` and remove any entries pertaining to `develop`.

Please let us know how this goes for you!

**Comment by fynntang** [comment] 2023-10-12 03:15
> Hi @fynntang, although there have been people reporting the same difficulties on Sonoma, we haven't been able to reproduce them and, more importantly, they have always turned out to be unrelated to the macOS version itself. See #3209. Here are a few pointers to help you troubleshot:
> 
> * You can try to go through our [troubleshooting docs](https://multipass.run/docs/troubleshoot-networking#heading--troubleshoot-networking-on-macos).
> * If that doesn't work, please note that there is a long-standing [issue with Apple's firewall](#2387) blocking its own `bootp` service. The workaround for that one is to [add an exclusion for bootp](https://github.com/canonical/multipass/issues/2387#issuecomment-1515004315).
> * Finally, unfortunately DHCP leases get duplicated and go stale on macOS, particularly if you repeat VM names. Here's [how you can reset them](https://apple.stackexchange.com/a/196236). If you have any leases that you don't want to loose, you can instead edit `/var/db/dhcpd_leases` and remove any entries pertaining to `develop`.
> 
> Please let us know how this goes for you!

Hi @ricab Thank you. My problem has been resolved through [#2387](https://github.com/canonical/multipass/issues/2387#issuecomment-1515004315) . It should be noted that after completing this operation, a reboot is required

**Comment by ricab** [comment] 2023-10-12 10:26
OK, glad you managed to get it going. Thank you for letting us know @fynntang.

**Comment by ricab** [comment] 2023-10-12 10:26
Duplicate of #2387

**Closed by ricab** 2023-10-12 10:26 UTC
