### ISSUE TITLE
multipass widget 'open shell' makes odd, unusably small terminal on high-dpi screens

### ISSUE THREAD

**Issue by cassiocassio** [canonical/multipass#1518] opened 2020-05-01 11:32 UTC
**To Reproduce**
On a high-dpi screen
1. open a terminal from the dash
2. open a window from the menubar widget 'open shell command'

**Expected behavior**
An ubuntu 'standard' sized and coloured terminal to open in both cases

- 20.04 Focal on 16" macbook pro "retina" 3072x1920 under VMware Fusion

![Multipass Open Shell menubar widget opens unusual terminal](https://user-images.githubusercontent.com/4593556/80802564-91caae80-8ba7-11ea-8e92-f328df8684fe.png)

![Screenshot from 2020-05-01 04-31-37](https://user-images.githubusercontent.com/4593556/80802731-14536e00-8ba8-11ea-9360-f358a0b69684.png)

**Comment by ricab** [comment] 2020-05-01 12:20
Hi, I believe this is what you'd get if you just launched `xterm` directly from the command line. One workaround is

`echo xterm*faceName: xft:monospace:pixelsize=35 > ~/.Xresources`

Of course if you then open `xterm` in a different resolution it will be huge. But the fact that xterm does not follow the scale that is centrally set is outside multipass's scope.

We intend to provide ways to select preferred terminals in the future, so that will probably help.

**Comment by Saviq** [comment] 2020-05-01 13:10
We'll be working on this soon :)

**Comment by Saviq** [comment] 2020-05-01 13:10
Duplicate of #899

**Closed by Saviq** 2020-05-01 13:10 UTC
Labels: question
