### ISSUE TITLE
multipass list columns don't align with long image names

### ISSUE THREAD

**Issue by anonymouse64** [canonical/multipass#943] opened 2019-08-06 04:53 UTC
For example, with some of my snaps I have built (all of which have valid snap name lengths) and other random VMs:

```
$ multipass list
Name                    State             IPv4             Image
snapcraft-edgex-device-simpleStopped           --               Ubuntu Snapcraft builder for Core 18
snapcraft-edgex-device-mqttStopped           --               Ubuntu Snapcraft builder for Core 18
snapcraft-demo-grove-pi Stopped           --               Ubuntu Snapcraft builder for Core 18
smashing-taipan         Suspended         --               Ubuntu 18.04 LTS
comical-copperhead      Stopped           --               Ubuntu 18.04 LTS
snapcraft-my-snap-name  Stopped           --               Ubuntu Snapcraft builder for Core 18
snapcraft-edgexfoundry  Stopped           --               Ubuntu Snapcraft builder for Core 18
snapcraft-netplan       Stopped           --               Ubuntu Snapcraft builder for Core 18
snapcraft-test-snapd-netplan-applyStopped           --               Ubuntu Snapcraft builder for Core 18
studious-courser        Stopped           --               Ubuntu 19.04
immediate-starfish      Suspended         --               Ubuntu Core 16
snapcraft-edgex-pi      Stopped           --               Ubuntu Snapcraft builder for Core 18
tremendous-angora       Suspended         --               Ubuntu 16.04 LTS
snapcraft-edgex-device-groveStopped           --               Ubuntu Snapcraft builder for Core 18
prudent-zorilla         Running           10.137.198.92    Ubuntu 16.04 LTS
exemplary-whippoorwill  Stopped           --               Ubuntu Core 16
famed-cicada            Deleted           --               Not Available
```

I think that the columns should grow in this case to better align output

**Comment by Saviq** [comment] 2019-09-19 11:39
Duplicate of #500

**Closed by Saviq** 2019-09-19 11:39 UTC
Labels: help wanted, good first issue
