### ISSUE TITLE
multipassd.log bloating disk

### ISSUE THREAD

**Issue by vegardjervell** [canonical/multipass#2343] opened 2021-11-15 12:18 UTC
When i run an instance of multipass over time (3-7 days without restart) the multipassd.log grows until it completely fills my disk. The only way I've found to free the disk space is to overwrite the log file from the command line and then purge the instance. This could of course be due to me misusing multipass in some way, but I fail to see how. It seems like the daemon never trunctuates the log, but just keeps writing as long as it's active.

I'm running MacOS 10.14.6
multipass version: multipassd 1.7.2+mac

I use multipass to run a fortran-package (that only runs on Linux) that is called from python code I'm writing on MacOS and executing via multipass. Multipass appears to have some hangups when python imports standard libraries such as scipy, numpy, pandas, matplotlib, and throws a bunch of errors into the log, but the code runs just fine.

The log file looks like this, with the "cannot stat" error repeated for 200+GB. I've posted on [stackoverflow](https://stackoverflow.com/questions/69559554/multipass-log-multipassd-log-bloating-disk/69559555#69559555), and someone else seems to have the same type of issue.

[2021-11-15T11:56:12.609] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/__init__.cpython-38-x86_64-linux-gnu.so': no such file
[2021-11-15T11:56:12.610] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/__init__.abi3.so': no such file
[2021-11-15T11:56:12.610] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/__init__.so': no such file
[2021-11-15T11:56:12.657] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/_api/__init__.cpython-38-x86_64-linux-gnu.so': no such file
[2021-11-15T11:56:12.658] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/_api/__init__.abi3.so': no such file
[2021-11-15T11:56:12.658] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/_api/__init__.so': no such file
[2021-11-15T11:56:12.670] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/cbook/__init__.cpython-38-x86_64-linux-gnu.so': no such file
[2021-11-15T11:56:12.671] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/cbook/__init__.abi3.so': no such file
[2021-11-15T11:56:12.671] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/matplotlib/cbook/__init__.so': no such file
[2021-11-15T11:56:12.697] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/PIL/__init__.cpython-38-x86_64-linux-gnu.so': no such file
[2021-11-15T11:56:12.698] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/PIL/__init__.abi3.so': no such file
[2021-11-15T11:56:12.698] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/PIL/__init__.so': no such file
[2021-11-15T11:56:12.775] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.776] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.776] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.777] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.777] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.777] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.778] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.778] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/tls': no such file
[2021-11-15T11:56:12.779] [error] [sftp server] handle_stat: cannot stat  '/Users/vegardjervell/Documents/soret_model/venv_ubuntu/lib/python3.8/site-packages/Pillow.libs/x86_64': no such file

**Comment by Saviq** [comment] 2021-11-15 12:45
@vegardjervell upgrade to the latest Multipass version, it has that bug fixed (#2207).

**Comment by Saviq** [comment] 2021-11-15 12:45
Duplicate of #2207

**Closed by Saviq** 2021-11-15 12:45 UTC
Labels: bug

**Comment by vegardjervell** [comment] 2021-11-15 16:58
My bad, didn't catch that, thank you :)
