### ISSUE TITLE
multipassd won't start due to umlaut in priv_key_path

### ISSUE THREAD

**Issue by countofcount** [canonical/multipass#1349] opened 2020-02-11 07:24 UTC
Multipassd is not starting automatically after install on Windows. 

Trying to start it via CMD / PS throws:
`error: failed to export ssh private key to file 'C:/Users/M├Ârs/AppData/Roaming/multipassd/ssh-keys/id_rsa`

Where `C:/Users/M├Ârs/` is supposed to read as `C:/Users/M<o-umlaut, i.e. ö>rs` not sure, which Windows env variable is used to construct the `priv_key_path` in `create_priv_key` but internationalization might be worthwhile considering for #756.

**Comment by Saviq** [comment] 2020-02-11 11:52
Hi @countofcount, thanks for reporting - this relates to #1111 and definitely needs fixing.

**Comment by townsend2010** [comment] 2020-02-12 17:41
I don't think this relates to #1111.  That bug is about unicode characters not being presented correctly while doing `shell` or `exec`.  This bug is about unicode characters not being handled correctly in our daemon code itself.

**Comment by Saviq** [comment] 2020-02-19 16:17
Duplicate of #1314

**Closed by Saviq** 2020-02-19 16:17 UTC
Labels: bug, high
