### ISSUE TITLE
YAML colon handling incompatible with cloud-init's pyyaml

### ISSUE THREAD

**Issue by gucharbon** [canonical/multipass#1097] opened 2019-09-27 14:27 UTC
### Context

- I'm running `multipass 0.8.0+win` on Windows 10 (17763).
- I'm trying to install Docker using cloud-init. 
- I'm using multipass to start a virtual machine using the following command:

`multipass launch -n swarm --cpus 2 --mem 4G --cloud-init cloud-config.yaml`

> Note: I didn't know how to name this issue, feel free to rename it

### Issue

`cloud-init` fails to load YAML with the following error:

```
2019-09-27 14:59:06,516 - util.py[WARNING]: Failed loading yaml blob. Invalid format at line 19 column 16: "while scanni
ng a plain scalar
  in "<unicode string>", line 19, column 16:
        -   [echo, Installing docker using script f ...
                   ^
found unexpected ':'
  in "<unicode string>", line 19, column 57:
     ... g docker using script from https://get.docker.com]
                                         ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details."
2019-09-27 14:59:06,550 - util.py[WARNING]: Failed loading yaml blob. Invalid format at line 19 column 16: "while scanni
ng a plain scalar
  in "<unicode string>", line 19, column 16:
        -   [echo, Installing docker using script f ...
                   ^
found unexpected ':'
  in "<unicode string>", line 19, column 57:
     ... g docker using script from https://get.docker.com]
                                         ^
```

### Given cloud-config

```yaml
#cloud-config

groups:
  - docker

users:
  - name: gcharbon
    gecos: Guillaume Charbonnier
    primary_group: gcharbon
    groups: docker
    home: /home/gcharbon
    shell: /bin/bash
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa <ssh_key>

package_upgrade: true

rumcmd:
  - [ mkdir, /run/install_docker ]
  - [ echo, "Installing docker using script from https://get.docker.com" ]
  - [ curl, -fsSL, "https://get.docker.com", -o, /run/install_docker/get-docker.sh ]
  - [ sh, /run/install_docker/get-docker.sh ]
  - [ docker, swarm, init ]

final_message: >
   The system is finally up, after $UPTIME seconds.
   Docker has been installed and packages are up to date
```

### Additional information

The command `sudo cat /var/lib/cloud/instances/swarm/user-data.txt` returns the following:

```yaml
#cloud-config
groups:
    -   docker
users:
    -   name: gcharbon
        gecos: Guillaume Charbonnier
        primary_group: gcharbon
        groups: docker
        home: /home/gcharbon
        shell: /bin/bash
        lock_passwd: true
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
            -   ssh-rsa <ssh_key>
    -   default
package_upgrade: true
rumcmd:
    -   [mkdir, /run/install_docker]
    -   [echo, Installing docker using script from https://get.docker.com]
    -   [curl, -fsSL, https://get.docker.com, -o, /run/install_docker/get-docker.sh]
    -   [sh, /run/install_docker/get-docker.sh]
    -   [docker, swarm, init]
final_message: "The system is finally up, after $UPTIME seconds. Docker has been installed and packages are up to date\n
"
```

As you can see, quotes around commands in `runcmd` block disappeared.

Why does `multipass` removes the quotes around URLs ? 
Am I not using the correct format expected by `cloud-init` or is it a problem related to `multipass`? 

I tried to follow [this example](https://github.com/number5/cloud-init/blob/master/doc/examples/cloud-config.txt#L125) when writing my cloud-config file, that's why I'm confident that cloud-config syntax is correct.

> Note: BTW, is it expected behaviour that default user is added even if it was not specified in my `cloud-config.yml`? 

### Picture of a cute animal

I hope you will be happy to have taken a look to this issue once you will see my bunny sleeping with my cat 🐰 🐱 
![image](https://user-images.githubusercontent.com/36370689/65777178-cffc7d00-e143-11e9-9206-eb9a685d9c52.png)

Thanks in advance and thank you for the awesome tool that is ` multipass` :)

**Comment by townsend2010** [comment] 2019-09-27 17:50
Hi @gucharbon,

Thanks for the kind words and the animal pic :smiley: 

I took a quick look and I think I have an idea of what is going on.  So we use yaml-cpp (https://github.com/jbeder/yaml-cpp) for emitting the cloud-init yaml and it appears that in order to preserve the quote, one needs to use `YAML::DoubleQuoted`.

We obviously don't do that, so we'll need to detect when the string is quoted and then use `YAML::DoubleQuoted` in those cases.

**Comment by Saviq** [comment] 2019-09-30 09:57
> We obviously don't do that, so we'll need to detect when the string is quoted and then use `YAML::DoubleQuoted` in those cases.

This sounds weird, why would we need to "detect" a quoted string? Looks like the YAML parser on the python side requires quoting, so we should just quote by default?

**Comment by townsend2010** [comment] 2019-10-01 12:50
Ok, I was wrong with my initial thought on this.  So the issue is the ':' in the string and how pyyaml is handling that.  See https://pyyaml.org/wiki/YAMLColonInFlowContext

Also, even the cloud-init docs reference that the ':' can be an issue:
https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot
in the second example under that.  In particular, the
```
# Note, that the list has to be proper yaml, so you have to quote
# any characters yaml would eat (':' can be problematic)
```
I experimented some to see if there is some way to get pyyaml to accept the ':' within a string, but  I could not find a way.  I think you're going to have to do some experimenting to see if it's possible at all to get that string to show up properly.  But given that pyyaml link above, I think this is in pyyaml and not Multipass.

I'm going to close this, but if it can be proven that Multipass is doing something wrong with the string, then we can reopen and figure out what the problem is.

**Comment by gucharbon** [comment] 2019-10-01 12:53
The issue is not really with pyyaml. The file I give to multipass is a valid cloud-config.

The problem is that it is first parsed by multipass, and then written without proper quoting.
So:
-  if you say that multipass will never quote and the solution is for YAML to handle unquoted strings, OK, problem lies within pyyaml.
- if you say that multipass should be able to feed cloud-init the exact same file that user gave, then problem lies within multipass

**Comment by Saviq** [comment] 2019-10-01 13:16
@gucharbon we can't pass the string verbatim as we need to inject our own bits that are required for Multipass to function. The YAML we're passing out (unquoted) is valid, other parsers deal with it fine. So "without proper quoting" is not saying the truth IMO.

That said, knowing that property of `pyyaml`, and that being our only target (through cloud-init), we should deal with it somehow. Maybe we can force quoting when emitting the yaml from `yaml-cpp`?

**Comment by townsend2010** [comment] 2019-10-01 13:21
@Saviq, I tried forcing quoting in yaml-cpp and it quotes **eveything** regardless if quotes are in the original YAML or not which then breaks all sorts of other things.  This is why I suggested initially that we may have to detect if there are quotes in the passed in YAML and preserve those when emitting the YAML.

I did find a solution that kind of works, if it's OK that quotes show up in the output as well.  This is what I did:
```
#cloud-config

runcmd:
  - [ echo, '"Installing docker using script from https://get.docker.com"' ]
```

The string does show up quoted in the log, but it does work and pyyaml does not complain.  @gucharbon, is this good enough for you?

**Comment by Saviq** [comment] 2019-10-01 13:22
@townsend2010 you mean `emitter.SetStringFormat(YAML::DoubleQuoted);` breaks all sorts of other things? That sounds even more wrong…

**Comment by Saviq** [comment] 2019-10-01 14:00
OK this looks like a composite of two issues, `pyyaml` being weird about unquoted colons (where other parsers, and evidently printers, are fine), and jbeder/yaml-cpp#261, which means we can't use `YAML::DoubleQuoted`, because it then quotes _everything_, regardless of type… Which sounds even worse.

@gucharbon a workaround is indeed what @townsend2010 suggested for now… We'll follow up with fixing this proper, too.

**Comment by gucharbon** [comment] 2019-10-01 14:25
Thanks for the quick workaround. I'll try it and and keep it like that if it works. I will simply have a cloud-init file dedicated to `multipass` and will not use the same when using cloud providers. 

As multipass is used for local development (at least for me) this is not an issue

**Comment by OddBloke** [comment] 2020-01-07 14:22
cloud-init has support for [MIME multi-part user-data](https://cloudinit.readthedocs.io/en/latest/topics/format.html#mime-multi-part-archive) which might provide a way for multipass to inject its own user-data without having to munge the user's input at all.

(Alternatively, we could explore providing the multipass user-data as vendor-data, so that multipass can just pass the user-data through untouched.)

**Comment by dominikborkowski** [comment] 2020-01-07 14:28
I've ran into this issue while debugging similar case: executing runcmd section per cloud-init's examples. Using single quotes around double quotes provides an OK workaround; however, I'd love to see an actual fix that will avoid having to do that.

This may be useful for people trying to check their results:

```
multipass exec YOUR_INSTANCE -- sudo cloud-init devel schema -c /var/lib/cloud/instance/user-data.txt --annotate
```

**Comment by dominikborkowski** [comment] 2020-01-07 15:01
@gucharbon : How have you been able to solve this issue using nested quotes? In my tests the resulting runcmd script fails to run, because there are double quotes around a given command. For instance, here's the input cloud.cfg script:
```
runcmd:
    - mkdir -p ~bin
    - '"curl -fsSL https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip -o ~/packer.zip"'
    - unzip packer.zip
    - mv ~/packer/packer ~/bin/
```

Here's the resulting  `/var/lib/cloud/instance/user-data.txt`
```
#cloud-config
runcmd:
    -   mkdir -p ~bin
    -   "\"curl -fsSL https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip -o ~/packer.zip\""
    -   unzip packer.zip
    -   mv ~/packer/packer ~/bin/
```
And here's the final script cloud-init tries to run `var/lib/cloud/instance/scripts/runcmd`:
```
#!/bin/sh
mkdir -p ~bin
"curl -fsSL https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip -o ~/packer.zip"
unzip packer.zip
mv ~/packer/packer ~/bin/
```

Which then when one attempts to run it:

```
sudo /var/lib/cloud/instance/scripts/runcmd
/var/lib/cloud/instance/scripts/runcmd: 3: /var/lib/cloud/instance/scripts/runcmd: curl -fsSL https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip -o ~/packer.zip: not found
```

As soon as one removes the double quotes, shell executes curl just fine.
I'd appreciate any hints you may have on this. Thanks!

**Comment by alokpr** [comment] 2020-05-07 23:23
I have been bit by this bug as well. What is the workaround please?

**Closed** 2021-01-29 20:07 UTC
