### ISSUE TITLE
Installed multipass on Mac OS X with Brew. Exec/Shell fails with ssh connection failed: 'Failed to process system configuration files'

### ISSUE THREAD

**Issue by leonidbelkind** [canonical/multipass#1351] opened 2020-02-12 16:12 UTC
Very straight forward installation: Mac OS X Catalina

$ multipass version
multipass  1.0.0+mac
multipassd 1.0.0+mac

$ multipass shell
shell failed: ssh connection failed: 'Failed to process system configuration files'

I understand that the error is coming from libssh implementation of an ssh client. Would appreciate any ideas.

**Comment by Saviq** [comment] 2020-02-12 16:36
Hi @leonidbelkind, is your SSH configuration complex by any chance?

We just fixed a similar problem in #1259, can you try [a recent build of master](https://github.com/canonical/multipass/commit/915e1e0dbff484fe77d0e5533bcc3b273b17ee47#commitcomment-37256739)?

**Comment by leonidbelkind** [comment] 2020-02-12 16:59
Using the default image, nothing fancy.
Can try the build...

Where is the client trying to take a config file from?

**Comment by Saviq** [comment] 2020-02-12 17:26
@leonidbelkind this would be your host's `.ssh`, in `/Users/<username>/`.

**Comment by leonidbelkind** [comment] 2020-02-13 08:14
Removed some lines from the config (using Proxy directives) and the problem disappeared

**Comment by Saviq** [comment] 2020-02-13 08:45
Duplicate of #1259

**Comment by Saviq** [comment] 2020-02-13 08:46
Thanks @leonidbelkind that was exactly the problem - it'll be fixed in the next release.

**Closed by Saviq** 2020-02-13 08:45 UTC
Labels: question
