### ISSUE TITLE
For unknown reasons, multipass will not display previously created VM instances

### ISSUE THREAD

**Issue by alexeyp0708** [canonical/multipass#2097] opened 2021-05-08 11:16 UTC
**Describe the bug**
**Additional info**
- OS: windows 8.1
- multipass  1.6.2
- local.driver => virtualbox

Once on my user machine, for unknown reasons, multipass stopped seeing my VM-s.
Call `Psexec.exe -s VBoxManage.exe list vms` sees all virtual machines created in multipass
First of all, I disabled multipassd, and removed multipass by cleaning up the registry.
Then I installed multipass again.
But the VM-s did not appear.
I found out that earlier virtualbox VM-s and settings were located in the system partition along the path `C: \ Windows \ system32 \ config \ systemprofile \ VirtualBox VMs \` .
Their settings were accessed through the PSTools tools.
But for reasons unknown to me, the location changed to `%USERPROFILE% \ VirtualBox VMs \`
The command `multipass launch --name test` created a VM in the directory `%USERPROFILE% \ VirtualBox VMs \`
Thus, multipass commands work with images with `%USERPROFILE% \ VirtualBox VMs \`.
I also saw mutipass/test instance in the virtualbox panel (launched from user).

This is very confusing. The documentation does not say anything about such things, but it is assumed that the images should work through the system user.
Now even when reinstalling multipass, it accesses the% USERPROFILE% directory.

I decided to restore the state of the system a week earlier.

I decided to restore the state of the system through the restore service.
After  restore the state of the system:
- `multipass list` => No instances found.
- `PsExec.exe -s VBoxManame.exe list vms` => ... my old VMS list 
- `multipass launch --name test`
- `multipass list` => test
- `PsExec.exe -s VBoxManame.exe list vms` => test + my old VMS list 

I suppose that the failure began from the moment when I launched the Avast antivirus to check and clean the system.
But the facts can hardly be established with certainty.

The next serious question now arises:
- How can I restore to multipass, VM instances?

conclusions:
- multipass should have a diagnostic tool that can assess the state of the system and the deviations in which multipass will malfunction.
- in multipass there should be a tool for displaying multipass settings state in which the user can make a summary analysis.
- a tool for searching and restoring copies that were lost for some reason
- Import and export tool for multipass instances 
- Install the ability to change the directory of storage of VMS instances. Of course, if you need system rights, then assign system rights to this directory or suggest to the user to do it (For example, with the command `psexec.exe -s multipass  instances-directory D:/directory`)

// Added:

- `PsExec.exe -s VBoxManame.exe list vms` => Command see old virtual machines created by multipass.
`PsExec.exe -s VBoxManame.exe startvm instance` => error code 1.
This is because the images do not actually exist in `C: \ Windows \ System32 \ config \ systemprofile \ AppData \ Roaming \ multipassd \ virtualbox`.
Perhaps they were removed when removing multipass + stripping traces (registry + files). Or when restoring the system.

**Comment by alexeyp0708** [comment] 2021-05-09 00:33
Again the problem repeated itself.
I worked calmly with the test instance.
Soon the command `multipass shell test` gives an Error: Timeout 127.0.0.1
multipass sees the image and runs it.
I reboot the computer and the image disappears again.
Folder `C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances` is empty.
File C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\multipassd-instance-image-records.json => { }

Magically.
Where are the guarantees for the preservation of virtual machine instances?

**Comment by github348** [comment] 2021-05-12 13:42
hi @alexeyp0708 you can change the location of multipass instances i have a similar issue this worked for me 
run powershell as admin run these commands 
Stop-Service Multipass
setx /M MULTIPASS_STORAGE "<path>"
replace <path> with the location where you want to store your vms

**Comment by Saviq** [comment] 2022-03-18 06:43
I'm gonna blame Windows on this.

**Comment by Saviq** [comment] 2022-03-18 06:43
Duplicate of #1119

**Closed by Saviq** 2022-03-18 06:43 UTC
Labels: bug
