### ISSUE TITLE
Aliases are the same as image names (for different images)

### ISSUE THREAD

**Issue by tpeeters** [canonical/multipass#2356] opened 2021-11-25 16:19 UTC
I just installed multipass on Ubuntu 20.04 using `snap install multipass`

When I type `multipass find`, I see the following list of images:

![photo_2021-11-25_17-17-22](https://user-images.githubusercontent.com/2772142/143474941-5dea3f98-0a54-48a9-9766-24b31634e802.jpg)

This is very confusing. When I launch an `18.04` instance, will I get `snapcraft:core18` or `bionic`? As you can see, the same ambiguity exists for 20.04.

I think it should not be possible to have an image and alias name that are the same for different images.

**Comment by Saviq** [comment] 2021-11-25 17:39
Hi @tpeeters!

The part before the colon (the "remote", e.g. `snapcraft`) applies to aliases as well. So `snapcraft:core18 == snapcraft:18.04 != 18.04`. Adding the remote to all the aliases would have been very verbose… Maybe we need to take the remote out into a separate column.

I'll duplicate it to #1842 since it deals with the same issue.

**Comment by Saviq** [comment] 2021-11-25 17:39
Duplicate of #1842

**Closed by Saviq** 2021-11-25 17:39 UTC

**Comment by tpeeters** [comment] 2021-11-25 18:12
Hi @Saviq. Thanks for the explanation.

Yeah, putting the remote in a separate column could help. I'm not using multipass a lot so I was not aware of this, I thought that "snapcraft:core18" was just an image name.
