### ISSUE TITLE
There is a problem with restoring the snapshot

### ISSUE THREAD

**Issue by danielesk** [canonical/multipass#3386] opened 2024-01-27 11:27 UTC
**Describe the bug**
After I installed Ubuntu 22.04 LTS, I took a snapshot. Later, I performed other operations, such as installing a desktop and so on. However, when I try to restore the snapshot I created for the first time, it always fails. Moreover, it creates a new snapshot every time the restoration fails.
I suspect that the issue is caused by the large differences between the image instance files before and after the operations.

**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: [Windows11 22631.3085]
- multipass   1.13.0+win
- multipassd  1.13.0+win
- `multipass info --all`
- `hyperv`

**Additional context**

**Comment by georgeliao** [comment] 2024-01-29 09:56
Hi @danielesk , sorry that you have run into this problem. 

However, it is hard for us to reproduce and diagnose without details. Can you provide the exact commands you have run and the exact error message you got from the restore command? And furthermore, the daemon log would be helpful as well.

**Comment by townsend2010** [comment] 2024-02-09 14:38
Hi @danielesk!

Just following up to see if you can provide any more of the details that @georgeliao asked for.  If not, then we will close this soon.  Thanks!

**Comment by townsend2010** [comment] 2024-02-12 18:50
I'm closing this now since there has been no activity for a few weeks.  Please reopen if you have any more details.  Thanks!

**Closed by townsend2010** 2024-02-12 18:50 UTC
Labels: question, needs triage
