### ISSUE TITLE
Mount fails when using encrypted home directory on host

### ISSUE THREAD

**Issue by wmww** [canonical/multipass#1825] opened 2020-11-02 19:54 UTC
Multipass fails to mount from an encrypted home directory

**To Reproduce**
```
multipass mount $HOME <VM name>:Home
multipass exec <VM name> ls Home
```

**Additional info**
 - OS: Ubuntu 20.04
```
wmww@wmwwXPS:~$ multipass version
multipass  1.5.0
multipassd 1.5.0
wmww@wmwwXPS:~$ multipass info --all
Name:           snapcraft-dump-snap
State:          Running
IPv4:           10.230.247.71
Release:        Ubuntu 18.04.5 LTS
Image hash:     c5d28e76db45 (Ubuntu Snapcraft builder for Core 18)
Load:           0.00 0.00 0.00
Disk usage:     1.0G out of 247.9G
Memory usage:   109.0M out of 4.8G
Mounts:         /home/wmww/code/snaps/dump-plugin-snap => /root/project
                    UID map: 1000:0
                    GID map: 1000:0
                /home/wmww                             => Home
                    UID map: 1000:default
                    GID map: 1000:default

Name:           snapcraft-mate-wayland
State:          Stopped
IPv4:           --
Release:        --
Image hash:     c5d28e76db45 (Ubuntu Snapcraft builder for Core 18)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /home/wmww/code/snaps/mate-wayland-snap => /root/project
                    UID map: 1000:0
                    GID map: 1000:0
```

**Comment by townsend2010** [comment] 2022-04-25 13:37
Duplicate of #1325

**Closed by townsend2010** 2022-04-25 13:37 UTC
